create issue on failed release by default
projen/projen pull request #1009
Opened 2021-08-28 00:09 UTC by iliapolo

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-08-29 04:52 UTC, eladb reviewed
Interesting approach.. not sure this is going to be super effective but I am curious.

Technically you could have opened tickets by querying the workflow status (similar to how the GitHub badge works).

2021-08-29 04:52 UTC, eladb commented on src/release/publisher.ts
> +  readonly issueOnFail?: boolean;
Names are inconsistent between Publisher and Release

2021-08-29 04:52 UTC, eladb commented on src/release/publisher.ts
> +            title: `Publishing v\${{ steps.extract-version.outputs.VERSION }} to ${opts.registryName} failed`,
```suggestion
            title: `Publishing v$(cat dist/version.txt) to ${opts.registryName} failed`,
```

2021-08-29 04:52 UTC, eladb commented on src/release/publisher.ts
> +        },
seems redundant:

```suggestion
        {
          name: 'Extract Version',
          if: '${{ failure() }}',
          id: 'extract-version',
          run: 'echo "::set-output name=VERSION::$(cat dist/version.txt)"',
        },
```

2021-08-30 16:29 UTC, Chriscbr requested changes
Could you generalize this just a little bit to add an API (maybe a method call on `project.release`) so users can add their own custom steps to run on release failures? Or if this is already doable, just add some documentation for it in perhaps.

use case: If I want to run https://github.com/marketplace/actions/send-email when release fails, there should be a natural way to add this, based on the failure() mechanism we are using here.

Let's add a section in docs/publisher.md about this as well.

2021-08-30 16:29 UTC, Chriscbr commented on .projenrc.js
> +  failureIssue: true,
Not in love with this API name. Maybe `notifyOnFailure` or `issueOnFailure`?

2021-08-30 19:36 UTC, iliapolo commented on src/release/publisher.ts
> +            title: `Publishing v\${{ steps.extract-version.outputs.VERSION }} to ${opts.registryName} failed`,
This doesn't work - the title is being passed as is to the action, it doesn't undergo bash interpolation befoehand.

2021-08-30 19:36 UTC, iliapolo commented on src/release/publisher.ts
> +        },
See https://github.com/projen/projen/pull/1009#discussion_r698753772

2021-08-30 19:37 UTC, iliapolo commented on .projenrc.js
> +  failureIssue: true,
Yeah there's no good name really, i'll go with `issueOnFailure` since it was my initial name as well.

2021-08-30 19:42 UTC, iliapolo commented on src/release/publisher.ts
> +  readonly issueOnFail?: boolean;
Fixed

2021-08-30 19:43 UTC, iliapolo commented on .projenrc.js
> +  failureIssue: true,
Changed

2021-08-30 19:52 UTC, iliapolo commented
@eladb 

> Interesting approach.. not sure this is going to be super effective but I am curious.
> Technically you could have opened tickets by querying the workflow status (similar to how the GitHub badge works).

Yeah this was my initial plan. I ended going down this route because:

1. I think its a nice projen feature, it gives better visibility as to which step exactly failed as well as which version.
2. It provides a nice way for maintainers to put such failures on project boards and prioritize this work.
3. It avoids the problem of handling workflows that are still in-progress. That is, what if you query the workflow status and it returns in-progress? do you query the last 2? last 5? We could have come up with a good enough heuristic, but this seemed simpler.

2021-08-30 19:54 UTC, iliapolo commented
@Chriscbr 

> Could you generalize this just a little bit to add an API (maybe a method call on project.release) so users can add their own custom steps to run on release failures?

That would be cool, but I don't currently have the capacity for it - as it requires some non trivial API design. 

I think we can start off with this and eventually evolve it to a nice `onFailure` notification system.

2021-08-30 20:48 UTC, Chriscbr approved these changes

2021-08-31 06:26 UTC, eladb commented on API.md
> +  * **issueOnFailure** (<code>boolean</code>)  Create a github issue on every failed publishing task. __*Default*__: false
These two options should have the same prefix so it's clear they are related.

I think `failureIssue` and `failureIssueLabel` is my preference.

2021-09-04 20:16 UTC, iliapolo commented on API.md
> +  * **issueOnFailure** (<code>boolean</code>)  Create a github issue on every failed publishing task. __*Default*__: false
Switched it back 👍

2021-09-05 10:02 UTC, iliapolo commented
@eladb You good with merging this?

2021-09-05 11:31 UTC, eladb approved these changes

2021-09-05 11:38 UTC, merged