feat(release): publishing npm packages to AWS CodeArtifact
projen/projen pull request #1021
Opened 2021-08-31 16:42 UTC by jumic

This PR introduces publishing npm packages to AWS CodeArtifact.

The authentication will be done using AWS CLI. This depends on PR https://github.com/cdklabs/jsii-release/pull/150 which has to be merged first.

`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` have to be defined as GitHub Secrets to follow the [IAM best practices](https://docs.aws.amazon.com/general/latest/gr/aws-access-keys-best-practices.html#iam-user-access-keys
). The names of those variables can be overridden. The default values will be applied if an AWS CodeArtifact URL is detected.

Closes #986.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-08-31 17:10 UTC, eladb requested changes

2021-08-31 17:10 UTC, eladb commented on src/node-package.ts
> +  readonly awsAccessKeyIdSecret?: string;
I am wondering if this should be collapsed under `codeArtifactOptions` (and a `CodeArtifactOptions` struct) which can later be reused for other publishing targets and will also make it easier to understand that this is only relevant for CodeArtifact:

```ts
export interface CodeArtifactOptions {
  readonly accessKeyIdSecret?: string;
  readonly secretAccessKeySecret?: string;
}

export interface NodePackageOptions {
  readonly codeArtifactOptions?: CodeArtifactOptions;
}
```

2021-08-31 20:11 UTC, jumic commented on src/node-package.ts
> +  readonly awsAccessKeyIdSecret?: string;
Yes, I think it's a good idea to change this. I updated the code as proposed.

2021-09-02 18:19 UTC, eladb requested changes

2021-09-02 18:19 UTC, eladb commented on src/node-package.ts
> +  public readonly awsAccessKeyIdSecret?: string;
Why not use the `codeArtifactOptions` here as well?

2021-09-02 19:05 UTC, jumic commented on src/node-package.ts
> +  public readonly awsAccessKeyIdSecret?: string;
I changed it. Now, variables `awsAccessKeyIdSecret` and `awsSecretAccessKeySecret` don't exist in the code anymore.

2021-09-03 05:56 UTC, eladb requested changes

2021-09-03 05:56 UTC, eladb commented on src/node-package.ts
> +    const isAwsCodeBuildRegistry = npmRegistryUrl && AWS_CODEARTIFACT_REGISTRY_REGEX.test(npmRegistryUrl);
Can we move this logic to the `Publisher` class? Feels like it belongs in there.

2021-09-03 08:29 UTC, jumic commented on src/node-package.ts
> +    const isAwsCodeBuildRegistry = npmRegistryUrl && AWS_CODEARTIFACT_REGISTRY_REGEX.test(npmRegistryUrl);
I moved the logic to `Publisher` class. Class `NodePackage` uses this new method, now.

2021-09-20 07:13 UTC, hoegertn commented
@eladb Can we keep this open or get this merged?

2021-11-01 20:30 UTC, jumic commented
@Chriscbr Thanks for reopening this PR. I just merged the current main branch to this branch.

Now, the PR has status "Changes requested" in the list of my pull requests. From my point of view, all reviews are marked as resolved. Am I missing something? The status of this PR should be "ready for review". Thanks.

2021-11-02 04:41 UTC, Chriscbr approved these changes

2021-11-02 04:48 UTC, merged

2021-11-02 04:51 UTC, Chriscbr commented
Everything looks good to me / I think you re-requested a review correctly, the PR must have just slipped through the cracks - thanks for the reminder.

2021-11-05 10:43 UTC, hoegertn commented
@jumic What do you think about adding support for Github OIDC instead of access key and secret key? Would love this.

2021-11-05 20:21 UTC, jumic commented
@hoegertn I just had a first look at Github OIDC. Definitely a good idea for this feature. I will submit an additional PR.