chore: migrate documentation to new leading main branch
projen/projen pull request #1024
Opened 2021-09-02 07:43 UTC by transacid

Some documentation files still point to the former leading master branch. This commit fixes that.
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-02 08:30 UTC, eladb requested changes

2021-09-02 08:30 UTC, eladb commented on README.md
> -* [awscdk-app-ts](https://github.com/projen/projen/blob/master/API.md#projen-awscdktypescriptapp) - AWS CDK app in TypeScript.
This needs to be fixed in `scripts/readme-projects.js`

2021-09-02 08:30 UTC, eladb commented on API.md
> +  * **main** (<code>boolean</code>)  Enable for the main/default branch. __*Default*__: true
This file is generated from source docs

2021-09-02 08:30 UTC, eladb commented on API.md
> +  * **main** (<code>boolean</code>)  Enable for the main/default branch. __*Default*__: true
This file is generated from source docs

2021-09-03 08:32 UTC, transacid commented on README.md
> -* [awscdk-app-ts](https://github.com/projen/projen/blob/master/API.md#projen-awscdktypescriptapp) - AWS CDK app in TypeScript.
ah ok ;)

2021-09-03 11:32 UTC, eladb commented on README.md
> -* [awscdk-app-ts](https://github.com/projen/projen/blob/master/API.md#projen-awscdktypescriptapp) - AWS CDK app in TypeScript.
Still missing the update to this file

2021-09-03 11:32 UTC, eladb requested changes
See note

2021-09-03 11:38 UTC, transacid commented on README.md
> -* [awscdk-app-ts](https://github.com/projen/projen/blob/master/API.md#projen-awscdktypescriptapp) - AWS CDK app in TypeScript.
hmm sorry I think I don't understand what needs to be done there. Isn't the change in `src/inventory.ts` sufficient?

2021-09-15 22:19 UTC, Chriscbr approved these changes

2021-09-15 23:02 UTC, merged