Remove hard-coded python version
projen/projen pull request #1028
Opened 2021-09-03 08:36 UTC by lmarsden

* The Python version is currently hard-coded to ^3.6
* The Python version has a knock-on effect to the versions of other packages
  that are retrieved by poetry. Some projects may require more recent versions
  of Python.
* Remove the auto-addition of the Python dependency in favour of specifying
  it explicitly in the 'deps' section of each project.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-04 02:24 UTC, Chriscbr reviewed
If a python version is still required, maybe it should be exposed as a specific field to make it clear it should be configured? For example, we could add a field like `minPythonVersion` (and `maxPythonVersion` if appropriate) to `PythonPackagingOptions`, similar to what we have for Node projects, and have the dependency automatically added if poetry is used.

2021-09-07 16:37 UTC, lmarsden commented
> If a python version is still required, maybe it should be exposed as a specific field to make it clear it should be configured? For example, we could add a field like `minPythonVersion` (and `maxPythonVersion` if appropriate) to `PythonPackagingOptions`, similar to what we have for Node projects, and have the dependency automatically added if poetry is used.

I have reinstated the `python@^3.6` default python version for poetry projects for backwards compatibility. Poetry users will be used to declaring `python` as a package dependency, so I don't feel it merits `min/maxPythonVersion` fields on `PythonProject`. I considered adding `min/maxPythonVersion` to `PoetryPyprojectOptionsWithoutDependencies` but they don't naturally fit here either, as they are not written as standalone sections into `pyproject.toml` like the other fields. So went with simply defaulting to the existing version in cases where it is not specified, making this a non-breaking change but also fixing the issue that it was previously not possible to override the hard-code version.

2021-09-08 19:17 UTC, Chriscbr requested changes
OK - yeah let's try this out and see if it makes for a simpler experience. Thanks for updating the docs as well! Just one small nitpick below.

2021-09-08 19:17 UTC, Chriscbr commented on src/python/poetry.ts
> +    var pythonDefined: boolean = false;
```suggestion
    let pythonDefined: boolean = false;
```

2021-09-10 08:10 UTC, lmarsden commented on src/python/poetry.ts
> +    var pythonDefined: boolean = false;
Thanks, suggested change above now applied.

2021-09-10 18:05 UTC, Chriscbr requested changes
I should have called this out in the last review, but we should also add at tests here as well.

2021-09-13 08:59 UTC, lmarsden commented
Test now added

2021-09-13 22:15 UTC, Chriscbr approved these changes

2021-09-13 22:54 UTC, Chriscbr commented
Same issue as #1030 (not due to your code changes). This should fix it:
```
git checkout main
git pull
git checkout <pr-branch>
git merge main
yarn projen && yarn build  # in case build steps changed
git add .
git commit
git push
```

2021-09-14 11:25 UTC, merged

2021-09-14 11:27 UTC, lmarsden commented
Build now fixed. PR was automatically merged once this was done.