Fix ignored poetry options
projen/projen pull request #1030
Opened 2021-09-03 16:53 UTC by lmarsden

* The poetryOptions object in the PythonProject was previously ignored when synthesizing pyproject.toml.
* poetryOptions declarations are now written to pyproject.toml.
* This allows specification of e.g. private PyPI registries via `[tool.poetry.source]` entries:

```
poetryOptions: {
    source: [
      {
        name: "myprivateregistry",
        url: "https://pkgs.dev.azure.com/myorg/_packaging/myprivateregistry/pypi/simple/",
        secondary: true,
      },
    ]
  },
```

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-04 01:33 UTC, Chriscbr requested changes
Can you add some tests to `python-project.test.ts` or `poetry.test.ts` that illustrate the change?

2021-09-07 09:30 UTC, lmarsden commented
> Can you add some tests to `python-project.test.ts` or `poetry.test.ts` that illustrate the change?

Have now updated the code in `poetry.test.ts` to test for correct behaviour of the `poetry` options that were previously missing. `PoetryPyrojectOptions` (via `PoetryPyrojectOptionsWithoutDeps`) class now updated to support all `poetry` options documented at  https://python-poetry.org/docs/pyproject

2021-09-08 19:09 UTC, Chriscbr requested changes
Looks great @lmarsden, just a few small comments.

2021-09-08 19:09 UTC, Chriscbr commented on src/__tests__/python/poetry.test.ts
> +  expect(snapshot['pyproject.toml']).toContain('"bug tracker" = "https://github.com/test-python-project/issues"');
This is getting pretty long and detailed - let's replace all of this (in the new test case) with

```js
expect(snapshot['pyproject.toml']).toMatchSnapshot();
```

2021-09-10 15:50 UTC, lmarsden commented on src/__tests__/python/poetry.test.ts
> +  expect(snapshot['pyproject.toml']).toContain('"bug tracker" = "https://github.com/test-python-project/issues"');
Thanks for the suggestion. Snapshot added and tests updated.

2021-09-10 15:52 UTC, lmarsden commented on src/__tests__/python/poetry.test.ts
> +    poetryOptions: {
Done. Also see comment below.

2021-09-10 18:03 UTC, Chriscbr approved these changes

2021-09-13 08:14 UTC, lmarsden commented
Looks like the build is failing at the `Commit and push changes (if changed)` step in `build.yml` as it's attempting to push some changes to my fork at https://github.com/lmarsden/projen

Are there any changes I need to make?

2021-09-13 22:24 UTC, Chriscbr commented
Looks like some kind of transient snapshot error because of some issues with our integration tests. Usually re-running `yarn build` fixes this

2021-09-13 22:47 UTC, merged