feat(release): publish:git
projen/projen pull request #1047
Opened 2021-09-08 03:52 UTC by gradybarrett

Manual publishing to git. This includes prepending the
changelog artifact onto a project-level changelog,
commiting that change as a release commit, and tagging that
release commit.

Closes #726

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-08 05:57 UTC, gradybarrett commented on src/release/release.ts
> +      changelogFile: join(this.artifactsDirectory, this.version.changelogFileName),
Joining artifact directory from version rather than hard coding artifact directory in the task. Any concerns with updating the other publish tasks as well and removing the ARTIFACT_DIR constants?

2021-09-08 13:12 UTC, gradybarrett commented
I didn't push the commit or tag, but can if that's desirable.

2021-09-09 07:53 UTC, eladb requested changes

2021-09-09 07:53 UTC, eladb commented on src/release/publisher.ts
> +    */
```suggestion
   * The location of an .md file (relative to `dist/`) that includes the changelog for the release.
   *
   * @example changelog.md
   */
```

2021-09-09 07:53 UTC, eladb commented on src/release/release.ts
> +      changelogFile: join(this.artifactsDirectory, this.version.changelogFileName),
Sounds good to me

2021-09-09 07:53 UTC, eladb commented on src/util.ts
> +export async function tryReadFile(file: string) {
This function seems like it's only used by tests. Please move to `test/util.ts`

2021-09-09 07:53 UTC, eladb commented on src/util.ts
> +export function normalizeVersion(version: string) {
I can't see where this is used.

2021-09-09 07:53 UTC, eladb commented on src/version.ts
> +  public static async tryReadVersion(versionFile: string) {
Doesn't feel like this should be a public API as it is only used by builtin tasks. Move this to an internal file next to the builtins.

2021-09-09 07:53 UTC, eladb commented on src/release/update-changelog.ts
> +  if (!inputChangelogContent.includes(version)) {
Should we use the same search pattern as we do with the output? e.g. `[${version}]`?

2021-09-09 07:53 UTC, eladb commented on src/release/release.ts
> +    this.publisher.publishToGit({
Does it make sense to always include this task? Feels like it can be slightly misleading because users who don't use manual publishing may be confused why this task even exists. And vice versa - if you want manual publishing, then all the workflows related to automated publishing don't make sense.

So it feels like maybe we need this to be an opt-in thing, mutually exclusive with automated release workflow.

@Chriscbr any suggestions on now to model this?

2021-09-09 14:57 UTC, gradybarrett commented on src/version.ts
> +  public static async tryReadVersion(versionFile: string) {
I was thinking from the perspective of encapsulating the standard for how to read and process a version file. But maybe this is a case of yagni.

2021-09-09 15:26 UTC, gradybarrett commented on src/release/update-changelog.ts
> +  if (!inputChangelogContent.includes(version)) {
We should! Fixed.

2021-09-09 19:20 UTC, gradybarrett commented on src/release/release.ts
> +      changelogFile: join(this.artifactsDirectory, this.version.changelogFileName),
Pushed up 6a5e4e8d. Pretty minor change, but marked it as breaking since it might change the output artifacts directory for existing projects.

2021-09-10 01:32 UTC, Chriscbr reviewed
Didn't look at all of the implementation, but this looks cool. Let's be sure to update the docs / add some guidance about how to use this. 🙏 

We should probably make it clear in the docs if this is the only release method that creates/manages a CHANGELOG file for you.

2021-09-10 01:32 UTC, Chriscbr commented on src/release/release.ts
> +    this.publisher.publishToGit({
How about we only call this if `releaseEveryCommit` is false?

Are manual git releases compatible with scheduled releases (e.g. once a week - configured by `this.releaseSchedule`), or are those also incompatible?

Maybe it's possible to model these options as some a enum-like value like `ReleaseStrategy` which a user could provide as:

- `ReleaseStrategy.schedule({ cronExpression: ..., changelog: true })`
- `ReleaseStrategy.continuous({ changelog: false })`
- `ReleaseStrategy.manual({ changelog: true })`

I think that would be a pretty cool-looking API, at least if my mental model is on the same page as everyone else's.

2021-09-10 03:46 UTC, gradybarrett commented on src/release/release.ts
> +    this.publisher.publishToGit({
Technically it's compatible because `publish:git` is idempotent, but I'm not sure it makes sense as part of those flows.
I was thinking along the same lines regarding an enum-like approach. The first time I interacted with `project.release` I half expected it to have a type of `ReleaseType` (`ReleaseStrategy` is a better name 😄).

2021-09-10 18:02 UTC, gradybarrett commented on src/release/release.ts
> +    this.publisher.publishToGit({
@Chriscbr @eladb I'm most of the way through adding in ReleaseStrategy, but I noticed that technically releaseEveryCommit and releaseSchedule can coexist - there's no check for mutual exclusion. Was that intended?

2021-09-10 18:58 UTC, Chriscbr commented on src/release/release.ts
> +    this.publisher.publishToGit({
Probably not intended, no.

2021-09-10 21:48 UTC, gradybarrett commented on src/release/release-strategy.ts
> +
@Chriscbr let me know what you think of this.

2021-09-10 22:01 UTC, gradybarrett commented on src/release/release-strategy.ts
> +  readonly changelog?: boolean;
This could also be the project changelog file path. 🤔 

``js
ReleaseStrategy.manual({ changelog: 'foo/changelog.md' });
``

2021-09-11 08:00 UTC, gradybarrett commented on src/release/release-strategy.ts
> +  readonly changelog?: boolean;
The first option didn't work when I thought about integrating changelogs with automated releases in the future.

2021-09-11 08:01 UTC, gradybarrett commented on src/release/release.ts
> +    this.publisher.publishToGit({
Refactored and added ReleaseStrategy. Let me know what you guys think.

2021-09-11 08:04 UTC, gradybarrett commented
> Didn't look at all of the implementation, but this looks cool. Let's be sure to update the docs / add some guidance about how to use this. 🙏

We should probably make it clear in the docs if this is the only release method that creates/manages a CHANGELOG file for you.

Should have this covered now between class, method, and release.md docs. Let me know if there are any holes anywhere.

2021-09-12 08:58 UTC, eladb commented on src/version.ts
> +  public static async tryReadVersion(versionFile: string) {
I try to avoid exposing APIs that I am not sure are actually needed :-D

2021-09-12 09:05 UTC, eladb requested changes
@gradybarrett I love it that we are modeling release triggers more formally.

See some initial notes. I hope I'll have time for a more thorough review later this week.
This is a very sensitive area of the code base 👍

2021-09-12 09:05 UTC, eladb commented on docs/releases.md
> +You can optimize the release experience using the `publish` and `pushArtifacts` manual release options
Kind of feels like the default for `yarn release` in "manual" mode should be to perform publishing. The piecemeal tasks are an implementation detail.

2021-09-12 09:05 UTC, eladb commented on src/release/release.ts
> +    this.releaseStrategy.isManual && this.publisher.publishToGit({
please use an "if" statement

2021-09-12 09:05 UTC, eladb commented on docs/releases.md
> +releaseStrategy: ReleaseStrategy.scheduled({ schedule: '0 17 * * *' }),
@Chriscbr how will this be usable if projenrc is in JSON? We either need to explicitly support "union-like classes" or we need to prevent them in the "options" API...

2021-09-12 19:42 UTC, gradybarrett commented on src/version.ts
> +  public static async tryReadVersion(versionFile: string) {
Fair enough. :) I'll move it for now.

2021-09-12 20:41 UTC, gradybarrett commented on docs/releases.md
> +You can optimize the release experience using the `publish` and `pushArtifacts` manual release options
Yep, that's fair. Do you think we should even expose the ability to shut off publishing in manual mode?

```js
releaseStrategy: ReleaseStrategy.manual({
  changelog: true,
  changelogPath: 'my/changelog.md'
}),
```

2021-09-13 05:05 UTC, gradybarrett commented on docs/releases.md
> +releaseStrategy: ReleaseStrategy.scheduled({ schedule: '0 17 * * *' }),
I don't think the current implementation will serialize without establishing a new standard and expectation for how to serialize/de-serialize union-like classes. Supporting means that the projenrc.json/yaml representations will have special/different rules.

For example:

```json
{
  "releaseTrigger":
    "type": "continuous"
    "options": {
      "changelog": "true"
    }
}
```

which when parsed executes the `ReleaseTrigger.<type>` factory and passes it provided options. Potentially not great for dev ux continuity.

2021-09-13 05:16 UTC, Chriscbr commented on docs/releases.md
> +releaseStrategy: ReleaseStrategy.scheduled({ schedule: '0 17 * * *' }),
Created an issue: #1062

Not sure what you mean by the "options" API. We support other union-like classes currently in project constructors, like `depsUpgrade: DependenciesUpgradeMechanism` - but as you mentioned, they can't be provided in the CLI during `projen new` or in projenrc.json.

2021-09-19 05:34 UTC, gradybarrett commented on docs/releases.md
> +You can optimize the release experience using the `publish` and `pushArtifacts` manual release options
Simplified a bit.

2021-10-04 08:20 UTC, eladb requested changes
Great job. A few additional minor comments and I think we are ready!

2021-10-04 08:20 UTC, eladb commented on src/release/publisher.ts
> +    const taskName = (gitBranch == 'main' || gitBranch == 'master') ? 'publish:git' : `publish:git:${gitBranch}` ;
```suggestion
    const taskName = (gitBranch === 'main' || gitBranch === 'master') ? 'publish:git' : `publish:git:${gitBranch}` ;
```

2021-10-04 08:20 UTC, eladb commented on src/release/release-trigger.ts
> +   * Whether or not this is a continuous release.
Add a sentence explaining what continuous release means (i.e. "releases every commit")

2021-10-04 08:20 UTC, eladb commented on src/release/release-trigger.ts
> +   * then push the generated artifacts.
Doesn't `publish:git` already pushes?

2021-10-04 08:20 UTC, eladb commented on src/release/release.ts
> +   * @deprecated Use `releaseTrigger` instead
```suggestion
   * @deprecated Use `releaseTrigger: ReleaseTrigger.continuous()` instead
```

2021-10-04 08:20 UTC, eladb commented on src/release/release.ts
> +   * @deprecated Use `releaseTrigger` instead
```suggestion
   * @deprecated Use `releaseTrigger: ReleaseTrigger.scheduled()` instead
```

2021-10-04 08:20 UTC, eladb commented on src/release/release.ts
> +   * @default - Continuous releases
```suggestion
   * @default - Continuous releases (`ReleaseTrigger.continuous()`)
```

2021-10-04 08:20 UTC, eladb commented on src/release/release.ts
> +  readonly projectChangelogFile?: string;
This only applies with manual releases, right? Shouldn't this just be part of `ReleaserTrigger.manual()`?

2021-10-04 16:42 UTC, gradybarrett commented on src/release/release-trigger.ts
> +   * then push the generated artifacts.
Whoops, forgot to update that. Thanks.

2021-10-04 16:43 UTC, gradybarrett commented on src/release/release-trigger.ts
> +   * Whether or not this is a continuous release.
Done

2021-10-04 16:44 UTC, gradybarrett commented on src/release/release.ts
> +  readonly projectChangelogFile?: string;
Yes. I'll remove it from the others.

I originally intended to add support for it everywhere, but I think it's better to wait and add that incrementally.

2021-10-04 16:47 UTC, gradybarrett commented on src/release/release.ts
> +  readonly projectChangelogFile?: string;
Oh yes, this is no longer used. Should have been removed in the release trigger refactor.

2021-10-04 16:47 UTC, gradybarrett commented on src/release/release.ts
> +  readonly projectChangelogFile?: string;
Removed.

2021-10-04 16:48 UTC, gradybarrett commented on docs/releases.md
> +releaseStrategy: ReleaseStrategy.scheduled({ schedule: '0 17 * * *' }),
Resolving this now that we have #1062.

2021-10-04 16:56 UTC, eladb approved these changes

2021-10-04 17:23 UTC, gradybarrett commented
Thanks @eladb! 🎉

2021-10-04 17:24 UTC, eladb commented
Thank you for such high quality contribution 🙏

2021-10-04 17:31 UTC, merged

2021-10-04 21:51 UTC, hoegertn commented
https://github.com/projen/projen/blame/180393e9795f4d0f4d7720268c0a87328a38469c/src/release/update-changelog.task.ts#L19

Is this name mismatch intended? I get errors after upgrading and trying to use the release job. to sure if this is the issue but seems weird to me.

2021-10-05 02:45 UTC, gradybarrett commented
@hoegertn definitely not intended. Just missed a rename when switching to use the new release tag file.

#1116 to fix.

2021-10-05 05:58 UTC, gradybarrett commented
There still possibly something weird about release tag prefixes and the dist/changelog.md. I'll look more at it tomorrow. Might just be a local setup thing. In any case, when there's no prefix defined we need to strip off the `v` prefix from the release tag. I'll fix that tomorrow unless someone beats me to it.

2021-10-05 09:48 UTC, hoegertn commented
Can confirm this: https://github.com/projen/projen/blame/main/src/release/update-changelog.ts#L64

Fails due to the v being on the tag but not in the changelog file