feat(eslint): import aliasing
projen/projen pull request #1048
Opened 2021-09-08 14:37 UTC by mtimbs

allow specification of configuration to remove lint errors for projects that utilise import aliasing.

e.g `import { bar } from '@src/foo'`

## Notes
I'm not entirely happy with the API here. I'd have much rather preferred to take an option for `alias` as an object. However, when trying to compile I got jsii errors saying map types were unsupported

```typescript
readonly alias?: {
  map: [string, string][];
  extensions: string[];
};
```

If there is a way to support this kind of API I believe it would be more intuitive for the consumer than having different options for the map and the extensions as submitted in this PR.

```typescript
  /**
   * Enable import alias for module paths
   * @default []
   */
  readonly aliasMap?: ;

  /**
   * Enable import alias for module paths
   * @default []
   */
  readonly aliasExtensions?: string[];
```
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-08 19:41 UTC, Chriscbr requested changes
Neat, it would be great to support this!

2021-09-08 19:41 UTC, Chriscbr commented on src/eslint.ts
> +  readonly aliasMap?: [string, string][];
Because we are using [jsii](https://aws.github.io/jsii/) under the hood to compile projen and generate APIs in other languages, I don't believe we can use certain fancier types like [string, string] in our exported interfaces. Instead we should probably change this to a record/dictionary type:
```suggestion
  readonly aliasMap?: { [key: string]: string };
```

...and add some code in the constructor that converts this back into an array of tuples.

2021-09-09 00:21 UTC, mtimbs commented on src/eslint.ts
> +  readonly aliasMap?: [string, string][];
Ok, I'll make the necessary changes. I also considered automatically configuring this based on the `.tsconfig` that we have access to already within Eslint - but opted for this approach to be more explicit. If we need to deviate from the normal eslint structure it might be ok to have this implicit configuration based on aliases declared in the `.tsconfig`?

2021-09-10 02:07 UTC, Chriscbr commented on src/eslint.ts
> +  readonly aliasMap?: [string, string][];
Do you need to define import aliases in both places for source code to compile and lint without errors?

If the user provides import aliases/paths within the tsconfig options and we could pass them to the eslint config as well (so they don't have to write them twice), I think that could be convenient! I'm also okay with leaving them separate if needed.

2021-09-10 02:33 UTC, mtimbs commented on src/eslint.ts
> +  readonly aliasMap?: [string, string][];
Yeah unfortunately need to define them in 3 places. Jest config, tsconfig and eslint. Let me try and work some magic to infer them from tsconfig as I think that would be a nicer developer experience (so long as it is documented what is happening)

2021-09-13 12:00 UTC, mtimbs commented on src/eslint.ts
> +  readonly aliasMap?: [string, string][];
I ended up making the changes to the types only. The reference to tsconfig available was just the path, not the actual config options

2021-09-16 04:43 UTC, Chriscbr requested changes
Just a few small changes and this should be good to ship.

2021-09-16 04:43 UTC, Chriscbr commented on src/__tests__/eslint.test.ts
> +  });
I think it's OK to remove this test - doesn't seem to validate anything specific to the aliases feature.

2021-09-16 04:43 UTC, Chriscbr commented on src/eslint.ts
> +          ...( options.aliasMap && options.aliasExtensions && {
Looking at https://www.npmjs.com/package/eslint-import-resolver-alias, I think aliasExtensions can be omitted, so it should probably be:
```suggestion
          ...( options.aliasMap && {
```

2021-09-16 07:11 UTC, mtimbs commented on src/__tests__/eslint.test.ts
> +  });
Done

2021-09-16 18:49 UTC, Chriscbr requested changes

2021-09-16 18:49 UTC, Chriscbr commented on src/__tests__/eslint.test.ts
> +      dirs: ['src'],
Please revert the changes here

2021-09-17 01:55 UTC, mtimbs commented on src/__tests__/eslint.test.ts
> +      dirs: ['src'],
Sorry! All done

2021-09-17 18:59 UTC, Chriscbr approved these changes

2021-09-17 19:00 UTC, Chriscbr commented
Looks like the snapshots need to be updated: https://github.com/projen/projen/runs/3627825547#step:9:9

2021-09-18 12:03 UTC, merged