fix(new): Use NPM for `projen new` instead of Yarn
projen/projen pull request #1077
Opened 2021-09-16 13:07 UTC by MarkMcCulloh

Fixes #885 

Note that the workaround is no longer needed because NPM doesn't have that issue. See the linked issue for the reasoning behind the change.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-16 13:24 UTC, MarkMcCulloh commented on src/cli/cmds/new.ts
> +  return `npm i --silent -D -f --no-package-lock --prefix=${dir} ${module}`;
ℹ️  Note the `-f`. If this is not used, then there are almost always going to be peer dependency issues failures. Most external projects have projen as a peer dependency, but since projen has a 0 major version number and moves quickly, it's pretty impossible to satisfy so NPM install will fail. Yarn didn't install peer deps, so it avoided this. In case the external projects has peer deps necessary for synthesis, we should make sure to install them.

2021-09-16 13:27 UTC, MarkMcCulloh commented on src/cli/cmds/new.ts
> -
ℹ️  No longer needed because NPM doesn't have that issue. See the linked issue for the reasoning behind the change.

2021-09-21 03:41 UTC, Chriscbr requested changes
Looks good to me, just one small comment to address.

2021-09-21 03:41 UTC, Chriscbr commented on src/cli/cmds/new.ts
> +  return `npm i --silent -D -f --no-package-lock --prefix=${dir} ${module}`;
Hmm, I wonder if the silent flag really helps us at all. Maybe take it out

Also since we don't have to type this command ourselves, might as well spell out the arguments to improve readability. 🙂 
```suggestion
  return `npm install --save-dev -f --no-package-lock --prefix=${dir} ${module}`;
```

2021-09-21 03:41 UTC, Chriscbr commented on src/cli/cmds/new.ts
> -
Awesome!

2021-09-21 16:53 UTC, Chriscbr approved these changes

2021-09-21 17:00 UTC, merged

2021-10-04 09:23 UTC, eladb reviewed
Thanks!