fix(new): Unable to use external project from many package specs
projen/projen pull request #1094
Opened 2021-09-21 23:08 UTC by MarkMcCulloh

Fixes #879 
(The original issue was (I think) fixed with https://github.com/projen/projen/pull/1077, this fixes the other issue brought up regarding `npx projen new --from cdk-appsync-project@latest`)

Previously, one was unable to use `--from`  with a spec that was not of the form `package` or `package@version`. Meaning you could not install from a tarball or one of the other many sources, even a dist tag (e.g. `package@latest`).

This change makes use of the results of the `npm install` command to figure out the actual `package@semanticVersion` so that we can use it to parse the actual package name.
Also, changed `yarn` -> `npm` in a few comments to reflect the changes from my last PR.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-22 04:52 UTC, Chriscbr requested changes

2021-09-22 04:52 UTC, Chriscbr commented on src/cli/cmds/new.ts
> +  const dependencyInfo = installResult.toString().split('\n')[0].slice(2);
Not sure if I understand why we are calling slice(2) - what does the full output look like? Is there any other way we can get the correct package version in a more stable way, e.g. by reading it from the package.json?

2021-09-22 04:52 UTC, Chriscbr commented on src/__tests__/new.test.ts
> +    expect(actual).toMatchSnapshot();
These snapshots are pretty big and have a lot that isn't important - maybe we can reduce it to something like:
```suggestion
    expect(actual['package.json']).toMatchSnapshot();
    expect(actual['.projenrc.js']).toMatchSnapshot();
    expect(actual['./cdk-appsync-project@1.1.3']).toBeDefined(); // check our tarball wasn't deleted
```

2021-09-22 07:05 UTC, MarkMcCulloh commented on src/cli/cmds/new.ts
> +  const dependencyInfo = installResult.toString().split('\n')[0].slice(2);
I agree the approach here wasn't ideal. Initially, I couldn't think of a way to use the package.json because we don't really know the resolved package name or version.

If we can live with the assumption that base package.json right after installing the external project will have at most projen and the one other project in the dev deps, then I have another approach. I updated the PR with it.

2021-09-23 01:48 UTC, Chriscbr requested changes

2021-09-23 01:48 UTC, Chriscbr commented on src/cli/cmds/new.ts
> +  }
Won't `npm install --save-dev` create a package.json if it didn't exist before?

2021-09-23 01:48 UTC, Chriscbr commented on src/cli/cmds/new.ts
> +  const packageName = Object.keys(packageJson.devDependencies).find(name => name != 'projen');
minor
```suggestion
  const packageName = Object.keys(packageJson.devDependencies).find(name => name !== 'projen');
```

2021-09-23 01:52 UTC, MarkMcCulloh commented on src/cli/cmds/new.ts
> +  }
Depends on the version of NPM apparently, I had different behavior in a couple of environments

2021-09-23 02:08 UTC, Chriscbr approved these changes

2021-09-23 02:15 UTC, merged