feat: signoff dependency upgrade pr's
projen/projen pull request #1100
Opened 2021-09-27 09:36 UTC by iliapolo

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-27 10:20 UTC, iliapolo commented on src/upgrade-dependencies.ts
> -          'committer': `${COMMIT_AUTHOR_NAME} <${COMMIT_AUTHOR_EMAIL}>`,
Replaced by adding the `Set git identity` step, which is also necessary for the sign-off.

2021-09-27 10:22 UTC, iliapolo commented on src/github/constants.ts
> +};
These details used to be scattered over the code, so I consolidated to a github-actions user that should be used from now on. Also changed `Automation` to `github-actions` to be consistent with the github username that appears in the UI on occasion.

2021-09-27 10:26 UTC, iliapolo commented on src/__tests__/node-project.test.ts
> +    expect(snapshot.jobs.pr.steps[4].with.labels).toStrictEqual(project.autoApprove?.label);
Step added to the workflow so index changed from `3` to `4`.

2021-09-27 10:27 UTC, iliapolo commented on src/__tests__/node-project.test.ts
> +    expect(snapshot['.github/workflows/upgrade-projen.yml']).toBeUndefined();
This was actually a bug in the test that went undetected due to a bug in the code...

2021-09-27 10:28 UTC, iliapolo commented on src/__tests__/upgrade-dependencies.test.ts
> +  const deps = 'jest jest-junit npm-check-updates projen standard-version dep1';
This was actually a bug in the test that went undetected due to a bug in the code...

2021-09-27 20:01 UTC, Chriscbr approved these changes
Interesting - yeah the tradeoff here feels reasonable to me. I think providing a unified API (where "dependabot" or "GitHub workflow" are two supported implementations of a common interface) could be useful down the line, but for now the `DependenciesUpgradeMechanism` class isn't doing much for us.

2021-09-28 01:22 UTC, Chriscbr commented on src/node-project.ts
>          ignoreProjen: !options.projenUpgradeSecret,
This is outside of the immediate scope of this PR, but there's currently a small bug where the projen repository itself should be auto-approving PRs, but it is not because the upgrade.yml workflow is using the `GITHUB_TOKEN` workflow instead of `PROJEN_GITHUB_TOKEN`. Adding `projenUpgradeSecret: 'PROJEN_GITHUB_TOKEN'` to the constructor should fix this - but if we do so, then this "ignoreProjen" flag gets flipped and projen will try upgrading itself.

Could you try adding this line and see if that fixes it? :)
```suggestion
      const upgradeDependencies = new UpgradeDependencies(this, {
        // if projen secret is defined we can also upgrade projen here.
        ignoreProjen: !options.projenUpgradeSecret || this.package.packageName === 'projen',
```

2021-09-29 10:09 UTC, iliapolo commented
@eladb You good with this change?

2021-09-29 10:19 UTC, iliapolo commented on src/node-project.ts
>          ignoreProjen: !options.projenUpgradeSecret,
I dont think this is necessary actually. The upgrade task won't try to upgrade `projen` because its not a dependency of `projen`. The only thing the explicitly upgrades projen is:

https://github.com/projen/projen/blob/epolon/upgrade-sign-off/src/node-project.ts#L754

Which already special cases `projen` itself. We should change `.projenrc` to configure:

```ts
depsUpgrade: {
  workflowOptions: {
    secret: 'PROJEN_UPGRADE_TOKEN`
  }
}
```

And that should do it. 

I'll take of this in a subsequent PR

2021-09-30 12:55 UTC, eladb requested changes

2021-09-30 12:55 UTC, eladb commented on src/github/constants.ts
> +export const SET_GIT_IDENTITY_WORKFLOW_STEP = {
add type

2021-09-30 12:55 UTC, eladb commented on src/upgrade-dependencies.ts
> +   * @default false
Why not `true` by default?

2021-09-30 12:55 UTC, eladb commented on src/util.ts
> +      console.log(`Source: Key=${key}, value=${value}`);
revert

2021-09-30 13:03 UTC, iliapolo commented on src/util.ts
> +      console.log(`Source: Key=${key}, value=${value}`);
Whoops, good catch.

2021-09-30 13:03 UTC, iliapolo commented on src/upgrade-dependencies.ts
> +   * @default false
Hmm, no reason I guess...will change 👍

2021-09-30 13:04 UTC, iliapolo commented on src/github/constants.ts
> +export const SET_GIT_IDENTITY_WORKFLOW_STEP = {
👍

2021-09-30 13:19 UTC, iliapolo commented
@eladb Ready for another pass

2021-09-30 14:25 UTC, eladb commented on src/upgrade-dependencies.ts
> +   * @default true.
```suggestion
   * @default true
```

2021-09-30 14:26 UTC, eladb approved these changes

2021-10-02 19:37 UTC, merged