fix: :bug: update the default CDK version to 1.129.0
projen/projen pull request #1184
Opened 2021-10-29 14:15 UTC by nikhil-zadoo

The current cdk version has dependency issues with jest which fails with error "npm ERR!   peer jest@"^27.0.0" from ts-jest@27.0.7".
The later versions have fixed this dependency issue. So updating the default cdk version to the latest.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-10-29 23:48 UTC, Chriscbr requested changes

2021-10-29 23:48 UTC, Chriscbr commented on src/awscdk-app-ts.ts
> +   * @default "v1.129.0"
```suggestion
   * @default "1.129.0"
```

2021-10-29 23:48 UTC, Chriscbr commented on src/awscdk-construct.ts
> +   * @default "v1.129.0"
```suggestion
   * @default "1.129.0"
```

2021-11-12 23:57 UTC, Chriscbr commented on src/awscdk-construct.ts
> +   * @default "v1.129.0"
@nikhil-zadoo It looks like this still needs to be updated

2021-11-16 03:28 UTC, Chriscbr approved these changes

2021-11-17 16:47 UTC, nikhil-zadoo commented
Can someone help with the failing build?
I am not sure what permissions are missing.

2021-11-17 16:57 UTC, neilkuan commented
hi @nikhil-zadoo 

you need to update the `test/__snapshots__/inventory.test.ts.snap` and commit again.
see build fail log...
```bash
Run git diff --exit-code || echo "::set-output name=has_changes::true"
diff --git a/test/__snapshots__/inventory.test.ts.snap b/test/__snapshots__/inventory.test.ts.snap
index 977fec6..ba3974e 100644
--- a/test/__snapshots__/inventory.test.ts.snap
+++ b/test/__snapshots__/inventory.test.ts.snap
@@ -3581,7 +3581,7 @@ Array [
         "switch": "cdk-test-dependencies",
       },
       Object {
-        "default": "\\"v1.129.0\\"",
+        "default": "\\"1.129.0\\"",
         "docs": "Minimum target version this library is tested against.",
         "featured": true,
         "fullType": Object {
```

2021-11-18 18:28 UTC, merged