feat: allow customization of versionrc file
projen/projen pull request #1211
Opened 2021-11-06 12:13 UTC by Hi-Fi

allows to use changelog easily with repos not in public GitHub

fixes #1204

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-09 06:02 UTC, Hi-Fi commented
@eladb @Chriscbr Does this look valid?

2021-11-10 00:10 UTC, Chriscbr requested changes
Thanks @Hi-Fi for the pull request! Exposing these options makes sense to me, I just have a small nitpick regarding the API naming / types. Otherwise looks good to me. 👍

2021-11-10 00:10 UTC, Chriscbr commented on src/release/release.ts
> +  readonly versionrc?: object;
I think based on the naming scheme we use in other projen APIs, `versionrcOptions` would be a more fitting name here (also leaves open the possibility of `versionrc` in the future to be a boolean enable/disable property, or a string property to rename the file, etc.). Also I think we can make the type slightly more specific so the API is friendlier in other JSII languages:
```suggestion
  readonly versionrcOptions?: Record<string, any>;
```

2021-11-10 00:10 UTC, Chriscbr commented on src/version.ts
> +  readonly versionrc?: object;
Same changes here

2021-11-10 05:59 UTC, Hi-Fi commented on src/release/release.ts
> +  readonly versionrc?: object;
Made change through the PR to use `versionrcOptions` (or one in capital letters)

2021-11-10 17:19 UTC, Hi-Fi commented
> Thanks @Hi-Fi for the pull request! Exposing these options makes sense to me, I just have a small nitpick regarding the API naming / types. Otherwise looks good to me. 👍

I think those are not nitpicking, as naming is quite often the hard part and changing of arguments is a hassle to those who have started to use those.

2021-11-11 05:32 UTC, Chriscbr approved these changes

2021-11-12 06:15 UTC, Chriscbr approved these changes

2021-11-12 06:29 UTC, merged