feat: enforce conventional commits with PR linter
projen/projen pull request #1224
Opened 2021-11-13 01:50 UTC by Chriscbr

Introduces `semanticPr` (boolean) and `semanticPrOptions` (object) fields to GithubProject, which adds PR validation that checks that the pull request titles follow [Conventional Commits](https://www.conventionalcommits.org/). This is enabled by default, and can be disabled with `semanticPr: false`.

Supersedes #1188

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-14 06:53 UTC, eladb requested changes

2021-11-14 06:53 UTC, eladb commented on src/github/semantic-pr.ts
> +    const types = options.types ?? [
Since the default is that only `fix` and `feat` are included in the change log, I rather we only allow `chore` as an additional type which basically indicates (not included in the change log).

So I think the default should be `[ 'feat', 'fix', 'chore' ]`.

2021-11-14 06:53 UTC, eladb commented on src/github/semantic-pr.ts
> +export class SemanticPullRequest extends Component {
I am wondering if we should make this component/workflow a bit more general purpose so it can include additional PR linting jobs (for example, like @iliapolo's linter which validates that FEAT PRs always include README updates and FIX PRs always include a change to a test). Other linting could be to validate DCO, commit message, BREAKING CHANGES, etc.

So to that extend, maybe wan just call this `PullRequestLint` and the workflow `pull-request-lint.yml`).

And then initially we just include support for semantic titles, but we can add more stuff later.

2021-11-15 05:50 UTC, Chriscbr commented on src/github/semantic-pr.ts
> +export class SemanticPullRequest extends Component {
Yeah, I was unsure on the right level of abstraction to use here... the way you describe it makes a lot more sense. 😄 Right now the semantic title checking is performed by a GitHub action I found, but that should just be an implementation detail.

2021-11-15 05:51 UTC, Chriscbr commented on src/github/semantic-pr.ts
> +    const types = options.types ?? [
Updated.

2021-11-15 05:53 UTC, Chriscbr commented
Updated the PR. I considered abbreviating the options as "prLint" or "prLintOptions" in some places, but leaned against it since I could easily imagine times where someone might type in "pull" and see no autocomplete results just because of this shorthand.

2021-11-15 05:54 UTC, eladb approved these changes

2021-11-15 06:01 UTC, merged