feat(awscdk-construct): awscdk-construct used aws-cdk v2 by default
projen/projen pull request #1228
Opened 2021-11-15 13:21 UTC by corymhall

This updates the awscdk-construct to use cdk v2 by default instead of
v1.

Some of the things that are updated:

- `constructs@^10.0.5` & `aws-cdk-lib` are added as a devDependency in addition to
  peerDependency
- the `cdkAssert` property is deprecated and replaced with
  `cdkAssertions`

BREAKING CHANGE: cdkVersion default value updated to `2.0.0`
- `cdkAssert` deprecated and default changed to `false`
- new property `cdkAssertions` added and defaulted to `true`

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-15 13:24 UTC, eladb reviewed
Nice!

2021-11-15 13:24 UTC, eladb commented on src/awscdk-construct.ts
> +        this.addDevDeps(this.formatModuleSpec('@aws-cdk/assert'));
addPeerDeps automatically adds a dev dependency, so I don't think this is needed

2021-11-15 14:17 UTC, corymhall commented on src/awscdk-construct.ts
> +        this.addDevDeps(this.formatModuleSpec('@aws-cdk/assert'));
It looks like we have been explicitly setting that to `false`

https://github.com/projen/projen/blob/dcfcfde305885778b804abe624f0f000b177a3de/src/awscdk-construct.ts#L127

2021-11-15 15:30 UTC, eladb commented on src/awscdk-construct.ts
> +        this.addDevDeps(this.formatModuleSpec('@aws-cdk/assert'));
Oh right because it is explicitly taken cared of in addCdkDependency(). 

I am wondering what's the utility of add addCdkDependency() for v2... maybe we should throw an error there?

2021-11-15 16:58 UTC, corymhall commented on src/awscdk-construct.ts
> +        this.addDevDeps(this.formatModuleSpec('@aws-cdk/assert'));
I think it is still used for the `-alpha` modules.

2021-11-15 17:18 UTC, eladb commented on src/awscdk-construct.ts
> +        this.addDevDeps(this.formatModuleSpec('@aws-cdk/assert'));
Yes you are right.

I do think that we can enable the pinned dev dependency option when using v2

2021-11-15 17:58 UTC, corymhall commented on src/awscdk-construct.ts
> +        this.addDevDeps(this.formatModuleSpec('@aws-cdk/assert'));
Ok i'll update that.

2021-11-18 20:45 UTC, corymhall commented on src/awscdk-construct.ts
> +        this.addDevDeps(this.formatModuleSpec('@aws-cdk/assert'));
Ok I reworked this a little. I kept the v1 functionality the same, but for v2 `pinDevDependency` will not be set so will default to `true`. Also, `cdkDependencies` will not apply for v2. You will just add any `alpha` modules as `peerDeps` and they will automatically get set as `devDeps` as well due to `pinDevDependency`.

2021-12-06 14:49 UTC, bilalq commented on src/awscdk-construct.ts
> +   * @depricated - use cdkAssertions instead
Typo here. Won't surface the deprecation warning in tools looking for it unless the typo is corrected, I believe.

2021-12-06 19:52 UTC, corymhall commented on src/awscdk-construct.ts
> +   * @depricated - use cdkAssertions instead
Good catch!

2021-12-06 19:54 UTC, corymhall commented
@eladb I think this is ready for a (hopefully) final review.

2021-12-07 09:38 UTC, eladb requested changes
What about setting the default to v2 for awscdk-app-xxx? Do we want to include it here or in a subsequent commit?

2021-12-07 09:38 UTC, eladb commented on src/awscdk/awscdk-construct.ts
> +      } : undefined,
Setting this explicitly to undefined means users can't configure this behavior via `options`. Maybe switch the order so options are applied after this default

2021-12-07 09:38 UTC, eladb commented on src/awscdk/awscdk-construct.ts
>      if (options.constructsVersion) {
Can we turn this into a switch statement so top level conditions are all evaluated against the same value (cdkMajor)

2021-12-07 09:38 UTC, eladb commented on src/awscdk/awscdk-construct.ts
> +   * For CDK 2.x use 'peerDeps' instead
Is this enforced? (I'd expect an error if this is used with v2)

2021-12-07 09:38 UTC, eladb commented on src/awscdk/awscdk-construct.ts
> +   * Not used for CDK 2.x
Is this enforced?

2021-12-08 13:42 UTC, corymhall commented on src/awscdk/awscdk-construct.ts
> +   * For CDK 2.x use 'peerDeps' instead
Added error messages and deprecated the property.

2021-12-08 13:42 UTC, corymhall commented on src/awscdk/awscdk-construct.ts
> +   * Not used for CDK 2.x
Added error messages and deprecated the property.

2021-12-08 13:42 UTC, corymhall commented
> What about setting the default to v2 for awscdk-app-xxx? Do we want to include it here or in a subsequent commit?

I'll create a separate PR for the app side of things.

2021-12-08 13:55 UTC, eladb approved these changes
Looks 👍

2021-12-08 14:08 UTC, merged

2021-12-08 18:25 UTC, Chriscbr commented
Awesome!! 🙌