fix: convert generated lambda paths to posix
projen/projen pull request #1237
Opened 2021-11-18 19:40 UTC by misterjoshua

Fixes #1234
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-18 20:27 UTC, misterjoshua commented
By building on Linux and linking on Windows, I was able to get this correct result:

![image](https://user-images.githubusercontent.com/644092/142491268-4d5d97b7-3474-4171-ae79-86ea9ba06e7b.png)

I'm not sure how I can add tests to Projen to make sure this doesn't regress - perhaps in the future, we could look at adding a matrix build or some sort of matrix integration test.

2021-11-19 02:02 UTC, Chriscbr requested changes

2021-11-19 02:02 UTC, Chriscbr commented on src/awscdk/lambda-function.ts
>  }
@misterjoshua Is it possible we could instead update the variable definitions earlier in the file to use `posix.join(...)` and `posix.relative(...)` etc.? Could you test if that works?

2021-11-19 17:28 UTC, misterjoshua commented on src/awscdk/lambda-function.ts
>  }
I'll see what I can do.

2021-11-19 20:51 UTC, misterjoshua commented on src/awscdk/lambda-function.ts
>  }
@Chriscbr I've updated the variables earlier in the file.

This way of doing it seems harrier to me. The POSIX functions need more care to ensure they receive only POSIX paths, so I need to rely more heavily on `convertToPosixPath`. That said, my opinions here aren't strong as long as it works on Windows.

Here's a screenshot from Windows:

![image](https://user-images.githubusercontent.com/644092/142688049-388e99c8-894a-4184-a471-043e7fddfa4c.png)

2021-11-19 22:19 UTC, Chriscbr commented on src/awscdk/lambda-function.ts
>  }
@misterjoshua  Ah, I see... I think I was assuming that all our inputs (project.outdir, options.constructFile, options.entrypoint, and possibly even bundle.outfile) could be provided as POSIX paths, and we could just decide at render time whether to print paths as POSIX or Windows. Based on your code I'm guessing we can't assume that about the inputs here?

For now I'm OK with going back to the fix you provided when you first submitted this PR since it only touched a couple lines.

2021-11-20 00:32 UTC, misterjoshua commented on src/awscdk/lambda-function.ts
>  }
> @misterjoshua Ah, I see... I think I was assuming that all our inputs (project.outdir, options.constructFile, options.entrypoint, and possibly even bundle.outfile) could be provided as POSIX paths, and we could just decide at render time whether to print paths as POSIX or Windows. Based on your code I'm guessing we can't assume that about the inputs here? For now I'm OK with going back to the fix you provided when you first submitted this PR since it only touched a couple lines.

@Chriscbr Project's outdir is definitely a native path and many components seem to depend on that, so I think changing that one from native to POSIX would be a pretty big breaking change for Windows users. AutoDiscover and Bundler also provide native paths to LambdaFunction, but I don't think changes there would be that impactful, so I think consistency is the only issue in those cases. If we're to be consistent with Project's `outdir`, I think it's best to assume input paths are native paths.

I agree that we should decide at render time which format is appropriate. LambdaFunction knows best here, and converting native paths to POSIX works fine in this case. So, I'll revert the latest commits and get us back to ec364c4.

2021-11-20 00:45 UTC, Chriscbr approved these changes

2021-11-20 00:53 UTC, merged