fix: release.yml cannot be modified with escape hatches
projen/projen pull request #1255
Opened 2021-11-25 06:40 UTC by Chriscbr

Fixes a bug where the workflows generated by the `Release` component cannot be accessed or modified using escape hatches because they are generated during the `preSynthesize()` stage of the component lifecycle.

This requires making some changes to `Publisher`, which `Release` relies upon, so that it can provide a link to the jobs it will generate even if `Publisher`'s jobs are not all available at the time construction finishes.

In addition, workflows that are not created via the `github.addWorkflow` method were not getting added to `GitHub` so they could not be discovered with `tryFindWorkflow`. This is fixed by adding a register hook within the `GithubWorkflow` constructor.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-25 06:42 UTC, Chriscbr commented on src/github/workflows.ts
> +    github._registerWorkflow(name, this);
An alternative to tracking workflows in `GitHub` is would be to do a search for all components that are `instanceof GithubWorkflow` whenever someone accesses `github.workflows` or calls `github.tryFindWorkflow()`. I don't have a strong opinion on which way to do this / I'm open to trying that instead if this `_registerWorkflow` hook is undesirable

2021-11-25 06:45 UTC, Chriscbr commented on src/release/publisher.ts
> +export class Publisher extends Component implements IJobProvider {
Instead of having `Publisher` implement `IJobProvider`, I could create a separate component that is generated by `Publisher` to isolate the behavior

2021-11-25 06:48 UTC, Chriscbr commented
I'm not sure I love this solution, though it does work. Open to other ideas of course. :)

It's worth mentioning this bug also exists in `UpgradeDependencies` -- that component generates resources at pre-synth time because it requires a list of all dependenciess and a list of all `Release` branches. So neither the workflow nor task generated by it are can be escape hatched around.

2021-11-25 06:59 UTC, eladb requested changes
Generally like the design. A few semantic comments

2021-11-25 06:59 UTC, eladb commented on src/github/workflows.ts
> +    github._registerWorkflow(name, this);
Might be more idiomatic to look up than to register. I think this is how findFile works.

2021-11-25 06:59 UTC, eladb commented on src/github/workflows.ts
> +  public _addJobsFromProvider(provider: IJobProvider) {
Add docs

2021-11-25 06:59 UTC, eladb commented on src/github/workflows.ts
> +  readonly jobs: Record<string, workflows.Job>;
I'd use a method instead of a property here to signal that this can be late bound.

Something like `renderJobs()`

2021-11-25 06:59 UTC, eladb commented on src/github/workflows.ts
> +  public _addJobsFromProvider(provider: IJobProvider) {
I'd make this public can all it `addJobsLater()`

2021-11-26 04:17 UTC, Chriscbr commented on src/github/workflows.ts
> +  public _addJobsFromProvider(provider: IJobProvider) {
Done

2021-11-26 04:20 UTC, Chriscbr commented on src/github/workflows.ts
> +  public _addJobsFromProvider(provider: IJobProvider) {
Good suggestion. I like how colloquial the name sounds

2021-11-26 04:48 UTC, eladb approved these changes

2021-11-26 04:48 UTC, eladb commented on src/github/github.ts
> +    return undefined;
```suggestion
    return this.workflows.find(w => w.name === name);
```

2021-11-26 05:00 UTC, merged