fix: error in IntegrationTest is not thrown correctly
projen/projen pull request #1276
Opened 2021-12-01 01:58 UTC by Chriscbr

`getDependency` throws an error if the dependency isn't found, so the "ts-node dependency is required for integration tests" error message never appears to the user.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-01 07:05 UTC, eladb requested changes

2021-12-01 07:05 UTC, eladb commented on src/awscdk/integration-test.ts
> -    if (!project.deps.getDependency('ts-node')) {
Can we add `tryGetDependency()`?

2021-12-01 20:50 UTC, Chriscbr commented on src/awscdk/integration-test.ts
> -    if (!project.deps.getDependency('ts-node')) {
Done!

2021-12-02 07:34 UTC, eladb requested changes

2021-12-02 07:34 UTC, eladb commented on src/deps/dependencies.ts
> +  public tryGetDependency(name: string, type?: DependencyType): Dependency | undefined {
Try to avoid catching exceptions in happy flows since they could be thrown for many different reasons. 

Implement `getDependency()` by means of `tryGetDepencency()` instead of the other way.

2021-12-02 21:16 UTC, Chriscbr commented on src/deps/dependencies.ts
> +  public tryGetDependency(name: string, type?: DependencyType): Dependency | undefined {
Ahh yeah this makes sense. Updated.

2021-12-07 19:05 UTC, Chriscbr commented
Superseded by #1302

2021-12-07 19:05 UTC, closed without merging