feat: adding ability to set git-push flags for manual releases
projen/projen pull request #1277
Opened 2021-12-01 06:05 UTC by willdady

closes #1267 

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-01 08:17 UTC, eladb requested changes

2021-12-01 08:17 UTC, eladb commented on src/release/release-trigger.ts
> +   readonly gitPushFlags?: string[]
Where is this used? Is it passed down to `ReleaseTrigger`'s constructor?

2021-12-01 08:17 UTC, eladb commented on src/release/release-trigger.ts
> +  readonly gitPushFlags?: string[]
Add modifier:

```suggestion
  public readonly gitPushFlags?: string[]
```

Also - who consumed this property?

2021-12-01 08:17 UTC, eladb commented on src/release/publisher.ts
> +    publishTask.exec(`git push ${flags} origin ${gitBranch}`);
Missing unit tests

2021-12-01 21:45 UTC, willdady commented on src/release/release-trigger.ts
> +   readonly gitPushFlags?: string[]
I had somehow missed this and have fixed. Yes this is now passed correctly to the constructor via the `manual` static method e.g. `ReleaseTrigger.manual({ gitPushFlags: ['-o', 'skip.ci'] })`

2021-12-01 21:47 UTC, willdady commented on src/release/release-trigger.ts
> +  readonly gitPushFlags?: string[]
Done. Modifier added.

2021-12-01 21:47 UTC, willdady commented on src/release/publisher.ts
> +    publishTask.exec(`git push ${flags} origin ${gitBranch}`);
Test has been updated

2021-12-02 02:02 UTC, willdady commented
Closing this because I don't think this is the best approach. It would be simpler to allow the user to override the `git push` command in it's entirety, rather than _just_ the flags. e.g.

```
ReleaseTrigger.manual({ gitPushCommand: `git push --follow-tags -o ci.skip origin ${CI_DEFAULT_BRANCH}` })
```

2021-12-02 02:02 UTC, closed without merging