feat: allow customising or disabling git-push used by manual release
projen/projen pull request #1282
Opened 2021-12-02 21:39 UTC by willdady

This adds the ability for a user to customise (or disable) the git-push command which is run as part of a manual release.

closes #1267 

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-02 22:31 UTC, Chriscbr requested changes
Thanks for submitting this PR! Just one requested API change below.

2021-12-02 22:31 UTC, Chriscbr commented on src/release/publisher.ts
> +  readonly gitPushCommand?: string | null;
```suggestion
  readonly gitPushCommand?: string;
```

Projen is compiled with JSII to other languages where `undefined` and `null` will be treated as equivalent, so distinguishing between them may lead to errors.

How about we instead add a line in the docstring that says e.g. `To disable pushing, use a no-op command such as "true"`?

2021-12-03 00:41 UTC, willdady commented on src/release/publisher.ts
> +  readonly gitPushCommand?: string | null;
Thanks @Chriscbr. How about, `To disable pushing, set to an empty string`? 

I feel `gitPushCommand: true` reads a little weirdly for something which is disabling something.

2021-12-03 21:45 UTC, Chriscbr commented on src/release/publisher.ts
> +  readonly gitPushCommand?: string | null;
Fair point. I suppose the alternative here is to add another field. This solution sounds good to me. 🙂

2021-12-03 21:45 UTC, Chriscbr approved these changes

2021-12-03 21:48 UTC, Chriscbr commented
From the build error it looks like PR code just needs to be linted and the docs updated (`yarn eslint` and `yarn docgen` probably)

2021-12-04 07:10 UTC, willdady commented
Build is failing as it's trying to do a git-push to _my_ fork?

2021-12-04 21:42 UTC, Chriscbr commented
The actual error is in the build step right before (this is a bit confusing). It should be possible to fix this by merging the latest changes from `main` and re-building

2021-12-04 21:46 UTC, willdady commented
> The actual error is in the build step right before (this is a bit confusing). It should be possible to fix this by merging the latest changes from `main` and re-building

@Chriscbr Thanks. I've just done this now.

2021-12-04 22:09 UTC, Chriscbr commented
Sorry for the confusion - when I said it will be fixed by "re-building" I meant running a build on your local machine, and then committing any of the changes that it makes (it may update test snapshots or docs) to your branch. If you look at the diff, you can see it incorrectly includes changes to "cdk8sPlusVersion" in API.md that are unrelated to your PR.

2021-12-05 02:49 UTC, merged