fix(cleanup): Add manifest of generated files and use it for cleaning
projen/projen pull request #1306
Opened 2021-12-07 23:56 UTC by MarkMcCulloh

fixes #1265

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-08 06:36 UTC, eladb requested changes

2021-12-08 06:36 UTC, eladb commented on src/cleanup.ts
> +export const FILE_MANIFEST = '.projen/files.json';
There's a const for `.projen` somewhere :-)

2021-12-08 06:36 UTC, eladb commented on src/cleanup.ts
> +    fileFile.files.forEach((file: string) => {
style: please use a normal `for` loop instead of `.forEach()`

2021-12-08 06:36 UTC, eladb commented on src/cleanup.ts
> +    const fileFile = JSON.parse(readFileSync(fileManifestPath, 'utf-8'));
Handle the case when this file is corrupted (fall back to previous behavior)

2021-12-08 06:36 UTC, eladb commented on src/project.ts
> +        files: this.files.filter(f => f.readonly).map(f => f.path.replace(/\\/g, '/')),
why do we need the `replace()` here?

2021-12-08 06:36 UTC, eladb commented on src/cleanup.ts
> +      for (const f of findGeneratedFiles(dir, exclude)) {
Can you please add a unit test?

2021-12-08 06:40 UTC, eladb commented
@MarkMcCulloh looks great. I've updated the title to reflect the problem this fix is solving. 
Also, please add details to your PR description about the "how" this is is implemented.

2021-12-08 14:44 UTC, MarkMcCulloh commented on src/project.ts
> +        files: this.files.filter(f => f.readonly).map(f => f.path.replace(/\\/g, '/')),
Forcing posix paths for windows users to prevent any issues there

2021-12-08 14:58 UTC, MarkMcCulloh commented on src/project.ts
> +        files: this.files.filter(f => f.readonly).map(f => f.path.replace(/\\/g, '/')),
If this is not done it would be possible for discrepancies between window/non-windows users in this file. Seems to be worth avoiding that.

2021-12-09 02:57 UTC, Chriscbr commented on src/util/synth.ts
> +  readonly excludeContent?: boolean;
optional: The type signature is different from "excludeGlobs" so it might make sense to name it differently
```suggestion
  /**
   * Only snapshot the names of files and not their contents.
   * The value for a path will be `true` if it exists.
   *
   * @default false include file content
   */
  readonly omitContents?: boolean;
```

2021-12-09 02:57 UTC, Chriscbr commented on src/cleanup.ts
> +  }
It might simplify the control flow / improve readability to break when conditions fail instead of nesting the happy cases together. e.g.

```ts
const fileManifestPath = path.resolve(dir, FILE_MANIFEST);
if (!existsSync(fileManifestPath)) {
  return legacyCleanup(...);
}

const fileManifest = JSON.parse(readFileSync(fileManifestPath, 'utf-8'));
if (!fileManifest.files) {
  return legacyCleanup(...);
}

// actual work
```

2021-12-09 02:57 UTC, Chriscbr commented on test/cleanup.test.ts
> +});
Perhaps we should explicitly validate here that foo/bar.txt was NOT deleted even though it does not have the projen marker in it - since I believe this is new behavior?

2021-12-09 03:44 UTC, MarkMcCulloh commented on test/cleanup.test.ts
> +});
There is a new behavior, but it's the opposite of that: `foo/bar.txt` IS deleted even though it does not have the projen marker in it. I updated the test with some more assertions as well as the PR description to be more clear.

2021-12-09 03:48 UTC, MarkMcCulloh commented on src/cleanup.ts
> +  }
I made some changes and I think the flow is more clear although it is different than you suggested. Let me know if it could still be better, I'm happy to oblige 😁

2021-12-09 10:00 UTC, eladb requested changes
Please resolve all remaining conversation

2021-12-09 10:00 UTC, eladb commented on src/project.ts
> +        files: this.files.filter(f => f.readonly).map(f => f.path.replace(/\\/g, '/')),
k. add a comment explaining that in the code plz (isn't there a better way to do it? `path.posix` or something?)

2021-12-09 10:00 UTC, eladb commented on src/util/synth.ts
> +  readonly omitContents?: boolean;
Nit: always use "positive" names (avoid "omit", "disable", etc). So I'd call this something like `includeContents` (with `true` as default) or `onlyFileNames` (with `false as a default).

2021-12-10 23:16 UTC, MarkMcCulloh commented on src/project.ts
> +        files: this.files.filter(f => f.readonly).map(f => f.path.replace(/\\/g, '/')),
These paths may or may not be fully user-controlled, so unfortunately afaik this is the only place this logic could be to catch this.
I do wish `path` had a helper for this.

2021-12-12 12:50 UTC, eladb approved these changes

2021-12-12 12:57 UTC, merged