fix: codecov should run on main branch to generate baseline
projen/projen pull request #1320
Opened 2021-12-10 22:03 UTC by ahammond

Per https://docs.codecov.com/docs/error-reference
"In order to produce an accurate coverage comparison,
Codecov must have the coverage report for the pull request base."

Users who are using squash commits can't re-use the last uploaded
coverage from the previously merged feature-branch as the base.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-11 06:07 UTC, Chriscbr requested changes
Please add a unit test

2021-12-13 14:27 UTC, eladb requested changes

2021-12-13 14:27 UTC, eladb commented on src/javascript/node-project.ts
> +      // run codecov if enabled or a secret token name is passed in
Why do we need to add this to the release workflow? Can we just create a separate workflow to keep the code coverage baseline?


Wondering if this might be a good opportunity to extract a `CodeCov` component which will take care of adding itself to the workflows.

2021-12-13 16:20 UTC, ahammond commented on src/javascript/node-project.ts
> +      // run codecov if enabled or a secret token name is passed in
Ooooooh, that'd be cool. The only reason I figured to pack it in here is that tests have already run and there's coverage data free for the taking.

2021-12-28 18:50 UTC, ahammond commented
Should I add a UT for this or make a separate workflow?

2021-12-29 15:17 UTC, eladb commented on src/javascript/node-project.ts
> +      // run codecov if enabled or a secret token name is passed in
Let's create a `CodeCov` component and bake this knowledge in there (and also move the stuff from the build workflow in)

2022-01-02 21:20 UTC, eladb commented
## Please read this to avoid merge hell

Hola! apologies for hassle. I've enabled Prettify as part of #1453. This means that most of the source files have changed and you will likely see quite a lot of merge conflicts when you try to merge from `main`.

*But there's an easy way to handle this.*

First, merge your branch from this tag:

```sh
$ git fetch origin
$ git merge 1020d0ad3f95bb4e1201f8640d440ffb43ccf230
```

Edit the `.projenrc.js` file in your branch and add this to **line 57** (right
after `codeCov: true`):

```js
  prettier: true,
```

Now, run:

```sh
$ git clean -fdx .
$ yarn
$ bash projen.bash
$ yarn eslint
$ git add .
$ git commit -m 'format code'
```

This will reformat all the code in your branch to match `main`.

Now, merge from main:

```sh
$ git merge origin/main
```

Sorry again for the inconvenience...

2022-01-20 01:31 UTC, closed without merging

2022-02-09 02:19 UTC, ahammond commented on src/javascript/node-project.ts
> +      // run codecov if enabled or a secret token name is passed in
@eladb is there any guidance on how to do this (create a CodeCov component)? I'm willing to do some work on this, but I'm out of my depth. Is there an example component I could pattern this after?