fix(awscdk): generated lambda code not compatible with CDK v2
projen/projen pull request #1327
Opened 2021-12-13 10:03 UTC by eladb

Extract the logic that handles CDK dependencies (and supports v1/v2 differences) into a new component called `AwsCdkDeps` and reuse across  `AwsCdkTypeScriptApp` and `AwsCdkConstructLibrary`.

Then, use it in `LambdaFunction` to determine how to render import statements in the generated function construct source code.

Change the default CDK version for `awscdk-app-ts` to `^2`.

BREAKING CHANGE: The `cdkVersion` option is now a *semver range* and not just a specific version. To enable the previous behavior, prefix with `^`.
* **awscdk:** `LambdaFunction` and `AutoDiscover` now requires `cdkDeps` so they can interact with CDK version manager.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-13 15:10 UTC, corymhall reviewed
The only thing I keep going back and forth on is if we should have any special handling of the `-alpha` modules. Right now we are just requiring users to add them as `peerDeps` or `deps`, but maybe we should keep using `cdkDependencies`? By removing `cdkDependencies` we are removing some of the abstraction when maybe we shouldn't.

Otherwise LGTM.

2021-12-13 15:13 UTC, corymhall approved these changes

2021-12-13 15:38 UTC, eladb commented
> The only thing I keep going back and forth on is if we should have any special handling of the `-alpha` modules.

I feel like we might want to add a separate abstraction for this in the future

2021-12-13 15:44 UTC, eladb commented on src/awscdk/awscdk-app-ts.ts
> +  expect(template.toJSON()).toMatchSnapshot();
We can tweak it later. I kind of like the fact that this is actually capturing the app.

2021-12-13 17:49 UTC, Chriscbr requested changes
Nice encapsulation!

Please check if any of the docs need to be updated or moved relating to dependencies - e.g. https://github.com/projen/projen/blob/main/docs/awscdk-construct.md#dependencies

2021-12-13 17:49 UTC, Chriscbr commented on src/awscdk/awscdk-deps.ts
> +  readonly constructsVersion?: string;
The indentation of *'s is a inconsistent throughout this file (cleanup)

2021-12-13 17:49 UTC, Chriscbr commented on src/awscdk/awscdk-deps.ts
> +   * Adds CDK modules as test dependencies.
nit: explain what this means (I'm not sure if "test dependencies" is universally understood)

2021-12-13 17:49 UTC, Chriscbr commented on src/awscdk/awscdk-deps.ts
> +    this.addRuntimeDeps(...deps.map(m => this.formatModuleSpec(m)));
What do you mean? can we not guard this in a "if cdkMajorVersion !== 2" branch? Do we need "runtime" type dependencies even in library type projects?

2021-12-13 17:49 UTC, Chriscbr commented on test/__snapshots__/new.test.ts.snap
> +  cdkVersion: \\"^2\\",
Should we call this out as a breaking change?

2021-12-13 17:49 UTC, Chriscbr commented on test/__snapshots__/new.test.ts.snap
> +  // release: undefined,      /* Add release management to this project. */
I wonder if we should highlight / feature any options relating to the new features you've added (feel free to leave as is)

2021-12-13 17:49 UTC, Chriscbr commented on test/awscdk/awscdk-app.test.ts
>  import { mkdirSync, writeFileSync } from 'fs';
Ahh just realizing now I moved a lot of the source files as part of The Big Refactoring, but didn't move/rename the tests to match up. I should clean up the rest when I have a chance

2021-12-13 17:49 UTC, Chriscbr commented on src/awscdk/awscdk-deps.ts
> +   */
Why is this required? Perhaps include guidance on which kind of dependency type to use?

2021-12-14 06:38 UTC, eladb commented on src/awscdk/awscdk-deps.ts
> +  readonly constructsVersion?: string;
Fixed

2021-12-14 06:39 UTC, eladb commented on src/awscdk/awscdk-deps.ts
> +   */
added

2021-12-14 06:41 UTC, eladb commented on src/awscdk/awscdk-deps.ts
> +    this.addRuntimeDeps(...deps.map(m => this.formatModuleSpec(m)));
The name of this private method is misleading. It will add a dependency based on `dependencyType`. I'll rename.

2021-12-14 06:45 UTC, eladb commented on src/awscdk/awscdk-deps.ts
> +    this.addRuntimeDeps(...deps.map(m => this.formatModuleSpec(m)));
Renamed to `addDepsWithRequestedType()` and simplified this method.

2021-12-14 06:46 UTC, eladb commented on src/awscdk/awscdk-deps.ts
> +   * Adds CDK modules as test dependencies.
Renamed to `addCdkDevDependencies()`.

2021-12-14 07:54 UTC, Chriscbr requested changes

2021-12-14 07:54 UTC, Chriscbr commented on src/awscdk/awscdk-construct.ts
> +   * @deprecated Not supported in v2. For v1, use `project.cdkDeps.addCdkDependencies()`
```suggestion
   * @deprecated Not supported in v2. For v1, use `project.cdkDeps.addV1Dependencies()`
```

2021-12-14 07:54 UTC, Chriscbr commented on src/awscdk/awscdk-construct.ts
> +   * @deprecated Not supported in v2. For v1, use `project.cdkDeps.addCdkDevDependencies()`
```suggestion
   * @deprecated Not supported in v2. For v1, use `project.cdkDeps.addV1DevDependencies()`
```

2021-12-14 08:05 UTC, eladb commented on test/__snapshots__/new.test.ts.snap
> +  // release: undefined,      /* Add release management to this project. */
Leaving as is for now

2021-12-14 08:06 UTC, eladb commented on test/__snapshots__/new.test.ts.snap
> +  cdkVersion: \\"^2\\",
This is actually not a breaking change because `cdkVersion` is a required property. It will just change the initial value for new projects, but won't break any existing users.

2021-12-14 12:11 UTC, merged