feat: GitLab CI model and base classes
projen/projen pull request #1357
Opened 2021-12-20 21:37 UTC by dontirun

Related to #137, #942

This PR adds the model and some opinionated base classes for GitLab CI configurations (which should be reviewed). This currently does not tie the classes into a project configuration. I have not added any tests, but would be happy to add them as this PR progresses.

Base schema from [here](https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json)
Initial TypeScript Interfaces (before opinionated modifications) generated from [here](https://app.quicktype.io/#)

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-27 20:45 UTC, Chriscbr requested changes
This looks like a great start! I think it would be awesome to have GitLab components in projen.

I've added some initial comments below. Be sure to add tests, and if you could also write up a short high level summary in `docs/gitlab.md` it would be very helpful for understanding the API as well.

2021-12-27 20:45 UTC, Chriscbr commented on src/gitlab/configuration-model.ts
> + * Default settings for the CI Configuration.
Please clarify what these defaults mean/do (do they apply just to the jobs within this file?)

2021-12-27 20:45 UTC, Chriscbr commented on src/gitlab/configuration.ts
> +  }
I think it might be preferable to remove this API and simply let users provide a value the constructor and make `default` property public and mutable through getters/setters.

2021-12-27 20:45 UTC, Chriscbr commented on src/gitlab/configuration.ts
> +  public configurePagesJob(job: Job) {
See comment on configureDefault

2021-12-27 20:45 UTC, Chriscbr commented on src/gitlab/configuration.ts
> +      if (this.services.includes(service)) {
I'm not sure if this will work as intended since Service is an interface and the objects might be equal-by-value but different in identity. Please add a unit test for this

2021-12-27 20:45 UTC, Chriscbr commented on src/gitlab/configuration.ts
> +  constructor(project: Project, name: string) {
I think it should be possible to configure many of the options at construction time, no?
```suggestion
  constructor(project: Project, name: string, options: CiConfigurationOptions) {
```

Same goes for the GitlabConfiguration and NestedConfiguration classes.

2021-12-27 20:45 UTC, Chriscbr commented on src/gitlab/configuration.ts
> +    variables: Record<string, number | VariableConfig | string>,
We can't represent type unions in the languages JSII transliterates to, so as this is a public API, I'd prefer changing the type signature to `Record<string, any>` here.

2021-12-27 20:45 UTC, Chriscbr commented on src/gitlab/configuration.ts
> +  public configureWorkflow(workflow: Workflow) {
See comment on configureDefault

2021-12-27 20:45 UTC, Chriscbr commented on src/gitlab/gitlab-configuration.ts
> +  public createNestedTemplates(...names: string[]) {
Explain in the docstring how to customize the nested templates since it seems like in this method we can only provide the names of the new templates.

Would it make sense if instead the took as a parameter `Record<string, NestedConfigurationOptions>` or `Record<string, CiConfigurationOptions>` instead?

2021-12-27 20:45 UTC, Chriscbr commented on src/gitlab/configuration.ts
> +        : `.gitlab/ci-templates/${name.toLocaleLowerCase()}.yml`;
Perhaps document this behavior in the class docstring and/or in `docs/gitlab.md`

2021-12-28 18:44 UTC, dontirun commented on src/gitlab/configuration-model.ts
> +       */
Running `npx projen eslint` is reformatting the multi-line 'nested' docstrings to look like this. I agree it's ugly. I'll change these to be single line to make it look better.

2021-12-28 20:17 UTC, dontirun commented on src/gitlab/gitlab-configuration.ts
> +  public createNestedTemplates(...names: string[]) {
I like the idea of `Record<string, CiConfigurationOptions>` . I'll add some details on how to make further configuration changes in the docstring

2021-12-28 20:52 UTC, dontirun commented on src/gitlab/configuration-model.ts
> +       */
FIxed in https://github.com/projen/projen/pull/1357/commits/d0f34e044b1ca39ad40233c42eb4002c3e91ed21

2021-12-28 20:53 UTC, dontirun commented on src/gitlab/configuration-model.ts
> + * Default settings for the CI Configuration.
FIxed in https://github.com/projen/projen/pull/1357/commits/d0f34e044b1ca39ad40233c42eb4002c3e91ed21

2021-12-28 21:06 UTC, dontirun commented on src/gitlab/configuration.ts
> +  }
Updated in https://github.com/projen/projen/pull/1357/commits/cee5171ae03af5ebdc4da06eb2f5331d3c5a94fe

2021-12-28 21:06 UTC, dontirun commented on src/gitlab/configuration.ts
> +  public configurePagesJob(job: Job) {
Updated in https://github.com/projen/projen/pull/1357/commits/cee5171ae03af5ebdc4da06eb2f5331d3c5a94fe

2021-12-28 21:06 UTC, dontirun commented on src/gitlab/configuration.ts
> +      if (this.services.includes(service)) {
fixed  and added tests in https://github.com/projen/projen/pull/1357/commits/a9c83f899dce32885b209531fdf9c1fca2ae40bd

2021-12-28 21:07 UTC, dontirun commented on src/gitlab/configuration.ts
> +  constructor(project: Project, name: string) {
Resolved in https://github.com/projen/projen/pull/1357/commits/6d42ed0b3bd482a03fb6924aff5f964a01fd5f90

2021-12-28 21:08 UTC, dontirun commented on src/gitlab/configuration.ts
> +    variables: Record<string, number | VariableConfig | string>,
Resolved in https://github.com/projen/projen/pull/1357/commits/d0f34e044b1ca39ad40233c42eb4002c3e91ed21

2021-12-28 21:08 UTC, dontirun commented on src/gitlab/configuration.ts
> +  public configureWorkflow(workflow: Workflow) {
Updated in https://github.com/projen/projen/pull/1357/commits/cee5171ae03af5ebdc4da06eb2f5331d3c5a94fe

2021-12-28 21:09 UTC, dontirun commented on src/gitlab/gitlab-configuration.ts
> +  public createNestedTemplates(...names: string[]) {
Resolved in https://github.com/projen/projen/pull/1357/commits/26866b2b9f27a0450049df1f47c01b03b28b82f1

2021-12-28 21:10 UTC, dontirun commented on src/gitlab/configuration.ts
> +        : `.gitlab/ci-templates/${name.toLocaleLowerCase()}.yml`;
I added some details to the docstring in https://github.com/projen/projen/pull/1357/commits/26866b2b9f27a0450049df1f47c01b03b28b82f1, but I think a `docs/gitlab.md` file would be helpful to have as well

2021-12-28 22:19 UTC, dontirun commented on src/gitlab/configuration.ts
> +        : `.gitlab/ci-templates/${name.toLocaleLowerCase()}.yml`;
Added `docs/gitlab.md` documentation in https://github.com/projen/projen/pull/1357/commits/e2ec61092f40ccc8a8ab32aea75735b9587ea4da

2021-12-29 00:45 UTC, Chriscbr requested changes

2021-12-29 00:45 UTC, Chriscbr commented on docs/gitlab.md
> +[GitLab CI/CD](https://docs.gitlab.com/ee/ci/yaml/gitlab_ci_yaml.html) uses a `.gitlab-ci.yml` configuration located in the root of your repository. Optionally `.gitlab-ci.yml` files can be split int
Let me know if this sounds any better
```suggestion
[GitLab CI/CD](https://docs.gitlab.com/ee/ci/yaml/gitlab_ci_yaml.html) uses a `.gitlab-ci.yml` file located at the root of your repository to specify continuous integration and continuous deployment processes. GitLab CI configuration files can be split into multiple files using the [include](https://docs.gitlab.com/ee/ci/yaml/#include) fields in order to increase readability or reduce duplication of the same configuration in multiple places.
```

2021-12-29 00:45 UTC, Chriscbr commented on src/gitlab/configuration.ts
> +  readonly default?: Default;
Please add docstrings for the other options in this interface (default, workflow, jobs)

2021-12-29 00:45 UTC, Chriscbr commented on src/gitlab/configuration.ts
> +  public addServices(...services: (string | Service)[]) {
Does specifying a service with a string have the same meaning as using `{ name: 'the-string' }`? if so, I feel like this is an implementation detail that probably shouldn't be covered in our API -- plus introducing type unions makes the API more obtuse when this gets compiled to other languages using JSII.

Can we simplify the API like this maybe:
```suggestion
  public addService(options: Service) {
```
(Users can call this in a for loop to add multiple services if they want)

2021-12-29 00:45 UTC, Chriscbr commented on src/gitlab/configuration.ts
> +  public default?: Default;
These fields should be kept readonly since they may refer to objects/arrays, and leaving them mutable by anyone can lead to object reference issues. We can add (safe) getters/setters/methods to mutate these later if needed
```suggestion
  public readonly default?: Default;
```

2021-12-29 00:45 UTC, Chriscbr commented on src/gitlab/configuration.ts
> +  public pages?: Job;
```suggestion
  public readonly pages?: Job;
```

2021-12-29 00:45 UTC, Chriscbr commented on src/gitlab/configuration.ts
> +  public workflow?: Workflow;
```suggestion
  public readonly workflow?: Workflow;
```

2021-12-29 02:22 UTC, dontirun commented
I previously missed that the Global `services` keyword [is deprecated](https://docs.gitlab.com/ee/ci/yaml/#globally-defined-image-services-cache-before_script-after_script).

In general it might make more sense to make a property in the `CiConfiguration` Class for each of the properties in the `Default` interface (ex. `defaultAfterScript`) and reassemble everything in the `renderCI` method.

This would also give more flexibility in adding more methods to help the user configure these properties 

```typescript
  private renderCI() {
    return {
      default: { afterScript: this.defaultAfterScript, ... },
      include:
        this.include.length > 0 ? snakeCaseKeys(this.include) : undefined,
      pages: snakeCaseKeys(this.pages),
      services:
        this.services.length > 0 ? snakeCaseKeys(this.services) : undefined,
      variables:
        Object.entries(this.variables).length > 0 ? this.variables : undefined,
      workflow: snakeCaseKeys(this.workflow),
      stages: this.stages.length > 0 ? this.stages : undefined,
      ...snakeCaseKeys(this.jobs),
    };
  }
}

```

2021-12-30 20:01 UTC, Chriscbr requested changes
Just a few more small changes and I think this PR is about ready to ship 👍 

On further thought, I'm not totally sure what the best practices are here regarding leaving class properties public or private, since this class is both like an L1 (not a lot of opinionated defaults) but also like an L2 (it some provides convenience methods). I want to say it probably makes sense to make most of the properties private by default so that they can be changed as needed in the future and make the class more L2-like, but I don't have a strong opinion on this.

@eladb do you have any guidance here?

2021-12-30 22:39 UTC, dontirun commented on src/gitlab/configuration.ts
> +   * Path to CI file egenrated by the configuration.
```suggestion
   * Path to CI file generated by the configuration.
```

2021-12-30 23:28 UTC, dontirun commented on src/gitlab/configuration.ts
> +      }
Something like this?

```typescript
/**
 * Throw an error if the provided Include is invalid.
 * @see https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/config/external/mapper.rb
 * @param include the Include to validate.
 */
private assertIsValidInclude(include: Include) {
  const combos = [include.local, (include.file && include.project), include.remote, include.template];
  const len = combos.filter(x => Boolean(x)).length
  if (len !== 1) {
    throw new Error(
      `${this.name}: GitLab CI include ${include} contains ${len} property combination(s).
      A valid include configuration specifies *one* of the following property combinations.
      * local
      * file, project
      * remote
      * template  
      `
    );
  }
}
```

2021-12-30 23:51 UTC, dontirun commented
> Just a few more small changes and I think this PR is about ready to ship 👍
> 
> On further thought, I'm not totally sure what the best practices are here regarding leaving class properties public or private, since this class is both like an L1 (not a lot of opinionated defaults) but also like an L2 (it some provides convenience methods). I want to say it probably makes sense to make most of the properties private by default so that they can be changed as needed in the future and make the class more L2-like, but I don't have a strong opinion on this.
> 
> @eladb do you have any guidance here?

My thoughts here were to make this closer to a L1, but with some private properties (with convenience methods) to prevent the creation of CI files with invalid field configurations.

In the future I would like something closer to the `GithubProject` (or what comes out of this [RFC](https://github.com/projen/projen/issues/942)) where standard jobs are created for the different workflows that projen uses for GitHub (Release, build, etc). That future `GithubProject` would probably have more private properties as it would be closer to a L3

2021-12-30 23:52 UTC, Chriscbr commented on src/gitlab/configuration.ts
> +      }
Yes that looks good.

2021-12-30 23:58 UTC, dontirun commented on src/gitlab/configuration.ts
> +      }
Updated in https://github.com/projen/projen/pull/1357/commits/b85f20e419841c9702317913f937f6718d319c72

2022-01-02 18:11 UTC, Chriscbr approved these changes

2022-01-02 21:19 UTC, eladb commented
## Please read this to avoid merge hell

Hola! apologies for hassle. I've enabled Prettify as part of #1453. This means that most of the source files have changed and you will likely see quite a lot of merge conflicts when you try to merge from `main`.

*But there's an easy way to handle this.*

First, merge your branch from this tag:

```sh
$ git fetch origin
$ git merge 1020d0ad3f95bb4e1201f8640d440ffb43ccf230
```

Edit the `.projenrc.js` file in your branch and add this to **line 57** (right
after `codeCov: true`):

```js
  prettier: true,
```

Now, run:

```sh
$ git clean -fdx .
$ yarn
$ bash projen.bash
$ yarn eslint
$ git add .
$ git commit -m 'format code'
```

This will reformat all the code in your branch to match `main`.

Now, merge from main:

```sh
$ git merge origin/main
```

Sorry again for the inconvenience...

2022-01-02 21:46 UTC, merged