feat(awscdk-app-ts): add synth:silent cdk task
projen/projen pull request #1364
Opened 2021-12-23 19:36 UTC by dannysteenman

In a recent [pull request](https://github.com/projen/projen/pull/1323) the projen tasks like "projen synth" got updated and write their output to "/dev/null". 

I mostly run `projen synth` locally to debug my code by adding various console.log calls but now they get suppressed by default. So with this PR, I would like to introduce a new cdk task that adds surpression by running `projen synth:silent`. 

Another reason to revert the change is to stay consistent with the mapping of the task `cdk synth`. 

I've tested it in a new project and this is what the tasks look like in `.projen/tasks.json`:
```json
    "synth": {
      "name": "synth",
      "description": "Synthesizes your cdk app into cdk.out (part of \"yarn build\")",
      "steps": [
        {
          "exec": "cdk synth"
        }
      ]
    },
    "synth:silent": {
      "name": "synth:silent",
      "description": "Synthesizes your cdk app into cdk.out and surpresses the template in stdout (part of \"yarn build\")",
      "steps": [
        {
          "exec": "cdk synth > /dev/null"
        }
      ]
    },
```

and in `package.json`:
```json
    "synth": "npx projen synth",
    "synth:silent": "npx projen synth:silent",
```

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-24 06:28 UTC, eladb requested changes
Where is the part that we switch which task is executed using "build"

2021-12-24 06:28 UTC, eladb commented on src/awscdk/cdk-tasks.ts
>        description: 'Synthesizes your cdk app into cdk.out (part of "yarn build")',
Remove "part of yarn build" here

2021-12-24 09:33 UTC, dannysteenman commented on src/awscdk/cdk-tasks.ts
>        description: 'Synthesizes your cdk app into cdk.out (part of "yarn build")',
Updated description and updated the postCompileTask in the build to use the silent synth cdk task

2021-12-24 09:34 UTC, eladb requested changes
Can you please add a unit test?

2021-12-24 09:34 UTC, dannysteenman commented on src/awscdk/awscdk-app-ts.ts
> +    this.postCompileTask.spawn(this.cdkTasks.synthSilent);
Updated postCompileTask to use the silent synth cdk task.

2021-12-26 07:02 UTC, eladb approved these changes

2021-12-27 08:50 UTC, dannysteenman commented
@eladb something is going wrong on the self mutation step in the build action. Is there something I need to enable/modify on my side to make it pass?

2021-12-27 09:21 UTC, eladb commented
Yes, build locally and push any changes.

Self mutation doesn't work on forks (see https://github.com/projen/projen/issues/1362)

2021-12-27 10:38 UTC, dannysteenman commented
somehow I missed the eslint correction, sorry for that.

2021-12-27 20:07 UTC, merged