RFC: Project creation prompts
projen/projen pull request #1365
Opened 2021-12-24 01:46 UTC by MarkMcCulloh

There are no open issues on this currently, but a relevant one for this is #613.

Requesting feedback on the proposal for an interactive experience in `projen new`.

[Rendered Version](https://github.com/MarkMcCulloh/projen/blob/prompts-rfc/rfcs/project-creation-prompt.md)

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-24 06:24 UTC, eladb requested changes
Looks good to me. @Chriscbr thoughts?

2021-12-24 06:24 UTC, eladb commented on rfcs/project-creation-prompt.md
> +- `@promptType` - See https://github.com/terkelg/prompts#-types
Isn't the jsii type sufficient here?

2021-12-24 06:24 UTC, eladb commented on rfcs/project-creation-prompt.md
> +- `@promptMessage` - See https://github.com/terkelg/prompts#message
Can you maybe provide some
Examples on user cases  for where these will be used

2021-12-24 07:12 UTC, MarkMcCulloh commented on rfcs/project-creation-prompt.md
> +- `@promptType` - See https://github.com/terkelg/prompts#-types
In most cases yes, although I can think of at least one advanced use case for overriding it. Updated with this example:

- An array would have a default prompt type of [list](https://github.com/terkelg/prompts#listmessage-initial).  
  `@promptType multiselect` would allow you to provide a set of distinct options instead.

2021-12-24 07:13 UTC, MarkMcCulloh commented on rfcs/project-creation-prompt.md
> +- `@promptMessage` - See https://github.com/terkelg/prompts#message
A couple of examples have been added 👍

2021-12-25 00:43 UTC, Chriscbr reviewed
Looks good to me!

What happens if someone uses `projen new` (without any flags) outside of a TTY, such as in a bash script? error perhaps?

2021-12-25 00:43 UTC, Chriscbr commented on rfcs/project-creation-prompt.md
> +There is one exception: If a project option meets the above criteria but is also:
Is this saying no prompts at all will be shown by default, or that the only prompt shown by default will be the one to choose the project type?

2021-12-25 20:24 UTC, MarkMcCulloh commented on rfcs/project-creation-prompt.md
> +There is one exception: If a project option meets the above criteria but is also:
I corrected this to say `projen new <project>` instead of `projen new`. I think the overall idea is that prompts are not shown by default unless synthesis is not possible without them. So in the case of `projen new`, without additional info projen can't do anything. But in the case of `projen new typescript` for example, there is no current need for a prompt unless the user wants to opt-in with --prompt.

I added a section with some example situations to illustrate as well.

2021-12-25 20:28 UTC, MarkMcCulloh commented
> What happens if someone uses `projen new` (without any flags) outside of a TTY, such as in a bash script? error perhaps?

Good point, added a note on that in the doc: 

> We should check if in a TTY before a prompt is presented and error otherwise.

2021-12-29 17:58 UTC, Chriscbr approved these changes

2021-12-29 18:07 UTC, merged