feat: extend prettier support
projen/projen pull request #1367
Opened 2021-12-25 15:40 UTC by henrysachs

allow to create a prettierrc with all config values aswell as the corresponding ignore file
it also supports overrides

fixes #1318

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-25 16:05 UTC, henrysachs commented
I dont know if we should update the docs but the tests only run if 

`export EDITOR="vim"`

but some people for example me have configured their editor to be vscode for GIT or SOPS

2021-12-25 16:25 UTC, henrysachs commented
onfortunately the bump test doesn't run locally for me which blocks the build. I will probably turn it off locally to build projen and tinker with the config. It seems to run in CI.

2021-12-25 17:46 UTC, henrysachs commented
i also uploaded my sample repo to see the new feature in action: https://github.com/henrysachs/prettierprojen/blob/main/.projenrc.js

I will now try to implement a basic test and would like some feedback on the implementation. Maybe @bilalq wants to take a look if that matches what his issue described :)

2021-12-25 19:02 UTC, henrysachs commented
so as all checks went green i mark you @eladb and @Chriscbr and kindly ask you for a review. I don't see any other buttons to do this in the github ui and hope this is the intended way.

2021-12-26 07:52 UTC, eladb requested changes

2021-12-26 07:52 UTC, eladb commented on src/cdk/jsii-project.ts
> +  public readonly prettier?: Prettier;
Can we add this at a lower level? `TypeScriptProject` or even `NodeProject`?

Also, doesn't seem like this is being assigned anywhere.

2021-12-26 07:52 UTC, eladb commented on src/javascript/node-project.ts
> +  public addPrettierIgnore(pattern: string) {
Docstrings

2021-12-26 07:52 UTC, eladb commented on src/javascript/prettier.ts
> + * Respect the default value of CSS display property.
Please move the descriptions of the specific options to docstrings of individual members instead of the enum type itself.

(throughout this file)

2021-12-26 07:52 UTC, eladb commented on src/javascript/prettier.ts
> +  readonly arrowParens?: ArrowParens;
There seem to be duplication between `PrettierOverrideOptions` and `PrettierConfig`. Can we reuse somehow?

2021-12-26 07:52 UTC, eladb commented on src/javascript/prettier.ts
> +export interface PrettierConfig {
Rename to `PrettierOptions` to match convention

2021-12-26 07:52 UTC, eladb commented on src/javascript/prettier.ts
> +export interface PrettierConfig {
All public APIs should have docstrings:

```suggestion
/**
 * Options for `Prettier`.
 */
export interface PrettierConfig {
```

2021-12-26 07:52 UTC, eladb commented on src/javascript/prettier.ts
> +   * Which end of line characters to apply.
All optional (`?`) props should have a `@default` docstring tag which describes the default either explicitly as a value or via a description (see examples in the code).

2021-12-26 07:52 UTC, eladb commented on src/javascript/prettier.ts
> +  public readonly overrides: PrettierOverride[];
We prefer not to expose mutable arrays. You can use this pattern:

```ts
public readonly _overrides: PrettierOverride[];

public get overrides() { return [...this._overrides]; }
public addOverride(...) { this._overrides.push(...); }
```

2021-12-26 07:52 UTC, eladb commented on src/javascript/prettier.ts
> +  public readonly config: PrettierConfig;
These are not really escape hatches. Since you are using `JsonFile`, users can already escape hatch into this file directly. Escape hatches should not part of the API of the component.

Seems like this is just exposing the underlying configuration for mutation, which seems fine.

2021-12-26 07:52 UTC, eladb commented on src/typescript/typescript.ts
> +    if (options.prettier ?? false) {
Move to `NodeProject`.

2021-12-26 07:52 UTC, eladb commented on src/typescript/typescript.ts
> +   * @default false
Why not `true`?

2021-12-26 21:01 UTC, henrysachs commented on src/cdk/jsii-project.ts
> +  public readonly prettier?: Prettier;
i just took inspiration from eslint there as i find those two kinda complementary. Thats also why i haven't moved it to `NodeProject`. But I can do this as I prefer it too.

2021-12-26 21:02 UTC, henrysachs commented on src/typescript/typescript.ts
> +   * @default false
I was a bit hesitant as Prettier is opionated about formatting when turned on. Also than i need to toggle the eslint flag too. Would that be fine for you? if so the next topic would be if prettier in enabled in `NodeProject` eslint wouldn't exist but that shouldn't be a problem as the getter would just return undefined.

2021-12-26 21:03 UTC, henrysachs commented on src/javascript/prettier.ts
> +  public readonly config: PrettierConfig;
okay i just those comments from eslint tbh. I will change the comment.

2021-12-27 10:49 UTC, henrysachs commented
@eladb I have implemented all remarks but I'm still unsure about activating prettier by default because it is pretty opinionated about formatting and i'm not sure if any user wants to have this strict rules about this. Also I would need to set it in eslint where its currently off by default. I'm fine with both just want to clarify the impact. 😅

2021-12-27 10:54 UTC, henrysachs commented
had to update my fork because the build was failing

2021-12-29 11:11 UTC, henrysachs commented
@eladb not to stress you but had you had a chance looking at this? I think it resolved all points you had except the default value which I would like to discuss. ☺️

2021-12-29 12:21 UTC, eladb requested changes
A few additional minor changes. I am okay leaving the default disabled for now.

2021-12-29 12:21 UTC, eladb commented on src/javascript/node-project.ts
> +  * @param {string} pattern filepatterns so exclude from prettier formatting
type is already annotated in the code:

```suggestion
  * @param pattern filepatterns so exclude from prettier formatting
```

2021-12-29 12:21 UTC, eladb commented on src/javascript/prettier.ts
> + * @interface PrettierOptions
redundant:

```suggestion
```

2021-12-29 12:21 UTC, eladb commented on src/javascript/prettier.ts
> + * @export
Remove

2021-12-29 12:21 UTC, eladb commented on src/javascript/prettier.ts
> +  public readonly _overrides: PrettierOverride[];
Why does this need to be public?

2021-12-29 18:19 UTC, henrysachs commented on src/javascript/prettier.ts
> +  public readonly _overrides: PrettierOverride[];
I thought jsii had issues with privates. Changed to private as its available through the getter and setter.

2021-12-29 18:29 UTC, henrysachs commented
oh i was at the stage if resolving conflicts too :D

2021-12-29 18:33 UTC, eladb approved these changes

2021-12-29 18:34 UTC, merged

2021-12-29 18:46 UTC, eladb commented
@henrysachs Great job!