feat(awscdk): add plugins to CDK typescript app (#1244)
projen/projen pull request #1399
Opened 2021-12-27 22:06 UTC by tiararodney

This enables CDK plugins to be provided via the rendered `cdk.json`.

```javascript
new awscdk.AwsCdkTypeScriptApp({
  name: 'test',
  defaultReleaseBranch: 'main',
  cdkVersion: '1.133.0',
  cdkPlugins: ['cdk-assume-role-credential-plugin'],
});
```

plugins will be added as a devDependency to the package manifest and support all
common projen specifiers:

- plain ('cdk-assume-role-credential-plugin')
- versioned (foo@^1.0.0)
- scoped (@foo/foo)
- versioned and scoped (@foo/bar@^1.0.0)
- local (foo@/my/local/path/index.js)

resolves: #1244

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-28 06:44 UTC, eladb commented on src/awscdk/awscdk-app-ts.ts
> +    const cdkPlugins = ( options.cdkPlugins ?? [] ).map( ( plugin:string ) => {
Please format according to code style

2021-12-28 06:44 UTC, eladb commented on src/awscdk/awscdk-deps.ts
> +   * Plugins are regular node packages
Add `@default`

2021-12-28 17:49 UTC, tiararodney commented on src/awscdk/awscdk-app-ts.ts
> +    const cdkPlugins = ( options.cdkPlugins ?? [] ).map( ( plugin:string ) => {
https://github.com/tiararodney/projen/commit/bdcb0b09e71b5a417ed19b3efb1d3a48e949d8e8

2021-12-28 17:49 UTC, tiararodney commented on src/awscdk/awscdk-deps.ts
> +   * Plugins are regular node packages
https://github.com/tiararodney/projen/commit/bdcb0b09e71b5a417ed19b3efb1d3a48e949d8e8

2021-12-28 20:23 UTC, eladb requested changes

2021-12-28 20:23 UTC, eladb commented on src/awscdk/awscdk-app-ts.ts
> +      //field prefix (scope and semver) count
```suggestion
      // field prefix (scope and semver) count
```

2021-12-28 20:23 UTC, eladb commented on src/awscdk/awscdk-app-ts.ts
> +      const fpc = (plugin.match(/@/g) || []).length;
```suggestion
      const fpc = (plugin.match(/@/g) ?? []).length;
```

2021-12-28 20:23 UTC, eladb commented on src/awscdk/awscdk-app-ts.ts
> +        //remove the semver prefix
```suggestion
        // remove the semver prefix
```

2021-12-28 20:23 UTC, eladb commented on src/awscdk/awscdk-deps.ts
> +   * AWS CDK plugins that extend the CDK features.
```suggestion
   * AWS CDK CLI plugins that extend the CDK features.
```

2021-12-28 20:23 UTC, eladb commented on src/awscdk/awscdk-deps.ts
> +   *
Can you add a "@link" to the relevant AWS CDK docs here?

2021-12-28 20:23 UTC, eladb commented on src/awscdk/cdk-config.ts
> +  /**
```suggestion

  /**
```

2021-12-28 20:23 UTC, eladb commented on test/awscdk/awscdk-app.test.ts
> +    expect( files['cdk.json'].plugin ).toStrictEqual(['foo']);
Plz fix formatting

2022-01-02 21:20 UTC, eladb commented
## Please read this to avoid merge hell

Hola! apologies for hassle. I've enabled Prettify as part of #1453. This means that most of the source files have changed and you will likely see quite a lot of merge conflicts when you try to merge from `main`.

*But there's an easy way to handle this.*

First, merge your branch from this tag:

```sh
$ git fetch origin
$ git merge 1020d0ad3f95bb4e1201f8640d440ffb43ccf230
```

Edit the `.projenrc.js` file in your branch and add this to **line 57** (right
after `codeCov: true`):

```js
  prettier: true,
```

Now, run:

```sh
$ git clean -fdx .
$ yarn
$ bash projen.bash
$ yarn eslint
$ git add .
$ git commit -m 'format code'
```

This will reformat all the code in your branch to match `main`.

Now, merge from main:

```sh
$ git merge origin/main
```

Sorry again for the inconvenience...

2022-01-18 20:26 UTC, pflorek commented on src/awscdk/awscdk-deps.ts
> +   *
I assume there is no documentation except https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/plugin.ts and there is an argument on the command line

2022-01-21 01:26 UTC, closed without merging