feat: make cdktf construct dependencies settable
projen/projen pull request #1400
Opened 2021-12-27 22:44 UTC by DanielMSchmidt

The smart default is a goodie to make life easier, but the main part is making it easy to override the constructs version

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-28 06:41 UTC, eladb requested changes

2021-12-28 06:41 UTC, eladb commented on src/cdktf/cdktf-construct.ts
> +  readonly constructsVersion?: string;
This is actually the minimum version. Let's change this to be semver requirement so users can express a richer set:

```suggestion
  /**
   * Construct version to use
   * @default "^10.0.12"
   */
  readonly constructsVersion?: string;
```

Also, we try to reduce the set of "featured" options to a minimum. This is unlikely something someone would really want to touch.

2021-12-28 11:12 UTC, eladb requested changes

2021-12-28 11:12 UTC, eladb commented on src/cdktf/cdktf-construct.ts
> +      options.constructsVersion || getDefaultConstructVersion();
```suggestion
      options.constructsVersion ?? getDefaultConstructVersion();
```

2021-12-28 11:12 UTC, eladb commented on src/cdktf/cdktf-construct.ts
> +        return "3.0.0";
```suggestion
        return "^3.0.0";
```

2021-12-28 11:12 UTC, eladb commented on src/cdktf/cdktf-construct.ts
> +      return "10.0.12";
```suggestion
      return "^10.0.12";
```

2021-12-28 16:55 UTC, DanielMSchmidt commented
Thank you for your reviews and patience @eladb !

2022-01-02 21:20 UTC, eladb commented
## Please read this to avoid merge hell

Hola! apologies for hassle. I've enabled Prettify as part of #1453. This means that most of the source files have changed and you will likely see quite a lot of merge conflicts when you try to merge from `main`.

*But there's an easy way to handle this.*

First, merge your branch from this tag:

```sh
$ git fetch origin
$ git merge 1020d0ad3f95bb4e1201f8640d440ffb43ccf230
```

Edit the `.projenrc.js` file in your branch and add this to **line 57** (right
after `codeCov: true`):

```js
  prettier: true,
```

Now, run:

```sh
$ git clean -fdx .
$ yarn
$ bash projen.bash
$ yarn eslint
$ git add .
$ git commit -m 'format code'
```

This will reformat all the code in your branch to match `main`.

Now, merge from main:

```sh
$ git merge origin/main
```

Sorry again for the inconvenience...

2022-01-03 09:46 UTC, DanielMSchmidt commented
Closed in favor of #1464 and 🎉  for prettier 🎉

2022-01-03 09:46 UTC, closed without merging