fix(mergify): not all build jobs are considered
projen/projen pull request #1406
Opened 2021-12-28 09:15 UTC by eladb

Fixes #1382 by synthesizing the filter with all the build jobs. This has to be done lazily because jobs can be added.

BREAKING CHANGE: `AutoMerge` now takes `buildWorkflow` instead of the ID of the `buildJob`.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-28 16:32 UTC, iliapolo requested changes

2021-12-28 16:32 UTC, iliapolo commented on src/github/auto-merge.ts
> +    this.conditions.push(...conditions);
Seems like we don't really need the `conditions` array if we already have the `lazyConditions`.

```suggestion
    this.lazyConditions.push({ renderConditions: () => conditions });
```

2021-12-28 16:32 UTC, iliapolo commented on src/github/auto-merge.ts
> +  public addConditionsLater(later: IAddConditionsLater) {
```suggestion
  public addLazyConditions(later: IAddConditionsLater) {
```

2021-12-28 16:32 UTC, iliapolo commented on src/github/auto-merge.ts
> +export interface IAddConditionsLater {
```suggestion
export interface ILazyConditions {
```

2021-12-28 16:32 UTC, iliapolo commented on src/github/auto-merge.ts
> +  renderConditions(): string[];
```suggestion
  render(): string[];
```

2021-12-28 16:32 UTC, iliapolo commented on src/github/auto-merge.ts
> +  public addConditions(...conditions: string[]) {
I guess we don't strictly need this method since we only add lazy conditions. Maybe drop it for now to keep it clean?

2021-12-29 13:48 UTC, eladb commented on src/github/auto-merge.ts
> +  public addConditions(...conditions: string[]) {
I think that if we have `addConditionsLater()` it makes sense to also have `addConditions()`? It also helps signify the difference between them.

2021-12-29 13:48 UTC, eladb commented on src/github/auto-merge.ts
> +    this.conditions.push(...conditions);
Done.

2021-12-29 13:50 UTC, eladb commented on src/github/auto-merge.ts
> +  public addConditionsLater(later: IAddConditionsLater) {
I actually prefer "addConditionsLater()" because the "later" applies to how we are adding the conditions and not the nature of the condition ("lazy condition" sounds weird). But that's really a matter of personal preference.

2021-12-29 13:50 UTC, eladb commented on src/github/auto-merge.ts
> +export interface IAddConditionsLater {
Keeping with the "later" semantics (reasons above).

2021-12-29 13:51 UTC, eladb commented on src/github/auto-merge.ts
> +  renderConditions(): string[];
Done.

2021-12-29 13:56 UTC, iliapolo approved these changes

2021-12-29 15:47 UTC, merged