fix: package-js task not checked by mergify
projen/projen pull request #1426
Opened 2021-12-30 00:20 UTC by Chriscbr

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-30 06:20 UTC, eladb requested changes
I think it might be possible to add the integ task as a post build job now to the build workflow.

Something like this:

```ts
project.buildWorkflow.addPostBuildJob('integ', ...);
```

2021-12-30 17:35 UTC, eladb approved these changes

2021-12-30 17:35 UTC, eladb commented on .projenrc.js
> +      name: 'Prepare repository',
So hairy... I wonder if we can offer an even higher level abstractions for post build jobs.

Something like:

```ts
buildWorkflow.addPostBuildJobCommand("...", { tools: {} });

```

2021-12-30 18:15 UTC, Chriscbr commented on .projenrc.js
> +      name: 'Prepare repository',
I'll see what I can do

2021-12-30 18:25 UTC, Chriscbr commented
Ahhhhhhhhhhh that explains the errors... in each job step the directory you're in gets reset. I forget these things sometimes 🙃

2021-12-30 19:13 UTC, Chriscbr commented
> ./projen.bash: line 8: /home/runner/work/projen/projen/dist/bin/projen: Permission denied

It looks like GitHub actions also marks files as un-executable for some reason...

2022-01-02 13:04 UTC, eladb requested changes

2022-01-02 13:04 UTC, eladb commented on src/build/build-workflow.ts
> +  public addPostBuildJobTask(task: Task, options: AddPostBuildJobTaskOptions) {
Can we _also_ add a lower-level `addPostBuildJobCommand()` which will be used by `addPostBuildJobTask()`?

2022-01-02 13:04 UTC, eladb commented on src/build/build-workflow.ts
> +  public addPostBuildJobTask(task: Task, options: AddPostBuildJobTaskOptions) {
Feels like we should be able to use this in `JsiiProject` to execute the `jsii-pacmak` commands, no?

2022-01-02 20:58 UTC, Chriscbr commented on src/build/build-workflow.ts
> +  public addPostBuildJobTask(task: Task, options: AddPostBuildJobTaskOptions) {
Done

2022-01-02 20:59 UTC, Chriscbr commented on src/build/build-workflow.ts
> +  public addPostBuildJobTask(task: Task, options: AddPostBuildJobTaskOptions) {
This part is a little bit less clear so I'm going to leave this open for later refactoring if that's OK.

2022-01-02 21:00 UTC, Chriscbr commented on .github/workflows/build.yml
> +          repository: ${{ github.event.pull_request.head.repo.full_name }}
I don't think it matters which operation goes first (downloading build artifacts or checking out the repo?) but I could be wrong

2022-01-02 21:19 UTC, eladb commented
## Please read this to avoid merge hell

Hola @Chriscbr, apologies for hassle. I've enabled Prettify as part of #1453. This means that most of the source files have changed and you will likely see quite a lot of merge conflicts when you try to merge from `main`.

*But there's an easy way to handle this.*

First, merge your branch from this tag:

```sh
$ git fetch origin
$ git merge 1020d0ad3f95bb4e1201f8640d440ffb43ccf230
```

Edit the `.projenrc.js` file in your branch and add this to **line 57** (right
after `codeCov: true`):

```js
  prettier: true,
```

Now, run:

```sh
$ git clean -fdx .
$ yarn
$ bash projen.bash
$ yarn eslint
$ git add .
$ git commit -m 'format code'
```

This will reformat all the code in your branch to match `main`.

Now, merge from main:

```sh
$ git merge origin/main
```

2022-01-02 21:58 UTC, eladb commented on src/build/build-workflow.ts
> +  public addPostBuildJobTask(task: Task, options: AddPostBuildJobTaskOptions) {
Sure.

2022-01-02 21:59 UTC, eladb approved these changes

2022-01-03 00:02 UTC, Chriscbr commented
~magic incantations~ merge instructions worked as expected 👍

2022-01-03 02:34 UTC, merged

2022-01-05 05:22 UTC, moltar commented
I think this PR _might be_ causing this:

```diff
diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
index 49af2d1..4d90af6 100644
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -24,7 +24,7 @@ jobs:
         with:
           node-version: 16.13.0
       - name: Install dependencies
-        run: npm ci
+        run: npm install
       - name: build
         run: npx projen build
       - name: Turbo Build

```

Not sure if this is an intended consequence. But I think we should be always using `npm ci` in GitHub Actions?

2022-01-05 07:31 UTC, eladb commented
> I think this PR _might be_ causing this:
> 
> 
> 
> ```diff
> 
> diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
> 
> index 49af2d1..4d90af6 100644
> 
> --- a/.github/workflows/build.yml
> 
> +++ b/.github/workflows/build.yml
> 
> @@ -24,7 +24,7 @@ jobs:
> 
>          with:
> 
>            node-version: 16.13.0
> 
>        - name: Install dependencies
> 
> -        run: npm ci
> 
> +        run: npm install
> 
>        - name: build
> 
>          run: npx projen build
> 
>        - name: Turbo Build
> 
> 
> 
> ```
> 
> 
> 
> Not sure if this is an intended consequence. But I think we should be always using `npm ci` in GitHub Actions?

This is the PR that changed this behavior: https://github.com/projen/projen/pull/1467 and it was intentional.