updated to handle older git installs
projen/projen pull request #1437
Opened 2021-12-30 18:09 UTC by gherlein

git before 2.28 did not support "init -b" which causes failures.  Ubuntu 20.04 has an older git and is in widespread use.  This change detects the version of git installed and if it is too old it changes the branch name to "main" manually.  You cannot do this change on an empty repo though, you must do a commit first.  So the sequence of git commands is different for older versions too, doing the add+commit and then changing the default branch to main.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-31 17:41 UTC, eladb requested changes

2021-12-31 17:41 UTC, eladb commented on src/cli/cmds/new.ts
> +      .toString()
Can we use `semver` library here to parse and compare?

2021-12-31 17:41 UTC, eladb commented on src/cli/cmds/new.ts
> +      console.log('older version of git detected, changing branch name to main');
Use `logger`

2022-01-02 08:00 UTC, eladb requested changes

2022-01-02 08:00 UTC, eladb commented on src/cli/cmds/new.ts
> +      logging.info('default branch name set to main');
Either change to debug or omit:

```suggestion
```

2022-01-02 15:02 UTC, gherlein commented on src/cli/cmds/new.ts
> +      git('branch -m main');
yes, good idea - the --force will be better

2022-01-02 21:19 UTC, eladb commented
## Please read this to avoid merge hell

Hola! apologies for hassle. I've enabled Prettify as part of #1453. This means that most of the source files have changed and you will likely see quite a lot of merge conflicts when you try to merge from `main`.

*But there's an easy way to handle this.*

First, merge your branch from this tag:

```sh
$ git fetch origin
$ git merge 1020d0ad3f95bb4e1201f8640d440ffb43ccf230
```

Edit the `.projenrc.js` file in your branch and add this to **line 57** (right
after `codeCov: true`):

```js
  prettier: true,
```

Now, run:

```sh
$ git clean -fdx .
$ yarn
$ bash projen.bash
$ yarn eslint
$ git add .
$ git commit -m 'format code'
```

This will reformat all the code in your branch to match `main`.

Now, merge from main:

```sh
$ git merge origin/main
```

Sorry again for the inconvenience...

2022-01-03 17:14 UTC, eladb commented
I _think_ that you just need to now run:

```sh
git merge origin/main
```

To sync your branch from main.

2022-01-03 17:35 UTC, gherlein commented
***@***.***:~/src/constructs/after/projen$ git merge
origin/main
Auto-merging yarn.lock
Auto-merging src/typescript/typescript.ts
CONFLICT (content): Merge conflict in src/typescript/typescript.ts
Auto-merging src/javascript/jest.ts
CONFLICT (content): Merge conflict in src/javascript/jest.ts
Auto-merging src/javascript/eslint.ts
Auto-merging src/index.ts
CONFLICT (content): Merge conflict in src/index.ts
Auto-merging src/cli/cmds/new.ts
CONFLICT (content): Merge conflict in src/cli/cmds/new.ts
Auto-merging src/build/build-workflow.ts
CONFLICT (content): Merge conflict in src/build/build-workflow.ts
Auto-merging package.json
CONFLICT (content): Merge conflict in package.json
Auto-merging .projenrc.js
CONFLICT (content): Merge conflict in .projenrc.js
Auto-merging .projen/tasks.json
Auto-merging .projen/files.json
Auto-merging .gitignore
Removing .github/workflows/integ.yml
Auto-merging .gitattributes
Automatic merge failed; fix conflicts and then commit the result.

Are those expected?  Should I just go fix them?

Starting over is seeming way faster...


--------------------------------------------------------------------------------------------------------------
Greg Herlein   |   +1-415-368-7546   |   LinkedIn
<http://www.linkedin.com/in/gherlein>




On Mon, Jan 3, 2022 at 9:14 AM Elad Ben-Israel ***@***.***>
wrote:

> I *think* that you just need to now run:
>
> git merge origin/main
>
> To sync your branch from main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/projen/projen/pull/1437#issuecomment-1004234529>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABKK5EZWRKYCOO6YY35Q2DUUHKOZANCNFSM5LADI67Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-03 17:57 UTC, eladb commented
Looks like a reasonable set of conflicts. But if you feel more comfortable starting over, by all means

On Jan 3, 2022, at 19:37, Greg Herlein ***@***.***> wrote:

﻿

***@***.***:~/src/constructs/after/projen$ git merge
origin/main
Auto-merging yarn.lock
Auto-merging src/typescript/typescript.ts
CONFLICT (content): Merge conflict in src/typescript/typescript.ts
Auto-merging src/javascript/jest.ts
CONFLICT (content): Merge conflict in src/javascript/jest.ts
Auto-merging src/javascript/eslint.ts
Auto-merging src/index.ts
CONFLICT (content): Merge conflict in src/index.ts
Auto-merging src/cli/cmds/new.ts
CONFLICT (content): Merge conflict in src/cli/cmds/new.ts
Auto-merging src/build/build-workflow.ts
CONFLICT (content): Merge conflict in src/build/build-workflow.ts
Auto-merging package.json
CONFLICT (content): Merge conflict in package.json
Auto-merging .projenrc.js
CONFLICT (content): Merge conflict in .projenrc.js
Auto-merging .projen/tasks.json
Auto-merging .projen/files.json
Auto-merging .gitignore
Removing .github/workflows/integ.yml
Auto-merging .gitattributes
Automatic merge failed; fix conflicts and then commit the result.

Are those expected? Should I just go fix them?

Starting over is seeming way faster...


--------------------------------------------------------------------------------------------------------------
Greg Herlein | +1-415-368-7546 | LinkedIn
<http://www.linkedin.com/in/gherlein>




On Mon, Jan 3, 2022 at 9:14 AM Elad Ben-Israel ***@***.***>
wrote:

> I *think* that you just need to now run:
>
> git merge origin/main
>
> To sync your branch from main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/projen/projen/pull/1437#issuecomment-1004234529>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABKK5EZWRKYCOO6YY35Q2DUUHKOZANCNFSM5LADI67Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

—
Reply to this email directly, view it on GitHub<https://github.com/projen/projen/pull/1437#issuecomment-1004247212>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAESGDCDU2AWMNSX5RKU6RDUUHNANANCNFSM5LADI67Q>.
You are receiving this because you commented.Message ID: ***@***.***>

2022-01-18 07:19 UTC, Chriscbr commented
Superseded by https://github.com/projen/projen/pull/1485

2022-01-18 07:19 UTC, closed without merging