feat: eject from projen
projen/projen pull request #1459
Opened 2022-01-03 03:20 UTC by Chriscbr

Closes #596

Adds support for ejecting from projen with the "eject" task. 

TODO:
- [ ] add tests
- [ ] add docs/eject.md

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-03 06:46 UTC, eladb commented
I think I would have approached this slightly differently. Instead of treating "eject" as an action, I would model it as a project properly (`ejected`) and then downstream code can just reflect on this property and make decisions such as inclusion of the marker or whether a file needs to be read/write or readonly.

2022-01-03 06:46 UTC, eladb requested changes

2022-01-03 06:46 UTC, eladb commented on src/typescript/typescript.ts
> +      resolver.addLine(`// ${TextFile.PROJEN_MARKER}`);
How about we get rid of the `PROJEN_MARKER` const and expose `project.marker?` which will be undefined if we are ejecting? This will intrinsically signal that the market shouldn't be emitted.

2022-01-03 06:46 UTC, eladb commented on src/awscdk/lambda-function.ts
> +import { IS_PROJEN_EJECTING } from "../common";
Instead of a global const, let's propagate this through `project.ejected`.

See my general comment about modeling eject as a desired state as oppose to an action.

2022-01-03 06:46 UTC, eladb commented on src/component.ts
> +  public eject() {}
Not sure this is needed. Projen is a desired state system. As such it's preferable to model things as state as oppose to actions.

2022-01-03 06:46 UTC, eladb commented on src/file.ts
> +  readonly marker?: boolean;
Instead of making this an input option, I think we should just expose this as a property that includes the marker string itself, and it will be undefined if `project.ejected` is true.

2022-01-03 06:46 UTC, eladb commented on src/file.ts
> +  private checkForProjenMarker() {
Why is this needed?

2022-01-03 17:14 UTC, Chriscbr commented
> I think I would have approached this slightly differently. Instead of treating "eject" as an action, I would model it as a project properly (`ejected`) and then downstream code can just reflect on this property and make decisions such as inclusion of the marker or whether a file needs to be read/write or readonly.

Wow yeah that sounds way simpler, thanks for the suggestion! I'll update this PR with take 2 when I have a chance 👍 

When I started this I thought adding an `eject()` method on components would have an upside of "localizing" all of the eject-related logic to one place, but after working through the changes, I noticed in some places that just wasn't really practical (e.g. changing the contents of `SourceCode` files after the file was synthesized). So I think in addition to dropping that, accessing the state through `project` makes a lot more sense as well.

2022-01-10 03:50 UTC, Chriscbr commented on src/typescript/typescript.ts
> +      resolver.addLine(`// ${TextFile.PROJEN_MARKER}`);
Hmm, interesting idea - if the marker string is within `Project`, I think it might also be easier to fix https://github.com/projen/projen/issues/1179.

2022-01-10 03:52 UTC, Chriscbr commented on src/file.ts
> +  readonly marker?: boolean;
I've added a marker property within `Project`.

I could be off mark (pun intended?), but I think `marker` should still be an overridable option in files so that the marker can be "skipped" where needed. For example, `eslint` throws an error if `.eslintrc.json` has a field `"//": "Generated by projen..."`, so we configure the `JsonFile` with `marker: false`. In this PR I moved the property from `ObjectFile` to `FileBase` class since I thought it made more sense from a data modeling perspective. WDYT?

2022-01-10 03:55 UTC, Chriscbr commented on src/file.ts
> +  private checkForProjenMarker() {
Mmm... I added this to try and make it easier to discover projen-generated files with missing markers (or that files that stil contain markers after ejecting). I'm ok with taking this out, though it could helpful for debugging, lmk what you think.

I've since updated the logging messages to be a bit less complainy

2022-01-10 04:20 UTC, Chriscbr commented on src/task-runtime.ts
> +    const manifestPath = join(this.workdir, ".projen/tasks.json");
Inlining here saves us from importing the `Tasks` class when this file gets bundled by esbuild

2022-01-10 06:20 UTC, eladb commented on src/file.ts
> +  readonly marker?: boolean;
Yes absolutely

2022-01-10 08:11 UTC, eladb requested changes

2022-01-10 08:11 UTC, eladb commented on src/task-runtime.ts
> +    const manifestPath = join(this.workdir, ".projen/tasks.json");
Would still be nice to avoid the duplicate. Would it make sense to move this const here and import it from `tasks.ts`?

2022-01-10 08:11 UTC, eladb commented on src/typescript/typescript.ts
> +    const resolver = new TextFile(this, ".projen/jest-snapshot-resolver.js");
Why not use `PROJEN_DIR`?

2022-01-10 08:11 UTC, eladb commented on src/typescript/typescript.ts
> +    }
```suggestion
    if (!this.marker) {
      resolver.addLine(`// ${this.marker}`);
    }
```

2022-01-10 08:11 UTC, eladb commented on src/web/react.ts
> +      if (!project.ejected) {
```suggestion
      if (!project.marker) {
```

2022-01-10 08:11 UTC, eladb commented on src/web/react.ts
> -    project.addTask("eject", {
Should we still make this available through `react:eject` or somethin?

2022-01-25 01:59 UTC, Chriscbr commented
Pls keep

2022-01-25 03:06 UTC, Chriscbr commented on src/web/react.ts
> -    project.addTask("eject", {
I'm not sure if this makes sense since the `ReactProject` type is currently designed around using Create React App (adding react-scripts as a dep, setting up react-rewired, etc.), so if you _actually_ ran `react:eject`, projen would still think it's a CRA project and add the react-scripts dependency back etc. and it would be an awkward experience.

2022-01-25 03:07 UTC, Chriscbr commented on src/typescript/typescript.ts
> +    const resolver = new TextFile(this, ".projen/jest-snapshot-resolver.js");
I can't remember why I did this. Reverted

2022-01-25 03:09 UTC, Chriscbr commented on src/project.ts
> +  public get marker(): string | undefined {
Hmm... I can see what you mean. I've made the change.

The only case where it's a bit awkward is if you're trying to use the marker while constructing the actual file class, as in `new SampleFile(p, { contents: [this.marker] } )`. But I'm OK with that tradeoff

2022-01-25 03:09 UTC, Chriscbr commented on src/project.ts
> +  public readonly ejectTask?: Task;
Updated

2022-01-25 09:13 UTC, eladb commented on docs/eject.md
> +you can `eject` at any time.
Judgement isn't needed :-)

```suggestion
To stop from using projen to manage your project configuration,
you can `eject` at any time and continue to manage your configuration manually.
```

2022-01-25 09:13 UTC, eladb commented on .projenrc.js
> +function setupBundleTaskRunner() {
Curious, could we not use `Bundler` for this?

2022-01-25 09:13 UTC, eladb commented on src/file.ts
> +        : `${PROJEN_MARKER}. To modify, edit ${PROJEN_RC} and run "npx projen".`;
Maybe in the future we can ask the `project` about the name of the projenrc file (e.g. when it's not a .js file).

2022-01-25 09:13 UTC, eladb approved these changes
Great job!

2022-01-25 09:30 UTC, merged

2022-01-25 17:44 UTC, Chriscbr commented on docs/eject.md
> +you can `eject` at any time.
I was thinking of this sort of how a 5-star hotel might tell you "If you aren't totally satisfied with our service, we will gladly give you a complete refund" -- but I see what you mean about keeping things factual and to the point 👍