feat(javascript): allow users to run post-upgrade tasks
projen/projen pull request #1476
Opened 2022-01-03 20:50 UTC by misterjoshua

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-03 21:16 UTC, misterjoshua commented on src/javascript/upgrade-dependencies.ts
> +      });
I use `tryFind` here because `NodeProject` creates two instances of `UpgradeDependencies` in many `NodeProject`-based integration tests because projen [detects itself here.](https://github.com/projen/projen/blob/ee76669988ebf04a47367debcd00031473339aac/src/javascript/node-project.ts#L716)

I had considered moving the creation of this task up to `NodeProject`, but wasn't sure whether I should follow form with how `post-compile` is added to projects via `ProjectBuild`, since it has a similar nature to `post-upgrade` in `UpgradeDependencies`.

2022-01-11 15:59 UTC, misterjoshua commented
@Chriscbr Hey. Any ideas what's needed to move this PR along, discussion, code-change, or otherwise?

2022-01-11 18:28 UTC, Chriscbr requested changes
Hi, thanks for the ping. I took one more look to see if there's any quick fixes for the upgrade task not being available for escape hatching, but since I couldn't see any, I'm cool with adding this for now. Just a few small comments 🙂

2022-01-11 18:28 UTC, Chriscbr commented on src/javascript/node-project.ts
> +  }
Let's remove this since the `upgradeWorkflow` property is public anyways - I'd prefer to minimize the API surface area we're adding.

2022-01-11 18:28 UTC, Chriscbr commented on src/javascript/upgrade-dependencies.ts
> +    task.spawn(this.postUpgradeTask);
Can we add a unit test? I think we just want to validate that is there is some way to run things after the upgrade task.

2022-01-11 20:16 UTC, misterjoshua commented on src/javascript/node-project.ts
> +  }
No problemo.

2022-01-11 20:32 UTC, misterjoshua commented on src/javascript/upgrade-dependencies.ts
> +    task.spawn(this.postUpgradeTask);
Okay, I've added a unit test that checks that the `upgrade` task spawns `post-upgrade` as its last step. In the test, I didn't add anything to the `post-upgrade` task, but I can if you feel it's necessary.

2022-01-11 20:34 UTC, misterjoshua commented
@Chriscbr Alright - I've made changes following your review. Let me know whether you need anything else! Thanks.

2022-01-11 20:35 UTC, Chriscbr approved these changes

2022-01-11 20:37 UTC, merged