feat: option to ignore specific packages on dependency upgrade
projen/projen pull request #1480
Opened 2022-01-04 19:49 UTC by dontirun

Also fixes  https://github.com/projen/projen/issues/1356#issuecomment-1005046584 

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-04 20:10 UTC, eladb commented
@iliapolo can you take a look?

2022-01-05 14:00 UTC, iliapolo requested changes
@dontirun Thanks for this. See my comments. 

We should repurpose this PR to simply ignore `projen` by default if `projenVersion` is defined. Also this needs a test.

2022-01-05 14:00 UTC, iliapolo commented on src/javascript/node-project.ts
> +  public readonly ignoredUpgrades: string[] = [];
This functionality actually already exists:

https://github.com/projen/projen/blob/1e0bdedcd2e3a0366ef3143d7b7207bf1d58d4b1/src/javascript/upgrade-dependencies.ts#L23-L29

You can configure it on a node project via:

```ts
depsUpgradeOptions: {
  exclude: ['projen']
}
```

2022-01-05 14:00 UTC, iliapolo commented on src/javascript/node-project.ts
> +      if (options.projenVersion) {
I agree that if a user specified `projenVersion` we should add `projen` to the ignore list. But this should be done here:

https://github.com/projen/projen/blob/1e0bdedcd2e3a0366ef3143d7b7207bf1d58d4b1/src/javascript/node-project.ts#L693

2022-01-05 16:04 UTC, dontirun commented on src/javascript/node-project.ts
> +  public readonly ignoredUpgrades: string[] = [];
I completely missed that 🤦. I'll redothe PR

2022-01-05 16:28 UTC, dontirun commented on src/javascript/node-project.ts
> +      if (options.projenVersion) {
If we specify it here we should make sure that it's not overwritten by the [deepMerge](
https://github.com/dontirun/projen/blob/1588d8c1ea69fd536ef1ab03e7df441850497d1f/src/javascript/node-project.ts#L714).

2022-01-24 16:16 UTC, dontirun commented
@iliapolo Is this something that is still wanted/needed?

2022-02-20 16:31 UTC, iliapolo requested changes
@dontirun Sorry for letting this hang for a while. 

See my comments.

2022-02-20 16:31 UTC, iliapolo commented on src/javascript/node-project.ts
> +      }
This feels a bit cluttered. As I see it, all we need to do is provide a default value to `ignoreProjen`, both in the dependabot config and the dep upgrade. 

So, I think we just need to add: 

```ts
ignoreProjen: !!options.projenVersion,
```

Here:

https://github.com/projen/projen/blob/fafd5056e572185359e19d50b685f37ed496d1aa/src/javascript/node-project.ts#L693-L695

And here:

https://github.com/projen/projen/blob/fafd5056e572185359e19d50b685f37ed496d1aa/src/javascript/node-project.ts#L703-L705

No?

2022-02-20 16:31 UTC, iliapolo commented on src/javascript/node-project.ts
> +      !options.projenVersion &&
If we apply the above suggestion, we won't need to add this condition here.

2022-03-10 01:33 UTC, closed without merging