feat(awscdk): allow user to specify integration test stacks
projen/projen pull request #1496
Opened 2022-01-08 18:03 UTC by misterjoshua

Fixes #1495

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-11 21:54 UTC, misterjoshua commented on src/awscdk/integration-test.ts
> +  readonly name: string;
I've moved responsibility for naming the integration test to `IntegrationTest`'s creator. Here's why: If the user wants to create an integration test with specific `stacks`, they can't currently use `AutoDiscover`, as there's no mechanism to provide additional options on a per-test basis, and all of the task commands are rendered at construction time. But, if a user tries to manually add `IntegrationTest` to the project, then either: AutoDiscover finds it first due to the `**/*.integ.ts` glob and the user's `IntegrationTest` conflicts, or the user has to provide a different filename like `test/my-stage.myinteg.ts` and `IntegrationTest` fails to derive the name of the integration test.

2022-01-11 22:11 UTC, misterjoshua commented
@Chriscbr Here's another PR for you whenever you get a chance. This one helps integration test AWS CDK Stages.

2022-01-11 23:13 UTC, misterjoshua commented on src/awscdk/integration-test.ts
> +  readonly name: string;
Strictly speaking, this isn't the only solution. It should also be possible to implement a pragma system like the AWS CDK's main repository does with `!cdk-integ`, but where `IntegrationTest` parses a list of stacks to deploy from the entrypoint file before generating the build script. Something like:

**test/my-stage.integ.ts:**
```ts
const app = new cdk.App();
// ... add the constructs here
app.synth();

// Pragma follows:
// !awscdk-integ pragma:stacks=my-stage/*
```

2022-01-11 23:59 UTC, Chriscbr commented
I'll defer this one to Elad since I think he's a bit more familiar with these components 😅

2022-01-12 12:46 UTC, eladb requested changes

2022-01-12 12:46 UTC, eladb commented on src/awscdk/integration-test.ts
> +   * @default - The CLI is not told any one stack in particular
Can we make the default `"*"`? I believe this will deploy all stacks.

2022-01-12 12:46 UTC, eladb commented on src/awscdk/integration-test.ts
> +  readonly name: string;
Would it make sense to keep this optional with the current behavior as the default?

2022-01-12 16:42 UTC, misterjoshua commented on src/awscdk/integration-test.ts
> +   * @default - The CLI is not told any one stack in particular
@eladb We can make the default `"*"`, but if the integration test contains a stage with stacks in it, that wildcard does not locate the stacks in the stage. For the following example, you need to use `"my-stage/*"`:

```ts
import { App, Stack, Stage } from "@aws-cdk/core";

const app = new App();
const stage = new Stage(app, 'my-stage');
new Stack(stage, 'stack1');
new Stack(stage, 'stack2');
app.synth();
```

If you try to use `cdk deploy "*"` here, CDK CLI will say, `No stacks match the name(s) *`

Here's a project I threw together to demonstrate: https://github.com/misterjoshua/projen-multi-stack

![image](https://user-images.githubusercontent.com/644092/149182623-3184efe6-9ece-4132-b372-f681ced33253.png)

I'm not sure if this is a CDK CLI bug or something else - I had assumed there was a reason for "*" not to match the stacks.

2022-01-12 16:46 UTC, misterjoshua commented on src/awscdk/integration-test.ts
> +  readonly name: string;
Sure, we can do that.

2022-01-12 17:05 UTC, misterjoshua commented
Bah. I botched the merge to update. I'm going to rebase this PR from main.

2022-01-12 18:46 UTC, eladb approved these changes

2022-01-12 18:47 UTC, merged

2022-01-12 19:02 UTC, misterjoshua commented
Thanks for the help! :)

2022-01-13 01:37 UTC, mmcculloh-dms commented on src/awscdk/integration-test.ts
> +   * @default - The CLI is not told any one stack in particular
The logic for "*" is intentional, you can use "**" for all stacks of all stages. I believe `--all` does the same as well.

2022-01-13 06:24 UTC, eladb commented on src/awscdk/integration-test.ts
> +   * @default - The CLI is not told any one stack in particular
`**` sounds like the right direction

2022-01-13 06:32 UTC, misterjoshua commented on src/awscdk/integration-test.ts
> +   * @default - The CLI is not told any one stack in particular
I agree. I didn't know about that option!

2022-01-13 06:53 UTC, misterjoshua commented on src/awscdk/integration-test.ts
> +   * @default - The CLI is not told any one stack in particular
I just confirmed. :) 
![image](https://user-images.githubusercontent.com/644092/149280179-ee509f25-c11a-44dd-8016-c6838d6ef558.png)

2022-01-13 07:03 UTC, misterjoshua commented on src/awscdk/integration-test.ts
> +   * @default - The CLI is not told any one stack in particular
Here's a PR that changes the default to `**`: https://github.com/projen/projen/pull/1524