fix(new): fix issue with default git installation on mac
projen/projen pull request #1512
Opened 2022-01-11 03:46 UTC by erlanggatjhie

Fixes https://github.com/projen/projen/issues/1511

This PR is about an attempt to fix an issue where projen fails to retrieve git version in mac osx.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-11 06:09 UTC, eladb requested changes

2022-01-11 06:09 UTC, eladb commented on src/util.ts
> +  return gitVersionOutput.replace(/[a-z,/s]|\(.*\)/g, "").trim();
Wouldn't it make more sense to use a regular expression that matches the version instead of omitting the non-version parts?

Eg https://gist.github.com/jhorsman/62eeea161a13b80e39f5249281e17c39

2022-01-11 06:46 UTC, Chriscbr commented on src/util.ts
> +  return gitVersionOutput.replace(/[a-z,/s]|\(.*\)/g, "").trim();
@eladb I'm not I understand the benefit of this version check / what we get by using the new `git init -b` syntax. What if we just called `git branch -M main` every time?

2022-01-11 07:14 UTC, eladb commented on src/util.ts
> +  return gitVersionOutput.replace(/[a-z,/s]|\(.*\)/g, "").trim();
The reason I've changed this to use `-b` was that newer git versions emit an annoying warning that `master` is being deprecated. 

I am okay to revert though. Seems like it's not worth it

2022-01-12 00:12 UTC, erlanggatjhie commented on src/util.ts
> +  return gitVersionOutput.replace(/[a-z,/s]|\(.*\)/g, "").trim();
I have updated the code as per your suggestion @eladb and decided just to use a simple regex there. However, if you think that the revert is the best option then I will just close this PR then :).

2022-01-12 08:34 UTC, eladb approved these changes

2022-01-12 08:41 UTC, merged

2022-01-12 10:45 UTC, lrevnic commented
This fixed also the windows issue as well https://github.com/projen/projen/issues/1518. Thank you!