feat(cdk8s): import an explicit k8s spec version
projen/projen pull request #1558
Opened 2022-01-24 03:49 UTC by misterjoshua

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-24 20:20 UTC, Chriscbr requested changes

2022-01-24 20:20 UTC, Chriscbr commented on src/cdk8s/cdk8s-app-ts.ts
> +  readonly cdk8sApiVersion?: string;
This name seems misleading, since it's not the version of cdk8s that is changing. How about `k8sVersion`?

2022-01-24 20:20 UTC, Chriscbr commented on src/cdk8s/cdk8s-app-ts.ts
> +      exec: `cdk8s import ${k8sSpec} -o src/imports`,
I'm not sure if this is the ideal place to specify the k8s import. By default, `cdk8s import` (without specifying any spec files) will import all specs listed in `cdk8s.yaml` ([docs](https://cdk8s.io/docs/latest/cli/import/#crds)). Instead of updating this command, projen should auto-generate cdk8s.yaml with the correct list of specs instead.

2022-01-24 20:32 UTC, misterjoshua commented on src/cdk8s/cdk8s-app-ts.ts
> +  readonly cdk8sApiVersion?: string;
`k8sSpecVersion` sounds good.

2022-01-24 20:35 UTC, misterjoshua commented on src/cdk8s/cdk8s-app-ts.ts
> +      exec: `cdk8s import ${k8sSpec} -o src/imports`,
I believe the app creates a `cdk8s.yaml` as `SampleCode`. I wonder if we should bring this file into projen management so that we can control the file via the project options?

2022-01-24 21:11 UTC, Chriscbr commented on src/cdk8s/cdk8s-app-ts.ts
> +      exec: `cdk8s import ${k8sSpec} -o src/imports`,
That sounds good 👍

2022-01-24 21:49 UTC, misterjoshua commented
@Chriscbr Hey. I've changed the new option to `k8sSpecVersion`, and I've added a `YamlFile` to generate `cdk8s.yaml`. Ready for another review when you get a chance.

2022-01-24 23:02 UTC, misterjoshua commented on src/cdk8s/cdk8s-app-ts.ts
> -    this.gitignore.include("imports/");
This line seems like it was left dangling from #1536, since now the imports are `src/imports` by default, so I removed it.

2022-01-25 00:16 UTC, Chriscbr approved these changes
Nice! 👍

2022-01-25 00:25 UTC, merged