feat(cdk8s): add integration tests
projen/projen pull request #1575
Opened 2022-01-28 19:41 UTC by misterjoshua

Adds CDK8S integration tests.

Fixes #1573

﻿---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-28 20:29 UTC, misterjoshua commented
@Chriscbr Hey. I've created this PR which adds cdk8s integration tests. I've roughly followed the approach @eladb used to create awscdk integration tests. I also incorporated an equivalent of @jogold's `integ:snapshot-all`. Please let me know what you think. :)

2022-02-04 18:49 UTC, Chriscbr requested changes
Looks great @misterjoshua , I like the idea that integration / snapshot testing can be used across CDKs. 😄 I've added a few comments.

PR description looks good - can we add something similar to our high-level docs? For example `docs/cdk8s.md`

2022-02-04 18:49 UTC, Chriscbr commented on src/cdk8s/integration-test.ts
> +    deployTask.exec(`kubectl apply -f ${deployDir}`);
hmm I wonder if this is something users would want to customize in the future. e.g. "after `kubectl apply`, it should also check and wait for the rollout status to be done". Probably a good idea to wait for use cases before over-engineering this though, so let's leave this as is. 👍

2022-02-04 18:49 UTC, Chriscbr commented on src/cdk8s/auto-discover.ts
> +export class AutoDiscover extends Component {
As long as this is a separate component from the one in the `awscdk` module, can we also add unit tests for it? :)

2022-02-04 18:49 UTC, Chriscbr commented on src/cdk8s/integration-test.ts
> +export class IntegrationTest extends Component {
I wonder if we can try and reduce the code duplication between cdk8s and awscdk integ tests. Perhaps add an `IntegrationTestBase` class and/or `AutoDiscoverBase` class to the `cdk` module and then extend them / override the behaviors as needed within cdk8s and awscdk? It might require moving some initialization to private methods or protected methods etc. Could be a bit of work but if it makes sense it would help unify the abstraction that integ testing shares some common interface between CDK types.

2022-02-04 18:59 UTC, misterjoshua commented on src/cdk8s/auto-discover.ts
> +export class AutoDiscover extends Component {
Sure, that shouldn't be a problem.

2022-02-04 19:03 UTC, misterjoshua commented on src/cdk8s/integration-test.ts
> +    deployTask.exec(`kubectl apply -f ${deployDir}`);
Yes. I had also considered that users might want to use `--prune` with `--selector` and `--prune-whitelist`. I agree that we should wait for use cases before going too deep here.

2022-02-04 19:03 UTC, misterjoshua commented on src/cdk8s/integration-test.ts
> +export class IntegrationTest extends Component {
This had crossed my mind as well, but I didn't want to make a sweeping change without this type of discussion first. I'll see what I can come up with. :)

2022-02-04 22:52 UTC, misterjoshua commented
I've pushed up some WIP so I can resume work on this at home over the weekend.

2022-02-05 07:53 UTC, misterjoshua commented
By now I'm more or less happy with the shape of `IntegrationTestBase`, so I'll leave that alone until we review it. I'll see what I can do about the `AutoDiscoverBase` concept and the dangling `TYPESCRIPT_INTEG_EXT` consts in each project type soon.

2022-02-05 20:06 UTC, misterjoshua commented
Extending a base class with a protected abstract method for `AutoDiscover` in cea291f felt awkward when writing tests for auto-discovery, so in 983eca0 and 980442e I moved to a compositional structure for `AutoDiscover`.

I figure it makes more sense to have a unique `AutoDiscover` for each project type. This way, we can share smaller, re-usable components and add them to `AutoDiscover` as the project type needs. As of 930442e, this is what all this looks like:

![image](https://user-images.githubusercontent.com/644092/152656525-afb07a85-208f-438d-a7b1-404032b8a0ba.png)

```plantuml
@startuml

title Relationships - Class Diagram

class awscdk.AutoDiscover
class awscdk.IntegrationTestAutoDiscover
class awscdk.IntegrationTest
class awscdk.LambdaAutoDiscover
class awscdk.LambdaFunction

class cdk8s.AutoDiscover
class cdk8s.IntegrationTestAutoDiscover
class cdk8s.IntegrationTest

class cdk.AutoDiscoverBase
class cdk.IntegrationTestAutoDiscoverBase

cdk.IntegrationTestAutoDiscoverBase <|-down- awscdk.IntegrationTestAutoDiscover
cdk.IntegrationTestAutoDiscoverBase <|-down- cdk8s.IntegrationTestAutoDiscover

cdk.AutoDiscoverBase <|-down- awscdk.LambdaAutoDiscover
cdk.AutoDiscoverBase <|-down- cdk.IntegrationTestAutoDiscoverBase

awscdk.AutoDiscover -up-> awscdk.IntegrationTestAutoDiscover
awscdk.AutoDiscover -up-> awscdk.LambdaAutoDiscover
awscdk.IntegrationTestAutoDiscover -> awscdk.IntegrationTest
awscdk.LambdaAutoDiscover -left-> awscdk.LambdaFunction

cdk8s.AutoDiscover -up-> cdk8s.IntegrationTestAutoDiscover
cdk8s.IntegrationTestAutoDiscover -> cdk8s.IntegrationTest

@enduml
```

I took initiative here because I had some time to burn. I'm happy to revert back to cea291f and take any other approach. :)

2022-02-07 22:44 UTC, Chriscbr requested changes
> I figure it makes more sense to have a unique AutoDiscover for each project type. This way, we can share smaller, re-usable components and add them to AutoDiscover as the project type needs.

Yep this makes sense to me. If the public APIs need to change in the future we can always refactor as needed, but this looks pretty much good to ship. (very clean diagrams by the way!)

Just one more small comment :)

2022-02-07 22:44 UTC, Chriscbr commented on src/cdk/auto-discover-base.ts
> +export class AutoDiscoverBase extends Component {
Let's make `AutoDiscoverBase` and `IntegrationTestBase` abstract for now, since they don't do much on their own (minimizing API surface area):
```suggestion
export abstract class AutoDiscoverBase extends Component {
```
This might require updating tests to use a stub child class

2022-02-07 23:50 UTC, Chriscbr approved these changes

2022-02-07 23:59 UTC, merged