feat(awscdk-app-py): adding support for building CDK apps with python
projen/projen pull request #1579
Opened 2022-01-29 23:23 UTC by marciocadev

Just like it was done for Java I made a python cdk project template

I needed to decouple the existing pytest class to create a specific test template for python cdk

closes #1577 
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-02-23 23:33 UTC, Chriscbr requested changes
This looks fantastic @marciocadev ! Really excited to have this added to projen. :) I've just added a few small comments.

2022-02-23 23:33 UTC, Chriscbr commented on README.md
> +* [awscdk-app-py](https://projen.github.io/projen/api/API.html#projen-awscdk-awscdkpythonapp) - AWS CDK app in Python.
Can you check if any of our manually-written docs in `docs/` should to be updated to mention something about this new project type?

2022-02-24 00:42 UTC, marciocadev commented on src/awscdk/awscdk-app-py.ts
> +export interface AwsCdkPythonAppOptions
Thanks, this kind of detail is important

2022-02-24 00:44 UTC, marciocadev commented on src/awscdk/awscdk-app-py.ts
> +      },
I think you're right, I didn't notice that the 'internal.ts' file had this configuration, I'll change and test again

2022-02-24 00:50 UTC, marciocadev commented on README.md
> +* [awscdk-app-py](https://projen.github.io/projen/api/API.html#projen-awscdk-awscdkpythonapp) - AWS CDK app in Python.
Yes, I have to add the 'awscdk-app-py' on awscdk-apps.md

Sorry I didn't see this one :(

2022-02-24 01:19 UTC, marciocadev commented on src/awscdk/awscdk-app-py.ts
> +import { PythonProject, PythonProjectOptions } from "../python/python-project";
To change this I need to remove the 'PythonProject' reference from 'pytest.ts' and change to 'Project'

It's not a big change and I think it's more natural this way

2022-02-24 01:38 UTC, marciocadev commented on src/awscdk/awscdk-app-py.ts
> +import { PythonProject, PythonProjectOptions } from "../python/python-project";
@Chriscbr I thought this would work but when I tested it an error was generated

Apparently the import on the same line is generating a circular reference as both 'PythonProject' and 'AwsCdkPythonApp' import 'Pytest'

So I made this change

```
import { Pytest } from "../python/pytest";
import { PythonProject, PythonProjectOptions } from "../python/python-project";
```

2022-02-24 02:04 UTC, Chriscbr requested changes

2022-02-24 02:04 UTC, Chriscbr commented on src/awscdk/awscdk-app-py.ts
> +  public readonly pytest?: Pytest;
This doesn't seem right - `pytest` is also a public property on `PythonProject` so I don't think we should re-declare it.

I think we can change the code in `python-project.ts` so that the pytest samples are only generated if `sample` is true. So for example in `python-project.ts`:

```ts
const pytest = options.pytest ?? true;
const sample = options.sample ?? true;
if (pytest) {
  this.pytest = new Pytest(this, options.pytestOptions);
  if (sample) {
    new PytestSample(this, this.pytest.testdir);
  }
}

if (sample) {
  new PythonSample(this, {});
}
```

This way, you should not need to override `super(... pytest: false...)` in the constructor of AwsCdkPythonApp, and I think it might fix the circular dependency issue since you should not need to import `Pytest` within `awscdk-app-py.ts`. Let me know if this makes sense

2022-02-25 00:37 UTC, marciocadev commented on src/awscdk/awscdk-app-py.ts
> +  public readonly pytest?: Pytest;
I removed the property `pytest` from `awscdk-app-py.ts` file and change the `pytest` from `python-project.ts` to writable, that way I can overwrite the `pytest` to my aws class

2022-02-25 01:28 UTC, Chriscbr approved these changes
Thanks @marciocadev ! 🙏

2022-02-25 01:36 UTC, merged