feat(awscdk): add LambdaExtension bundling
projen/projen pull request #1647
Opened 2022-02-26 22:02 UTC by misterjoshua

WIP

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-02-27 00:21 UTC, misterjoshua commented
If supporting TS-based Lambda Extensions is too specific, we could simplify extension bundling by keeping just the bundler `outfile` and `outdir` changes.

2022-03-10 21:37 UTC, Chriscbr requested changes
This looks great @misterjoshua ! I just added a few small nitpicks and questions 🙂

2022-03-10 21:37 UTC, Chriscbr commented on src/awscdk/lambda-extension.ts
> +    bundle.bundleTask.exec(`chmod +x ${bundle.outfile}`);
Why is this needed? Can we add a comment?

Would it make sense to add this as an option to addBundle instead, like `executable` or `markExecutable`?

2022-03-10 21:37 UTC, Chriscbr commented on docs/awscdk.md
> +Example extension:
Can you add a blurb about what this extension does? Without familiarity with lambda extensions, I don't think it's super clear what it does / where I would insert my functionality.

2022-03-10 21:37 UTC, Chriscbr commented on docs/awscdk.md
> +Example extension:
Let's also add a link to this samples repo for good measure: https://github.com/aws-samples/aws-lambda-extensions

2022-03-13 00:09 UTC, Chriscbr approved these changes

2022-03-13 00:10 UTC, merged