feat: Exclude packages that has version set by Projen from upgrade task
projen/projen pull request #1665
Opened 2022-03-06 19:38 UTC by Hi-Fi

fixes: #1659

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-07 09:20 UTC, Hi-Fi commented
@Chriscbr How does this look related to upgrade issue?

2022-03-07 20:05 UTC, Chriscbr requested changes

2022-03-07 20:05 UTC, Chriscbr commented on src/javascript/upgrade-dependencies.ts
> +    if (includeLength === 0 || (includeLength > 0 && ncuIncludesLength > 0)) {
Why do we create the task if `includeLength === 0`?

2022-03-08 04:26 UTC, Hi-Fi commented on .projen/tasks.json
> +          "exec": "npm-check-updates --dep dev --upgrade --target=minor --reject='@types/fs-extra,@types/node,@typescript-eslint/eslint-plugin,@typescript-eslint/parser,eslint,jest-junit,npm-check-up
It's more like opinion thing, as with current solution user still gets correct version to lockfile as this step runs the upgrade step.

`ncu` doesn't seem to be updating versions in that format, so the filtering out just fully pinned (or ones with `~` could be done if needed).

2022-03-08 04:28 UTC, Hi-Fi commented on test/upgrade-dependencies.test.ts
> +  test("at NodeProject", () => {
These tests were also for my TDD approach, but if snapshot tests are the main thing I can remove these.

In this case TDD with snapshots would have been quite a lot of harder and slower.

2022-03-08 04:30 UTC, Hi-Fi commented on src/javascript/upgrade-dependencies.ts
> +    if (includeLength === 0 || (includeLength > 0 && ncuIncludesLength > 0)) {
Include's are exlicit includes, e.g. `projen` for `upgrade-projen` task. 

So we should create task if...
- we don't have any explicit includes
- we have explicit includes, that are not pinned versions (`ncuIncludes`).

2022-03-08 18:19 UTC, Chriscbr approved these changes

2022-03-08 18:20 UTC, merged