feat(node-project): Added ability to provide scoped private packages
projen/projen pull request #1688
Opened 2022-03-15 03:21 UTC by AminFazlMondo

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-15 17:33 UTC, Chriscbr requested changes
Cool! I've added a few small comments. Could you please add a section in our hand-written docs to document this feature? Just a few sentences would be great. :) Perhaps in `docs/node.md`, or wherever you see most appropriate.

(This is just brainstorming, nothing that needs to be addressed). How does this experience work locally / how do you authenticate to install packages when projen isn't running in CICD? I wonder if we should also add some kind of `npx projen codeartifact:auth` command, or some kind of "install hook" that allows you to specify one or more commands to run before installing dependencies in any task. Or is there a simpler way, like generating a .npmrc file, etc...

2022-03-15 17:33 UTC, Chriscbr commented on src/javascript/node-project.ts
> +  }
Let's put these static methods and constants outside of the class (either in this file or in `util.ts`) so we can reuse them or use them for testing

2022-03-15 17:33 UTC, Chriscbr commented on test/node-project.test.ts
> +          registryUrl: `https://${domain}-${accountId}.d.codeartifact.${region}.amazonaws.com/npm/${repository}/`,
nit: Can we extract this to `const registryUrl = ...` above?

2022-03-15 17:33 UTC, Chriscbr commented on test/node-project.test.ts
> +          registryUrl: `https://${domain}-${accountId}.d.codeartifact.${region}.amazonaws.com/npm/${repository}/`,
Can we extract this to `const registryUrl = ...` above?

2022-03-16 09:40 UTC, AminFazlMondo commented
> Cool! I've added a few small comments. Could you please add a section in our hand-written docs to document this feature? Just a few sentences would be great. :) Perhaps in `docs/node.md`, or wherever you see most appropriate.
> 
> (This is just brainstorming, nothing that needs to be addressed): How does this experience work locally / how do you authenticate to install packages when projen isn't running in CICD? I wonder if we should also add some kind of `npx projen codeartifact:auth` command, or some kind of "install hook" that allows you to specify one or more commands to run before installing dependencies in any task. Or is there a simpler way, like generating a .npmrc file, etc...

I was thinking about that too, but wanted to iterate on it with others' input. Will investigate that in future.

2022-03-17 13:23 UTC, hoegertn commented
Support for scoped registries is already there using the NpmRc class. Would it be possible to read this to generate the login in CICD instead of adding another way of configuring this?

2022-03-17 20:33 UTC, Chriscbr commented
@AminFazlMondo what do you think?

2022-03-17 21:19 UTC, AminFazlMondo commented
That is right, we probably could use the npmRc for the registry but the code artifact token is required for the private one, soe It is right to say that this is more to generate token in CICD pipeline.
Are we suggestion that some of the code can be changed?

2022-03-22 06:38 UTC, charliehart-mondo commented
> Support for scoped registries is already there using the NpmRc class. Would it be possible to read this to generate the login in CICD instead of adding another way of configuring this?

I think the local npmrc file option is ok if that's the correct route to go, but it still needs to have the token setup presumably as an environment variable in a workflow step.

This is from the docs: https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow#create-and-check-in-a-project-specific-npmrc-file

The codeartifact-auth step in this PR currently does "npm config set" for the relevant details (registry, _authToken, always_auth), it (or a different action) could be changed to update an environment variable instead and combine that with an npmrc file (would this be auto generated/updated based on config?)

https://github.com/MondoPower/codeartifact-auth/blob/main/src/index.ts

Either way, I suspect most of the code in this PR is required to add a login step regardless of if it does "npm config set" or sets an env variable, so which approach seems to fit best?

2022-03-22 22:09 UTC, Chriscbr requested changes

2022-03-22 22:09 UTC, Chriscbr commented on src/javascript/node-package.ts
> +      ),
Can we pass in options.codeArtifactOptions so that the user doesn't have to specify the options in both scopedPackagesOptions and codeArtifactOptions ?

2022-03-22 22:10 UTC, Chriscbr commented
Managing the config via npmrc (with the `NpmConfig` component) could make sense, but it might be awkward since projen can't completely manage the file if it's being updated whenever someone runs `aws codeartifact login` or runs `npm config set ...`. So I'm ok with this approach

2022-03-29 12:26 UTC, AminFazlMondo commented
Hi @Chriscbr ,

Thanks for you feedback, after that it made us re-think the solution.
Originally, we wanted to support for the situation in which the code artifact details to publish to be different from the ones specified in the scoped packages. With what you mentioned above, we came to the conclusion that it is not a common use case and used the same details for scoped packages for simplicity.
We also made a task (`ca:login`) to login to code artifact (thanks for your suggestion), which can also be used in local development.
We would appreciate you having another look and share your thoughts with us or if looks good to you approve this.
Cheers,

2022-03-29 12:26 UTC, AminFazlMondo commented on src/javascript/node-project.ts
> +    });
Done

2022-03-29 12:26 UTC, AminFazlMondo commented on test/node-project.test.ts
> +          secretAccessKeySecret,
Added test case for it

2022-04-06 00:24 UTC, Chriscbr requested changes
This looks really great @AminFazlMondo ! I've left just a few more comments, but I think we're close to getting this merged in. 🙂

2022-04-06 00:24 UTC, Chriscbr commented on docs/node.md
> +This feature supports specifying options on how to access packages in each of the scopes, otherwise will try to install from default npm registry.
```suggestion
This feature supports specifying options on how package managers should access packages in each of the scopes. If no options are specified, npm or yarn will try to install scoped packages from thepublic npm registry.
```

2022-04-06 00:24 UTC, Chriscbr commented on src/javascript/node-package.ts
> +   * scope of the packages
```suggestion
   * Scope of the packages
```

2022-04-06 00:24 UTC, Chriscbr commented on src/javascript/node-package.ts
> +   * Url of the registry for scoped packages
```suggestion
   * URL of the registry for scoped packages
```

2022-04-06 00:24 UTC, Chriscbr commented on src/javascript/node-package.ts
> +   * @default undefined
```suggestion
   * @default - fetch all scoped packages from the public npm registry
```

2022-04-06 00:24 UTC, Chriscbr commented on docs/node.md
> +Currently, it only supports AWS CodeArtifact, either by directly access via credentials or by assuming a role using the specified credentials.
```suggestion
Currently, it only supports fetching packages from AWS CodeArtifact, either by directly access via credentials or by assuming a role using the specified credentials.
```

2022-04-06 00:24 UTC, Chriscbr commented on src/javascript/node-package.ts
> +        { exec: "which aws" },
```suggestion
        { exec: "which aws" }, // check that AWS CLI is installed
```

2022-04-06 00:24 UTC, Chriscbr commented on src/javascript/node-project.ts
> +   * Get steps for scoped package
```suggestion
   * Get steps for scoped package access
```

2022-04-06 00:24 UTC, Chriscbr commented on src/javascript/node-project.ts
> +            "aws-region": "us-east-2",
Is there a reason this is hard-coded? Can we make it customizable?

2022-04-06 00:24 UTC, Chriscbr commented on src/javascript/node-package.ts
>    readonly codeArtifactOptions?: CodeArtifactOptions;
If I understand correctly, this field is being used to also provide access to Code Artifact for installing packages (not just publishing). Please update the description to reflect this

2022-04-06 00:24 UTC, Chriscbr commented on src/javascript/node-package.ts
> +          const commands = [
Let's add a comment for future maintainers.
```suggestion
          // reference: https://docs.aws.amazon.com/codeartifact/latest/ug/npm-auth.html
          const commands = [
```

2022-04-06 00:24 UTC, Chriscbr commented on docs/node.md
> +### Scoped Private Packages
Please update this section to also explain that for the feature to work on GitHub, the user must add secrets named `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to their repo (I believe this is true?)

2022-04-12 06:27 UTC, charliehart-mondo commented on src/javascript/node-project.ts
> +            "aws-region": "us-east-2",
Good pick up.

It's possible that a user will have multiple scopes each in a different region (and in fact account if they have access), so we need to ensure those details are passed to the ca:login script so it can generate an auth token in the correct region/account (via the --region and --domain-owner cli options) - I'll update that shortly.

However, the region you set for configure-aws-credentials can be independent of those if I'm not mistaken so long as you override it in the cli (it is a required property for that github action unfortunately ), We could grab the first repositoryurl from the array of scoped packages, parse the url and get the region from there - or we could leave it hard-coded.

I'm going to suggest we leave it hard-coded

2022-04-12 07:35 UTC, charliehart-mondo commented on src/javascript/node-project.ts
> +            "aws-region": "us-east-2",
We could obviously also add another property to set it in the options, I'm not sure if it's best/helps though?

2022-04-12 07:49 UTC, charliehart-mondo commented on docs/node.md
> +### Scoped Private Packages
The user can set custom secret names so long as that is passed to the codeartifact options. From there configure-aws-credentials will use the default or custom secret names that get passed along. I'll update the docs to reflect that codeartifact options are required (will that be enough to prompt users to set those secrets given it's a requirement for that?)

2022-04-12 16:49 UTC, Chriscbr approved these changes
Looks great! Thanks @AminFazlMondo and @charliehart-mondo :)

2022-04-12 16:56 UTC, merged