feat: Add GithubActionTypeScriptProject
projen/projen pull request #1714
Opened 2022-03-25 21:22 UTC by kaizen3031593

Very, very, very rough draft on a project geared towards TypeScript github actions. My idea is for this to have the following features:

- Projen managed `action.yml` file
- automatic packaging to a single `/dist/index.js` file via the `@vercel/ncc` library.

I'm currently missing a bunch of docs and have absolutely zero tests; not even sure if it works. Ended up not having that much time to work on it today :(. There's also a lot of projen conventions that I fear I am stomping over, so happy to hear what mistakes I'm making.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-25 22:01 UTC, Chriscbr reviewed
This looks great! 👍 Let me know when it's ready for another review

2022-04-04 20:19 UTC, kaizen3031593 reviewed
Some of my initial thoughts. Also, is 18k additions to `API.md` normal?

2022-04-04 20:19 UTC, kaizen3031593 commented on src/github-actions/actions.ts
> +  readonly metadata?: ActionMetadata;
I really want to do `Partial<ActionMetadata>` here but JSII won't let me :(.

My thought is that `ActionMetadata` should simply model the GitHub schema as an "L1", which means things like `name` are required. However, I don't really want to require `name` here in the "L2", cuz we can copy `this.name` over.

The only thing I can think of is creating another interface, `GitHubActionMetadata`, that mirrors `ActionMetadata` except it is all optional properties (i.e. basically `Partial<ActionMetadata>`). And then we have `readonly metadata?: GitHubActionMetadata;`. 

But before I do that I want to make sure there's no prior art for something like this. It seems fairly common.

2022-04-04 20:19 UTC, kaizen3031593 commented on src/github/actions-metadata-model.ts
> +export enum RunsUsing {
I originally wanted to use an enum-like class here (like Lambda's `Runtime`) so that when `node18` comes out or whatever we can instantly support it. But I ended up having problems with that idea since `runsOn` needs to be a string. We'd need to post-process the enum-like class into a string, and I didn't want to deal with that, so I used enum instead.

2022-04-05 23:43 UTC, Chriscbr requested changes

2022-04-05 23:43 UTC, Chriscbr commented on README.md
> -`jsii` projects:
Revert

The list in the README should get automatically updated by the projen build, no need to manually edit it.

2022-04-05 23:43 UTC, Chriscbr commented on src/github-actions/actions.ts
> + * Properties for creating a GitHubActionTypeScriptProject
```suggestion
 * Properties for `GitHubActionTypeScriptProject`
```

2022-04-05 23:43 UTC, Chriscbr commented on src/github-actions/actions.ts
> +   */
Trying to tweak the API description to be a bit more intent based than implementation based

```suggestion
  /**
   * Options for the GitHub Action metadata stored in `action.yml`
   *
   * @default - an action named after the project `name` that runs from dist/index.js
   */
```

2022-04-05 23:43 UTC, Chriscbr commented on src/github-actions/actions.ts
> +  readonly metadata?: GitHubActionMetadata;
Suggestion to protect API surface area from future name conflicts / be more explicit
```suggestion
  readonly actionMetadata?: GitHubActionMetadata;
```

2022-04-05 23:43 UTC, Chriscbr commented on src/github-actions/actions.ts
> +    const defaultMetadataOptions: ActionMetadata = {
I'm not sure if we need to define both interfaces `ActionMetadata` and `GithubActionMetadata`
```suggestion
    const defaultMetadataOptions: GithubActionMetadata = {
```

2022-04-05 23:43 UTC, Chriscbr commented on src/github-actions/actions.ts
> +    });
I think we should model `action.yml` file as its own component -- as an L1. (YamlFile and JsonFile etc. can all be thought of as L0s). Take a look at `typescript-config.ts` for an idea of how this should look. Since it would be an L1, the API for this component doesn't need to be intent based, and instead just creates a YamlFile with data that has been typed checked.

```ts
/**
 * Properties for `ActionMetdata`
 */
export interface ActionsMetadataOptions extends GithubActionsMetadata {}

/**
 * A GitHub Action Metadata file.
 */
export class ActionMetadata {
  constructor(project: Project, options: ActionsMetadataOptions) {
    const fileName = options.fileName ?? "action.yml";
    // ...
  }
}
```

This component can probably go in the `actions` folder.

2022-04-05 23:43 UTC, Chriscbr commented on src/github/actions-metadata-model.ts
> +export enum RunsUsing {
Ok

2022-04-05 23:43 UTC, Chriscbr commented on src/github/workflows-model.ts
> +   * TBD
Description?

2022-04-05 23:43 UTC, Chriscbr commented on docs/api/API.md
> +[actions.GitHubActionTypeScriptProject](#projen-actions-githubactiontypescriptproject)|Create a GitHub Action with TypeScript.
This looks fine - but the API.md file in the root directory should not be getting generated (I'm not sure how it ended up in the PR). Can you manually remove it?

2022-04-05 23:46 UTC, Chriscbr commented on src/github-actions/actions.ts
> +    });
In the future I think we'll auto-generate these L1s

2022-04-29 00:43 UTC, Chriscbr commented
Superseded by #1811

2022-04-29 00:43 UTC, closed without merging