feat(circleci): Add support for CircleCi
projen/projen pull request #1718
Opened 2022-03-27 18:42 UTC by karlderkaefer

Adding support to generate pipelines for CircleCi

fixes #1717 
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-06 00:29 UTC, Chriscbr commented
Hey @karlderkaefer - thanks for taking initiative on this! This is definitely a feature we want in projen -- but it might be a while before we're able to get to review this. I appreciate your patience 🙏

2022-05-31 17:50 UTC, Chriscbr requested changes

2022-05-31 17:50 UTC, Chriscbr commented on src/circleci/circleci.ts
> +  public readonly file: YamlFile | undefined;
See other comment
```suggestion
  public readonly file: YamlFile;
```

2022-05-31 17:50 UTC, Chriscbr commented on src/circleci/circleci.ts
> +   */
No need to have a docstring for the constructor
```suggestion
```

2022-05-31 17:50 UTC, Chriscbr commented on test/cirlceci/circleci.test.ts
> +  console.log(circleci);
```suggestion
```

2022-05-31 17:50 UTC, Chriscbr commented on test/cirlceci/circleci.test.ts
> +  console.log(circleci);
```suggestion
```

2022-06-13 16:39 UTC, karlderkaefer commented on src/circleci/circleci.ts
> +    if (circleCiEnabled) {
fixed in b882b4f97a84a417ed1da2a17e52f5dd46432840

2022-06-13 16:45 UTC, karlderkaefer commented
@Chriscbr thanks for your review and time, I have addressed all suggestions. I got one question to commit messages, I did not follow the conventional message on every commit, should I rebase and rewrite commit messages, or is that not so important since PRs getting squash merged anyway?

2022-06-13 19:32 UTC, merged