feat(cdk8s-app-py): adding support for building CDK8s apps with python
projen/projen pull request #1720
Opened 2022-03-28 15:50 UTC by marciocadev

## Refactoring
I had to refactor the python module to correct the circular dependency in python project tests

## Testing against local projects
Testing this solution is a little different as it is necessary import the projen python dependency

```console
$ cd /path/to/local/projen
$ yarn compile # <-- compile the solution
$ yarn package:python # <-- create the projen python package
$ yarn link
```

Now, to create new projects:

```console
$ mkdir /my/new/project
$ cd /my/new/project
$ npm init -y # <-- needed to yarn lynk
$ yarn link projen
$ alias pj="node_modules/projen/bin/projen"
$ pj new cdk8s-app-py
$ source .env/bin/activate
$ pip install /path/to/local/projen/dist/python/projen-0.0.0-py3-none-any.whl # <-- point to your local projen code
$ pj new cdk8s-app-py # <-- run again to resolve the projen dependency
```

Now you can make some changes on your **.projenrc.py** file and run `python .projenrc.py`

I try this on `.projenrc.py`

```
from projen.cdk8s import Cdk8sPythonApp

project = Cdk8sPythonApp(
    author_email="test@gmail.com",
    author_name="First Last",
    cdk8s_version="1.5.53",
    module_name="cdk8s_app_py_playground",
    name="cdk8s-app-py-playground",
    version="0.1.0",

    deps=["cdk8s-plus-22@^1.0.0-beta.157"],
)

project.synth()
```

and this on `app.py`

```
#!/usr/bin/env python
from cdk8s_plus_22 import ContainerProps, Deployment, Service, ServicePort
from constructs import Construct
from cdk8s import App, Chart

class MyChart(Chart):
    def __init__(self, scope: Construct, id: str):
        super().__init__(scope, id)

        Service(
            scope=self,
            id="service",
            ports=[ServicePort(port=80, target_port=8080)]
        )

        Deployment(
            scope=self,
            id="deployment",
            replicas=2,
            containers=[
                ContainerProps(
                    name="hello-k8s",
                    image="paulbouwer/hello-kubernetes:1.7",
                    port=8080
                )
            ]
        )

app = App()
MyChart(app, "cdk8s-app-py-playground")

app.synth()
```

and get this on `dict/cdk8s-app-py-test.k8s.yaml`

```
apiVersion: v1
kind: Service
metadata:
  name: cdk8s-app-py-playground-service-c8eae0d2
spec:
  externalIPs: []
  ports:
    - port: 80
      targetPort: 8080
  selector: {}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdk8s-app-py-playground-deployment-c8ecd1ba
spec:
  replicas: 2
  selector:
    matchLabels:
      cdk8s.deployment: cdk8s-app-py-playground-deployment-c8a6cc0d
  template:
    metadata:
      labels:
        cdk8s.deployment: cdk8s-app-py-playground-deployment-c8a6cc0d
    spec:
      containers:
        - env: []
          image: paulbouwer/hello-kubernetes:1.7
          imagePullPolicy: Always
          name: hello-k8s
          ports:
            - containerPort: 8080
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          volumeMounts: []
      hostAliases: []
      initContainers: []
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: false
        sysctls: []
      volumes: []
```

closes #1680 
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-06 00:30 UTC, Chriscbr commented
Thanks for getting started with this @marciocadev 🙂 This is definitely a feature we want in projen,  though it might be a while before we're able to get to review this. Thanks for being patient!

2022-05-31 18:13 UTC, Chriscbr requested changes
Looks great - only a couple of small nitpicks 👍

2022-05-31 18:13 UTC, Chriscbr commented on src/awscdk/awscdk-app-py.ts
> +    }
How about we change `AppCode` to create a `SampleFile` instead of `SourceCode`? (Or perhaps add some kind of `sample?: boolean` option to `SourceCode` so that it acts like a `SampleFile`)

2022-05-31 18:13 UTC, Chriscbr commented on src/cdk8s/cdk8s-app-py.ts
> +export interface Cdk8sPythonOptions extends PythonProjectOptions {
```suggestion
/**
 * Options for `Cdk8sPythonApp`
 */
export interface Cdk8sPythonAppOptions extends PythonProjectOptions {
```

2022-05-31 18:13 UTC, Chriscbr commented on test/cdk8s/cdk8s-app-project-py.test.ts
> +test("", () => {
```suggestion
test("basic options", () => {
```

2022-06-23 05:15 UTC, marciocadev commented
I changed the file 'semver.ts' because the alpha, beta, and release candidate format did not match the PEP440


I also put the option to add cdk8s-plus-XX according to the version of kubernetes as defined on the cdk8s website
[cdk8s](https://cdk8s.io/docs/latest/plus/)

2022-06-24 14:02 UTC, lazinessdevs commented on src/cdk8s/cdk8s-app-py.ts
> +    this.addDevDependency(`constructs@${this.constructsVersion}`);
I extract that common logic and change cdk8s-app-ts and cdk8s-app-py

2022-06-24 14:05 UTC, marciocadev commented on src/cdk8s/cdk8s-app-py.ts
> +    this.addDevDependency(`constructs@${this.constructsVersion}`);
I extract the common logic and change `Cdk8sTypeScriptApp` and `Cdk8sPythonApp` to use `Cdk8sDeps`

2022-07-16 02:22 UTC, Chriscbr approved these changes

2022-07-21 16:10 UTC, mrgrain commented
@marciocadev I think this PR is ready now. Could you please update the PR title and body to reflect our[ contribution guidelines](https://github.com/projen/projen/blob/main/CONTRIBUTING.md#making-a-pull-request). Specifically the breaking changes need to be called out.

2022-07-21 17:36 UTC, marciocadev commented
> @marciocadev I think this PR is ready now. Could you please update the PR title and body to reflect our[ contribution guidelines](https://github.com/projen/projen/blob/main/CONTRIBUTING.md#making-a-pull-request). Specifically the breaking changes need to be called out.
> 
> PS: For the future, it is much quicker to review if different fixes and features are they are split out into separate Pull Requests. E.g. the fix for Python versioning.

Hi @mrgrain 

Sorry for the numerous changes in the same PR

Unfortunately I was only able to identify certain changes during the creation of this branch.

In order for the `cdk8s-app-py` project to be made I had to make many changes that were not initially planned, from changes to `python` and `cdk8s` projects to fixes in versioning python dependencies according to PEP 404

I will make the requested changes

2022-07-21 17:49 UTC, mrgrain commented
> Sorry for the numerous changes in the same PR
> 
> Unfortunately I was only able to identify certain changes during the creation of this branch.

No worries, I know how it goes sometime. 😅  And I know splitting things our can be a pain. 
 
We really appreciate your contribution!

2022-07-21 18:36 UTC, marciocadev commented
> > Sorry for the numerous changes in the same PR
> > Unfortunately I was only able to identify certain changes during the creation of this branch.
> 
> No worries, I know how it goes sometime. 😅 And I know splitting things our can be a pain.
> 
> We really appreciate your contribution!

I make some changes on body of this PR, I believe that the only BREAKING CHANGE will be the possibility of defining which cdk8s-plus-XX according to the Kubernetes version

As for the PR title I'm not sure what to change, can you help me with that?

2022-07-22 12:42 UTC, mrgrain commented
Title is fine, I made some minor tweaks. 👍🏻 

--- 

I might be missing some context, but I think the `PytestSample` interface has changed
https://github.com/projen/projen/pull/1720/files#diff-641dcd3b3e747147391e8bed1f17c5b7d702b555eb1f11c9ebc65bfb9c53251dR23

I personally would also classify the  semver fix as breaking, but I can see how that's debatable. 😀 

--- 

If you don't mind, would you phrase the breaking change section more in the style of what needs to be done to resolve the break. [v0.58.0 is a good example](https://github.com/projen/projen/releases/tag/v0.58.0)

e.g.


BREAKING CHANGE: `PytestSample` now requires an explicit `moduleName`, as part of the new `options: PytestSampleOptions` parameter (replacing `testdir`). If you have a `PythonProject` the module name is available via `pythonProject.moduleName`

2022-07-22 13:41 UTC, marciocadev commented
You're right, I make the change on BREAKING CHANGE, I forgot the change on PytestSample

2022-07-24 10:13 UTC, mrgrain commented
@mergifyio update

2022-07-24 10:26 UTC, merged