fix: Add support for upper case variables
projen/projen pull request #1721
Opened 2022-03-28 22:49 UTC by marciocadev

Fixing the issue of job variables rendering as snake case and don't respecting the original format

closes #1693 
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-30 00:35 UTC, Chriscbr requested changes
Unit test?

2022-04-05 23:49 UTC, Chriscbr requested changes

2022-04-05 23:49 UTC, Chriscbr commented on test/gitlab/configuration.test.ts
> +  );
Super small nit - let's just assert that it contains the caps variable and ignore the rest, so that this test doesn't get broken by formatting changes and such.
```suggestion
  expect(snapshot[".gitlab/ci-templates/foo.yml"]).toContain("AWS_REGION: eu-central-1");
```

2022-04-05 23:49 UTC, Chriscbr commented on test/gitlab/configuration.test.ts
> +  );
See other comment
```suggestion
  expect(snapshot[".gitlab/ci-templates/foo.yml"]).toContain("AWS_REGION: eu-central-1");
```

2022-04-06 17:04 UTC, marciocadev commented on test/gitlab/configuration.test.ts
> +  );
done

2022-04-06 20:52 UTC, Chriscbr approved these changes

2022-04-06 20:59 UTC, merged