feat: Renovatebot configuration
projen/projen pull request #1758
Opened 2022-04-10 06:11 UTC by Hi-Fi

Allow configuring renovatebot to each project type with few configurable fields.

Fix #1667
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-10 14:06 UTC, Hi-Fi commented
@eladb @Chriscbr does this look OK?

Sidenote: [CONTRIBUTING.md](CONTRIBUTING.md) is a bit vague with
> Shout out to collaborators.

2022-04-13 00:10 UTC, pgollucci commented on test/javascript/node-project.test.ts
> +    minNodeVersion: "14.0.0",
Will be default soon. Do we need the minVersion?

2022-04-13 00:11 UTC, pgollucci commented on test/javascript/node-project.test.ts
> +    mergify: false,
Does renovate bot work  with Mergify, Dependabot, or the new Github branch merge stuff?

2022-04-13 00:12 UTC, pgollucci reviewed
I might separate out json5 from the rest but in general it looks good to me

2022-04-13 03:12 UTC, Hi-Fi commented on test/javascript/node-project.test.ts
> +    minNodeVersion: "14.0.0",
Might be that test would be fine without it. Added it to ensure that `.projen/deps.json` defines version for `@types/node`. 

Same thing for `projenVersion`. 

Do you see that those version definitions should be removed?

2022-04-13 03:13 UTC, Hi-Fi commented on test/javascript/node-project.test.ts
> +    mergify: false,
I don't see why it wouldn't, as it "just" creates PRs like users and dependabot.

2022-04-13 03:19 UTC, Hi-Fi commented
> I might separate out json5 from the rest but in general it looks good to me

Main thing here is the possibility to add the comment (but only inside JSON, not for whole object), as Renovatebot parser fails if there's keys that are not recognized (like `"//"` used elsewhere).

Programmatic creation of JSON5 doesn't have possibility for comments, so adding that "projen created" comment is still pure string handling.

It could be done if needed also other way around, so first generate full JSON and then regexp change that `"//"` element to comment.

2022-04-20 04:11 UTC, Hi-Fi commented
@pgollucci do you think there's some changes needed or is this OK to be merged? Improving configuration options etc. is then easier when base is available (which hopefully would work users as is)

2022-05-03 05:44 UTC, Hi-Fi commented
@eladb @Chriscbr @pgollucci 

This has been some time already without comments or anything. Is there some issue that should be fixed, or could this be merged and taken to use so it's easier to see if some features to this are needed.

2022-05-03 16:59 UTC, Chriscbr requested changes
Hey @Hi-Fi - looks great, I've got just a couple comments on this PR!

2022-05-03 16:59 UTC, Chriscbr commented on src/renovatebot.ts
> +  readonly scheduleInterval?: string[];
In TypeScript an enum value can be interchangeable with a string, but when JSII translates this into other languages, this will not be valid. See https://aws.github.io/jsii/specification/2-type-system/#enum

We can either change the default to match the type, like `@default ["at any time"]`, or change the type to match the default, like `readonly scheduleInterval?: RenovateScheduleInterval;` (and convert it to a string array as an implementation detail). Another option is to create a union-like class so that the user can custom options like this: `RenovateScheduleInterval.custom("every third wednesday")` (example: https://github.com/aws/aws-cdk/blob/4cb2fe8ff410cbb769565453d43feaa820047acb/packages/%40aws-cdk/aws-apigatewayv2/lib/parameter-mapping.ts#L14)

2022-05-03 16:59 UTC, Chriscbr commented on src/renovatebot.ts
> + * From https://docs.renovatebot.com/presets-schedule/
```suggestion
 * @see https://docs.renovatebot.com/presets-schedule/
```

2022-05-03 16:59 UTC, Chriscbr commented on docs/api/API.md
> +[Renovatebot](#projen-renovatebot)|Defines renovatebot configuration for projen project.
Let's also mention this in `docs/node.md`.

2022-05-03 16:59 UTC, Chriscbr commented on test/javascript/node-project.test.ts
> +    minNodeVersion: "14.0.0",
I think we can remove the projenVersion and minNodeVersion safely. (unless there's a reason we don't want @types/node to be updated to the latest minor versions?) It looks like the component should ignore projen by default regardless

2022-05-03 16:59 UTC, Chriscbr commented on test/javascript/node-project.test.ts
> +  expect(snapshot["renovate.json5"]).toMatchSnapshot();
Can we also add an assertion on the list of ignored dependencies, by parsing the json5 file? e.g.

```suggestion
  expect(json5.parse(snapshot["renovate.json5"]).ignoreDeps).toEqual(...);
  expect(snapshot["renovate.json5"]).toMatchSnapshot();
```

2022-05-03 16:59 UTC, Chriscbr commented on src/renovatebot.ts
> +  readonly labels?: string[];
Where does this field get used? (this definitely seems like a useful option to have!)

2022-05-03 16:59 UTC, Chriscbr commented on src/json.ts
> +    }
Can we add a unit test to `json.test.ts` that checks that json5 files have a marker added as a comment instead?

2022-05-04 04:20 UTC, Hi-Fi commented on src/renovatebot.ts
> +  readonly labels?: string[];
Apparently I wrote API first, and forgot to take this to use. So just usage missing.

2022-05-04 04:20 UTC, Hi-Fi commented on src/json.ts
> +    }
Sure, will do that

2022-05-04 04:26 UTC, Hi-Fi commented on test/javascript/node-project.test.ts
> +    minNodeVersion: "14.0.0",
OK, I'll remove those. As projen's own upgrade is now included in `upgrade` script, I think it should be only ignored if user specifies the version in `.projenrc.js`.

It's then user's own responsibility to add mutation check to project, or check PR carefully if upgrade to projen itself is included.

2022-05-04 04:30 UTC, Hi-Fi commented on src/renovatebot.ts
> +  readonly scheduleInterval?: string[];
Noticed that JSII thing, as original was `RenovateScheduleInterval | string` type.

Maybe would go with string, and just mention that some basic values are available from enum.

2022-05-04 05:17 UTC, Hi-Fi commented on test/javascript/node-project.test.ts
> +  expect(snapshot["renovate.json5"]).toMatchSnapshot();
Added checking of ignores in the test

2022-05-04 05:18 UTC, Hi-Fi commented on src/renovatebot.ts
> +  readonly labels?: string[];
Added usage and included in tests

2022-05-04 05:33 UTC, Hi-Fi commented on docs/api/API.md
> +[Renovatebot](#projen-renovatebot)|Defines renovatebot configuration for projen project.
Added mention next to dependabot

2022-05-04 16:39 UTC, Chriscbr approved these changes
LGTM.

2022-05-04 16:40 UTC, merged