feat: add prebuild steps to build workflow
projen/projen pull request #1771
Opened 2022-04-15 19:12 UTC by kaizen3031593

Exposing pre-build steps on the build workflow. `BuildWorkflow` has a property called `preBuildSteps` so I think this API was unnecessarily omitted.

In addition to `addPostBuildSteps`, `BuildWorkflow` also has APIs for `addPostBuildJob` and `addPostBuildJobTask`, but I can't see a use case for needing to add Jobs pre-build so I did not add the corresponding `pre` APIs.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-15 19:13 UTC, kaizen3031593 commented on test/javascript/node-project.test.ts
> +describe("extend github build workflow", () => {
I couldn't find a test file for `BuildWorkflow` but similar tests were done in this file so I stuck them here. But happy to get some direction on where I should be adding tests.

2022-04-15 19:43 UTC, Chriscbr requested changes
LGTM 👍 

It's worth calling out that any steps added through this API will only affect the `build.yml` workflow that runs on pull requests -- but not in other builds, like in `release.yml` and `upgrade.yml`. We actually have another API for doing this: `workflowBootstrapSteps`.

I wonder if it would make sense to rename the component `PullRequestBuildWorkflow` to make this more clear?

2022-04-15 19:43 UTC, Chriscbr commented on test/javascript/node-project.test.ts
> +      "- name: build\n        run: npx projen build\n      - name: hello-world\n        run: echo 'hello world'"
Can we make this less whitespace / indentation sensitive? How about we `YAML.parse` the contents and make an assertion on that perhaps?

2022-04-15 19:43 UTC, Chriscbr commented on test/javascript/node-project.test.ts
> +describe("extend github build workflow", () => {
This is fine - but I agree with your intuition that this should belong in a separate file specific to the component. 🙂

2022-04-15 19:49 UTC, kaizen3031593 commented
> It's worth calling out that any steps added through this API will only affect the `build.yml` workflow that runs on pull requests -- but not in other workflows where the repo is built, like in `release.yml` and `upgrade.yml`. We actually have another API for doing this: `workflowBootstrapSteps`.

🤦is there really a use case for this then? Seems like `workflowBootstrapSteps` covers this and more. `addPreBuildSteps` is only a use case when someone wants a prebuild step in `build.yml` and not `release.yml` or `upgrade.yml`. I can't think of why...

This might be another case of "had trouble finding the property I needed" rather than "projen is missing an API"

2022-04-18 20:50 UTC, Chriscbr commented
@kaizen3031593 That's fair. I think it might still make sense to add this API though, if only to mirror the `addPostBuildSteps` API for feature parity. 🙂

2022-04-19 19:47 UTC, closed without merging