fix: cannot disable automerge and while keeping mergify enabled
projen/projen pull request #1783
Opened 2022-04-19 22:15 UTC by Chriscbr

Supersedes #1766
Fixes #1765

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-20 21:55 UTC, kaizen3031593 requested changes
Some minor nits

2022-04-20 21:55 UTC, kaizen3031593 commented on test/github/mergify.test.ts
> +  test("with automerge", () => {
```suggestion
  test("with automerge options", () => {
```

2022-04-20 21:55 UTC, kaizen3031593 commented on src/javascript/node-project.ts
> +    if (autoMerge && this.github?.mergify && this.buildWorkflow?.buildJobIds) {
nit, but how do you feel about just going `options.autoMerge !== false &&...` it just feels like we're creating a const for no reason as we don't use it outside of the if.

2022-04-20 21:55 UTC, kaizen3031593 commented on src/javascript/node-project.ts
> +   * @default true
default is boolean but here, `autoMerge` is of type `AutoMerge`

2022-04-20 21:55 UTC, kaizen3031593 commented on src/javascript/node-project.ts
> +   * @default true
It seems odd to me that `autoMerge` as a property is boolean but `autoMerge` as the exposed reference is type `AutoMerge`. At a minimum this one should be documented better than "Automatic PR merges."

2022-04-20 21:55 UTC, kaizen3031593 commented on src/github/github-project.ts
> +  readonly autoMerge?: boolean;
Should we have `@default true` here (instead of the other place)?

2022-04-20 22:45 UTC, Chriscbr commented on src/github/github-project.ts
> +  readonly autoMerge?: boolean;
Whoops, yes thanks for catching this.

2022-04-20 22:46 UTC, Chriscbr commented on src/javascript/node-project.ts
> +   * @default true
Updating the docstring

2022-04-20 22:48 UTC, Chriscbr commented on src/javascript/node-project.ts
> +    if (autoMerge && this.github?.mergify && this.buildWorkflow?.buildJobIds) {
I don't have a strong opinion on it, I guess I just prefer this since it's a pattern we've been using in the rest of projen (`const something = input ?? default`). But yeah I can see arguments for either side. I'll inline it to make it more concise.

2022-04-21 16:36 UTC, kaizen3031593 approved these changes
Yay!

2022-04-21 16:46 UTC, merged