feat(gitlab): add missing types to implement caching in GitLab pipelines
projen/projen pull request #1800
Opened 2022-04-26 15:26 UTC by nbyl

#1357 added the types to build GitLab CI pipelines. The [base schema](https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json) unfortunately broke the implementation of caching into two entities. In the [manual](https://docs.gitlab.com/ee/ci/yaml/#cache), this is only one entity.

In the current state, caching between pipeline runs is actually not very usable. You can only express when to cache, not what. 

This PR adds the types needed to generate cache statements according to the GitLab reference for [GitLab 14.10](https://docs.gitlab.com/14.10/ee/ci/yaml/).

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-26 21:58 UTC, Chriscbr requested changes

2022-04-26 21:58 UTC, Chriscbr commented on test/gitlab/configuration.test.ts
> +  expect(snapshot).toMatchSnapshot();
Please scope these down to the appropriate changes
```suggestion
  expect(snapshot[".gitlab/ci-templates/foo.yml"]).toMatchSnapshot();
```

2022-04-26 21:58 UTC, Chriscbr commented on test/gitlab/configuration.test.ts
> +  expect(snapshot).toMatchSnapshot();
```suggestion
  expect(snapshot[".gitlab/ci-templates/foo.yml"]).toMatchSnapshot();
```

2022-04-27 16:27 UTC, Chriscbr commented on test/gitlab/__snapshots__/configuration.test.ts.snap
> +exports[`adds correct entries for path-based caching 1`] = `undefined`;
@nbyl These should not be empty. I think we should be capturing a different file name?

2022-04-27 18:08 UTC, nbyl commented on test/gitlab/__snapshots__/configuration.test.ts.snap
> +exports[`adds correct entries for path-based caching 1`] = `undefined`;
@Chriscbr Sorry, i missed that. I've updated the file path and snapshots.

2022-04-27 18:12 UTC, Chriscbr approved these changes
👍

2022-04-27 18:20 UTC, merged