fix: resolve issue with option fqns in java when they do not exist in…
projen/projen pull request #1850
Opened 2022-05-13 03:41 UTC by agdimech

This PR resolves an issue whereby the Java projenrc synthesizer was throwing an error when fqns couldn't be resolved to a type in the jsii manifest.

```
return [jsiiType.namespace, jsiiType.name].filter((x) => x).join(".");
                     ^
TypeError: Cannot read property 'namespace' of undefined
```

The use case for this happening is I have a custom project type that extends JavaProject. As part of the bootstrap options iterator, it tries to resolve projen specific fqns i.e: projen.github.* into types within the .jsii manifest which I generate as part of my package. Given projen types are not bundled as part of my .jsii file, this will error out as above.

I am not sure if this is related, but I did notice the projen submodules were all empty in my .jsii file as shown below:

`"projen": {
      "submodules": {
        "projen.awscdk": {},
        "projen.build": {},
        "projen.cdk": {},
        "projen.cdk8s": {},
        "projen.cdktf": {},
        "projen.github": {},
        "projen.github.workflows": {},
        "projen.gitlab": {},
        "projen.java": {},
        "projen.javascript": {},
        "projen.python": {},
        "projen.release": {},
        "projen.typescript": {},
        "projen.vscode": {},
        "projen.web": {}
      }`

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-05-13 15:55 UTC, Chriscbr requested changes

2022-05-13 15:55 UTC, Chriscbr commented on src/java/projenrc.ts
>      }
Can we add unit tests for this?

Perhaps we could start by extracting these 10 lines to a helper function like `generateJavaOptionNames(options, jsiiManifest)` and test it in isolation in `test/java/projenrc.test.ts`. (or feel free to test it a different way)

2022-05-14 03:47 UTC, agdimech commented on src/java/projenrc.ts
>      }
Sure, just posted a new revision with the incorporated feedback Had a small issue in the last PR where the manifest looking was throwing if a fqn didn't exist in the option. This is also fixed in the latest revision.

2022-05-16 03:12 UTC, Chriscbr approved these changes

2022-05-16 03:29 UTC, agdimech commented
Apologies,  just fixed eslint errors and posted a new revision.

2022-05-16 05:14 UTC, merged