fix: resolve issue where generated import prefix is incorrect in .pro…
projen/projen pull request #1851
Opened 2022-05-13 05:28 UTC by agdimech

I am seeing an error whereby the generated .projenrc.py does not have the correct module_name. The FQN is aws-prototyping-sdk... however the exported python moduleName is aws_prototyping_sdk.

This PR ensures that the declared module_name takes precedence.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-05-13 15:56 UTC, Chriscbr requested changes

2022-05-13 15:56 UTC, Chriscbr commented on src/python/projenrc.ts
> +    emit(toPythonImport(importName));
Can we add a unit test for this?

2022-05-14 04:01 UTC, agdimech commented on src/python/projenrc.ts
> +    emit(toPythonImport(importName));
Added unit test in latest revision.

2022-05-16 05:08 UTC, Chriscbr approved these changes

2022-05-16 05:25 UTC, merged