feat(cdk-config): add methods for adding includes and excludes
projen/projen pull request #1919
Opened 2022-06-08 09:53 UTC by ryansonshine

This change adds `addExcludes` and `addIncludes` to the `CdkConfig` allowing users to customize the includes and excludes values in `cdk.json`.

Closes #1898

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-08 16:24 UTC, Chriscbr requested changes

2022-06-08 16:24 UTC, Chriscbr commented on src/awscdk/cdk-config.ts
> +  public readonly exclude: string[];
Please make these fields private. We don't want these collections to be mutated outside of the `addXxx` methods. (`readonly` only enforces that you can't reassign the variable to a new array)

2022-06-08 16:24 UTC, Chriscbr commented on src/awscdk/cdk-config.ts
> +  }
Let's make this `string[]` instead:
```suggestion
  public addIncludes(...patterns: string[]) {
    this.include.push(...patterns);
  }
```

We use a tool named jsii to translate projen's API into other languages like Java - and since they cannot express type unions as easily, other users will just see a method that accepts "Object" instead of "string" or "Array\<string>".

2022-06-08 16:24 UTC, Chriscbr commented on src/awscdk/cdk-config.ts
> +  }
See comment above
```suggestion
  public addExcludes(...patterns: string[]) {
    this.exclude.push(...patterns);
  }
```

2022-06-09 02:33 UTC, ryansonshine commented on src/awscdk/cdk-config.ts
> +  }
Ah interesting, is there a way to make jsii throw an error or warning when union types are used?

2022-06-09 18:36 UTC, Chriscbr requested changes

2022-06-09 18:36 UTC, Chriscbr commented on test/awscdk/cdk-config.test.ts
> +    expect(config.include).toEqual(defaultIncludes);
Can we avoid using typescript error suppressions? Either of these options would work fine:

- We can expose `include` and `exclude` "safely" by creating a getter which returns a copy of the array. e.g.:

```ts
public get includes(): string[] {
  return [...this._includes];
}
```
- We can make an assertion on the snapshot instead:
```ts
const config = Testing.synth(project)["cdk.json"];
expect(snapshot["cdk.json"].watch.include).toEqual(...);
```

2022-06-09 18:38 UTC, Chriscbr commented on src/awscdk/cdk-config.ts
> +  }
That's a good question - I'm not sure off the top of my head, but I'll take a look into it :)

2022-06-10 02:51 UTC, Chriscbr approved these changes

2022-06-10 02:52 UTC, merged