draft: initial code for sequences
projen/projen pull request #1940
Opened 2022-06-18 08:42 UTC by ThomasSteinbach

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-21 13:47 UTC, mrgrain requested changes

2022-07-21 13:47 UTC, mrgrain commented on src/gitlab/configuration.ts
> +  private readonly _stages: string[] = [];
Any reason this public property should be private now?
If so, could there be a way to keep the the current access and deprecate it in favour of the new API?

2022-07-21 13:47 UTC, mrgrain commented on src/gitlab/configuration.ts
> +  public readonly jobs: Sequence = new Sequence();
Is there a way keep the the current interface, deprecate it and offer this feature as a new API?

2022-07-21 13:47 UTC, mrgrain commented on src/gitlab/sequence.ts
> +import { AllowFailure, Artifacts, Cache, CacheKeyFiles, Environment, Filter, Image, IncludeRule, Inherit, Job, JobWhen, Need, Parallel, Release, Retry, Secret, Service, Trigger } from "./configuratio
This feel looks like it's generated from a source. If so, would it be feasible to add the generation process in here, instead of committing the result? (And having to manually keep it up to date.)

2022-11-03 23:32 UTC, pflorek commented
@ThomasSteinbach I really like the idea to group jobs and apply modification on them ❤️ 

There is one important point. This GitLab module has in mind to be open to changes. Therefore the new feature should not be closed. A simple function like `Sequence.tryFindJob(name: string)` or just return the map `Sequence.jobs` would be sufficient.

This comes really handy as a replacement of the child pipelines or addition. For instance I have a child pipeline on schedule and another one on merge request. But the DAG doesn't display that setup. With this feature I can have the same experience and the benefits of keyword `needs`.

Initially I didn't understand the term `Sequence`. For me it's just a group of jobs. Maybe we can add some functional stuff like `Sequence.map`

2022-12-22 08:25 UTC, robert-affinidi commented
@ThomasSteinbach what is the advantage of sequences over GitLab own extension (via extends) mechanism and yaml anchoring? (Except adding abstraction to it)

2023-02-07 01:41 UTC, pflorek commented
> @ThomasSteinbach what is the advantage of sequences over GitLab own extension (via extends) mechanism and yaml anchoring? (Except adding abstraction to it)

@robert-affinidi 

One can consider it as a monad. The proposed sequence contains a set of jobs. The sequence offers modifiers that apply given values to the contained Set of jobs. For example add tag `shared` to all jobs in the sequence. It's a nice shortcut.

2024-01-05 11:59 UTC, mrgrain commented
stale.

2024-01-05 11:59 UTC, closed without merging