chore(README): add install command to README.md
projen/projen pull request #1962
Opened 2022-06-30 12:46 UTC by marciocadev

Fixes #1936

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-03 20:09 UTC, Chriscbr commented
Is installing projen globally needed to use it? I believe with recent versions of npm, it should get automatically installed (or prompt you to install it) if you run "npx projen"

2022-07-04 17:59 UTC, marciocadev commented
I can change to `npx projen` but I think we can show how to install globally and locally, personally I prefer to install globally

Local install
```console
$ npx projen
Need to install the following packages:
   projen
Ok to proceed? (y)
```

Global install
```console
$ npm i -g projen
```

What do you think ?

By the way, I will remove the `git init` command from create a new project since `projen new` already initializes git in the folder
```console
$ mkdir my-project
$ cd my-project
$ git init
$ npx projen new PROJECT-TYPE
🤖 Synthesizing project...
...
```

to

```console
$ mkdir my-project
$ cd my-project
$ npx projen new PROJECT-TYPE
🤖 Synthesizing project...
...
```

2022-07-04 20:12 UTC, Chriscbr commented
Sure, including both options sounds ok.

> By the way, I will remove the `git init` command from create a new project since `projen new` already initializes git in the folder

Good catch 👍

2022-07-09 11:06 UTC, cgatt commented on README.md
> +### Local install
This is currently unclear as it implies that running `npx projen` is required before doing the "create project" steps below. I think it would be better to split this into two sections such as:

---

To create a new project, run the commands and follow the instructions for one of the following options:

### Using `npx`
```console
$ mkdir my-project
$ cd my-project
$ npx projen new PROJECT-TYPE
Need to install the following packages:
   projen
Ok to proceed? (y)
🤖 Synthesizing project...
...
```

### Installing Projen Globally
```console
$ npm i -g projen
$ mkdir my-project
$ cd my-project
$ projen new PROJECT-TYPE
🤖 Synthesizing project...
...
```
---

While this duplicates a couple of lines, it is much clearer to those who may not be familiar with `npx`

2022-07-09 11:57 UTC, lazinessdevs commented on README.md
> +### Local install
I agree with you, it's not a big change and will make it clearer how to proceed

2022-07-09 11:58 UTC, marciocadev commented on README.md
> +### Local install
I agree with you, it's not a big change and will make it clearer how to proceed

2022-07-15 09:52 UTC, mrgrain commented on README.md
> +
I appreciate the sentiment here, but it also makes this more complicated than it is. If your main concern is about users new to `npx`, would something like this not be better?

```suggestion
_projen_ doesn't need to be installed. You will be using [npx](https://docs.npmjs.com/cli/v7/commands/npx) to run _projen_ which takes care of all necessary setup steps.
...
```

```

2022-07-19 08:31 UTC, mrgrain requested changes
@marciocadev Have you got any feedback to my suggestion?

2022-07-21 13:31 UTC, marciocadev commented
> 

No, I make the changes

2022-07-21 14:13 UTC, mrgrain requested changes

2022-07-21 14:13 UTC, mrgrain commented on README.md
> +...
```suggestion
```
Let's remove these extra dots as well.

2022-07-21 14:20 UTC, mrgrain approved these changes

2022-07-21 14:30 UTC, merged