feat: add smithy build support to projen
projen/projen pull request #1970
Opened 2022-07-06 00:29 UTC by mayurm88

For folks using [smithy](https://awslabs.github.io/smithy/index.html) in their project, it would be great to support generation of `smithy-build.json` file using projen.

The types defined in this PR could be refined further for type safety but this PR is a starting point for those changes. [This](https://awslabs.github.io/smithy/1.0/guides/building-models/build-config.html#projections) was used as a reference for defining types in smithy-build.ts file.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-07 20:55 UTC, Chriscbr reviewed
This looks cool, it would be great to have smithy support in projen! :) Thanks as well for adding several test cases.

2022-07-07 20:55 UTC, Chriscbr commented on src/smithy-build.ts
> +import { Component } from "./component";
Can we move this file into a new submodule (`src/smithy/smithy-build.ts`)?

2022-07-07 20:55 UTC, Chriscbr commented on src/smithy-build.ts
> +  readonly ignoreMissingPlugins?: boolean;
Typically we include a docstring for each option, including a description of what the default value or behavior is, like `@default "1.2.3"` or `@default - no projections`. See https://github.com/projen/projen/blob/main/src/gitlab/configuration.ts for an example of how it's formatted. (You can also include a link to any relevant smithy docs if you think it would help someone reading the docs).

2022-07-07 20:55 UTC, Chriscbr commented on src/smithy-build.ts
> +export class SmithyBuild extends Component {
We should include a docstring for the component and any public properties/methods.

2022-07-07 20:55 UTC, Chriscbr commented on src/smithy-build.ts
> +  public plugins?: PluginsType;
For properties that are mutable like `imports`, `plugins`, and `projections`, we usually try to avoid publicly exposing the underlying data structures to prevent bugs where different constructs try to mutate the objects directly and it becomes hard to refactor code. See the design guidelines on this page for more info (it's for a totally different repo, but we try to also follow the spirit of it in projen): https://github.com/cdk8s-team/cdk8s-plus/blob/0babfd9aa72d96f1d364bbc28a9aa516729a5775/CONTRIBUTING.md#mutability Instead, it's preferred to include getter methods that return a copy of the data structure -- see the link for an example.

`manifest` can be private altogether (it does not need a getter method) since the user can just view the individual fields `version`, `outputDirectory, etc).

For example:
```ts
public get projections() {
  return { ...this._projections };
}
```

2022-07-13 22:00 UTC, mayurm88 commented on src/smithy-build.ts
> +  readonly ignoreMissingPlugins?: boolean;
Thank you for guiding me on this. Added docstring for each of these options including the default behaviour.

2022-07-13 22:00 UTC, mayurm88 commented on src/smithy-build.ts
> +export class SmithyBuild extends Component {
done

2022-07-13 22:01 UTC, mayurm88 commented on src/smithy-build.ts
> +  public plugins?: PluginsType;
Makes complete sense. Added these getter methods and made `imports`, `plugins` and `projections` private. Also made `manifest` private.

2022-07-16 01:56 UTC, Chriscbr approved these changes

2022-07-16 01:56 UTC, Chriscbr commented on src/smithy/smithy-build.ts
> +  readonly ignoreMissingPlugins?: boolean;
These options should also probably have docstrings (they can be the same as the ones defined in the class below)

2022-07-18 09:50 UTC, mrgrain requested changes
@mayurm88 Let's add these extra jsdocs and this is good to go!

2022-07-18 23:41 UTC, mayurm88 commented on src/smithy/smithy-build.ts
> +  readonly ignoreMissingPlugins?: boolean;
Thanks and apologies for not adding these earlier.

2022-07-19 08:22 UTC, mrgrain approved these changes
🚢

2022-07-19 08:34 UTC, mrgrain requested changes

2022-07-19 08:34 UTC, mrgrain commented on src/smithy/smithy-build.ts
> +
```suggestion

```

2022-07-19 08:34 UTC, mrgrain commented on src/smithy/smithy-build.ts
> +
```suggestion

```

2022-07-19 08:34 UTC, mrgrain commented on src/smithy/smithy-build.ts
> +
```suggestion

```

2022-07-19 08:34 UTC, mrgrain approved these changes

2022-07-19 08:41 UTC, mrgrain commented on src/smithy/smithy-build.ts
> +
```suggestion

```

2022-07-19 09:00 UTC, merged