feat!: add Project.defaultCommitManagedFiles prop
projen/projen pull request #1972
Opened 2022-07-11 07:43 UTC by skyrpex

By default, files managed by projen are commited to the repository. That's not entirely necessary in some cases, and this commit allows customizing this behavior. By providing the Project.defaultCommitManagedFiles prop, we can tell projen whether to commit the files or not (if the File.commited prop is omitted).

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-11 17:52 UTC, eladb commented on src/project.ts
> +  readonly defaultCommitManagedFiles?: boolean;
```suggestion
  readonly commitGenerated?: boolean;
```

Maybe simpler name?

2022-07-18 07:46 UTC, eladb requested changes
There are some files, such as GitHub workflows for example, that MUST be committed. I suspect we need to explicitly indicate that for these files when this option is set to false. Otherwise it's not really usable.

The way I would handle this is add a _required_ prop to FileBase and let the compiler guide you through all the possible files and make an intentional decision whether it must be committed or not.

2022-07-18 08:43 UTC, skyrpex commented on src/project.ts
> +  readonly defaultCommitManagedFiles?: boolean;
`commitGenerated` it is.

2022-07-18 08:47 UTC, skyrpex commented
> There are some files, such as GitHub workflows for example, that MUST be committed. I suspect we need to explicitly indicate that for these files when this option is set to false. Otherwise it's not really usable.
> 
> The way I would handle this is add a _required_ prop to FileBase and let the compiler guide you through all the possible files and make an intentional decision whether it must be committed or not.

Right, these files need to be committed. The prop you're talking about, do you want it on projen, or are you suggesting it as a temporary means to fix the files that should be truly committed?

2022-07-19 08:47 UTC, mrgrain submitted a review, later dismissed
To reflect the current status of this PR

2022-07-19 16:34 UTC, eladb commented on src/ignore-file.ts
> +      committed: filePath !== ".gitignore" ? false : undefined,
I believe .gitignore must be committed, no?

2022-07-20 20:35 UTC, Chriscbr reviewed
Unit test?

2022-07-20 20:35 UTC, Chriscbr commented on test/__snapshots__/integ.test.ts.snap
> -!/.npmignore
Is this a regression?

2022-07-21 07:41 UTC, skyrpex commented on src/dependencies.ts
> +        committed: true,
I thought this one file was necessary for projen to maintain some sort of state, but seeing the contents inside it, it doesn't seem required.

2022-07-21 07:51 UTC, skyrpex commented on src/ignore-file.ts
> +      committed: filePath !== ".gitignore" ? false : undefined,
`.gitignore` is committed while the rest of the ignore files aren't, although the logic is hard follow. Maybe a small refactor and some docs will help.

2022-07-21 07:51 UTC, eladb commented on src/dependencies.ts
> +        committed: true,
It' actually not used for anything (besides @MarkMcCulloh's IDE plugin)

2022-07-21 07:52 UTC, skyrpex commented on test/__snapshots__/integ.test.ts.snap
> -!/.npmignore
AFAIK `.npmignore` isn't needed at the repository level, isn't it? For any other operation, it'll be created by projen (eg, the release task).

2022-07-21 07:53 UTC, skyrpex commented on src/github/mergify.ts
> +        committed: true,
Something like `// Mergify needs to read the file from the repository in order to work.` ?

2022-07-21 07:54 UTC, eladb commented on src/github/mergify.ts
> +        committed: true,
Yes

2022-07-21 08:14 UTC, skyrpex commented on test/__snapshots__/integ.test.ts.snap
> -!/.npmignore
Yes, didn't get the logic for `IgnoreFile.commited` well.

2022-07-21 08:16 UTC, skyrpex commented on src/ignore-file.ts
> +      committed: filePath !== ".gitignore" ? false : undefined,
Yes, got it all wrong.

2022-07-21 09:56 UTC, skyrpex reviewed
Added some explanations to why some files must be committed, and also added some unit tests.

I haven't yet managed to ignore `.projen/deps.json` file if `commitGenerated` is false. Seems like it isn't reading the value of `project.commitGenerated` properly.

2022-07-21 09:56 UTC, skyrpex commented on src/github/pr-template.ts
> +      committed: true,
Done.

2022-07-21 09:56 UTC, skyrpex commented on src/github/workflows.ts
> +          committed: true,
Done.

2022-07-21 09:56 UTC, skyrpex commented on src/gitlab/configuration.ts
> +      committed: true,
Done.

2022-07-21 09:56 UTC, skyrpex commented on src/gitpod.ts
> +      committed: true,
Done.

2022-07-25 15:18 UTC, eladb approved these changes

2022-07-25 17:07 UTC, mrgrain commented
@skyrpex Once you've updated the branch and resolved the conflicts I think we are good to go. :shipit:

2022-07-25 17:17 UTC, MarkMcCulloh commented on src/dependencies.ts
> +        committed: true,
It is used for state, it's the default method to decide when to delete files that should no longer exist. It's not required per-say (cleanup will fallback to previous logic), but it is used

2022-08-05 07:35 UTC, skyrpex commented
@mrgrain rebased and pushed! 🤞🏻

2022-08-05 08:47 UTC, mrgrain approved these changes
Approved to ship

2022-08-05 08:48 UTC, merged