feat(object-file): added ability to apply JSON patches to object files
projen/projen pull request #1994
Opened 2022-07-25 15:30 UTC by tompahoward

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-26 14:03 UTC, Chriscbr reviewed
I like the idea of shortening the name from `addJsonPatch()` to `patch()` 🙂 

Looks great, just found one nitpick

2022-07-26 14:03 UTC, Chriscbr commented on test/object-file.test.ts
> +  test("addJsonPatch(p, v) adds to an existing array", () => {
I think the test names need to be updated based on the new API names

2022-08-10 09:58 UTC, mrgrain requested changes
@tompahoward Looking forward to this if you'll find the time to get it over the line =)

2022-08-16 21:39 UTC, tompahoward commented on test/object-file.test.ts
> +  test("addJsonPatch(p, v) adds to an existing array", () => {
done... finally 🎉

2022-08-17 09:35 UTC, mrgrain approved these changes
Looking good now! Thanks for fixing up the final bits 😃 

:shipit:

2022-08-17 09:46 UTC, merged