feat: Support more commands on Windows using shx
projen/projen pull request #2004
Opened 2022-07-30 21:29 UTC by kichik

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-30 21:34 UTC, kichik commented
I'm [using `cp`](https://github.com/CloudSnorkel/cdk-github-runners/blob/b816ef0b81f0fe802bced0049790151eb461d42f/.projenrc.js#L119-L120) and it would be nice to have it automatically use `shx`.

2022-08-02 17:24 UTC, mrgrain requested changes

2022-08-02 17:24 UTC, mrgrain commented on src/task-runtime.ts
> +          ["mkdir", "mv", "rm", "cp", "cd"].includes(cmd)
This is great addition, but I don't think `cd` is supported by `shx`. [1]

```suggestion
          ["mkdir", "mv", "rm", "cp"].includes(cmd)
```

[1] https://github.com/shelljs/shx#unsupported-commands

2022-08-02 17:29 UTC, kichik commented on src/task-runtime.ts
> +          ["mkdir", "mv", "rm", "cp", "cd"].includes(cmd)
Thanks. I misread the documentation.

2022-08-02 17:34 UTC, mrgrain approved these changes

2022-08-02 17:51 UTC, merged