feat: adding a README file to the jsii construct.
projen/projen pull request #203
Opened 2020-10-18 21:42 UTC by mbonig

*Issue #, if available:*

*Description of changes:*

Publishing to pypi requires a readme, so adding a simple README file to the jsii construct.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-18 22:07 UTC, mbonig commented
Since this itself is a jsii project I'm not sure how to get the build working. I think I could force it by making sure that the README.md doesn't get replaced but I'm not sure that's the right approach. Since a README.md file is expected to be manually maintained after the creation then I assume it can't be handled quite like the other files.

Taking suggestions.

2020-10-20 02:46 UTC, Chriscbr commented
Yeah, I've seen a similar approach used in `SampleCode` components in some of the projects - I think your solution makes natural sense (since I doubt most people would want to define their README through .projenrc.js). Maybe it's worthwhile to create a general component (maybe named `UserManagedFile` or `RawFile` or similar) for representing these kinds of files across the library, and have `Readme` extend that? Curious what y'all think.

2020-10-20 09:25 UTC, eladb commented
> Curious what y'all think.

I think it's a good idea. I don't like to duplicate this logic throughout. I'd call it `SampleFile` or something like that.

2020-10-20 16:33 UTC, mbonig commented
I refactored some functionality from the SampleCode class into a SampleFile abstract class. Wasn't loving the abstract class definition, feels like maybe this isn't an abstract class but something different so I'm open to suggestions.

2020-10-20 23:43 UTC, Chriscbr commented on src/typescript.ts
> +class SampleCode extends SampleFile {
I'm not sure if inheritance feels right here since this class is representing multiple files of sample code

2020-10-20 23:43 UTC, Chriscbr commented on src/readme.ts
> +}
Looks like this isn't being used

2020-10-22 23:04 UTC, mbonig commented on src/typescript.ts
> +export abstract class SampleFile extends Component {
Moved SampleFile out to file.ts.

I learn towards keeping them separate but could be persuaded either way.

2020-10-22 23:05 UTC, mbonig commented on src/typescript.ts
> +    if (fs.pathExistsSync(dir) && fs.readdirSync(dir).filter(x => x === filename)) {
Done

2020-10-22 23:07 UTC, mbonig commented on src/typescript.ts
> +class SampleCode extends SampleFile {
Those multiple files represent one "thing", the component and it's test, so it sorta feels appropriate to have them together. It doesn't feel like you'd want one without the other.

2020-10-22 23:08 UTC, mbonig commented on src/readme.ts
> +}
you're right, a holdover from a previous impl. it's been removed.

2020-10-22 23:29 UTC, mbonig commented
Had to update this code a little around SampleFile. Didn't make sense to write the test if the code wasn't written.

2020-10-23 05:47 UTC, eladb requested changes

2020-10-23 05:47 UTC, eladb commented on src/file.ts
> +export abstract class SampleFile extends Component {
Please separate to a different source file

2020-10-23 05:47 UTC, eladb commented on src/file.ts
> +export abstract class SampleFile extends Component {
Add docstrings to all public elements

2020-10-23 05:47 UTC, eladb commented on src/file.ts
> +  protected writeOnceFileContents(dir: string, filename: string, contents: string) {
Shouldn't that be `synthesize()`

2020-10-23 05:47 UTC, eladb commented on src/file.ts
> +export abstract class SampleFile extends Component {
I don't think this needs to be abstract. I'd expect the usage to be:

```ts
new SampleFile(project, 'README.me', {
  contents: 'bla bla read me'
};
```

And that's all. The class will take care of the rest

2020-10-23 05:47 UTC, eladb commented on src/typescript.ts
> +class SampleCode extends SampleFile {
I don't think `SampleCode` is needed as a class. Just use `SampleFile` here.

2020-10-23 15:25 UTC, mbonig commented on src/file.ts
> +export abstract class SampleFile extends Component {
How would you expect me to handle the situation in the Typescript project where a sample hello.ts and hello.test.ts files are created. I assume each would become 

```
new SampleFile(project, 'src/hello.ts', ...);
new SampleFile(project, 'src/hello.test.ts', ...);
```

However, the test file shouldn't be touched if the hello.ts file wasn't modified (this was a scenario I discovered when this build was failing because the new hello.test.ts tests fail).

In that case, would this be good?

```
const sourceFile = new SampleFile(project, 'src/hello.ts', ...);
if (sourceFile.wasCreated){
  new SampleFile(project, 'src/hello.test.ts', ...);
}
```

2020-10-23 17:04 UTC, mbonig commented on src/readme.ts
> +    this.text = text ?? '# jsii construct';
how would I get the project's name? `Project` doesn't seem to have the field.

2020-10-23 17:20 UTC, mbonig commented
I reworked the code to remove the abstract class and just make it more direct.

However, there is an issue that needs to be worked out. I tried to simplify the code per your suggestions @eladb but I have a problem with the samplecode in the Typescript project. As the index.ts and hello.test.ts file are now separate components I don't know how to ensure that the hello.test.ts file doesn't get written if the index.ts file doesn't get written. This was one of the reasons why they were in the same file before. I like the separation now but I can't stop the hello.test.ts file from being generated (which is causing this build to break, since the test is added but fails)

2020-10-23 17:46 UTC, Chriscbr commented
I think the solution you proposed earlier sounded good!
```ts
if (sourceFile.created) {
  new SampleFile(project, 'src/hello.test.ts', ...);
}
```

2020-10-25 11:15 UTC, eladb requested changes

2020-10-25 11:15 UTC, eladb commented on src/file.ts
> +
Any reason this moved? Please avoid combining aesthetic changes and functional changes. Let's revert

2020-10-25 11:15 UTC, eladb commented on src/file.ts
> -
Revert

2020-10-25 11:15 UTC, eladb commented on src/jsii-project.ts
> +    new Readme(this, '# jsii construct');
Let's put it in `Project` instead of `JsiiProject`. I think all projects should have a README.

2020-10-25 11:15 UTC, eladb commented on src/readme.ts
> +export class Readme extends SampleFile {
Use the "Sample" prefix to signal this is a sample file.

```suggestion
export class SampleReadme extends SampleFile {
```

2020-10-25 11:15 UTC, eladb commented on src/sample-file.ts
> +  private options: SampleFileOptions;
Always prefer `readonly` if possible.

```suggestion
  private readonly options: SampleFileOptions;
```

2020-10-25 11:15 UTC, eladb commented on src/sample-file.ts
> +  public created: boolean = false;
Don't allow accessing this directly. If there is a use case of a getter, then add a getter.

```suggestion
  private created: boolean = false;
```

2020-10-25 11:15 UTC, eladb commented on src/sample-file.ts
> +  synthesize(outdir: string) {
Always include access modifiers:

```suggestion
  public synthesize(outdir: string) {
```

2020-10-25 11:15 UTC, eladb commented on src/sample-file.ts
> +  protected writeOnceFileContents(dir: string, filename: string, contents: string) {
Why protected and not private? If there is no need to expose publicly (and protected is a type of public), keep private. We can always change later.

2020-10-25 11:15 UTC, eladb commented on src/typescript.ts
> +export class TypeScriptLibraryProject extends TypeScriptProject {
revert

2020-10-25 11:15 UTC, eladb commented on src/typescript.ts
> +export interface TypeScriptLibraryProjectOptions extends TypeScriptProjectOptions {
revert

2020-10-25 11:15 UTC, eladb commented on src/util.ts
> +export function fileExists(filePath: string) {
Feels unnecessary.

2020-10-25 11:15 UTC, eladb commented on src/typescript.ts
> +    new SampleFile(project, path.join(project.testdir, 'hello.test.ts'), { contents: testCode });
I think the correct way to model these two files (`src/index.ts` and `test/hello.test.ts`) is actually as `SampleDir`. If the directory exists, I wouldn't create anything:

```ts
new SampleDir(project, project.srcdir, {
  files: { 'index.ts': srcCode }
});

new SampleDir(project, project.testdir, {
  files: { 'hello.test.ts': testCode }
});
```

2020-11-01 18:41 UTC, pgollucci commented on src/util.ts
> +export function fileExists(filePath: string) {
I could see other things needing this, but if they do I can see them being in `util.ts`

2020-11-02 01:18 UTC, mbonig commented on src/typescript.ts
> +    new SampleFile(project, path.join(project.testdir, 'hello.test.ts'), { contents: testCode });
If the directory existence is the only thing that's checked, multiple sample files couldn't be put in the same directory.

2020-11-02 01:59 UTC, mbonig commented on src/jsii-project.ts
> +    new Readme(this, '# jsii construct');
moved

2020-11-02 02:00 UTC, mbonig commented on src/sample-file.ts
> +  protected writeOnceFileContents(dir: string, filename: string, contents: string) {
made private

2020-11-02 06:23 UTC, eladb commented on src/typescript.ts
> +    new SampleFile(project, path.join(project.testdir, 'hello.test.ts'), { contents: testCode });
Why not?

2020-11-02 14:43 UTC, mbonig commented on src/typescript.ts
> +    new SampleFile(project, path.join(project.testdir, 'hello.test.ts'), { contents: testCode });
You said that if the directory exists, it wouldn't create anything. So, if I did:
```
new SampleDir(project, project.srcdir, {
  files: { 'index.ts': srcCode }
});
new SampleDir(project, project.srcdir, {
  files: { 'main.ts': srcCode }
});
```

index.ts would be created (assuming the directory doesn't exist) but then main.ts would never be created.

2020-11-02 14:48 UTC, mbonig commented on src/util.ts
> +export function fileExists(filePath: string) {
Added it here because it felt more utilitarian and universal than just the one class that was using it.

2020-11-02 16:07 UTC, eladb commented on src/typescript.ts
> +    new SampleFile(project, path.join(project.testdir, 'hello.test.ts'), { contents: testCode });
But what's the motivation for not writing it like:

```ts
new SampleDir(project, project.srcdir, {
  files: {
    'index.ts': srcCode,
    'main.ts': srcCode,
  }
});
```

2020-11-02 16:12 UTC, mbonig commented on src/typescript.ts
> +    new SampleFile(project, path.join(project.testdir, 'hello.test.ts'), { contents: testCode });
Simply not looking at the interface close enough. That makes sense. Will make the change...

2020-11-02 17:12 UTC, mbonig commented on src/typescript.ts
> +    new SampleFile(project, path.join(project.testdir, 'hello.test.ts'), { contents: testCode });
k, I have reworked the code related to the typescript project's sample files into a new SampleDir class.

2020-11-02 17:13 UTC, mbonig commented on src/util.ts
> +export function fileExists(filePath: string) {
@eladb are you asking I refactor this into the one class that's calling it?

2020-11-02 18:13 UTC, eladb requested changes

2020-11-02 18:13 UTC, eladb commented on src/readme.ts
> + * Represents a README.md file. Unlike most other files this will only be created if the file doesn't already exist.
```suggestion
 * Represents a README.md sample file.
```

2020-11-02 18:13 UTC, eladb commented on src/sample-file.ts
> +  readonly files: SampleFiles;
```suggestion
  readonly files: { [fileName: string]: string };
```

2020-11-02 18:13 UTC, eladb commented on src/sample-file.ts
> +export interface SampleFiles {
This interface is not needed

2020-11-02 18:13 UTC, eladb commented on src/sample-file.ts
> +  public created: boolean = false;
Why is this API needed again?

It also should be `readonly`

2020-11-02 18:13 UTC, eladb commented on src/typescript.ts
> +class SampleCode {
Should still inherit from `Component`:

```suggestion
class SampleCode extends Component {
```

2020-11-02 18:13 UTC, eladb commented on src/util.ts
> +export function fileExists(filePath: string) {
yes please

2020-11-02 19:10 UTC, mbonig commented on src/sample-file.ts
> +  public created: boolean = false;
removing it.

2020-11-02 19:14 UTC, mbonig commented
There are still an unresolved questions:

How can I access the project name to make that the default content of the readme file?

2020-11-02 19:17 UTC, mbonig commented
Also, I though inline interfaces, e.g.: `{ [fileName: string]: string };`, were undoable with jsii?

2020-11-02 20:42 UTC, eladb commented
> Also, I though inline interfaces, e.g.: { [fileName: string]: string };, were undoable with jsii?

jsii treats this syntax as a special case for a map of strings.

2020-11-02 20:43 UTC, eladb commented
> How can I access the project name to make that the default content of the readme file?

I think we should expose `project.name`

2020-11-02 22:54 UTC, mbonig commented
> > How can I access the project name to make that the default content of the readme file?
> 
> I think we should expose `project.name`

New issue?

2020-11-03 06:27 UTC, eladb commented on src/sample-file.ts
> + * @field contents - The contents of the file.
```suggestion
```

2020-11-03 06:29 UTC, eladb approved these changes

2020-11-03 06:35 UTC, merged

2020-11-03 10:57 UTC, eladb commented
Sadly I had to revert this because it broke `projen new` see https://github.com/projen/projen/commit/68b1e7faa2444e11a1e7bdf59cc1a8d6ccea293c

2020-11-03 16:35 UTC, mbonig commented
Submitted new PR.