fix(release): publish to npm workflow fails when set project package …
projen/projen pull request #2113
Opened 2022-09-18 08:06 UTC by huaxk

Add pnpm/action-setup step into jsii-project prePublishSteps.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-20 10:06 UTC, mrgrain requested changes
Thanks for this fix @huaxk ! Would you mind adding a test case for this scenario?

2022-09-21 04:21 UTC, huaxk commented on src/cdk/jsii-project.ts
> +    let prePublishSteps: Array<Step> = [
OK!

2022-09-21 09:38 UTC, mrgrain requested changes
This looks great now! Just these two minor comments and we are good to go. 😃

2022-09-21 09:38 UTC, mrgrain commented on test/cdk/jsii.test.ts
> +  // const build = yaml.parse(output[".github/workflows/build.yml"]);
Any reason this was left in?
```suggestion
```

2022-09-21 09:38 UTC, mrgrain commented on test/cdk/jsii.test.ts
> +  // const tasks = output[".projen/tasks.json"].tasks;
Any reason this was left in?
```suggestion
```

2022-09-22 08:52 UTC, mrgrain approved these changes
🥳  Thanks again for providing this fix!

2022-09-22 08:53 UTC, merged