fix: ignore overriden dependencies in renovate
projen/projen pull request #2127
Opened 2022-09-26 12:25 UTC by Hi-Fi

Fixes #2126 

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-26 13:11 UTC, mrgrain commented on src/javascript/node-package.ts
> +  }
This is a clever approach! You might find it easier to change to behaviour of `addPackageResolutions()` to match the one of `addDeps()`. I.e. store the resolutions in a class property and render as part of `renderDependencies()` and/or `resolveDepsAndWritePackageJson()` instead of using `this.file.addOverride()`

2022-09-26 13:35 UTC, Hi-Fi commented on src/javascript/node-package.ts
> +  }
Thank you, have to check if some other option would be good. That was first approach that came to mind with just (mostly) getters.

2022-09-26 16:59 UTC, Hi-Fi commented on src/javascript/node-package.ts
> +  }
Figured out a bit simpler solution, which can be later extended (if needed) to replace at least partly object-file.ts. Pushing it soon.

2022-09-27 10:45 UTC, mrgrain requested changes
@Hi-Fi This is great! Thanks for contributing and the good work.

I'm not sure what is going wrong, but somehow the overrides still ended up in the generated upgrade task for projen itself. Once that's resolved, we can merge.

2022-09-27 10:45 UTC, mrgrain commented on .projen/tasks.json
> +          "exec": "yarn upgrade @types/conventional-changelog-config-spec @types/fs-extra @types/glob @types/ini @types/jest @types/node @types/semver @types/yargs @typescript-eslint/eslint-plugin @t
@Hi-Fi Looks like we need to remove the overrides when generating the upgrade task. Do you agree?

2022-09-27 10:45 UTC, mrgrain commented on src/javascript/upgrade-dependencies.ts
> +              dep.type !== DependencyType.OVERRIDE
But here you are removing it. Something is off. 🤔

2022-09-27 10:48 UTC, Hi-Fi commented on src/javascript/upgrade-dependencies.ts
> +              dep.type !== DependencyType.OVERRIDE
I noticed that those came at first, but then after that ignore those were not changing snapshots anymore... maybe have to recheck later.

2022-09-27 10:51 UTC, Hi-Fi commented on .projen/tasks.json
> +          "exec": "yarn upgrade @types/conventional-changelog-config-spec @types/fs-extra @types/glob @types/ini @types/jest @types/node @types/semver @types/yargs @typescript-eslint/eslint-plugin @t
Hmm... this is probably some issue with versions, as deps get those new dependencies, but is it then so that tasks are generated with old code... Or then I need to rerun projen

2022-09-27 10:51 UTC, Hi-Fi commented on .projen/tasks.json
> +          "exec": "yarn upgrade @types/conventional-changelog-config-spec @types/fs-extra @types/glob @types/ini @types/jest @types/node @types/semver @types/yargs @typescript-eslint/eslint-plugin @t
Thank you for noticing, I just looked tests for these.

2022-09-27 10:54 UTC, Hi-Fi commented on .projen/tasks.json
> +          "exec": "yarn upgrade @types/conventional-changelog-config-spec @types/fs-extra @types/glob @types/ini @types/jest @types/node @types/semver @types/yargs @typescript-eslint/eslint-plugin @t
Ah, I missed that one, package manager update is not handled correctly (this is for ncu)

2022-09-27 11:09 UTC, Hi-Fi commented on src/javascript/upgrade-dependencies.ts
> +              dep.type !== DependencyType.OVERRIDE
That removal was for ncu, not for upgrade task of package manager.

2022-09-27 12:49 UTC, mrgrain approved these changes
🥳

2022-09-27 12:58 UTC, merged