feat(scoped-packages): Added logic to generate workflow permission for GitHub OIDC and scoped private packages
projen/projen pull request #2399
Opened 2023-01-31 05:04 UTC by AminFazlMondo

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-02-01 10:01 UTC, mrgrain requested changes
Thanks for this change, feels important!

I left a few comments/qustions inline.
Most importantly, can you also please add a description to the PR explaining the issue this is solving and how you are solving it. This helps me review things better and quicker, but also for future posterity.

2023-02-02 04:15 UTC, AminFazlMondo commented on src/release/release.ts
> +  readonly additionalPermissions?: JobPermissions;
I have renamed the file and class, hope it is more clear now

2023-02-02 04:16 UTC, AminFazlMondo commented on src/build/build-workflow.ts
> +  readonly additionalPermissions?: JobPermissions;
I thought that might be openning up this for errors in future and missing the minimum permissions that it requires. But happy to be guided by you

2023-02-03 11:17 UTC, mrgrain commented on src/build/build-workflow.ts
> +  readonly additionalPermissions?: JobPermissions;
Thanks for your input and I agree with you in principle. For this case, I reckon if we do it like I suggested it would be very hard to accidentally mess things up. One would have to explicitly set `contents: JobPermission.NONE` to achieve breaking the build and that's hardly something someone would do without purpose.

Let's go with `permissions` and my suggestion.

2023-02-03 11:21 UTC, mrgrain commented on src/release/release.ts
> +  readonly additionalPermissions?: JobPermissions;
Apologies for the confusion. We should _not_ rename the whole class and file. Please revert.

I meant the `additionalPermissions` option. With the other discussion in mind, it should be called `workflowPermissions`. Similar to `workflowNodeVersion` just above it.

2023-02-03 11:22 UTC, mrgrain requested changes
See inline comments.

2023-02-05 22:16 UTC, AminFazlMondo commented on src/build/build-workflow.ts
> +  readonly additionalPermissions?: JobPermissions;
Thanks @mrgrain ,
I have made the changes you asked, and in order to avoid any confusion, I aslo made the original behavior as the default value for the passed in option to keep the interface the same, and if someone wants to override they can too.
Please let me know what you think?

2023-02-06 11:37 UTC, mrgrain commented on src/build/build-workflow.ts
> +  readonly workflowPermissions?: JobPermissions;
This one should still be called `permissions` only the one in release needs to workflow prefix.

```suggestion
  readonly permissions?: JobPermissions;
```

2023-02-06 11:40 UTC, mrgrain commented on src/build/build-workflow.ts
> +   * @default `{contents: 'write'}`
```suggestion
   * @default `{ contents: JobPermission.WRITE }`
```

2023-02-06 11:43 UTC, mrgrain commented on src/build/build-workflow.ts
> +   * Permission that are required for the job
```suggestion
   * Permissions granted to the build job
   * To limit access to `contents`, the desired permissions have to be set explicitly: `{ contents: JobPermission.NONE }`
```

2023-02-06 11:46 UTC, mrgrain commented on test/javascript/node-project.test.ts
> +      expect(buildWorkflow.jobs.release.permissions).toEqual(
```suggestion
      const workflow = yaml.parse(output[".github/workflows/release.yml"]);
      expect(workflow.jobs.release.permissions).toEqual(
```

2023-02-06 11:47 UTC, mrgrain commented on src/release/release.ts
> +   * @default `{contents: 'write'}`
```suggestion
   * Permissions granted to the release workflow job
   * @default `{ contents: JobPermissions.WRITE }`
```

2023-02-06 11:48 UTC, mrgrain requested changes
Thanks @AminFazlMondo 
Got a few minor change requests. Getting close now!

2023-02-06 21:29 UTC, AminFazlMondo commented
Thanks @mrgrain ,

I have made these changes, could you please have a look again?

Cheers,

2023-02-07 10:05 UTC, mrgrain requested changes
Hey @AminFazlMondo Looks good now.

On my final review round I noticed `aws-region` is hardcoded to `us-east-2` (and `role-duration-seconds` is as well). Is that on purpose?

If yes please explain it to me (maybe even add a comment) and I can approve.
If not on purpose, let's fix this and make both a parameter.

2023-02-07 10:05 UTC, mrgrain commented on src/javascript/node-project.ts
> +            "role-duration-seconds": 900,
How can the region be hardcoded? Am I missing something here? 
I realize this is also hard coded a bit further down already.

(Same goes for `role-duration-seconds` but that's probably not the most pressing)

2023-02-07 10:29 UTC, AminFazlMondo commented on src/javascript/node-project.ts
> +            "role-duration-seconds": 900,
The decision back in #1688 was to reuse the `codeArtifactOptions` to figure out the role to assume and others. This class interface does not contain any information about the dwfault AWS region or session duration, so needed to either be hard coded or added to some entries, which I am not sure if `codeArtifactOptions` is the best place for it.
Also, as it is only using IAM to get token and following operations (such as `ca:loging`) will have region as part of the CLI commands. There is nothing that misses the region that would like to infer that from the envinonmnet variable, hence, it is not doing ny damage.
Having said that, if others are adding customised commands that need to infer the AWS region, this might be problematic.

2023-02-07 10:37 UTC, mrgrain commented on src/javascript/node-project.ts
> +            "role-duration-seconds": 900,
Thanks for the explanation! That's annoying but it's also not getting any worse. 👍🏻

2023-02-07 10:37 UTC, mrgrain approved these changes

2023-02-07 10:49 UTC, merged