feat(smithy-build): support maven section for vscode smithy plugin
projen/projen pull request #2412
Opened 2023-02-03 02:35 UTC by cogwirrel

The VSCode Smithy Plugin requires maven dependencies and repositories to be specified in the smithy-build.json file, so we add these as optional properties to synthesize.

https://github.com/awslabs/smithy-vscode/blob/main/README.md#authoring-a-model

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-02-03 11:14 UTC, mrgrain requested changes
Looks good. Got a small doc request.

2023-02-03 11:14 UTC, mrgrain commented on src/smithy/smithy-build.ts
> +  readonly maven?: SmithyMavenConfig;
This just needs an `@default` description and we are good to go.

2023-02-04 04:29 UTC, cogwirrel commented on src/smithy/smithy-build.ts
> +  readonly maven?: SmithyMavenConfig;
Thanks for the speedy review! :) Updated :)

2023-02-06 09:59 UTC, mrgrain approved these changes
🚀

2023-02-06 10:00 UTC, merged