fix(tasks): Handle non-string task env vars
projen/projen pull request #2489
Opened 2023-03-09 15:22 UTC by icj217

Project types that do not use .projenrs.ts cannot guard against end users providing numbers for environment variables. Casting them to strings before storing internally

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-09 15:54 UTC, mrgrain commented
I like this! Your implementation needs to be a bit more clever though in what values are accepted, see failing tests.

Also can we do an explicit check and emit a warning (via `this.project.logger.warn()`) if we encounter a conversion?

2023-03-09 20:44 UTC, icj217 commented
> I like this! Your implementation needs to be a bit more clever though in what values are accepted, see failing tests.
> 
> Also can we do an explicit check and emit a warning (via `this.project.logger.warn()`) if we encounter a conversion?

@mrgrain I've fixed the tests (had to exclude `undefined` from being stringified) and added the warning messages.

2023-03-10 10:03 UTC, mrgrain commented on src/task.ts
> +
Should we do the same warning in the constructor?

2023-03-10 10:10 UTC, mrgrain commented on src/task-runtime.ts
> +      if (String(value).startsWith("$(") && String(value).endsWith(")")) {
Nice!

2023-03-10 10:11 UTC, mrgrain requested changes
Looking good. One last bit is missing.

2023-03-10 14:26 UTC, icj217 commented on src/task.ts
> +
Good idea. I've added that private method

2023-03-10 15:16 UTC, mrgrain approved these changes

2023-03-11 00:47 UTC, merged