chore(node-package): Use tasks for installing dependencies
projen/projen pull request #2494
Opened 2023-03-10 15:26 UTC by icj217

Spawning a task allows end users to hook into the dependency installation process and increases flexibility

This aligns node and python projects on the same dependency installation API. For node projects, had to explicitly exclude the `install` and `install:ci` tasks from being included in `package.json` scripts to prevent infinite loops.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-10 18:43 UTC, icj217 commented
Was able to resolve all but 1 of the failing tests. For some reason, when synthesizing a `TypescriptProject`, the `TaskRuntime` component can't find the chalk package. I can't think of any reason for this that makes sense, given that the `TaskRuntime` for the project being created is using the project code and `chalk` is an installed dependency. Hoping someone else w/more familiarity with the codebase might be able to shed some light on this.

```
 FAIL  test/typescript/typescript.test.ts
  ● TypeScriptProject with default settings › compiles

    TypeError: chalk.underline is not a function

      113 |     if (envlogs.length) {
      114 |       this.logDebug(
    > 115 |         chalk.gray(`${chalk.underline("env")}: ${envlogs.join(" ")}`)
          |                             ^
      116 |       );
      117 |     }
      118 |

      at new RunTask (src/task-runtime.ts:115:29)
      at TaskRuntime.runTask (src/task-runtime.ts:76:5)
      at NodePackage.installDependencies (src/javascript/node-package.ts:1450:13)
      at NodePackage.postSynthesize (src/javascript/node-package.ts:863:12)
      at TypeScriptProject.synth (src/project.ts:572:14)
      at Object.<anonymous> (test/typescript/typescript.test.ts:23:13)
```

2023-03-12 22:21 UTC, mrgrain requested changes
I love this 😍 

Just a small request

2023-03-12 22:21 UTC, mrgrain commented on src/javascript/node-package.ts
> +    this.removeScript(this.installTask.name);
yes that's fine. I'd rather have them filtered out in `renderScripts` if you don't mind making that change

2023-03-12 22:21 UTC, mrgrain commented on src/javascript/node-package.ts
> +    this.removeScript(this.installCiTask.name);
See above

2023-03-12 22:21 UTC, mrgrain commented on src/task-runtime.ts
> +import { gray, underline } from "chalk";
I came across this elsewhere. I think I need to make a PR forcing this everywhere.

2023-03-13 12:36 UTC, icj217 commented on src/task-runtime.ts
> +import { gray, underline } from "chalk";
Glad to hear I'm not crazy :)

2023-03-13 12:38 UTC, mrgrain approved these changes

2023-03-13 13:00 UTC, merged