feat(docker-compose): Allows an entrypoint to be defined in a docker-…
projen/projen pull request #2506
Opened 2023-03-14 16:27 UTC by Tucker-Eric

…compose service and allows `command` and `entrpoint` to additionally be defined as support Docker's `shell` execution methods (https://docs.docker.com/engine/reference/builder/#entrypoint)

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-14 17:20 UTC, mrgrain requested changes
Just the issue with the union types.

2023-03-14 17:20 UTC, mrgrain commented on src/docker-compose/docker-compose-render.ts
> +  readonly command?: string | string[];
```suggestion
  readonly command?: string[];
```

We can't have union types due, they don't work in other languages.

2023-03-14 17:20 UTC, mrgrain commented on src/docker-compose/docker-compose-render.ts
> +  readonly entrypoint?: string | string[];
```suggestion
  readonly entrypoint?: string[];
```
We can't have union types due, they don't work in other languages.

2023-03-14 17:22 UTC, mrgrain commented
> and allows command and entrypoint to additionally be defined as support Docker's shell execution methods 

Not super sure what you mean by this 😅

2023-03-14 21:27 UTC, Tucker-Eric commented on src/docker-compose/docker-compose-render.ts
> +  readonly entrypoint?: string | string[];
Ahhh, this makes so much sense now!

2023-03-14 21:34 UTC, Tucker-Eric commented
> > and allows command and entrypoint to additionally be defined as support Docker's shell execution methods
> 
> Not super sure what you mean by this 😅

Ahh, was supposed to support a string command/entrypoint for: 

![image](https://user-images.githubusercontent.com/6483755/225142934-d9e9e995-67a5-4748-8fe0-f492fb674db3.png)

but without union types it's not possible to support both.

2023-03-15 10:04 UTC, mrgrain approved these changes

2023-03-15 10:29 UTC, mrgrain commented
@mergifyio update

2023-03-15 10:38 UTC, mrgrain commented
@Tucker-Eric Our automation doesn't like your setup. 

> Mergify needs the author permission to update the base branch of the pull request.
https://github.com/gavel-io needs to [authorize modification on its head branch](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
err-code: F6886

If you can't would you mind re-raising the PR with your personal account?

Alternatively, if you branch is up to date with `main` I can merge manually, but depending on traffic you might have to do this multiple times.

2023-03-15 15:07 UTC, merged