Add devcontainer features setting
projen/projen pull request #2559
Opened 2023-03-27 07:43 UTC by tHyt-lab

Thank you for letting us use such a great product.
I wanted to configure Features in the devcontainer settings of VSCode, but it is not supported. We are now able to support Features in this PR.
It would be great if you could incorporate it.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-27 11:24 UTC, mrgrain requested changes

2023-03-27 11:24 UTC, mrgrain commented on src/vscode/devcontainer.ts
> +}
This should just be an interface.
Also I assume the `featureName` is always required?
And since it is only for dev containers rename to `DevContainerFeature`
```suggestion
export interface DevContainerFeature {
  public readonly featureName: string;
  public readonly version?: string;
}
```

2023-03-27 11:24 UTC, mrgrain commented on test/vscode/devcontainer.test.ts
> +test("no devcontainer configured", () => {
Thanks for adding these tests! 🎉 🚀

2023-03-27 11:24 UTC, mrgrain commented on test/vscode/devcontainer.test.ts
> +  expect(synthSnapshot(project)).not.toHaveProperty(DEVCONTAINER_FILE);
```suggestion

  // THEN
  expect(project.devContainer).toBe(undefined);
  expect(synthSnapshot(project)).not.toHaveProperty(DEVCONTAINER_FILE);
```

2023-03-27 11:24 UTC, mrgrain commented on src/vscode/devcontainer.ts
> +  public readonly featureName?: string;
`featureName` feels very verbose. Either `name` or `feature` should be enough. What do you think?

2023-03-27 19:10 UTC, mrgrain requested changes
Thanks for the changes. Almost, there. Just some docs missing and a couple of opportunities to simplify code.

2023-03-27 19:10 UTC, mrgrain commented on src/vscode/devcontainer.ts
> +  readonly version?: string;
Can you add a description to each of these please?

And `@default` for the `version`. Sorry I missed this in the first round.

2023-03-27 19:10 UTC, mrgrain commented on src/vscode/devcontainer.ts
> +      if (feature.name) {
Now that `feature.name` is required, we can skip the if!

2023-03-27 19:10 UTC, mrgrain commented on src/vscode/devcontainer.ts
> +        });
I don't think wrapping this into yet another function is necessary.

2023-03-27 23:22 UTC, tHyt-lab commented
Thanks for confirming! It is very informative.
I will fix it after work.

2023-03-28 09:24 UTC, tHyt-lab commented on src/vscode/devcontainer.ts
> +  readonly version?: string;
Added description of DevContainerFeature.

2023-03-28 09:26 UTC, tHyt-lab commented on src/vscode/devcontainer.ts
> +        });
Changed from Function to Object.

2023-03-28 09:27 UTC, tHyt-lab commented
Thanks for checking with me again and again! I learned a lot.
Please check back with me now that the corrections are complete.

2023-03-28 10:34 UTC, mrgrain approved these changes

2023-03-28 11:04 UTC, merged