feat: add generic type parameter to `Component` class
projen/projen pull request #2565
Opened 2023-03-28 17:00 UTC by jacklesliewise

If we allow `Component` to take a generic type parameter that extends `Project`, it means we can let a given `Component` access properties and methods that exist on a specific `Project` type.

For example, if we know that a `Component` is specifically for a `NodeProject`, we can pass `Component<NodeProject>` so that we can access `this.project.renderWorkflowSetup`.

Currently, if we want to do this we need to create a new custom `this._project` property with the extended project type. When we add this generic type parameter, we can simply access `this.project` instead.

Since we can just default to `Project` this will not be a breaking change.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-28 19:12 UTC, mrgrain commented
Heads up, while I like the I need to check what that means for jsii languages.

Best scenario is the generic will just be used for TS and jsii languages have the untyped version.
Worst scenario is that it breaks the generated types and we just can't do it.

2023-03-28 19:12 UTC, mrgrain requested changes
"Request changes" until I now the above.

2023-03-29 10:05 UTC, mrgrain commented
Okay I checked. Unfortunately jsii doesn't support Generics right now. It probably should have failed to compile the code here, but doesn't. 

I know this is a common nuisance, but the work around isn't too bad.

2023-03-29 10:05 UTC, closed without merging

2023-03-29 10:10 UTC, jacklesliewise commented
Ah that's a shame, no worries thanks for looking into it @mrgrain 👍