fix(jest): cannot set `preset` and `globals` config when using in a typescript project
projen/projen pull request #2567
Opened 2023-03-29 10:04 UTC by riywo

Some of `jestConfig` properties are not able to update through constructor
because of a bug by assigning hard coded default values.

This commit fixes the bug to assign hard coded values only if the same
properties are not set.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-29 22:38 UTC, mrgrain commented on src/typescript/typescript.ts
> +      };
The if statement and the assignment don't really match up. I reckon we should deep merge the object

2023-03-29 22:39 UTC, mrgrain requested changes
thanks for the fix. Your PR needs to include the license statement footer from the PR template (or see other PRs ).

2023-03-29 22:42 UTC, riywo commented
@mrgrain Ah, sorry! I created this PR by `gh pr create --fill` so that the PR template wasn't used. Updated the description by the footer.

2023-03-29 22:46 UTC, mrgrain commented
No worries! Really should have some automation for that. Although I'm surprised `gh pr` doesn't honor the template 🤔

2023-03-29 23:03 UTC, riywo commented on src/typescript/typescript.ts
> +      };
Ah, right. This breaks if there are some other options on `jest.config.globals`. Let me fix it.

Do we already have some deep merge libraries or functions in this project?

2023-03-31 12:03 UTC, mrgrain commented on src/typescript/typescript.ts
> +      };
There's a `deepMerge` in `util.ts`. I guess it works. 😅

2023-04-05 12:37 UTC, mrgrain commented on src/typescript/typescript.ts
> +      };
@riywo I'd love to see this fix merged. Is there anything else you need from me?

2023-04-05 16:08 UTC, riywo commented on src/typescript/typescript.ts
> +      };
Just done (including rebase). Check this change: https://github.com/projen/projen/compare/ff3a1fd619d1035cb8a170cb32e71903a7e5a554..8b6d45d1bd8a42b97f04ee42489356b7124c8a51

2023-04-05 16:11 UTC, riywo commented
@mrgrain I addressed your comment. Check this diff as well https://github.com/projen/projen/compare/ff3a1fd619d1035cb8a170cb32e71903a7e5a554..8b6d45d1bd8a42b97f04ee42489356b7124c8a51

2023-04-06 08:18 UTC, mrgrain approved these changes

2023-04-06 08:35 UTC, merged

2023-04-06 08:53 UTC, riywo commented
Thank you!