feat(typescript): add `disableTsconfigDev` property to not generate the `tsconfig.dev.json`
projen/projen pull request #2569
Opened 2023-03-30 08:39 UTC by gmukul01

Allows us to not generate the `tsconfig.dev.json` file and use the `tsconfig.json` for all the tasks.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-31 10:53 UTC, mrgrain requested changes
Great idea! Will need some test cases and questions answered.

Should we make sure that either tsconfig or tsconfigDev is available?
What happens with .projenrc.ts task when the dev config is gone?

PS: You can already do this by doing `disableTsConfig` and changing the name of the dev config. But that's a bad API.

2023-03-31 10:53 UTC, mrgrain commented on src/typescript/typescript.ts
> +    } else {
So we are disabling it, but then we are saying it is tsconfig?! I'm confused.

2023-03-31 12:53 UTC, gmukul01 commented
Should we make sure that either tsconfig or tsconfigDev is available? 
Answer: Yes I have make sure about this and even if you have passed both `disableTsconfigDev` and `disableTsconfig`  then it will definitely create the `tsconfig.dev.json`.

What happens with .projenrc.ts task when the dev config is gone?
Answer: Since I am assigning the default `tsconfig.json` to the `this.tsconfigDev`, all the tasks will consider the `tsconfig.json` for all the typescript commands.

2023-03-31 15:56 UTC, gmukul01 commented
@mrgrain Added the test cases also. :)

2023-04-01 17:40 UTC, mrgrain requested changes
Nice  once @gmukul01 and thanks for the test cases. I've added a couple small improvement suggestions to them.

Re `disableTsconfigDev` AND `disableTsconfig`. I think we should at least log a warning if both are disabled. But wondering if we should simply prohibit that and throw an error instead. That makes it at least explicit. What do you think? I'll have a look how we do handle this in similar situations.

Either way, the docstrings will need to mention that as well.

Edit: I had a look. We should simply throw an error in  this case. It's what we do elsewhere.
Example `throw new Error("Cannot specify both 'contents' and 'source' fields.");`

2023-04-01 17:40 UTC, mrgrain commented on test/typescript/typescript.test.ts
> +    expect(prj.tsconfigDev.fileName).toBe("tsconfig.dev.json");
```suggestion
    expect(prj.tsconfigDev.fileName).toBe("tsconfig.dev.json");
    expect(snapshot["tsconfig.dev.json"]).not.toBeUndefined();
```

2023-04-01 17:40 UTC, mrgrain commented on test/typescript/typescript.test.ts
> +    expect(prj.tsconfigDev.fileName).toBe("tsconfig.dev.json");
```suggestion
    expect(prj.tsconfigDev.fileName).toBe("tsconfig.dev.json");
    expect(snapshot["tsconfig.json"]).not.toBeUndefined();
    expect(snapshot["tsconfig.dev.json"]).not.toBeUndefined();
```

2023-04-03 08:14 UTC, gmukul01 commented on test/typescript/typescript.test.ts
> +    expect(prj.tsconfigDev.fileName).toBe("tsconfig.dev.json");
Done

2023-04-03 08:38 UTC, mrgrain requested changes
Good to go. :shipit: 🚀

2023-04-03 08:51 UTC, merged