chore: adds Badges for LICENSE and workflows Build and Release
projen/projen pull request #260
Opened 2020-11-01 18:32 UTC by pgollucci

2020-11-01 19:22 UTC, eladb commented on README.md
> -
Let's also leave this please

2020-11-02 06:21 UTC, eladb requested changes

2020-11-02 06:21 UTC, eladb commented on README.md
> +## Badges
Do we really need this heading?

2020-11-03 15:06 UTC, pgollucci commented on README.md
> +## Badges
I have no opinion. Removing it.

2020-11-03 17:22 UTC, eladb approved these changes

2020-11-03 17:26 UTC, merged