TypeScript TSConfig 5.0+ parameters, support for TSConfig extends.
projen/projen pull request #2607
Opened 2023-04-13 09:38 UTC by BradenM

This PR brings in the new parameters offered in typescript 5.0 (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html)
and implements support for the `extends` field.

The logic for the `extends` maintains backwards compatibility for:

- Existing projects by not writing it if undefined / empty.
- Typescript <5.0 by writing a single relative path if/when only a singular extension is added.

While also allowing for the newly introduced support for multiple bases via an array.

1.  Support for the `bundler` module resolution strategy, which mimics the resolution patterns of modern bundlers.
2.  Addition of new TypeScript 5.0 configuration options and handling of deprecated options:
    - `allowImportingTsExtensions`: Allows TypeScript files to import each other with TypeScript-specific extensions (`.ts`, `.mts`, `.tsx`).
    - `allowArbitraryExtensions`: Suppresses arbitrary extension import errors with the assumption that a bundler will handle them.
    - `customConditions`: Specifies a list of additional conditions that should succeed when TypeScript resolves from an `exports` or `imports` field of a `package.json`.
    - `verbatimModuleSyntax`: Simplifies TypeScript's handling of import/export `type` modifiers.
    - `resolvePackageJsonExports`: Forces TypeScript to consult the `exports` field of `package.json` files if it ever reads from a package in `node_modules`.
    - `resolvePackageJsonImports`: Forces TypeScript to consult the `imports` field of `package.json` when performing a lookup that begins with `#` from a file that has a `package.json` as an ancestor.
3.  Implementation of the `extends` field in TypeScript configurations, allowing configurations to inherit settings from other configurations using a string, a list of strings, or `TypescriptConfig` instances.
4.  Unit tests to verify the extends functionality.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-14 17:18 UTC, mrgrain requested changes
Nice one, thank you!

Just a small change required with regards to the union type.

2023-04-14 17:18 UTC, mrgrain commented on src/javascript/typescript-config.ts
> +  readonly extends?: string | string[] | TypescriptConfig | TypescriptConfig[];
Unfortunately union types aren't great in other jsii languages, so we avoid them.

Instead we need a class with a bunch of static methods:

`fromPaths(paths: string[])`
`fromTypescriptConfigs(configs: TypescriptConfig[])`

Give it  a private constructor and a public `toJSON()` method to render.

2023-04-14 17:18 UTC, mrgrain commented on src/javascript/typescript-config.ts
> +  public addExtends(value: string | TypescriptConfig) {
```suggestion
  public addExtends(value: string | TypescriptConfig) {
```
Same as above re union type.

2023-04-14 22:22 UTC, BradenM commented on src/javascript/typescript-config.ts
> +  readonly extends?: string | string[] | TypescriptConfig | TypescriptConfig[];
> Unfortunately union types aren't great in other jsii languages, so we avoid them.
Ah, interesting. Can definitely where that could get complicated quickly. Good to know, thanks.

Have added a `TypescriptConfigExtends` to handle this :+1:

2023-04-14 22:36 UTC, mrgrain commented
FYI. The build failure is unrelated. Working on a fix, but might take some days as I'm on leave.

2023-04-14 22:41 UTC, BradenM commented
@mrgrain Was just about to comment asking if that indeed the case. :+1:

No rush -- please do enjoy your leave :smile:

2023-04-17 10:11 UTC, mrgrain requested changes
This looks good now, just a couple of docstrings that need clarifications.

Also, what do you think in regards of having separate `TypescriptConfigExtends` helpers for TS4.x and TS5.x?

2023-04-17 10:11 UTC, mrgrain commented on src/javascript/typescript-config.ts
> + * Extending from more than one base config file requires TypeScript 5.0+.
Now that I think about it more, should we keep additional helper methods `fromPath()` and `fromTypescriptConfig()` that only take a single item. That way we could clearly mark them as TS4.X only.

2023-04-17 10:11 UTC, mrgrain commented on src/javascript/typescript-config.ts
> +   * Factory for creation from array of file paths.
Depending on my other comment re TS4.x, this needs some explanation on what is allowed for which TS version.

2023-04-17 10:11 UTC, mrgrain commented on src/javascript/typescript-config.ts
> +   * Factory for creation from array of other `TypescriptConfig` instances.
Depending on my other comment re TS4.x, this needs some explanation on what is allowed for which TS version.

2023-04-17 10:11 UTC, mrgrain commented on src/javascript/typescript-config.ts
> +   * @deprecated For TypeScript 5.0+ use `verbatimModuleSyntax` instead.
Let's turn this into a regular docstring remark that explains the situation. TS4.x is still a very valid choice at the moment and this might confuse people.

2023-04-17 10:27 UTC, BradenM commented on src/javascript/typescript-config.ts
> +   * @deprecated For TypeScript 5.0+ use `verbatimModuleSyntax` instead.
The reason I went with `deprecated` originally was due to the language being used in the typescript docs (see: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#deprecations-and-default-changes)

That said, I do see where you are coming from and find myself agreeing :+1: 
Will update to provide more info.

2023-04-17 10:32 UTC, mrgrain commented on src/javascript/typescript-config.ts
> +   * @deprecated For TypeScript 5.0+ use `verbatimModuleSyntax` instead.
Yes, it's tricky because ideally we would have a different interface per TS version but that's not very maintainable.
Also TS apparently never deprecates old versions, like you've correctly pointed out they have deprecated the use of certain flags with certain versions. I'm not sure what the best solution is here. Maybe `@deprecated` once TS5.5 is released.

2023-04-17 10:39 UTC, BradenM commented on src/javascript/typescript-config.ts
> + * Extending from more than one base config file requires TypeScript 5.0+.
This and related did cross my mind, but I wasn't too sure how 'strict' to be here or the level of introspection that should occur (i.e, looking through dependencies to validate the params against a specified typescript version and/or finding an installed version.)

If such introspection is already exposed somewhere / something you would consider, then I think throwing an error/warning when trying to use multiple extends on sub 5.0 would be a bit cleaner for the 'end user' than the possible confusion of the singular/plural methods.

Bit on the fence on that one though...

2023-04-17 10:45 UTC, BradenM commented on src/javascript/typescript-config.ts
> +   * @deprecated For TypeScript 5.0+ use `verbatimModuleSyntax` instead.
> Maybe @deprecated once TS5.5 is released.
Agreed. This makes the most sense.

2023-04-17 12:03 UTC, mrgrain commented on src/javascript/typescript-config.ts
> + * Extending from more than one base config file requires TypeScript 5.0+.
We do introspection in some places, but I'm not aware of that being setup for TypeScript yet. I agree it would be better, but likely has its own implications/challenges (the main one being that its possible to not specify and explicit version in code).

Alternatively we could play around with having a separate class, e.g. `TypescriptConfigV4Extend` to make it easier for users. But again this will have it's challenges to make jsii happy and avoid union types.

2023-04-20 10:45 UTC, BradenM commented on src/javascript/typescript-config.ts
> +  }
@mrgrain
What do you think about this non-strict validation instead of the extra methods and/or classes?

One alternative consideration I had here was throwing this message as an error and adding a `disableValidation` field to the config, but I felt that this would get the point across well enough without having to add more config.

2023-04-20 10:49 UTC, BradenM commented
@mrgrain The API docs need to be updated after [`aeb83f7` (#2607)](https://github.com/projen/projen/pull/2607/commits/aeb83f73ad107804826c5fefdf303ebca370cf30)

But I had just rebased before that commit, and now they don't seem to want to generate anymore... did something break with docgen recently?

2023-04-20 12:22 UTC, mrgrain commented on src/javascript/typescript-config.ts
> +        "TypeScript >= 5.0.0 is required to extends from more than one base config.",
The error sounds like it's the wrong way around:
```suggestion
        "TypeScript < 5.0.0 is can only extend from a single base config.",
```

2023-04-20 12:26 UTC, mrgrain commented
> I had just rebased before making that commit, and now they don't seem to want to generate anymore (had no issues in the commit right prior to the rebase)... did something break with docgen recently?

I'm not aware of anything, but that doesn't mean much.

2023-04-22 08:31 UTC, BradenM commented on src/javascript/typescript-config.ts
> +  }
I have added a fallback to this logic to look for a project local `tsc` executable and retrieve the current version from `tsc --version` output.

2023-04-24 15:42 UTC, mrgrain commented on src/javascript/typescript-config.ts
> +    const localTsc =
Instead of executing tsc, let's copy the mechanism from node-package
https://github.com/projen/projen/blob/3c28310404f113ff71ccfc5e52e6267f10c716e6/src/javascript/node-package.ts#L1278

2023-04-26 07:51 UTC, BradenM commented on src/javascript/typescript-config.ts
> +    const localTsc =
:man_facepalming: 
Honestly, not sure where my head was when I decided to jump right to parsing tsc output…
Thanks for pointing out what should have been obvious from the start haha :smile:

Will push changes shortly.

2023-04-26 09:32 UTC, mrgrain commented on src/javascript/typescript-config.ts
> +    const localTsc =
It was a good idea!

2023-04-26 09:33 UTC, mrgrain commented on src/javascript/typescript-config.ts
> +    const localTsc =
Tbh, we probably should have a generic method for getting the actual version of a dependency.

2023-04-27 06:31 UTC, BradenM commented on src/javascript/typescript-config.ts
> +    const localTsc =
@mrgrain I was thinking the same thing while updating this.
Decided to split it out into a separate PR:
https://github.com/projen/projen/pull/2634

If #2634 looks good to you, then I will update this PR to utilize the new methods.

2023-04-27 23:23 UTC, BradenM commented
Blocked by #2634
Will need to be rebased and updated (ref: https://github.com/projen/projen/pull/2607#discussion_r1178682242) one #2634 is merged.

2023-04-28 10:06 UTC, mrgrain requested changes

2023-04-28 10:06 UTC, mrgrain commented on src/javascript/typescript-config.ts
> +            : undefined,
One last request: Turn this into a private helper method `renderExtends()`
```suggestion
        extends: () => this.renderExtends(),
```

2023-04-28 10:07 UTC, BradenM commented on src/javascript/typescript-config.ts
> +            : undefined,
:+1: I wasn't the biggest fan of the nested ternary anyways :smile:

2023-04-28 10:08 UTC, mrgrain commented on src/javascript/typescript-config.ts
> +            : undefined,
Yes it's not... great. 😅

2023-04-28 10:18 UTC, mrgrain approved these changes

2023-04-28 10:31 UTC, merged