feat(javascript): Generic `tryResolveDependencyVersion` node-package method.
projen/projen pull request #2634
Opened 2023-04-27 06:28 UTC by BradenM

- feat(javascript): `tryResolveDependencyVersion` utility function.
- feat(javascript): `tryResolveDependencyVersion` node-package method.
- feat(javascript): utilize `tryResolveDependencyVersion` in `resolveDepsAndWritePackageJson`
- chore(docs): update generated api docs.
- test(javascript): add unit test for `tryResolveDependencyVersion`

Ref: https://github.com/projen/projen/pull/2607#discussion_r1177611408

Defines:

- Generic `tryResolveDependencyVersion` javascript/util utility for locating and reading a package version from a given dependencies package.json manifest.
- A public method `NodePackage.tryResolveDependencyVersion` that checks for a semantically valid (i.e, not '\*') dependency version via `project.deps`. If not found it will fallback on the `tryResolveDependencyVersion` utility from above.

Also refactors `NodePackage.resolveDepsAndWritePackageJson` to utilize `tryResolveDependencyVersion` (should have no change in behavior in theory).

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-27 07:57 UTC, mrgrain commented on src/javascript/node-package.ts
> +  public tryResolveDependencyVersion(dependencyName: string) {
```suggestion
  public tryResolveDependencyVersion(dependencyName: string): string {
```

2023-04-27 07:58 UTC, mrgrain commented on src/javascript/node-package.ts
> +    } catch (e) {}
```suggestion
    } catch {}
```

2023-04-27 07:59 UTC, mrgrain commented on src/javascript/node-package.ts
> +      if (version) return version.format();
I should really fix the eslint rule for that 🙈 
```suggestion
      if (version) {
        return version.format();
      }
```

2023-04-27 08:28 UTC, mrgrain requested changes

2023-04-27 08:28 UTC, mrgrain commented on src/javascript/node-package.ts
> +          const resolvedVersion = this.tryResolveDependencyVersion(name);
Let's use the one from utils here. Given that we already know projen doesn't know the version...
```suggestion
          const resolvedVersion = tryResolveDependencyVersion(name);
```

2023-04-27 09:03 UTC, BradenM commented on src/javascript/node-package.ts
> +  public tryResolveDependencyVersion(dependencyName: string) {
Strictly speaking, this should be `string | undefined`, not `string`.
On that note, I actually didn't type it purposely due to a bit of confusion on my part with how jsii handles union types (which you mentioned it had issues with earlier.).

Is that limitation specific to more complex unions such as what I had originally in #2607?

2023-04-27 09:06 UTC, BradenM commented on src/javascript/node-package.ts
> +      if (version) return version.format();
Not a fan? :smile: 
Personally, I find it a bit cleaner, but I can definitely see where others may not feel the same way.

2023-04-27 09:07 UTC, BradenM commented on src/javascript/node-package.ts
> +          const resolvedVersion = this.tryResolveDependencyVersion(name);
Makes sense :+1:

2023-04-27 09:13 UTC, BradenM commented on src/javascript/node-package.ts
> +  public tryResolveDependencyVersion(dependencyName: string) {
Sorry, got ahead of myself re-requesting a review.
Still pending on what the correct solution to this one is. Thanks.

2023-04-27 11:13 UTC, mrgrain commented on src/javascript/node-package.ts
> +  public tryResolveDependencyVersion(dependencyName: string) {
Gotcha. My ask is basically to explicitly add the expected return type, instead of implicitly relying on it.
If it's `string | undefined` than that's fine.

---

The jsii union types issue is mostly about user supplied types. Return types with undefined are fine.
See e.g. https://github.com/projen/projen/blob/b729a93146dc2a3f2a27a2ec67b48f8b24354964/src/tasks.ts#L114

2023-04-27 21:01 UTC, BradenM commented on src/javascript/node-package.ts
> +  public tryResolveDependencyVersion(dependencyName: string) {
Thanks for the clarification :+1: 
Have added the return type.

2023-04-27 21:38 UTC, BradenM commented
@mrgrain The changes from https://github.com/projen/projen/pull/2634#discussion_r1178772369 caused the test failures. Just needed to respecify the project outdir as a resolution path since we are using the util directly at that point. Should be all good now. :+1:

2023-04-28 08:22 UTC, mrgrain approved these changes
🚀

2023-04-28 09:37 UTC, BradenM commented
@mrgrain Not sure what went wrong with `post-build-integ` job...
```
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/feat/node-resolve-dependency*:refs/remotes/origin/feat/node-resolve-dependency* +refs/tags/feat/node-resolve-dependency*:refs/tags/feat/node-resolve-dependency*
  Error: fatal: unable to access 'https://github.com/BradenM/projen/': The requested URL returned error: 429
  The process '/usr/bin/git' failed with exit code 128
  Waiting 14 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/feat/node-resolve-dependency*:refs/remotes/origin/feat/node-resolve-dependency* +refs/tags/feat/node-resolve-dependency*:refs/tags/feat/node-resolve-dependency*
  Error: fatal: unable to access 'https://github.com/BradenM/projen/': The requested URL returned error: 429
  The process '/usr/bin/git' failed with exit code 128
  Waiting 13 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/feat/node-resolve-dependency*:refs/remotes/origin/feat/node-resolve-dependency* +refs/tags/feat/node-resolve-dependency*:refs/tags/feat/node-resolve-dependency*
  Error: fatal: unable to access 'https://github.com/BradenM/projen/': The requested URL returned error: 429
  Error: The process '/usr/bin/git' failed with exit code 128
```

429 sounds like rate limiting... maybe just needs a re-run?

2023-04-28 09:41 UTC, merged