fix(typescript): ts-jest-globals-deprecation
projen/projen pull request #2636
Opened 2023-04-27 22:30 UTC by wenindoubt

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-28 08:30 UTC, mrgrain requested changes

2023-04-28 08:34 UTC, mrgrain approved these changes

2023-04-28 08:34 UTC, mrgrain commented on src/typescript/typescript.ts
> +    if (semver.gte(tsJestPackageJson.version, "29.0.0")) {
Note the new helper might return undefined (it really shouldn't but hey). In that case we can swap the defaults around: If we have a version and it's lower than 29.0.0 we use the old globals, otherwise we use the new one.

2023-05-01 22:05 UTC, wenindoubt commented on test/typescript/typescript.test.ts
> +    }
Do you have ideas on how I could test for both versions?

Given the current implementation that I just pushed up, we would have to inject the `ts-jest` version [here](https://github.com/projen/projen/blob/main/src/typescript/typescript.ts#LL336C3-L336C3) so that it can be unit tested properly.

Is that what you had in mind?

2023-05-02 09:40 UTC, mrgrain requested changes

2023-05-02 09:40 UTC, mrgrain commented on src/typescript/typescript.ts
> +    }
That's a bit of a harsh reaction. I'd say we default to assuming a version >=29

2023-05-02 09:40 UTC, mrgrain commented on src/typescript/typescript.ts
> +        }),
Apologies for not being clear on my request here. We have to deepMerge with `jest.config.transform` so that users can provide their own transforms via the options.

2023-05-02 09:40 UTC, mrgrain commented on test/typescript/typescript.test.ts
> +    }
`jestOptions.jestVersion` should do it.

Have a test for `28`, `29` and one for the default without anything.

2023-05-02 22:11 UTC, wenindoubt commented on test/typescript/typescript.test.ts
> +    }
`jestOptions.jestVersion` is actually undefined in `TypeScriptProject`.

I was looking around the codebase and it looks like `JsiiProject` has `jestOptions.jestVersion` defined (`@^27`) because it actually has that property being set [here](https://github.com/projen/projen/blob/main/src/cdk/jsii-project.ts#L202).

2023-05-03 09:26 UTC, mrgrain commented on test/typescript/typescript.test.ts
> +    }
I meant in the test:

```ts
    const prj = new TypeScriptProject({
      defaultReleaseBranch: "main",
      name: "test",
      jestOptions: {
        jestVersion: "^27", // and one that's the same but with `^29`
        jestConfig: {
          globals: {
            "ts-jest": {
              shouldBePreserved: true,
            },
          },
        },
      },
    });
```

This will give you 3 test cases in total:
- The existing default one, with the expectation updated
- A new one for `jest@^27`, with the old expectations
- A new one for `jest@^29`, which will be the same as the default

2023-05-03 20:35 UTC, wenindoubt commented
@mrgrain Thank you for your guidance here. I've made additional changes per your comments. Please let me know if there's anything else you'd like me to consider changing.

2023-05-04 09:01 UTC, mrgrain commented on test/typescript/typescript.test.ts
> +  });
You are explicitly setting the config and then testing it's there. That's not checking our new code at all!
```suggestion
  test("uses transforms for ts-jest >= 29", () => {
    const prj = new TypeScriptProject({
      defaultReleaseBranch: "main",
      name: "test",
      jestOptions: {
        jestVersion: "^29",
      },
    });
    
    const expectedTransformConfig = {
      "^.+\\.(ts|tsx)$": [
        "ts-jest",
        {
          tsconfig: "tsconfig.dev.json",
        },
      ],
    };
    
    const snapshot = synthSnapshot(prj);
    const jest = snapshot["package.json"].jest;
    expect(jest.preset).toStrictEqual("ts-jest");
    expect(jest.transform).toStrictEqual(expectedTransformConfig);
  });
```

Same applied to the other tests

2023-05-05 16:18 UTC, wenindoubt commented on test/typescript/typescript.test.ts
> +  test("uses default values and jestVersion < 29", () => {
@mrgrain - I was having difficulty conveying this earlier on, but what happens if I do _not_ explicitly specify the configs in the tests, it will look inside of my actual `node_modules/ts-jest/package.json` and pick out that version.

For example, if `ts-jest` is `27.1.0`, then the default test and `ts-jest >=29` test will fail because it expects the new transform configuration.

```
{
  "name": "ts-jest",
  "version": "27.1.0",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
```

On the other hand, if `ts-jest` is `29.1.0`, then the `ts-jest < 29` test will fail.

```
{
  "name": "ts-jest",
  "version": "29.1.0",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
```

So the issue I'm running into is that it is looking inside of my actual `node_modules/ts-jest/package.json`

2023-05-09 08:24 UTC, mrgrain commented on src/typescript/typescript.ts
> +    const tsJestVersion = tryResolveDependencyVersion("ts-jest");
There's a public API version of this on the Node project/package. Can we use that instead of the util helper.

2023-10-08 16:14 UTC, diranged commented
Is this ever going to get pushed over the line?

2023-10-09 08:31 UTC, mrgrain commented
> Is this ever going to get pushed over the line?

Nope. It seems like it didn't actually work. Would love for someone to pick this up an bring over the line though.
Although it's worth noting that nothing has broken yet. It's still just a deprecation warning in `ts-jest` as of now.

2023-12-26 19:11 UTC, dkershner6 commented
> > Is this ever going to get pushed over the line?
> 
> Nope. It seems like it didn't actually work. Would love for someone to pick this up an bring over the line though. Although it's worth noting that nothing has broken yet. It's still just a deprecation warning in `ts-jest` as of now.

Picked up, line crossed (I think): https://github.com/projen/projen/pull/3201

2024-01-05 12:03 UTC, mrgrain commented
Resolved in https://github.com/projen/projen/pull/3201

2024-01-05 12:03 UTC, closed without merging