chore(licenses): adds some common licenses based on FreeBSD ports
projen/projen pull request #264
Opened 2020-11-01 22:56 UTC by pgollucci

2020-11-01 22:57 UTC, pgollucci commented
or - https://github.com/projen/projen/issues/122

2020-11-03 18:45 UTC, eladb requested changes
I tend to agree that perhaps it makes more sense to only include the common licenses and fall back to downloading the file if needed.

2020-11-05 14:36 UTC, eladb approved these changes

2020-11-05 14:46 UTC, merged

2020-11-05 14:47 UTC, pgollucci commented
?