fix(sample-file): allowing empty dirs
projen/projen pull request #2656
Opened 2023-05-05 18:21 UTC by andersonmgomes

fixes #1990 
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-05-05 20:52 UTC, andrestone commented on test/sample-file.test.ts
> +  expect(snapshot).toBeDefined();
Shouldn't we test if whether or not the directory is created?

2023-05-06 09:19 UTC, mrgrain requested changes

2023-05-07 15:42 UTC, andersonmgomes commented
@andrestone and @mrgrain ,
Absolutely yes! 
I fixed the test case and am now checking if the empty dir was created correctly.
Thank you for your review, and sorry about my fault in the first commit!

2023-05-07 15:57 UTC, mrgrain requested changes
No worries. One final adjustment is needed.

2023-05-07 15:57 UTC, mrgrain commented on test/sample-file.test.ts
> +  fs.rmSync(project.outdir, { force: true, recursive: true });
Thanks for cleaning up afterwards! 

Instead of doing this manually, let's use the existing helper instead. It does automatically cleanup.

https://github.com/projen/projen/blob/main/test/util.ts#L59

2023-05-07 16:04 UTC, mrgrain commented on test/sample-file.test.ts
> +  fs.rmSync(project.outdir, { force: true, recursive: true });
Or I think you can also keep using `synthSnapshot` and check if the directory exists. That helper also cleans up after itself.

2023-05-07 16:12 UTC, andersonmgomes commented on test/sample-file.test.ts
> +  fs.rmSync(project.outdir, { force: true, recursive: true });
mrgrain, I've tried to use synthSnapshot. The problem was checking if the "fooPath" existed before the cleaner did its job. On another side, if I do not call the synth method for the project, nothing happens, and any dir is created.
Can I change only line 47 to call the helper?

2023-05-08 08:47 UTC, mrgrain commented on test/sample-file.test.ts
> +  fs.rmSync(project.outdir, { force: true, recursive: true });
I see. In that case the `mkdtmp` helper should do it. It will cleanup after the test has run.

You'll need to create the directory first and pass it to the project as `outdir`. Then remove the manual cleanup. That should do it.

2023-05-09 08:30 UTC, merged