Feat/add codecoverage workflow
projen/projen pull request #266
Opened 2020-11-02 02:20 UTC by kcwinner

Fixes # n/a

Description
* Adds an option for enabling a codecoverage build step.

2020-11-02 16:18 UTC, eladb requested changes

2020-11-02 16:18 UTC, eladb commented on src/node-project.ts
> +  public get workflowCodecoverageSteps(): any[] {
Do we really need this API? Feels unneeded.

2020-11-02 16:18 UTC, eladb commented on src/node-project.ts
> +        name: 'Upload coverage to Codecov',
There's some implicit coupling between where coverage output goes and where this action picks this up from. Ideally the `Jest` component should expose the output location for code coverage and this code should read it from there?

2020-11-02 18:07 UTC, kcwinner commented on src/node-project.ts
> +  public get workflowCodecoverageSteps(): any[] {
Probably not? I only added it for consistency:
```
public get workflowBootstrapSteps() {
```
```
public get workflowAntitamperSteps(): any[] {
```

2020-11-02 18:30 UTC, kcwinner commented on src/node-project.ts
> +        name: 'Upload coverage to Codecov',
Currently the jest configuration is only setup for projects that extend typescript and coverage directory is not a parameter.

Should we:
A. Add Jest component to `node-project` instead of `typescript`
B. Move this to `typescript` workflow
C. Make the steps options in `.projectrc.js` instead - then it's user defined
  * E.g. `...this.postBuildSteps ?? []`
D. Assume defaults

Jest [coverageDirectory](https://jestjs.io/docs/en/configuration#coveragedirectory-string) option

2020-11-02 18:47 UTC, eladb commented on src/node-project.ts
> +        name: 'Upload coverage to Codecov',
I am comfortable moving `Jest` to `NodeProject` and exposing `coverageDirectory` from `NodeProject`

2020-11-02 18:49 UTC, kcwinner commented on src/node-project.ts
> +        name: 'Upload coverage to Codecov',
Sounds good! It'll take me a bit longer so hopefully can finish up in the next few days then

2020-11-02 20:54 UTC, eladb commented
No worries. Thanks!

2020-11-03 00:12 UTC, kcwinner commented on src/next.ts
> +      jest: false,
Needed because now `node-project` creates the jest config instead of `typescript`

2020-11-03 00:12 UTC, kcwinner commented on src/react.ts
> +      jest: false,
Needed because now `node-project` creates the jest config instead of `typescript`

2020-11-03 00:13 UTC, kcwinner commented on src/node-project.ts
> +  readonly buildWorkflowCodeCoverage?: boolean;
Still not sold on this name. Should it just be `codeCov`? Similar to `antitamper`?

2020-11-03 01:54 UTC, kcwinner commented on .npmignore
> +/test
Changed because of jest being moved to node-project

2020-11-03 01:54 UTC, kcwinner commented on .gitignore
> +/coverage
Changed because of jest being moved to node-project

2020-11-03 01:54 UTC, kcwinner commented on package.json
> +    "test": "jest --passWithNoTests --updateSnapshot && yarn run eslint",
Changed because of jest being moved to node-project

2020-11-03 03:28 UTC, kcwinner commented
Should be good for review. Had to change a few things because of antitamper with the new order of jest running

2020-11-03 18:57 UTC, eladb requested changes

2020-11-03 18:57 UTC, eladb commented on src/jest.ts
> +   * @default coverage
```suggestion
   * @default "coverage"
```

2020-11-03 18:57 UTC, eladb commented on src/jest.ts
> +    project.addDevDeps(`jest@${version}`);
I think that with the new "deps" mechanism we don't really need to specify a version by default:

```suggestion
    const version = options.jestVersion;
    const jestDep = version ? `jest@${version}` : 'jest';
    project.addDevDeps(jestDep);
```

This will have the effect of installing the latest jest version when the project is first created and then upgrades can be managed through `yarn upgrade`, dependabot, or any other tool

2020-11-03 18:57 UTC, eladb commented on src/jest.ts
> +const DEFAULT_JEST_VERSION = '^26.4.2';
Not required any more:

```suggestion
```

2020-11-03 18:57 UTC, eladb commented on src/jest.ts
>     * @default ^26.4.2
```suggestion
   * @default - installs the latest jest version
```

2020-11-03 18:57 UTC, eladb commented on src/jest.ts
> +      'ts-jest@^26.1.0',
Install latest:

```suggestion
      '@types/jest',
      'ts-jest',
```

2020-11-03 18:57 UTC, eladb commented on src/node-project.ts
> +  readonly buildWorkflowCodeCoverage?: boolean;
Yes, I like `codeCov` better.

2020-11-03 18:57 UTC, eladb commented on src/node-project.ts
> +   * The directory in which .ts tests reside.
```suggestion
   * The directory in which tests reside.
```

2020-11-03 18:57 UTC, eladb commented on src/node-project.ts
> +   * The Jest configuration
```suggestion
   * The Jest configuration (if enabled)
```

2020-11-03 18:57 UTC, eladb commented on src/node-project.ts
> +        ...options.jestOptions,
I was expecting testdir to be reflected somewhere in jest options, no?

2020-11-03 18:57 UTC, eladb commented on src/node-project.ts
> +   * code coverage metrics to https://codecov.io/
We should mention in this description that a secret needs to be added to the repo in order to be able to submit code overage to codecov.io.

Which makes me think that maybe a better API for enabling code coverage would be to simply specify the secret name. This will signal to users that a secret is needed.

Instead of:

```ts
{ buildWorkflowCodeCoverage: true } // with implicit secret name
```

Users will simply do:

```ts
{ codeCovSecret: 'CODECOV_TOKEN' }
```

2020-11-03 18:57 UTC, eladb commented on src/node-project.ts
> +  public get workflowCodecoverageSteps(): any[] {
`workflowBootstrapSteps` is needed somewhere which is why it's exposed.

2020-11-03 18:57 UTC, eladb commented on src/node-project.ts
> +          directory: this.jest?.config?.coverageDirectory,
I am assuming we should fail if `this.jest?.config?.coverageDirectory` is undefined, no?

2020-11-03 19:25 UTC, kcwinner commented on src/node-project.ts
> +   * code coverage metrics to https://codecov.io/
For public repositories a token is not required. 
I just changed to
```
/**
   * Define a GitHub workflow step for sending code coverage metrics to https://codecov.io/
   * Uses codecov/codecov-action@v1
   * A secret named 'CODECOV_TOKEN' is required for private repos
   * @default false
   */
  readonly codeCov?: boolean;
```

However, I do like representing it with `{ codeCovSecret: 'CODECOV_TOKEN' }` way better instead of assuming they will call it `CODECOV_TOKEN`. Only makes the public repo a bit more awkward. I can make that switch if we want

2020-11-03 19:40 UTC, kcwinner commented on src/node-project.ts
> +  public get workflowCodecoverageSteps(): any[] {
This seems to relate to Issue #74 a little bit I think. I put an example of what things could look like. But perhaps these should be exposed instead for building composable workflows?

I'm happy to remove it, though

2020-11-03 20:08 UTC, kcwinner commented on src/node-project.ts
> +        ...options.jestOptions,
That gets passed down via `project` unless we want it to be explicit

```
this.config = {
      clearMocks: true,
      collectCoverage: options.coverage ?? true,
      coverageDirectory: options.coverageDirectory ?? 'coverage',
      coveragePathIgnorePatterns: this.ignorePatterns,
      testPathIgnorePatterns: this.ignorePatterns,
      testMatch: [
        `**/${project.testdir}/**/*.js?(x)`,
      ],
    };
```

2020-11-04 06:31 UTC, eladb commented on src/node-project.ts
> +        ...options.jestOptions,
Feels slightly like the reverse direction. I rather this to be an explicit option for Jest and have the Project pass it down. No?

2020-11-04 06:34 UTC, eladb commented on src/node-project.ts
> +   * code coverage metrics to https://codecov.io/
Okay good to know about public repos. So I'd just introduce two options:

```
codeCov?: boolean;
codeCovTokenSecret?: string;
```

What we do in these cases to improve ergonomics is that if a user specifies a value to `codeCovTokenSecret` it implies that codeCov is true.

2020-11-04 15:02 UTC, kcwinner commented on src/node-project.ts
> +   * code coverage metrics to https://codecov.io/
Added and cleaned up the condition logic

2020-11-04 15:30 UTC, kcwinner commented on src/node-project.ts
> +        ...options.jestOptions,
Should the jest options `testdir` override the project level `testdir` then? Otherwise we can end up with a scenario like below. This causes tests to live in `test` directory but jest is configured with `__tests__` pattern so they never get read.

```
  testdir: 'test',
  codeCov: true,
  jestOptions: {
    testdir: '__tests__'
  }
```

Also - I found this (below) in the `AwsCdkTypeScriptApp`  class. Is there any specific reason for this or can I remove it? I don't see any other hardcoded references to `'test`' in the project type.
```
if (this.testdir !== 'test') {
  throw new Error('test sources are expected under the "test" directory');
}
```

2020-11-04 18:47 UTC, eladb commented on src/github-actions.ts
> +export interface GithubActionStep {
Seems like this is unrelated.

2020-11-04 18:47 UTC, eladb commented on src/node-project.ts
> +   * @default "CODECOV_TOKEN"
Would that work for public repos? Wouldn't GitHub look up the secret?

I was thinking that this should have a default value of `undefined` and if it's defined, it will imply `codeCov: true`.

2020-11-04 18:47 UTC, eladb commented on src/node-project.ts
> +            token: `\${{ secrets.${options.codeCovTokenSecret ?? 'CODECOV_TOKEN'} }}`,
The token is only needed if `codeCovTokenSecret` is defined, no? Otherwise, GitHub will require that `CODECOV_TOKEN` exists in the repo, no?

2020-11-04 22:41 UTC, kcwinner commented on src/node-project.ts
> +   * @default "CODECOV_TOKEN"
It still works even with a defined (but empty) secret. It could be confusing, though. 

https://github.com/kcwinner/cdk-appsync-transformer/runs/1355438476?check_suite_focus=true
https://codecov.io/github/kcwinner/cdk-appsync-transformer/commit/1f60a507fec0ebbbd97df2e5cbf159dd7cebbef1

2020-11-04 22:44 UTC, kcwinner commented on package.json
> -      "**/__tests__/**/*.ts?(x)",
Should this be supported alongside the testdir declaration?

Previously testmatch was the following no matter what value was supplied for `testdir`
```
"testMatch": [
      "**/__tests__/**/*.ts?(x)",
      "**/?(*.)+(spec|test).ts?(x)"
    ],
```

2020-11-04 23:16 UTC, kcwinner commented on src/node-project.ts
> +            token: `\${{ secrets.${options.codeCovTokenSecret ?? 'CODECOV_TOKEN'} }}`,
Same as above

2020-11-05 06:49 UTC, eladb reviewed
Almost there...

2020-11-05 06:49 UTC, eladb commented on src/node-project.ts
> +  public jest?: Jest;
```suggestion
  public readonly jest?: Jest;
```

2020-11-05 06:49 UTC, eladb commented on src/node-project.ts
> +   */
```suggestion
  /**
   * Define the secret name for a specified https://codecov.io/ token
   * A secret is required to send coverage for private repositories
   * @default - if this option is not specified, only public repositories are supported
   */
```

2020-11-05 06:49 UTC, eladb commented on src/node-project.ts
> +    this.testdir = options.jestOptions?.testdir ?? options.testdir ?? 'test';
This is a bit error prone.

I think if testdir is specified both in `jestOptions` and in options, they should be the same. Otherwise, fail.

Also doesn't seem like we need both lines.

2020-11-05 06:49 UTC, eladb commented on src/node-project.ts
> +        ...options.jestOptions,
the check in the awscdk typescript project encodes some hidden assumption, but for the life of me I can't recall what was it. Let's leave it please.

2020-11-05 06:49 UTC, eladb commented on src/node-project.ts
> +              token: `\${{ secrets.${options.codeCovTokenSecret} }}`,
What happens here if this options is not defined?

2020-11-05 08:26 UTC, eladb commented on package.json
> -      "**/__tests__/**/*.ts?(x)",
Yes that's a good point. Just a regression of current behavior so let's call out in a breaking change clause in the PR description perhaps.

2020-11-05 14:05 UTC, kcwinner commented on src/node-project.ts
> +              token: `\${{ secrets.${options.codeCovTokenSecret} }}`,
It has to be defined at this point, yeah? Otherwise we omit it and just pass in directory. I tried to find a better way to write it but the yaml library doesn't ignore null/undefined and it just gets passed into the workflow, which github doesn't like.

```
with: options.codeCovTokenSecret
            ? {
              token: `\${{ secrets.${options.codeCovTokenSecret} }}`,
              directory: project.jest.config.coverageDirectory,
            } : {
              directory: project.jest.config.coverageDirectory,
            },
```

2020-11-05 14:11 UTC, kcwinner commented on src/node-project.ts
> +    this.testdir = options.jestOptions?.testdir ?? options.testdir ?? 'test';
Yeah my mistake on committing it. Was just supposed to be a part of this conversation
https://github.com/projen/projen/pull/266#discussion_r517429109

2020-11-05 14:32 UTC, eladb commented on src/node-project.ts
> +              token: `\${{ secrets.${options.codeCovTokenSecret} }}`,
okay now I see. sorry.

2020-11-05 14:34 UTC, eladb reviewed
A few unresolved comments

2020-11-05 15:02 UTC, kcwinner commented
I think the last thing is figuring out how to handle the project `testdir` vs jestOptions `testdir`. Commented [here](https://github.com/projen/projen/pull/266#discussion_r518079677)

2020-11-05 15:05 UTC, kcwinner commented on package.json
> -      "**/__tests__/**/*.ts?(x)",
How is that annotated? Is it the same as in the CDK contributions?
```
BREAKING CHANGE: <describe what changed + link for details>
```

2020-11-05 15:58 UTC, eladb commented on package.json
> -      "**/__tests__/**/*.ts?(x)",
Yes

2020-11-05 16:00 UTC, eladb commented on src/node-project.ts
> +    this.testdir = options.jestOptions?.testdir ?? options.testdir ?? 'test';
Let's just require that `jestOptions.testdir` is the same as the project's:

```ts
const testdir = options.testdir ?? 'test';
if (jestOptions.testdir && jestOptions.testdir !== testdir) {
  throw new Error(`boom`);
}
```

2020-11-05 16:22 UTC, kcwinner commented on src/typescript.ts
>          this.addTestCommand(`rm -fr ${this.libdir}/`);
Need to figure out a solution to this. With the change, if you compile before test, you get the following, which is out of order
```
"test": "jest --passWithNoTests --updateSnapshot && rm -fr lib/ && yarn run eslint",
```

2020-11-05 17:05 UTC, kcwinner commented on src/typescript.ts
> +        this.addScript('test', `rm -fr ${this.libdir}/`);
@eladb Open to suggestions here. Since we need this to be at the beginning of the test command
It won't cause issues downstream but if something happens before this it will be dropped from the test command.

2020-11-05 18:19 UTC, Chriscbr commented on src/typescript.ts
> +        this.addScript('test', `rm -fr ${this.libdir}/`);
Maybe there is a need for a `prependScriptCommand()` API of some sort?

A more hacky workaround could be to change the `deleteScript` API to return the current script(s) given the particular command, so that you could do something like:
```ts
const testCmds = deleteScript('test');
this.addScript('test', testCmds.concat([`rm -fr ${this.libdir}/`]).join('&&'));
```
But I don't think that's an especially healthy abstraction

2020-11-05 18:45 UTC, eladb requested changes
Thanks so much for bearing with me! I know it's been a bit of a back and forth with this PR.
I thought a little more about jest match patterns and I think we should just leave the current behavior untouched. I think it's very common in jest to just put tests everywhere. It's not ideal from a bundling perspective but it's also not the end of the world, and we can decide to tackle this more formally in a subsequent PR.

To my understanding, all the stuff related to `testdir` is actually not instrumental in order to support codecov, correct? If that is indeed the case, let's limit the scope of this change to what's needed for codecov.

2020-11-05 18:45 UTC, eladb commented on package.json
> +      "**/test/?(*.)+(spec|test).ts?(x)"
I believe this shouldn't have the `**/` prefix. Otherwise, any subdirectory called `test/` could have test in it, and we just want tests to be under `test`. Also, it doesn't allow subdirectories under `test` to include tests, which is also something people use.

I think the correct pattern is:

```
test/**/?(.*)+(spec|test).ts?(x)
```

I am also thinking that perhaps we don't need to change this behavior in _this_ PR because it's not instrumental to enabling codecov.io and it will break users who decided to put tests under their `src/` directory.

When thinking about it, it's actually legitimate.

2020-11-05 18:45 UTC, eladb commented on src/jest.ts
> +      testMatch: [
I think we should just ignore the testdir here and just plug in:

```js
[
  '**/__tests__/**/*.js?(x)',	
  '**/?(*.)+(spec|test).js?(x)',
]
```

Which I believe is the default for jest.

2020-11-05 18:45 UTC, eladb commented on src/jest.ts
> +      `**/${this.testdir}/?(*.)+(spec|test).ts?(x)`,
Don't encode testdir into this pattern.

2020-11-05 18:45 UTC, eladb commented on src/jest.ts
> +  private readonly testdir: string;
Remove

2020-11-05 18:45 UTC, eladb commented on src/jest.ts
> +  readonly testdir?: string;
Remove this please

2020-11-05 18:45 UTC, eladb commented on src/typescript.ts
> +        this.addScript('test', `rm -fr ${this.libdir}/`);
Yes, there's a bit of a modeling issue with those mutable scripts. Let's pick this up in a subsequent PR?

2020-11-05 19:19 UTC, kcwinner commented
I agree about leaving the `testdir` out of the matching policy. I think people sprinkle them next to the they are testing and others don't.

2020-11-05 19:27 UTC, kcwinner commented
Reverted changes regarding Jest testdir. Reverted testMatch config changes.

2020-11-08 06:38 UTC, eladb approved these changes

2020-11-08 21:30 UTC, merged