feat(tasks): Add support for environment variables in task steps
projen/projen pull request #2663
Opened 2023-05-08 15:30 UTC by icj217

Currently tasks support environment variables, but only at the task level. These variables are resolved eagerly at the beginning of the task's execution. 

There are scenarios where having environment variables that are bound to a particular step can be quite useful, especially since its not possible to "pass state" from one step to another. The example below shows a scenario where a task starts a docker container and then needs to look up the container's ephemeral port and pass that info as an environment variable (`S3_ENDPOINT`) to another command. Currently, this environment variable has to be inline to the command, since it must be evaluated after the first spawn step finishes.

For example:
```typescript
project.tasks.addTask('tests:docker', {
            steps: [
                { spawn: 'start:docker:localstack' },
                { exec: `S3_ENDPOINT=http://localhost:$(docker compose port localstack 4566 | cut -d: -f2) docker compose run --rm tester` }
            ]
        })

```

With this change, environment variables can be defined at the individual step level (only resolved for `exec` and `builtin` steps), making the example above much cleaner to follow:

```typescript
project.tasks.addTask('tests:docker', {
            steps: [
                { spawn: 'start:docker:localstack' },
                { 
                    env: {
                        // Obtain value after start:docker:localstack finishes 
                        S3_ENDPOINT: '$(echo "http://localhost:$(docker compose port localstack 4566 | cut -d: -f2)")',
                    },
                    exec: `docker compose run --rm tester`
                }
            ]
        })
```

Features:
* Variables defined at step level will override task-level variables
* Can be defined in both upfront `steps` argument as well as in `task.exec()` and `task.builtin()` methods
* Variable values will be stringified (same as task/global variables)

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-05-09 08:34 UTC, mrgrain requested changes
Nice one @icj217 ! 🚀 

Just got a couple of small suggestions.

2023-05-09 08:34 UTC, mrgrain commented on src/task.ts
> +      warn(
Looks like this will now warn twice for a wrong env type: First when `addEnv` is called, and then again when the task file is rendered via `_renderSpec`.

2023-05-09 08:34 UTC, mrgrain commented on src/task-model.ts
> +   * @default {}
Can a user also define simple values? If so, let's make this clear in the docstring. An `@example` tag would also be great.

```ts
env: {
  foo: "bar"
}
```

2023-05-09 13:14 UTC, icj217 commented on src/task.ts
> +      warn(
Good catch. I've decided to defer all value manipulation until writing to the manifest, so this should be resolved now.

2023-05-17 19:42 UTC, icj217 commented
Friendly ping @mrgrain whenever you get a chance to re-review

2023-05-18 07:48 UTC, mrgrain approved these changes
🚀

2023-05-18 08:04 UTC, merged