chore(cdk): remove deprecated Semver
projen/projen pull request #267
Opened 2020-11-02 10:59 UTC by hoegertn

Removes the use of the deprecate Semver class and old-style dependency methods.

2020-11-02 14:52 UTC, eladb requested changes

2020-11-02 14:52 UTC, eladb commented on src/awscdk-app-ts.ts
>    readonly cdkVersion: string;
A required field with no "@default" means that it will impossible to run `projen new` without specifying this switch (we should probably [add a test](https://github.com/projen/projen/issues/268) that prevents this).

I understand putting "1.63.0" here is a bit weak, and I am wondering what is the ideal behavior. Here are a few options:

1. Create a [default macro] such as `$GIT_USER_NAME` and `$GIT_REMOTE` that will allow evaluating the latest version of an npm package during `projen new` and assigning that value here (e.g. `$NPM_MODULE_VERSION[aws-cdk]`).
2. Make `cdkVersion` an _optional_ attribute and call `addDep()` without a version specification - this means that projen will install the latest version of these modules and then the specific version will be managed in `package.json`. The problem with this approach is the fact that we really need to ensure that all CDK versions are synchronized, and one of the ways this is done is by controlling them through projen.
3. Determine the latest CDK version during _projen build_, including it as a resource in projen itself and using that as the default.

Personally, I am okay with leaving some static value for now (the current latest) and revisiting in a subsequent PR.

[default macro]: https://github.com/projen/projen/blob/a654767a7379309744dd73b48d7fd2f5b5bff67e/src/cli/cmds/new.ts#L116

2020-11-02 14:54 UTC, hoegertn commented on src/awscdk-app-ts.ts
>    readonly cdkVersion: string;
Already fixed as I read #268 

I wasn't aware of this and as it is not optional I was wondering what a default would be good for.

2020-11-02 14:56 UTC, hoegertn commented on src/awscdk-app-ts.ts
>    readonly cdkVersion: string;
On a side note, with this Semver change is it really meant to be managed in package.json instead of projen? I thought the goal was to make the package.json throw-away capable.

2020-11-02 16:01 UTC, eladb commented on src/awscdk-app-ts.ts
>    readonly cdkVersion: string;
In order to enable using dependency management tools like dependabot/ncu, we need specific versions to actually be managed inside package.json, so at the moment, it's "partially immutable". Versions are respected.

2020-11-02 16:05 UTC, eladb requested changes

2020-11-02 16:05 UTC, eladb commented on src/awscdk-construct.ts
> +    this.addDeps(...deps.map(m => `${m}@${this.version}`));
```suggestion
    this.addPeerDeps(...deps.map(m => `${m}@${this.version}`));
```

2020-11-02 16:05 UTC, eladb commented on src/awscdk-construct.ts
> +    this.addDeps(...deps.map(m => `${m}@${this.version}`));
Can we extract the logic that formats a CDK module spec into a private method:

```ts
private formatModuleSpec(module: string) {
  return `${module}@${this.version}`;
}
```

2020-11-02 16:27 UTC, hoegertn commented on src/awscdk-construct.ts
> +    this.addDeps(...deps.map(m => `${m}@${this.version}`));
Done

2020-11-02 18:47 UTC, eladb commented on src/awscdk-app-ts.ts
> +    this.addDeps(...modules.map(m => `${m}@${this.cdkVersion}`));
use `formatModuleSpec`

2020-11-02 22:56 UTC, hoegertn commented on src/awscdk-app-ts.ts
> +    this.addDeps(...modules.map(m => `${m}@${this.cdkVersion}`));
It is the only use case on the app project. So I have three options:

* Use the template string as currently
* Copy the method to this class and use it once
* Extract the method somewhere else and use it

Do you have a preference?

2020-11-02 22:57 UTC, hoegertn commented on src/awscdk-app-ts.ts
> +    this.addDeps(...modules.map(m => `${m}@${this.cdkVersion}`));
Ok it is used twice so it might be ok

2020-11-03 06:21 UTC, eladb approved these changes

2020-11-03 06:22 UTC, merged