feat(node-package): allow to remove resolutions
projen/projen pull request #2685
Opened 2023-05-18 11:49 UTC by tinovyatkin

This PR switches source of true for package resolutions from internal structure `packageResolutions` to project dependencies (as in case of all other dependencies).

This allows particulary to remove resolutions via simple `project.deps.removeDependency(name, DependencyType.OVERRIDE)` which is currently impossible (as resolution renders out `packageResolutions` and never syncs after initial addition).

Additional little change is to skip parsing on `addPackageResolutions` and instead use return value of `deps.addDependency`.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-05-18 13:37 UTC, mrgrain requested changes
Nice one! Can you please add a test showing that we can remove a resolution using `removeDependency` and this should be good to go.

2023-05-18 15:34 UTC, mrgrain commented on test/javascript/node-package.test.ts
> +  expect(pkgJson).toHaveProperty("dependencies.some-dep", "1.0.0");
I would have expected an assertion like this:
```suggestion
  expect(pkgJson).toHaveProperty("dependencies.some-dep", "1.0.0");
  expect(pkgJson).not.toHaveProperty("overrides.some-dep");
```

2023-05-18 15:41 UTC, mrgrain commented on src/javascript/node-package.ts
> +      }
Is this whole bit even necessary? Looks like we are now storing package resolutions (aka overrides) in two places:
- the private `packageResolutions` field, and
- the project dependencies

And then we are checking that both places are actually in sync?! And debug/warn if not?
Feels like we can just get rid of the `packageResolutions` field and take the dependencies as source of truth.

2023-05-18 16:05 UTC, tinovyatkin commented on src/javascript/node-package.ts
> +      }
I believe this is because current projen support for overrides is pretty limited (for example in NPM key for override can include version or even version range and value maybe an object, not just string) and this is some sort of future todo. Those more complicated cases can be solved via JsonPatch. I'll remove the `packageResolutions`.

2023-05-18 20:14 UTC, mrgrain approved these changes

2023-05-18 20:16 UTC, mrgrain requested changes
Code looks good now. You've got a failing build due to snapshot updates.

2023-05-19 07:22 UTC, mrgrain approved these changes

2023-05-19 07:22 UTC, merged