feat(javascript): add workflowNodePackageCacheEnabled
projen/projen pull request #2690
Opened 2023-05-20 06:10 UTC by riywo

This commit adds a new option for NodeProject
to enable package cache option on GitHub Actions workflows.

When this option is enabled, `actions/setup-node` step is configured to use proper `cache` input based on the package manager option.

Close #1439

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-05-30 14:58 UTC, mrgrain requested changes
Just a small rename

2023-05-30 14:58 UTC, mrgrain commented on src/javascript/node-project.ts
> +  readonly workflowNodePackageCacheEnabled?: boolean;
```suggestion
  readonly workflowPackageCache?: boolean;
```

2023-05-31 00:21 UTC, riywo commented on src/javascript/node-project.ts
> +  readonly workflowNodePackageCacheEnabled?: boolean;
Renamed!

2023-05-31 12:45 UTC, mrgrain commented
@riywo

```
This pull request cannot be embarked for merge
The merge queue pull request can't be updated
Details:

Pull request can't be updated with latest base branch changes

Mergify needs the author permission to update the base branch of the pull request.
https://github.com/opsbr needs to [authorize modification on its head branch](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
err-code: 43C09
```

2023-05-31 13:55 UTC, closed without merging