fix(cli): improve git config detection
projen/projen pull request #270
Opened 2020-11-02 23:15 UTC by hoegertn

This PR improves the handling of the git default values by:

* Taking `--include` into account to resolve included git config files
* Using the `github.user` config for remote URL generation

2020-11-02 23:47 UTC, Chriscbr commented on src/cli/cmds/new.ts
> +  const userEmail = execOrUndefined('git config --get --global --include user.email') ?? 'user@domain.com';
Is `--include` the same as `--includes`? (https://git-scm.com/docs/git-config#Documentation/git-config.txt---no-includes)

2020-11-03 06:20 UTC, eladb requested changes

2020-11-03 06:20 UTC, eladb commented on src/cli/cmds/new.ts
> +  const userEmail = execOrUndefined('git config --get --global --include user.email') ?? 'user@domain.com';
Yes, sounds like this should be `--includes`:

```suggestion
  const userEmail = execOrUndefined('git config --get --global --includes user.email') ?? 'user@domain.com';
```

2020-11-03 06:20 UTC, eladb commented on src/cli/cmds/new.ts
> +      const slug = execOrUndefined('git config --get --global --include github.user') ?? userEmail?.split('@')[0];
Maybe extract to a function:

```suggestion
      const slug = gitConfigGet('github.user') ?? userEmail?.split('@')[0];
```

2020-11-03 07:54 UTC, hoegertn commented on src/cli/cmds/new.ts
> +  const userEmail = execOrUndefined('git config --get --global --include user.email') ?? 'user@domain.com';
Done, the interesting thing is: It works also

2020-11-03 08:40 UTC, eladb approved these changes

2020-11-03 08:43 UTC, merged