feat: adding README generation
projen/projen pull request #276
Opened 2020-11-03 14:48 UTC by mbonig

Re-adds the README file and sample file rework. Now uses the synth and _outdir instead of __dirname.

2020-11-03 17:39 UTC, Chriscbr commented on src/sample-file.ts
> +  synthesize(_outdir: string) {
```suggestion
  public synthesize(outdir: string) {
```

2020-11-03 18:05 UTC, mbonig commented
do y'all care if I squash my commits?

2020-11-03 18:44 UTC, eladb requested changes
Can you please confirm that you have manually tested that `projen new` works?

2020-11-03 18:44 UTC, eladb commented on src/sample-file.ts
> +    fs.mkdirpSync(dir);
please use `writeFile` from `util.ts` which takes care of creating the directory tree

2020-11-03 18:44 UTC, eladb commented on src/sample-file.ts
> +      fs.writeFileSync(path.join(fullOutdir, filename), this.options.files[filename]);
Please use writeFile from util.ts (and then mkdirp is not required)

2020-11-03 19:00 UTC, mbonig commented
> Can you please confirm that you have manually tested that `projen new` works?

Yes. I went into `test/` and created a new directory, cd'd into that directory and then did `../../bin/projen new awscdk-app-ts`. The resulting code built as expected (projen runs without errors and a `yarn cdk synth` compiles without errors).

2020-11-04 18:49 UTC, eladb commented on src/sample-file.ts
> +    writeFile(fullFilename, contents);
By default I think `writeFile` creates readonly files, so here you'd need to explicitly set:

```ts
writeFile(fullFilename, contents, { readonly: false });
```

2020-11-04 18:49 UTC, eladb requested changes
files are written as read-only.

2020-11-08 06:38 UTC, eladb approved these changes

2020-11-08 06:42 UTC, merged