feat(jest): add jest test results processing
projen/projen pull request #279
Opened 2020-11-03 21:58 UTC by gradybarrett

First stab at the most basic implementation.

A possible next step would be a dedicated, opinionated JestJUnit config object

Fixes #278

2020-11-04 19:55 UTC, eladb requested changes
Can we just be opinionated and simply add jest-junit support, enabled by default?

2020-11-04 19:55 UTC, eladb commented on src/jest.ts
> +   * { testResultsProcessor: 'jest-junit' }
```suggestion
   * @example "jest-junit"
```

2020-11-05 18:29 UTC, gradybarrett commented
> Can we just be opinionated and simply add jest-junit support, enabled by default?

I didn't really consider that. I suppose we could. Let me switch this to reporters and do a little testing to make sure it works how I expect.

2020-11-05 21:53 UTC, gradybarrett commented
@eladb here's an interpretation of what you suggested. Let me know what you think.

cc: @Chriscbr

2020-11-05 22:40 UTC, Chriscbr requested changes
Just a few comments, looks good overall! Personally I think it would make more sense having junit reporting off by default, but that's just me

2020-11-05 22:40 UTC, Chriscbr commented on src/jest.ts
> +      project.addDevDeps('jest-junit@^12');
do we need a specific version here?

2020-11-05 22:40 UTC, Chriscbr commented on src/jest.ts
> +      const reportsDir = DEFAULT_TEST_REPORTS_DIR;
Maybe specify this as configurable with a prop like `junitReportingDir`

2020-11-05 22:40 UTC, Chriscbr commented on src/jest.ts
> +    const reporters: Array<[string, {[key: string]: any}] | string> = ['default'];
I think this should be a private field on the class. Also maybe we can add a method like `addReporter()` for it?

2020-11-05 22:40 UTC, Chriscbr commented on package.json
> +    "jest-junit": "^12",
I think unless there is a need for junit-formatted test reports in projen's own CI/CD processes, we should change the `.projenrc.js` for projen itself to disable junit reporting.

2020-11-05 22:44 UTC, Chriscbr commented on src/jest.ts
> +      project.addDevDeps('jest-junit@^12');
Actually this might be fine as is, since it looks like a lot of the other constructs in projen give specific versions by default (not sure if this is better or not, but hey)

2020-11-05 22:48 UTC, gradybarrett commented on src/jest.ts
> +      const reportsDir = DEFAULT_TEST_REPORTS_DIR;
I was headed down that road when I stopped myself because it felt like I was going back towards what I had originally, just packaged differently. I'm still trying to figure out the opinionated vs configurable line here. I figured I'd at least tee that change up for the next person, unless you or Elad feels strongly that it should be configurable right now.

2020-11-05 22:58 UTC, gradybarrett commented on src/jest.ts
> +      project.addDevDeps('jest-junit@^12');
I'm on the fence on this one. I suppose not, but in either case, someone can `project.addDevDeps('jest-junit@11')` after project initialization in order to override the version declared here. Since that's the case I think I'd rather see a known stable version declared here by default.

2020-11-05 23:04 UTC, gradybarrett commented on package.json
> +    "jest-junit": "^12",
> Just a few comments, looks good overall! Personally I think it would make more sense having junit reporting off by default, but that's just me

Hah, funny you should say that. I flip-flopped and committed about 3 times trying to decide how I felt about that. There's something nice about it just being on by default. If I need/want it, it's just there. It's not a particularly "expensive" operation, and I made sure the default reporter still runs.

I am, however, inclined to agree with you that generally, this might make more sense as an opt-in, rather than an opt-out feature.

2020-11-05 23:06 UTC, gradybarrett commented on package.json
> +    "jest-junit": "^12",
I figured I would see how you guys felt about it being on by default by committing the changes to the actual projen project. I agree that we should probably shut it off for projen specifically if we do leave it on by default.

2020-11-07 01:37 UTC, gradybarrett commented on package.json
> +    "jest-junit": "^12",
Switched back to disabled by default.

2020-11-07 02:08 UTC, gradybarrett commented on package.json
> +    "jest-junit": "^12",
I think I'm actually going to leave it the way it is. I feel like opt-out is actually consistent with how other configs are being handled so far in Projen, so I'd hate this to be one that's unexpectedly different.

It's also in line with 'coverageReporters' behavior, which gives you all 4 formats by default.

I'll turn it off for the actual projen project though.

2020-11-07 02:25 UTC, gradybarrett commented on src/jest.ts
> +    const reporters: Array<[string, {[key: string]: any}] | string> = ['default'];
I did some research and testing on `reporters` vs `coverageReporters`, and unfortunately, the two do not overlap in the same way as `reporters` and `testResultsProcessor`, so that will need to be a separate feature. The new JestReporters class can, however, be reused for both, so adding coverage reporters functionality should be easy after this, if it's needed.

2020-11-07 02:28 UTC, gradybarrett commented on src/jest.ts
> +      project.addDevDeps('jest-junit@^12');
Ha, ya, if nothing else, it's always good to be consistent. :)

2020-11-07 02:31 UTC, gradybarrett commented on src/jest.ts
> +type JestReporter = [string, {[key: string]: any}] | string;
@eladb is this frowned upon?

I know JSII doesn't support type aliases, so I didn't export either of these. It just feels bad to have to repeat `[string, {[key: string]: any}] | string` in 3 places.

2020-11-07 23:39 UTC, Chriscbr reviewed
Just a few comments/suggestions

2020-11-07 23:39 UTC, Chriscbr commented on src/jest.ts
> +class JestReporters extends Array<JestReporter> {
I see what you are going for here, but I'm not sure if extending an Array type is ideal from an abstraction/style standpoint. I feel like having the array as an instance property would have the upside of allowing other properties to be added in the future if needed (and allow the class to be exported by JSII potentially). But this is just me inferring from how I see code written in the aws-cdk (another project overseen by eladb), so I'm open to other options

2020-11-07 23:39 UTC, Chriscbr commented on src/jest.ts
> +type JestReporter = [string, {[key: string]: any}] | string;
Another option here is to create a basic class called `JestReporter` with an optional `options` field for storing the reporter config. Then by adding a method named `synthesize()` or similar which returns the object in the correct jest format (an array of [string, object]), then you can put `reporters: () => this.reporters.map(x => x.synthesize())` in the config below and it should synthesize the results properly, I think.

2020-11-09 21:50 UTC, gradybarrett commented on src/jest.ts
> +type JestReporter = [string, {[key: string]: any}] | string;
I was trying to keep that extra code to a minimum by relying on types, but in the long term going that route probably makes objectifying a given config easier.

2020-11-12 08:21 UTC, Chriscbr commented on .projenrc.js
> +    junitReporting: false,
I think I suggested that earlier because I thought leaving it as default (`true`) would add extra test artifacts to projen. But I just noticed now that they would get gitignored anyway, so yeah in that case it doesn't matter (keeping it false might just shorten the build time slightly 🤷 ).

2020-11-17 03:56 UTC, gradybarrett commented on .projenrc.js
> +    junitReporting: false,
Eh, I think the operation is pretty quick, so I'll remove this.

2020-11-17 03:57 UTC, gradybarrett commented on src/jest.ts
> +type JestReporter = [string, {[key: string]: any}] | string;
Cool. I'll leave it the way it is then. It'll grow into whatever it needs to be long term.

2020-11-17 04:07 UTC, gradybarrett commented on src/jest.ts
> +class JestReporters extends Array<JestReporter> {
It does feel that way. I'm going to remove this and move it back down into the Jest class. It'll naturally get abstracted when it needs to be.

2020-11-17 08:54 UTC, eladb approved these changes
🎉

2020-11-17 08:55 UTC, merged