chore: use Node16 module & moduleResolution when appropriate
projen/projen pull request #2791
Opened 2023-07-12 09:00 UTC by RomainMuller

Instead of using `CommonJS` and `Node`, apply the `Node16` module and module resolution settings, which are preferred when targeting node >=16 as it allows dynamically choosing the correct algorithms based on file extension as well as package.json configuration.

Additionally, automatically configure `target` and `lib` based on the configured minimum node version (if present).

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-07-12 09:14 UTC, mrgrain requested changes

2023-07-12 09:14 UTC, mrgrain commented on src/javascript/typescript-config.ts
> +  NODE = "Node",
```suggestion
  NODE = "node",
```

Let's keep all of these lower case as per the docs. AFAIK they are case insensitive anyway. 

https://www.typescriptlang.org/tsconfig#moduleResolution
<img width="142" alt="image" src="https://github.com/projen/projen/assets/379814/d4ed6b1d-444f-4519-91dd-521b1163d6dd">

2023-07-12 09:14 UTC, mrgrain commented on src/javascript/typescript-config.ts
> +export enum TypeScriptModule {
Same here, let's stick with lowercase

2023-07-12 09:15 UTC, mrgrain commented on package.json
> +  },
How come these are back now? They weren't needed before?

2023-07-12 09:19 UTC, mrgrain commented
Is this going to be a breaking change because the `module` field is now typed?

2023-07-12 09:19 UTC, RomainMuller commented on src/javascript/typescript-config.ts
> +  NODE = "Node",
I found they look better capitalized properly, but yeah... it makes no difference.

2023-07-12 09:19 UTC, RomainMuller commented on package.json
> +  },
This is the issue I made https://github.com/aws/jsii-compiler/pull/204 for :)

2023-07-12 09:21 UTC, RomainMuller commented
> Is this going to be a breaking change because the `module` field is now typed?

Good question. I suspect possibly maybe? I can revert this to being `string` and replace the enum with a constants helper?

2023-07-12 09:36 UTC, mrgrain commented on test/javascript/jest.test.ts
> +  moduleResolution: "nNode",
```suggestion
  moduleResolution: "node",
```

2023-07-12 09:38 UTC, RomainMuller commented on test/javascript/jest.test.ts
> +  moduleResolution: "nNode",
🤦🏻‍♂️

2023-09-05 15:29 UTC, doublecompile commented
Side note: I determined the proper configuration to get Projen and Jest working correctly with a TypeScript project where the `package.json` has `type` set to `module` (i.e. ESM instead of CommonJS), [check out this gist](https://gist.github.com/doublecompile/324afb33b6038526705dfebb3b529e42) for an example `.projenrc.ts`.

2023-10-22 15:31 UTC, mrgrain commented
Note to myself: https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping

jsii probably needs to update these as well

2025-04-22 11:30 UTC, mrgrain commented
closing stale PR

2025-04-22 11:30 UTC, closed without merging