feat: add runner group support
projen/projen pull request #2817
Opened 2023-07-24 22:19 UTC by Rami-Husein

Fixes #2814  

**[GitHub Actions: Restrict workflows to specific runners using runner group names](https://github.blog/changelog/2022-11-01-github-actions-restrict-workflows-to-specific-runners-using-runner-group-names/)**

`.projenrc.ts` properties:
- `workflowRunsOn`, 
- `githubOptions.pullRequestLintOptions.runsOn`
- `depsUpgradeOptions.workflowOptions.runsOn`
- `autoApproveOptions.runsOn`
- `staleOptions.runsOns`

...now all support specifying Runner Groups, by name.    

```
  workflowRunsOn: {
    group: "Default",
    labels: ["self-hosted", "Linux", "x64"],
  }
  ```
  
  The original support for specifying Labels in an array is still supported:
```
workflowRunsOn: ['ubuntu-latest', 'x86']
```

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-07-26 12:34 UTC, mrgrain requested changes
Looks pretty good, thank you! We just have to sort out the union type issue and I'll have a closer look then.

2023-07-26 12:34 UTC, mrgrain commented on src/build/build-workflow.ts
> +  readonly runsOn?: string[] | GroupRunnerOptions;
We can't use Union types unfortunately due to this not working well in other languages.

Can you change this to an additional new property `runsOnGroup` or similar that takes your new type.
And then extend the validation to make sure only one of the properties is set.

2023-07-26 12:34 UTC, mrgrain commented on src/build/build-workflow.ts
> +  readonly labels: string[];
I believe `labels` is optional. 
```suggestion
  readonly labels?: string[];
```

Source: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-groups-to-control-where-jobs-are-run

2023-07-26 12:34 UTC, mrgrain commented on src/build/build-workflow.ts
> +  readonly runsOn?: string[] | GroupRunnerOptions;
For all the union types, see other comment.

2023-07-28 19:36 UTC, rami-husein commented on src/build/build-workflow.ts
> +  readonly runsOn?: string[] | GroupRunnerOptions;
Ah, I see! I've fixed this in https://github.com/projen/projen/pull/2817/commits/b2ae37e270d5974c1293ab5b6e06f3954897a9df

2023-07-28 19:37 UTC, rami-husein commented on src/build/build-workflow.ts
> +  readonly labels: string[];
Good note! Fixed this in https://github.com/projen/projen/pull/2817/commits/b2ae37e270d5974c1293ab5b6e06f3954897a9df

2023-07-28 19:37 UTC, rami-husein commented on src/build/build-workflow.ts
> +  readonly runsOn?: string[] | GroupRunnerOptions;
Fixed in https://github.com/projen/projen/pull/2817/commits/b2ae37e270d5974c1293ab5b6e06f3954897a9df

2023-08-07 19:15 UTC, mrgrain requested changes
Sorry for the late review. Finally got around to it.
Mostly about avoid code duplication and  responsibilities. You get the idea.

2023-08-07 19:15 UTC, mrgrain commented on src/build/build-workflow.ts
> +    let testing = {
```suggestion
    const jobConfig = {
```

2023-08-07 19:15 UTC, mrgrain commented on src/build/build-workflow.ts
> +    }
Can we delegate this to the workflow instead of doing on on every workflow implementation?

2023-08-07 19:15 UTC, mrgrain commented on src/build/build-workflow.ts
> +      : { runsOn: options?.runsOn ?? this.defaultRunners };
Can we delegate this to the workflow instead of doing on on every workflow implementation?

2023-08-07 19:15 UTC, mrgrain commented on src/build/build-workflow.ts
> +      : { runsOn: options.runsOn ?? this.defaultRunners };
Can we delegate this to the workflow instead of doing on on every workflow implementation?

2023-08-07 19:15 UTC, mrgrain commented on src/github/auto-approve.ts
>  }
Can we delegate this to the workflow instead of doing on on every workflow implementation?

2023-08-07 19:15 UTC, mrgrain commented on src/build/build-workflow.ts
> +  }
Can we delegate this to the workflow instead of doing on on every workflow implementation?

2023-08-25 19:11 UTC, rami-husein commented on src/build/build-workflow.ts
> +    let testing = {
Fixed in https://github.com/projen/projen/pull/2817/commits/f22c02fb5fcfba9b01ed50e9e32778c87a331ef8

2023-08-25 19:13 UTC, rami-husein commented on src/github/workflows.ts
> -  // verify that job has a "runsOn" statement to ensure a worker can be selected appropriately
This verification was moved to [here](https://github.com/projen/projen/pull/2817/files#diff-2ef7bf776940d2981cb6052b7c3095b2a588ce40fd3aa53b6ad1405bf71bc274R35) because other, but related, verification needed to happen earlier on

2023-08-25 19:40 UTC, rami-husein commented on src/build/build-workflow.ts
> +  }
For this, and the others:
The logic can't occur after the creation of the Job, because the properties are readonly, and the creation of the Job occurs before the implementation of Workflow. If we want to have default runners, this logic needs to happen first.

However, in the interest of the DRY principle, I've moved the logic and verification into the [same file](https://github.com/projen/projen/blob/f22c02fb5fcfba9b01ed50e9e32778c87a331ef8/src/runner-options.ts) that holds the GroupRunnerOptions interface.

2023-08-25 19:41 UTC, rami-husein commented on src/runner-options.ts
> +    throw new Error(
This may be not the best error to throw. Let me know if you have an idea.

2023-08-28 11:50 UTC, mrgrain requested changes

2023-08-28 11:50 UTC, mrgrain commented on src/github/workflows.ts
> +): T | T[] | GroupRunnerOptions | GroupRunnerOptions[] | undefined {
This should not be neccessary. The function is already generic. What error do you get?

2023-08-28 11:50 UTC, mrgrain commented on src/runner-options.ts
> +    throw new Error(
Please make sure to mention the property names. I think the exact values here might be less relevant.

2023-09-06 20:32 UTC, rami-husein commented on src/github/workflows.ts
> +): T | T[] | GroupRunnerOptions | GroupRunnerOptions[] | undefined {
I think was a lack of knowledge of how the typescript server resolves generics, on my part. I kept getting an error that type `GroupRunnerOptions` was not assignable to `string[]`. I thought the solution was to add `GroupRunnerOptions` to the types of the function.

After some more reading, I believe the Typescript server infers the type of the generic from a prior use and is incompatible with union types. So instead of calling `arrayOrScalar(job.runsOnGroup ?? job.runsOn)` I should have called `arrayOrScalar(job.runsOnGroup) ?? arrayOrScalar(job.runsOn)` so only a single type is given. This change was made in https://github.com/projen/projen/pull/2817/commits/a9245047a4df48ac72a931096f11bc4843ad2fc7

I also removed the `GroupRunnerOptions` stuff from the `arrayOrScalar()` function, but left in the Array type check, because `GroupRunnerOptions` doesn't have a `.length` property.

2023-09-07 08:13 UTC, mrgrain commented
Looks good now! Thanks for the contribution. Once the build is green, we are good to go!

2023-09-07 10:36 UTC, mrgrain approved these changes

2023-09-07 10:37 UTC, merged