feat: introduce CompositeProject
projen/projen pull request #289
Opened 2020-11-08 22:39 UTC by misterjoshua

Fixes #

2020-11-08 22:52 UTC, misterjoshua commented
@eladb @hoegertn Fresh PR for `CompositeProject` here.

2020-11-08 23:02 UTC, hoegertn commented on src/composite-project.ts
> +}
`postSynthesize` is missing, isn't it?

2020-11-08 23:02 UTC, hoegertn commented on src/composite-project.ts
> +   *   'packages/foo': new NodeProject({ name: 'foo' }),
How does this handle os-specific path delimiters?

2020-11-08 23:06 UTC, misterjoshua commented on src/composite-project.ts
> +}
It is, but at least in the default implementation of `Project`, `synth()` calls its own `postSynthesize()`. I figured if I called it here, that a project's `postSynthesize()` would be called twice.

2020-11-08 23:07 UTC, misterjoshua commented on src/composite-project.ts
> +  readonly subPath: string;
Makes sense.

2020-11-08 23:08 UTC, misterjoshua commented on src/composite-project.ts
> +    this.projects[subPath] = true;
Yup, we should be able to.

2020-11-08 23:08 UTC, misterjoshua commented on src/composite-project.ts
> +  readonly subProject: Project;
Sounds good.

2020-11-08 23:25 UTC, misterjoshua commented on src/composite-project.ts
> +   *   'packages/foo': new NodeProject({ name: 'foo' }),
Hmm. I think `CompositeProject.addProject()` has the same problem, in that it depends on the user to employ `path.join('a', 'b')` to handle os-specific path delims. The notation for typescript/javascript is definitely too exotic:

```ts
{
  [path.join('packages, 'foo')]: new NodeProject({ name: 'foo' }),
  [path.join('packages', 'bar')]: new NextjsProject({ name: 'bar' }),
}
```

2020-11-09 00:02 UTC, misterjoshua commented on src/composite-project.ts
> +  }
> Maybe we could also offer access to the parent root then for .github stuff etc

@hoegertn I was thinking that there's a design decision to be made about how a project can know the parent root so that it knows the right place to put the .github stuff. Given that a sub-project is instantiated before it knows that it's a sub-project, it seems to me that there's a need to inform the sub-project of that. I could call back to the project to inform it here, for instance.

2020-11-09 00:04 UTC, misterjoshua commented on src/composite-project.ts
> +   *   'packages/foo': new NodeProject({ name: 'foo' }),
I've pushed up an alternative.

2020-11-09 03:47 UTC, misterjoshua commented
I'm starting to wonder if I like `ProjectComponent` more than everything else I've written here. 🤣 Well anyway, I'll leave this now for your guys' review.

2020-11-10 09:25 UTC, eladb requested changes
Looks promising!

2020-11-10 09:25 UTC, eladb commented on src/composite-project.ts
> +export interface CompositeProjectDeclarativeSubProject {
Name is too long... Maybe `CompositeProjectChild`.

2020-11-10 09:25 UTC, eladb commented on src/composite-project.ts
> +export interface ProjectComponentOptions {
Can we leave this private for now? Feels like it could be trouble and I am not sure I fully understand the use case here.

```suggestion
interface ProjectComponentOptions {
```

2020-11-10 19:33 UTC, eladb requested changes
Please add `composite-project.ts` to `index.ts`

2020-11-10 19:33 UTC, eladb commented on src/composite-project.ts
> +export interface CompositeProjectChild {
Now that it's private, can we just use `CompositeProjectOptions` and remove this type?

2020-11-10 19:33 UTC, eladb commented on src/composite-project.ts
> +  projects?: CompositeProjectChild[];
```suggestion
  readonly projects?: CompositeProjectChild[];
```

2020-11-10 19:54 UTC, misterjoshua commented on src/composite-project.ts
> +export interface CompositeProjectChild {
I'm sorry but I don't understand. I see that `CompositeProjectChild` and the private `ProjectComponentOptions` are the same. Is your suggestion here to eliminate the private one and re-use the remaining public type like in db183f2 that I've just pushed up?

2020-11-10 21:03 UTC, Chriscbr commented on test/composite-project.test.ts
> +  comp.addProject('packages/bar', new NodeProject({ name: 'bar' }));
Would it make more sense to use path.join here (and in the last test) as well just for consistency?

2020-11-10 21:20 UTC, misterjoshua commented on test/composite-project.test.ts
> +  comp.addProject('packages/bar', new NodeProject({ name: 'bar' }));
I've applied your suggestion. :)

2020-11-11 17:07 UTC, eladb commented on src/composite-project.ts
> +export interface CompositeProjectChild {
yes :-D

2020-11-11 17:08 UTC, misterjoshua commented on src/composite-project.ts
> +export interface CompositeProjectChild {
Sweet!

2020-11-11 18:12 UTC, eladb commented on src/composite-project.ts
> +  readonly projects?: CompositeProjectChild[];
```suggestion
  /**
   * Declaratively define sub-projects by their sub paths.
   * @default []
   * @example
   * [
   *   {
   *     path: path.join('packages', 'foo'),
   *     project: new NodeProject({ name: 'foo' }),
   *   },
   *   ...
   * ]
   */
  readonly projects?: CompositeProjectChild[];
```

2020-11-11 18:13 UTC, eladb commented on src/composite-project.ts
> +  addProject(subPath: string, project: Project) {
```suggestion
  addProject(subdir: string, project: Project) {
```

2020-11-11 18:13 UTC, eladb reviewed
A couple of minor tweaks and we are ready

2020-11-11 18:37 UTC, misterjoshua commented
> A couple of minor tweaks and we are ready

@eladb Cool. The changes you requested are in now.

2020-11-11 18:49 UTC, eladb approved these changes

2020-11-11 18:53 UTC, merged

2020-11-11 19:07 UTC, misterjoshua commented
@eladb It looks like the build broke in master because after a version bump, NodeProject is looking for the not-yet-released projen version in npm during the tests. I could push up a new pr and change the NodeProject references to Project so this isn't so much a factor.

2021-07-31 14:57 UTC, resistdesign commented
Am I allowed to cheer for a PR? 😛  🎉