fix(node-package): components should be able to change deps at preSynthesize stage
projen/projen pull request #2964
Opened 2023-10-06 09:28 UTC by tinovyatkin

Fixes #

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-06 10:07 UTC, mrgrain commented on test/javascript/node-package.test.ts
> +
Is this test change dictated by the fix? If so, I don't understand why the ordering matters here.
If not: Thanks for cleaning up! :D

2023-10-06 10:10 UTC, tinovyatkin commented on test/javascript/node-package.test.ts
> +
Yes. This test was assuming the NodePackage will read pre-existing package.json in the `preSynthesize` so it was creating _pre-existing package.json_ after creating the component itself. We just re-arrange here to create that file before the component (as it would happen in the real life)

2023-10-06 10:10 UTC, mrgrain requested changes
Oh nice, thanks for diving into this! I'm a bit surprised this isn't blowing anything up 🙈 

But I'm happy to merge it, if you mark this as a breaking change, and include some sort of guidance on how the original behavior could be replicated if needed.

2023-10-06 11:03 UTC, mrgrain commented on src/javascript/node-package.ts
> +    if (!this._prev) {
This is the breaking change and the required test change proof this.
And now that I'm thinking more about this, why did you get rid if the re-reading of package.json if the main goal was to move stuff to from `preSynthesize` to `synthesize`?

Projects are constructed first, components are usually constructed later. This applies to automatic components that the project creates, but also custom components added later in the rc file. Before your change, a component could manipulate `package.json` directly and any changes would be merged in. This not possible anymore.

2023-10-06 11:27 UTC, mrgrain commented
The other breaking changes would be down to the fact that previously all various steps performed by `renderDependencies()` would have been guaranteed to be completed by the time we hit `synthesize()` in a component. This order is not guaranteed anymore, even though `NodePackage` is likely to be one of the earlier components. 

Now the steps that are done in `renderDependencies` are quite obscure, so I'm happy to break that guarantee. As far as I can tell we'd loose the guarantee that the following has happened before `synthesize()`:
- Adding a devDep for every peerDep, including the semver check
- Resolving `file:` deps with the actual package name

Currently, these are only exposed via the deprecated `manifest` property. So again, happy to break it. But we should mark the version correctly and provide some guidance.

2023-10-06 11:27 UTC, mrgrain commented on src/javascript/node-package.ts
> +    if (!this._prev) {
Can we keep the re-reading of package.json?

2023-10-06 11:51 UTC, tinovyatkin commented on src/javascript/node-package.ts
> +    if (!this._prev) {
"Component can change package.json directly" - do you mean "on the disk"? Because if component would do JsonPatch or addOverride (that means do changes to this file the projen way) - that functionality will stay in touch.

If a component were doing direct changes to the packages.json on the disk, those changes would be respected only in very limited part (literally at dependencies section, as for example `version` field would be read in the constructor) and those changes would be thrown when package.json would be removed at `preSynthesize` (as all generated files). So, do I understand correctly that you want to keep functionality of a theoretical projen components that were ignoring projen way to manage dependencies and were relying on some internal knowledge that projen is reading dependencies versions from `package.json` twice? Is that something we want to keep and name breaking change?

> Can we keep the re-reading of package.json

We can, but it will complicate implementation with no real benefits (see above).

2023-10-06 11:56 UTC, tinovyatkin commented
> Currently, these are only exposed via the deprecated `manifest` property. So again, happy to break it. But we should mark the version correctly and provide some guidance.

I can't agree that changes in edge functionality of private, non-documented methods can be considered a breaking change for `0.x` versioned library, but neither a see a huge topic for discussion here. Could you provide some guidance how to make this "breaking" mark - I assume adding something to the PR title?

2023-10-06 14:21 UTC, mrgrain commented on src/javascript/node-package.ts
> +    if (!this._prev) {
How does it complicate the implemenation?

2023-10-06 14:25 UTC, mrgrain commented
> I can't agree that changes in edge functionality of private, non-documented methods can be considered a breaking change for `0.x` versioned library, but neither I'm seeing a huge topic for discussion here. Could you provide some guidance how to make this "breaking" mark - I assume adding something to the PR title?

And likewise because we are at `0.x.`, to me there's no reason to hold back on new minor version releases.

We usually do it like this:
https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-both--and-breaking-change-footer

Specifically including a section on how the previous behavior can be restored or worked around or why it can't.

2023-10-06 14:43 UTC, tinovyatkin commented
> Specifically including a section on how the previous behavior can be restored or worked around or why it can't.

I'm assuming this will be squashed on merge so I've added `!` to PR title and put a way of restoring "previous behavior" into PR description body. Would that be enough or I should reword the commit message itself?

2023-10-06 14:44 UTC, mrgrain commented
Commits are ignored. The PR title and description are what counts. Thanks for making the change!

2023-10-06 14:47 UTC, mrgrain commented on src/javascript/node-package.ts
> +    if (!this._prev) {
Okay, now I'm with you. Thanks for taking the time to explain!

2023-10-06 14:47 UTC, mrgrain approved these changes

2023-10-06 15:04 UTC, merged

2023-10-11 15:37 UTC, moltar commented
@tinovyatkin Sorry for the offtopic, but:

> (i.e. implementing [BrowsersList](https://github.com/browserslist/browserslist) config)

Are you implementing the BrowsersList? This was on my TODO for a while also. If so, will it be public? Thanks!