feat: Gitlab updated Service definition
projen/projen pull request #2992
Opened 2023-10-13 15:24 UTC by ctasada

Added the missing keywords for Services
* pull_policy: https://docs.gitlab.com/ee/ci/yaml/#servicepull_policy
* variables: Added in Gitlab 14.5 https://docs.gitlab.com/ee/ci/services/index.html#available-settings-for-services

Fixes #

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-13 18:14 UTC, mrgrain commented
Same as the other one, please run the build locally to add any mutations to your PR.

2023-10-15 13:31 UTC, mrgrain approved these changes

2023-10-15 13:32 UTC, mrgrain requested changes

2023-10-15 13:32 UTC, mrgrain commented on src/gitlab/configuration-model.ts
> +  readonly variables?: Record<string, number | string>;
In jsii languages this doesn't work very well. Let's just use a string here
```suggestion
  readonly variables?: Record<string, string>;
```

2023-10-16 07:53 UTC, ctasada commented on src/gitlab/configuration-model.ts
> +  readonly variables?: Record<string, number | string>;
@mrgrain this was copied from the `IncludeRule` section, where this value was already defined. I'm mentioning, because if we have a potential issue here, we may have it there too

2023-10-16 09:40 UTC, mrgrain commented on src/gitlab/configuration-model.ts
> +  readonly variables?: Record<string, number | string>;
Thanks @ctasada Acknowledged. The other definition will be wrong as well. Also confirmed that this indeed should be a string: https://docs.gitlab.com/ee/ci/yaml/#variablesvalue

Can you make the change for you PR and we can fix the other occurrence in a separate PR (would love if you did that, but not worries if not 😅 )

2023-10-16 16:19 UTC, ctasada commented on src/gitlab/configuration-model.ts
> +  readonly variables?: Record<string, number | string>;
@mrgrain Done. Fixed both definitions

2023-10-16 20:33 UTC, mrgrain requested changes

2023-10-16 20:33 UTC, mrgrain commented on src/gitlab/configuration-model.ts
> +  readonly variables?: Record<string, number | string>;
```suggestion
  readonly variables?: Record<string, string>;
```
@ctasada thanks for the fixes! Looks like you've missed one.

2023-10-17 05:05 UTC, ctasada commented on src/gitlab/configuration-model.ts
> +  readonly variables?: Record<string, number | string>;
Good catch @mrgrain I applied the change and rebuild to update the API.md too.

2023-10-17 09:54 UTC, mrgrain approved these changes

2023-10-17 10:11 UTC, merged