Extend-json-patch
projen/projen pull request #2997
Opened 2023-10-14 13:42 UTC by tinovyatkin

Fixes #

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-15 13:47 UTC, mrgrain commented on src/object-file.ts
> +  public patch(...patches: (JsonPatch | JsonPatch[])[]) {
Doesn't work well in jsii languages. Also the nested arrays syntax is confusing.
What is the benefit over multiple `file.patch([])`?

2023-10-15 14:04 UTC, mrgrain commented
I disagree on this one. The JSON Patch RFC is in my opinion quite clear on this topic:

>   If a normative requirement is violated by a JSON Patch document, or
   if an operation is not successful, evaluation of the JSON Patch
   document SHOULD terminate and application of the entire patch
   document SHALL NOT be deemed successful.

https://datatracker.ietf.org/doc/html/rfc6902/#section-5

While it doesn't state it outright, to me this read like validation and not upserting.

But I understand the issue that patch operations are currently getting lost in the implementation because they are flattened into a single array. That's what we should fix.

I imagine calling `.patch()` multiple times as the way to express intent of different operations. Each of the operations should then by applied individually. Users can catch a test failure in userland if they are okay with it:
```ts
// This would synthesize just fine, operation not applied
try {
  file.patch([
    JsonPatch.test("/first/second", undefined),
    JsonPatch.add("/first/second", []),
  ]);
catch {}

// This would throw
file.patch([
  JsonPatch.test("/first/second", undefined),
  JsonPatch.add("/first/second", []),
]);
```

We could potentially make this easier by adding an optional parameter`.patch(patches, throwError = true)` (obviously need a better name) or maybe a second `.patchNotFail()` method.

The reason I'm reluctant to default to silently failing is that I struggle to find a uniform user experience. What should happen when it fails? Silent upsert? Print a warning? Hard fail? I think each of these cases have valid scenarios and drawbacks if a standard handling is introduced. The only way to leave this up to the user is to transparently throw an exception and let them handle it.

--- 

### Syntax 

I also don't really see the benefit of the nested array syntax over multiple calls to `.patch()`

---

> updated version of JsonPatch that uses deepClone on patching operations

Nice 👍🏻 

> exposing isTestOperation method

But why?

> exposing very useful escapePathComponent static method (imported from the same fast-json-patch dependency) to simplify operation on fields containing / and ~ (i.e. scoped dependencies overrides in package.json)

Nice 👍🏻

2023-10-15 16:06 UTC, tinovyatkin commented
> I disagree on this one. The JSON Patch RFC is in my opinion quite clear on this topic:

Not sure I understand where we disagree: the problem of current implementation of `.patch` that it doesn't retain the scope of "operation" as it flattens all calls of `.patch` into a single array. This way any `.test` are getting as "patch a whole" all calls of `.patch` on a given file. That is incorrect and this PR proposes to fix that by adding a feature to call `.patch` with array of patches - in this case all operations of array will be the "patch as whole" for the `.test` operation.

Now, for some reason you are mixing throw behaviour of our dependency with RFC of JsonPatch. It has to relation, `thow` is not part of RFC, it's an implementation details of the internal dependency. So, silently ignoring "test failure" throw (and only that) is perfectly aligned with RFC, because it does exactly what RFC dictates - if test operation fails patch as whole should not be applied. I don't understand where you are seeing a base of confusion here and which other behaviour may be applied here?

```ts
// This would synthesize just fine, operation not applied
try {
  file.patch([
    JsonPatch.test("/first/second", undefined),
    JsonPatch.add("/first/second", []),
  ]);
catch {}
```

This would not work with lazy values and `.patch` and `.addOverrides` are applying after resolve. If you do it differently to make `.test` working it will be way bigger blast radius.

2023-10-17 17:39 UTC, mrgrain commented
Thanks for looking into my suggestion. You're right, I've missed that the operation is only executed during synth phase. My bad. 🤦🏻 

My general concerns about the possible variations of error handling still stand though. Let's see if we can find a different solution. I'd still stick with the principle of `one call of .patch()` = `one atomic operation`. We just need to find a way to make the test fail behavior flexible.

My detour the JSON Patch RFC is in relation to the proposed error handling. I have indeed misinterpreted the references to error handling as prescriptive. Which it is - but just for a different RFC (the one for HTTP PATCH). That's also on me. Guess I shouldn't do reviews on a Sunday evening 😅 . 

At the end of the I am currently relying on the explicit failure behavior, and I think it should be possible to find a solution that allows for all three options: `SILENT`, `WARN` and `FAIL`.

2023-10-18 21:00 UTC, tinovyatkin commented
> I'd still stick with the principle of `one call of .patch()` = `one atomic operation`. 

> At the end of the I am currently relying on the explicit failure behavior, and I think it should be possible to find a solution that allows for all three options: `SILENT`, `WARN` and `FAIL`.

Implemented new approach (see updated PR description) that hopefully follows your suggestions. It seems to be even more scoped implementation while giving almost the same DX.

2023-10-19 10:24 UTC, mrgrain commented on src/json-patch.ts
> +  THROW = "trow",
```suggestion
  THROW = "throw",
```

2023-10-19 10:31 UTC, mrgrain requested changes
Almost!

2023-10-19 10:31 UTC, mrgrain commented on src/json-patch.ts
> +    }
Can we the failure handling into ObjectFile? I'd much prefer to use `project.logger()` but that won't be available here. It also avoids the `TEST_FAILURE_BEHAVIOR_SYMBOL` and keeps `JsonPatch` a thin wrapper around the library.

2023-10-19 10:33 UTC, mrgrain commented on src/json-patch.ts
> +  public static escapePathComponent(path: string): string {
This feels a bit less like leaking the underlying implementation through.

```suggestion
  public static escapePath(path: string): string {
```

2023-10-19 10:33 UTC, tinovyatkin commented on src/json-patch.ts
> +    }
Not sure I understand how that avoids the symbol? Do you mean we should somehow extend `ObjectFile.patch` method to add failure behavior there rather to `JsonPatch.test` static method?

2023-10-19 10:38 UTC, tinovyatkin commented on src/json-patch.ts
> +    }
Just to clarify my position here: `JsonPatch` class is our wrapping class that is only used at `ObjectFile.patch` method. Not every JsonPatch implementation library would throw on test failure (we already discussed that is implementation detail of `fast-json-patch`). So I'm seeing pretty logical that we are handling that details in the class that wraps that dependency.

As we already agreed, JsonPatch.test has nothing to do with throw, so it would be looking weird at `ObjectFile.patch`

2023-10-19 10:42 UTC, tinovyatkin commented on src/json-patch.ts
> +    }
An example of implementation of JsonPatch that is not throwing on test failure: https://www.npmjs.com/package/@typewriter/json-patch#test-failed

2023-10-19 10:58 UTC, mrgrain commented on src/json-patch.ts
> +    }
> Just to clarify my position here: JsonPatch class is our wrapping class that is only used at ObjectFile.patch method. Not every JsonPatch implementation library would throw on test failure (we already discussed that is implementation detail of fast-json-patch). So I'm seeing pretty logical that we are handling that details in the class that wraps that dependency.

I guess this is where our disagreement is: I like how `fast-json-patch` handles test failures. Because it is the _only_ way users can make an informed decision how to handle test failures themselves, by catching the error and reacting accordingly.

`JsonPatch` is only a class because that's the best way to implement free-floating top level functions in jsii. It's public interface only has static methods. It makes sense to keep the code there from an code structure perspective, from a user perspective I argue it doesn't matter precisely because JsonPatch is a wrapping class that is only used in ObjectFile.patch(). The problem is that now the wrapper class suddenly needs awareness of the project to log a warning.


>Not sure I understand how that avoids the symbol?

Sorry I brought this up. It's an implementation detail and not relevant to the wider point.

2023-10-19 11:09 UTC, mrgrain commented on src/json-patch.ts
> +    }
Attempt to rephrase my position: I consider `JsonPatch` a low-level implementation of the standard and thus should be flexible to support different use cases.

`ObjectFile.patch()` is our high-level abstraction (that merely uses the low-level implementation) and this is were we should focus the UX at. Including making the skip behavior the default, which I'm fully on-board with.

2023-10-19 12:18 UTC, tinovyatkin commented on src/json-patch.ts
> +    }
@mrgrain I'm struggling to invent a good DX for extending `ObjectFile.patch` or maybe misunderstanding your idea. Could you provide the method shape as you envisioning it?

2023-10-19 13:34 UTC, mrgrain commented on src/json-patch.ts
> +    }
How about this?
https://github.com/projen/projen/pull/2997/commits/546c3c7d9c507a687b4a741ef92448ddb9fb321a

2023-10-19 14:19 UTC, tinovyatkin commented on src/json-patch.ts
> +    }
Added documentation doesn't even mentioning the `log` option (and I agree it's pretty much useless). I may propose either to remove `log` option or changing the `JsonPatch.apply` method signature to allow pass logger there. What do you think? Moving the whole `try/catch` into `ObjectFile.synthesizeContent` will be a way more weird solution as we will need to pass symbol and we will not be able to pass custom error class from `fast-json-patch`, etc.

2023-10-19 14:22 UTC, tinovyatkin commented on src/object-file.ts
> +import { JsonPatchError } from "fast-json-patch";
This is bad practice codewise - we have our internal wrapper for `fast-json-patch` and here we are using extra knowledge of internal implementation of `JsonPatch` class to handle it's errors

2023-10-19 14:24 UTC, tinovyatkin commented on src/object-file.ts
> +        switch (currentOp?._failureBehavior) {
This is violating bunch of OOP principals and bad practice code-wise - we are basically accessing one internal class properties from another place just because we know implementations details. This creates very bad "invisible" coupling between two classes.

2023-10-19 14:43 UTC, mrgrain commented on src/object-file.ts
> +import { JsonPatchError } from "fast-json-patch";
I agree, though we are already exposing the `fast-json-patch` exception anyway. Are you proposing we wrap all exceptions in a custom exceptions class (that either does the same thing, or takes information away from the user).

2023-10-19 14:45 UTC, mrgrain commented on src/object-file.ts
> +        switch (currentOp?._failureBehavior) {
Yep, you caught me. :P We need a `JsonPatchTestOperation` and I was too lazy to do it.

Saying that, the current `JsonPatch` class already is as far away from proper OOP as something can be.

2023-10-19 14:48 UTC, mrgrain commented on src/json-patch.ts
> +    }
> Added documentation doesn't even mentioning the log option

It does, I just renamed it to `WARN`.

> I may propose either to remove log option 

Yeah, I think I'm okay with that.

2023-10-19 14:59 UTC, tinovyatkin commented on src/json-patch.ts
> +    }
So, removing the `warn` we can rollback to have everything inside `JsonPatch` class and not spill around the implementation details, right?

2023-10-19 15:01 UTC, tinovyatkin commented on src/object-file.ts
> +import { JsonPatchError } from "fast-json-patch";
No, I proposed above to remove `warn` option and keep error handling inside the `JsonPatch` class.

2023-10-20 14:51 UTC, mrgrain approved these changes

2023-10-20 15:10 UTC, merged