Allow-set
projen/projen pull request #3016
Opened 2023-10-22 14:19 UTC by tinovyatkin

Fixes #

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-30 12:11 UTC, mrgrain requested changes

2023-10-30 12:11 UTC, mrgrain commented on src/_resolve.ts
> +      return value.source;
I think this is making to many assumptions. Specifically it is a different implementation then [RegExp.prototype.toString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/toString).

Happy to accept an implementation using `toString` instead. But also it seems okay to me to expect a user to call `toString()` themselves. For the Set & Map the conversion is less straightforward, so I agree the benefits outweigh the ambiguity.

2023-10-30 13:44 UTC, mrgrain commented on src/_resolve.ts
> +      return value.source;
Yes, hence my reluctance. In ESLint and Jest these are just strings that happen to be used as a RegExp. 
`/^tada$/.source` is equally easy to write.

2023-10-30 13:49 UTC, tinovyatkin commented on src/_resolve.ts
> +      return value.source;
`/^tada$/` seems to be even easier to write. But right now just throws with very very cryptic error message. I can keep that behaviour as is if you believe that is better DX than I'm proposing in this PR.

2023-10-30 16:14 UTC, mrgrain commented on src/_resolve.ts
> +      return value.source;
🤦🏻 Of course. Can we throw with a better error in that case?

2023-11-05 17:03 UTC, mrgrain approved these changes
Sorry this took so long. Approved and should be good to ship once the conflict is resolved.

2023-11-05 17:52 UTC, merged