feat: add Yarnrc component for YARN_BERRY
projen/projen pull request #3048
Opened 2023-10-27 22:26 UTC by blimmer

Relates to #2980 

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-27 22:31 UTC, blimmer reviewed
@mrgrain - I had some time today to work on this. Could you take a look at the inline questions on this draft PR review? Once I get confirmation on how you'd like to proceed, I can finish this up and get it ready for review.

TYIA!

2023-10-27 22:31 UTC, blimmer commented on docs/node.md
> +See [Yarn's installation documentation](https://yarnpkg.com/getting-started/install) for more information.
Per your thread(s) in #2980 , it felt like this is an OK assumption to make.

2023-10-27 22:31 UTC, blimmer commented on src/javascript/node-package.ts
> +      // - Do we duplicate the logic, and set the relevant options here, too? (e.g., if this.npmRegistryUrl is set, set the relevant yarnrc option)
@mrgrain - curious to hear your thoughts on this question.

2023-10-27 22:31 UTC, blimmer commented on src/javascript/node-package.ts
>    readonly devDependencies: Record<string, string>;
Please expand the file below, it's the main thing this PR adds.

2023-10-27 22:31 UTC, blimmer commented on src/javascript/yarnrc.ts
> +export enum YarnChecksumBehaviorV3 {
There's a new checksum behavior (`RESET`) that exists in V4, so I have two separate enums. Thoughts?

2023-10-27 22:31 UTC, blimmer commented on src/javascript/yarnrc.ts
> +export interface YarnNetworkSettingV3 {
Ditto here - anything that's suffixed `V3` is `V3` specific.

2023-10-27 22:31 UTC, blimmer commented on src/javascript/yarnrc.ts
> +export interface YarnrcOptionsV3 {
Some options were added/removed in V4, so I have two separate interfaces.

2023-10-27 22:31 UTC, blimmer commented on src/javascript/yarnrc.ts
> +  /** https://v3.yarnpkg.com/configuration/yarnrc#cacheFolder */
Copilot and ChatGPT helped me quite a bit in producing these, but a lot of the work was still manual. I was kinda lazy and just linked to the upstream docs instead of trying to script pulling the description in.

2023-10-27 22:31 UTC, blimmer commented on src/javascript/yarnrc.ts
> +export interface YarnrcOptionsV4 {
This one's V4-specific. I can also just call this `YarnrcOptions` without the `V4` if that makes more sense.

2023-10-28 16:46 UTC, blimmer commented on src/javascript/node-package.ts
> +      version = "4.0.1",
`corepack` requires a fully qualified version for the `packageManager` property. If you provide values like `yarn@4`, `yarn@stable`, `yarn@~4`, etc. you get this error:

```
Usage Error: Invalid package manager specification in package.json; expected a semver version

$ yarn ...
```

So, unfortunately, we have to specify a full version here.

2023-10-28 16:46 UTC, blimmer commented on src/javascript/node-package.ts
> +  private checkForConflictingYarnOptions(
I figured this was OK to start off: https://github.com/projen/projen/pull/3048#discussion_r1375096442

2023-10-30 14:49 UTC, mrgrain commented on src/javascript/node-package.ts
> +      version = "4.0.1",
Ugh. That's annoying. How about we make the version required?

2023-10-30 15:02 UTC, mrgrain commented on src/javascript/node-package.ts
> +  readonly yarnRcOptions?: YarnrcOptionsV3 | YarnrcOptionsV4;
```suggestion
  readonly yarnRcOptions?: YarnrcOptions;
```
This should be an enum like class:

```ts
YarnrcOptions.v3(options: YarnrcOptionsV3);
YarnrcOptions.v4(options: YarnrcOptionsV4);
```

Alternatively we can forgo the strict typing here, have a single `YarnrcOptions` interface and validate differently in the `v3` / `v4` static methods.

2023-10-30 15:03 UTC, mrgrain commented on src/javascript/node-package.ts
> +  readonly yarnRcOptions?: YarnrcOptionsV3 | YarnrcOptionsV4;
Or maybe it's even just the same interface and we validate it based on the version that is set. Differences between v3/v4 can be documented.

2023-10-30 15:30 UTC, mrgrain requested changes
Good stuff! Obviously we should automated the options, but we don't have infrastructure for this. 🤷🏻

2023-10-30 19:25 UTC, blimmer commented on src/javascript/node-package.ts
> +      version = "4.0.1",
How would that work if people didn't provide `yarnBerryOptions` at all? e.g.,

```ts
const project = new javascript.NodeProject({
  // ...
  packageManager: javascript.NodePackageManager.YARN_BERRY,
});
```

Would we throw a runtime error?

2023-10-30 20:35 UTC, blimmer commented on src/javascript/node-package.ts
> +  readonly yarnRcOptions?: YarnrcOptionsV3 | YarnrcOptionsV4;
I went ahead and used the same interface. I marked removed options with a `@deprecated` JSDoc annotation and added validation logic to warn users about invalid config usage.

2023-10-31 12:10 UTC, mrgrain commented on src/javascript/node-package.ts
> +      version = "4.0.1",
Yeah that's annoying. I think we might be able to turn `javascript.NodePackageManager` into an enum like class. With static props for the existing values and `YARN_BERRY()` a static method that requires a version?

Which feels like what we would really need to do for all corepack package managers?! So we'd end up having an interface like this:

```ts
const project = new javascript.NodeProject({
  // Corpack
  packageManager: javascript.CorePack.yarn('1.23.1'),
  packageManager: javascript.CorePack.yarn('4.0.1'),
  packageManager: javascript.CorePack.pnpm('8.0.0'),
  packageManager: javascript.CorePack.npm('100.0'),

 // pre-installed 
  packageManager: javascript.NodePackageManager.NPM,
  packageManager: javascript.NodePackageManager.PNPM,
  packageManager: javascript.NodePackageManager.YARN_CLASSIC,
  packageManager: javascript.NodePackageManager.YARN_BERRY,
});
```
The pre-installed ones maybe just all need to be deprecated right away? Or at least for `YARN_BERRY` which recommends corepack.

But let's do this separately. Happy to keep the default version for now.

2023-10-31 14:46 UTC, blimmer commented on src/javascript/node-package.ts
> +      version = "4.0.1",
Sounds good - I filed https://github.com/projen/projen/issues/3070 to track that. FYI, `npm` is the only one that cannot be managed by `corepack` (lol). If we're cool leaving the default version for now, this is ready for review & merge.

2023-11-01 00:09 UTC, mrgrain commented on src/javascript/node-package.ts
> +      version = "4.0.1",
Yep. I'll give it a final review tomorrow.

2023-11-01 22:00 UTC, blimmer commented
Btw, although this isn't directly related, we might be getting some nice Corepack reliability improvements in berry: https://github.com/yarnpkg/berry/issues/5912

2023-11-05 17:06 UTC, mrgrain approved these changes

2023-11-06 01:45 UTC, merged