docs: fix typos
projen/projen pull request #3053
Opened 2023-10-28 16:03 UTC by Mayureshd-18

Fixes #

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-28 20:02 UTC, mrgrain requested changes

2023-10-28 20:02 UTC, mrgrain commented on license-text/EUPL-1.2.txt
>                        EUROPEAN UNION PUBLIC LICENCE v. 1.2
This is s license text and we cannot change how the license creator chooses to spell license (which is BE and absolutely correct in this context)

2023-10-28 20:03 UTC, mrgrain requested changes
Appreciate this very much! Just revert the changes to the license text please.

2023-10-29 05:54 UTC, Mayureshd-18 commented
@mrgrain Done. Please review.
Regards

2023-10-29 16:46 UTC, mrgrain approved these changes

2023-10-29 17:06 UTC, merged