increase default cdk version
projen/projen pull request #306
Opened 2020-11-13 10:57 UTC by henrysachs

I increased the cdk version to match the yesterday released one and also replaced the deprecated function call from `addPeerDependencies`. Just some cleanups that help me in my custom Projen module.

2020-11-13 11:53 UTC, henrysachs commented
if its fine for all i maybe take a look at other deprecated functions and try to convert them.

2020-11-13 12:33 UTC, henrysachs commented
i now went through all files and replaced deprecated methods without breaking compatibility. That's why i added string to the Type aswell as Semver.

2020-11-13 12:42 UTC, henrysachs commented
The License File Test seems to be a bit flaky isn't it? it seems to sometimes fail and sometimes pass. 🤔

2020-11-13 15:21 UTC, eladb requested changes
Generally with the  new "deps" options you don't really need a version specifier

2020-11-13 15:21 UTC, eladb commented on src/cdk8s-construct.ts
> +      'constructs@^2.0.2',
Let's also bump cdk8s to the latest version and I believe it now uses the same constructs major version as the CDK.

2020-11-13 15:21 UTC, eladb commented on src/jsii-docgen.ts
> +    project.addDevDeps('jsii-docgen@^1.3.2');
I don't think a version is needed here. Just omit the version

2020-11-13 15:21 UTC, eladb commented on src/jsii-project.ts
> +      `jsii@^${jsiiVersion}`,
I think we can completely omit jsii version.

2020-11-13 15:21 UTC, eladb commented on src/typescript-typedoc.ts
> +    project.addDevDeps('typedoc@^0.17.8');
Omit version

2020-11-13 15:21 UTC, eladb commented on src/typescript.ts
> +  readonly typescriptVersion?: string | Semver;
Unions are Not recommended in jsii

2020-11-13 17:13 UTC, henrysachs commented
will now pick up the requested changed

2020-11-13 19:47 UTC, henrysachs commented on src/typescript.ts
> +  readonly typescriptVersion?: string | Semver;
i now moved everything to string but wouldn't that create a breaking change for everyone using this property?

2020-11-13 19:48 UTC, henrysachs commented on src/jsii-project.ts
> +      `jsii@^${jsiiVersion}`,
I'll omitted the version but kept the parameter, if a user want to set it to their own fixed version.

2020-11-13 20:06 UTC, henrysachs commented
i now removed jsii version as a parameter completly and therefore omitted the version

2020-11-16 09:02 UTC, eladb commented on src/jsii-project.ts
> +      `@types/node@^${minNodeVersion}`,
I suspect this is already covered by `TypeScriptProject` and therefore not required here anymore

2020-11-16 09:02 UTC, eladb commented on src/node-project.ts
> +      this.addDevDeps( `projen@${projenVersion}` );
```suggestion
      this.addDevDeps(`projen@${projenVersion}`);
```

2020-11-17 19:10 UTC, henrysachs commented
removed the min node version from jsii

2020-11-18 06:20 UTC, eladb approved these changes

2020-11-18 06:24 UTC, merged