Updated the name of Twitter to X
projen/projen pull request #3066
Opened 2023-10-30 18:09 UTC by tvermaashutosh

Fixes #3065 

Everyone must be well aware by now that the legal name of Twitter has been formally changed to X.
In this PR I have updated the name of Twitter to X in all the documentation (Texts and Links) of this repo.
Closes: https://github.com/reworkd/AgentGPT/issues/1345

@mrgrain 
Kindly review my PR and merge it please.
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-30 18:11 UTC, mrgrain commented
The contributor profiles are auto generated. We can't change them

2023-10-30 18:14 UTC, mrgrain requested changes

2023-10-30 18:14 UTC, mrgrain commented on src/cdk/construct-lib.ts
> +   * X account to @mention in announcement tweet.
Can you add something like (previously Twitter) to explain the difference in docs and property.

2023-10-30 18:14 UTC, mrgrain commented on src/cdk/construct-lib.ts
> +   * You can also add a X handle through `{ X: 'xx' }` which will be
```suggestion
   * You can also add a X handle through `{ twitter: 'xx' }` which will be
```
This is an external API the can't changed unilaterally from here.

2023-10-30 18:14 UTC, mrgrain commented on src/cdk/construct-lib.ts
> +   * The catalog will also post a tweet to https://x.com/awscdkio with the
```suggestion
   * The catalog will also post to https://x.com/awscdkio with the
```

2023-10-30 18:16 UTC, tvermaashutosh commented on src/cdk/construct-lib.ts
> +   * The catalog will also post a tweet to https://x.com/awscdkio with the
Just wait a minute. I'm making the required changes.

2023-10-30 18:20 UTC, tvermaashutosh commented
@mrgrain 
I have made all the requested changes in the PR.
Kindly review it now and merge it please.

2023-10-30 18:22 UTC, mrgrain requested changes

2023-10-30 18:22 UTC, mrgrain commented on README.md
> -      <td align="center" valign="top" width="14.28%"><a href="http://twitter.com/bracki"><img src="https://avatars.githubusercontent.com/u/49786?v=4?s=100" width="100px;" alt="Jan Brauer"/><br /><sub
Needs reverting

2023-10-30 18:22 UTC, mrgrain commented on docs/api/API.md
> +**X**?🔹 | <code>string</code> | X account to.<br/>__*Optional*__
This file shouldn't be changed manually, instead run the build. If you have to, see the build for the proper change.

2023-10-30 18:23 UTC, mrgrain requested changes
Some more stuff. Also the PR title needs fixing.

2023-10-30 18:28 UTC, tvermaashutosh commented
@mrgrain
I have made all the requested changes in the PR.
Kindly review it now and merge it please.

2023-10-30 19:10 UTC, mrgrain commented
Build is still failing.

2023-11-02 11:32 UTC, mrgrain commented
@tvermaashutosh Are you still interested in finishing this change?

2023-11-05 17:02 UTC, closed without merging