fix(typescript): bump @types/node version to 18
projen/projen pull request #3076
Opened 2023-11-01 08:32 UTC by matt9ucci

Node.js 16 reached EOL on September 11th, 2023.
https://nodejs.org/en/blog/announcements/nodejs16-eol
https://nodejs.org/en/about/previous-releases

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-11-01 11:00 UTC, mrgrain commented
Thanks for that @matt9ucci ! Is it just the `@types/node` or are we still defaulting to 16 in other places?

2023-11-01 12:56 UTC, matt9ucci commented
Thank you for the comment @mrgrain! It is just the `@types/node`.

It seems that the legacy JSII (1.X) is not compatible with `@types/node` v18. Some test cases [failed to compile it](https://github.com/projen/projen/actions/runs/6717467045/job/18255368027?pr=3076#step:5:721).
Therefore, I added [the lines](https://github.com/projen/projen/pull/3076/files#diff-c5619f357a419a8975c6a32de334c4348d90397ad0102eacd5c5a27300c49015R428-R432) which keep v16 for legacy JSII projects.

2023-11-05 17:01 UTC, mrgrain commented on src/cdk/jsii-project.ts
> +      );
Can you make this conditional? Only do this if we are on 1.x
```suggestion
      if ((options.jsiiVersion ?? "1.x").startsWith('1.x')) {
        this.addDevDeps(
          // https://github.com/projen/projen/pull/3076
          `@types/node@^${major(this.package.minNodeVersion ?? "16.0.0")}`
        );
      }
```

2023-11-05 17:02 UTC, mrgrain requested changes
See suggestion

2023-11-06 14:56 UTC, matt9ucci commented on src/cdk/jsii-project.ts
> +      );
Fixed.

2023-11-06 15:43 UTC, mrgrain approved these changes

2023-11-06 15:44 UTC, mrgrain approved these changes

2023-11-06 16:02 UTC, merged