feat(upgrade): Update pytest
projen/projen pull request #3084
Opened 2023-11-03 19:47 UTC by scottschreckengaust

The default version was failing with the default:
`npx projen new awscdk-app-py`

```
from projen.awscdk import AwsCdkPythonApp

project = AwsCdkPythonApp(
    author_email="user@example.com",
    author_name="Example User",
    cdk_version="2.1.0",
    module_name="module-name",
    name="name",
    version="0.1.0",
    pytest_options={"version": "7.4.3"},
)

project.synth()
```

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-11-06 10:18 UTC, mrgrain requested changes

2023-11-06 10:18 UTC, mrgrain commented on src/python/pytest.ts
> +   * @default "7.4.3"
This will need to change in line 32 as well

2023-11-07 00:43 UTC, scottschreckengaust commented on src/python/pytest.ts
> +   * @default "7.4.3"
Added the snapshots too

2023-11-07 10:39 UTC, mrgrain approved these changes

2023-11-07 10:51 UTC, merged