fix(util): use PATHEXT to check if file is executable on Windows
projen/projen pull request #3107
Opened 2023-11-10 23:13 UTC by gmeligio

## Motivation

1. NodeProject => package.json
1. package manager installation
1. other files executable consequences

## Changes

1. OsInspector . How to handle OS changes
1. util changes 

## Test

no change in D:\my-projen-project\package.json

logging: {
    level: LogLevel.DEBUG,
  },

## Questions

1. Does it need unit test?
1. How to handle OS information in a generic way?

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-11-14 10:05 UTC, mrgrain commented
This is awesome, thank you! I'll need a bit of time to review it.

I do wonder if we just want to bypass the check on windows though (maybe warn?)?
Because in the current implementation, you can set any file to being executable - however on windows it would need to be the correct file ending. So `new File('foobar.js', { executable: true })` would have no effect and probably still cause the change condition to trigger.

2023-11-16 17:40 UTC, gmeligio commented
Thank you for the explanation. Bypassing the `executable` check will work indeed. I guess that change will be somewhere around here 
https://github.com/projen/projen/blob/34edf99eaa7884cc279e946c56da8e322e6dc839/src/file.ts#L158-L171

Because Windows doesn't save the attribute on the file, but on the current installation, another option could be to use `git` to keep the file attributes. This variant will be cross-platform but I haven't used it before. Please take a look at the image below.

<img width="437" alt="image" src="https://github.com/projen/projen/assets/22875166/7bdb0b68-63be-40de-964f-7944588da407">

Indeed, bypassing the executable attribute is easier than refactoring the attribute checking to git. Please let me know what you think, and I can turn the PR in the bypass direction if you agree.

2023-11-27 13:17 UTC, mrgrain commented
Apologies for the late response, I was on annual leave. Let's bypass this by introducing a new helper function:
```ts
function assertExecutablePermissions(filePath: string, shouldBeExecutable: boolean): boolean; 
```
that clearly states in it's doc string that it always returns true on Windows.

2023-11-28 14:12 UTC, gmeligio commented
No worries. Sounds great! Thank you for the idea. I'll do that during this or next week.

2023-12-10 14:55 UTC, gmeligio commented
I added an implementation to bypass. Please, @mrgrain, take a look when you have time to see if it matches your proposal.

I modified your proposed signature
```ts
function assertExecutablePermissions(filePath: string, shouldBeExecutable: boolean): boolean; 
```
with 
```ts
function assertExecutablePermissions(shouldBeExecutable: boolean): boolean; 
```
Because when implementing, I didn't see the need for `filePath`. If it's in a `new File('foobar.js', { executable: true })`, the path may not exist, and I think it should not be checked. If it's in `isExecutable`, the path was already checked in that function and doesn't need to be passed to `assertExecutablePermissions`. So, I removed the `filePath` parameter at the end.

Please let me know if my interpretation needs to be corrected. I appreciate it very much.

2023-12-18 10:58 UTC, mrgrain requested changes
Made an inline comment, basically I'd like us to keep `this.executable` as is and only change the check inside `synthesize`. On Unix system, the check should stay as it is. On Windows we cannot reliably check, so the check needs to always pass.

2023-12-27 23:04 UTC, gmeligio commented on src/file.ts
> +    this.executable = assertExecutablePermissions(options.executable);
Makes sense. Initially, I was overriding the user intention to make sure the state had also the bypass. You're right this would be a breaking change for existing projects that use `file.executable`.

I reverted back to the previous code.

2023-12-27 23:10 UTC, gmeligio commented
Thank you for the review. I fixed the bypass to be only on `synthesize`. Now I see why the `filePath` parameter is needed in the `assertExecutablePermissions` function.

2023-12-29 16:30 UTC, mrgrain approved these changes
Perfect thank you!

2023-12-29 16:42 UTC, merged