feat: bump minNodeVersion to 18.14.0
projen/projen pull request #3148
Opened 2023-12-01 00:01 UTC by vinayak-kukreja

# BREAKING CHANGE
Since Node16 has been EOL for a bit, we can now switch to Node18.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-12-01 10:27 UTC, mrgrain requested changes

2023-12-04 17:46 UTC, vinayak-kukreja commented
Hey @tinovyatkin , could you tell me more about what issues CDK projects are facing with node upgrade with lambda runtime upgrade?

Node16 is EOL and we should be moving to Node18. I see JSII has also moved to it: https://github.com/aws/jsii/releases/tag/v1.92.0. Is there any blocker for you with this upgrade?

2023-12-18 13:52 UTC, tinovyatkin commented
@vinayak-kukreja The JSII PR you linked is perfectly fine from my point of view as it adds warnings of not being tested on that platform but keeps minimum Node version the same.

The change in this CR without changing any code or dependency just prevent `projen` from being installed on Node 16 without any benefits for the customers.

Regarding Node version upgrade in CDK project I meant that before Node 18 Lambda runtime were included `aws-sdk` v2 and many lambdas are using that. Now 18.x includes aws-sdk v3 and, while it's great change, to migrate a significant amount of lambdas from `aws-sdk v2` to `aws-sdk v3` some developers bandwidth needed to allocated and testing performed. Not every team has that immediately available and it's not a change you may just do with "closed eyes". So, in some our teams we have to postpone 18.x migration for lambda (and whole project, as we are unit-testing our lambdas on the project' version of Node) until we have a bandwidth for AWS SDK version upgrade also.

2023-12-18 14:53 UTC, mrgrain commented
jsii explicitly doesn't support & test EOL versions of node. The warning is a nice touch though. 
The next version of `jsii-compiler` (which will be `5.3`) will also change the minNodeVersion to 18.

> i believe many projects obusing this field (minimum! Node version) for sake of nothing. 

The sake is that it is a way to indicate which node versions a project is actively tested with. I agree that this skews heavily towards one side of scale on how you can use this field. But to quote the official npm docs: 

"You can specify the version of node that your stuff works on:"
https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines

Once we stop testing with an older version of node, we _just don't know anymore_ if iur stuff is working with it.

---

It is important to note that this field is advisory only in npm:

> Unless the user has set the [engine-strict config](https://docs.npmjs.com/cli/v10/using-npm/config#engine-strict) flag, this field is advisory only and will only produce warnings when your package is installed as a dependency.

Yarn classic swaps the default to enforcing `engines`, but you can easily disable it: `yarn install --ignore-engines`


--- 


Now, I don't have a particular rush to get of Node 16 and would be happy to leave this for a bit. GitHub Actions will probably the thing that forces us to move on at some point in the near future: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

2023-12-18 21:59 UTC, tinovyatkin commented
> Now, I don't have a particular rush to get off Node 16 and would be happy to leave this for a bit.

That's my whole point - if projen is not pushed by any dependency or code feature - what is the rush to disable Node 16? Any benefits for customers from merging this PR?

2024-03-01 02:57 UTC, garysassano commented
Node 16 reached EOL. Also GitHub urged devs to just [move to Node20 directly](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).

2024-03-01 02:57 UTC, garysassano commented
Node 16 reached EOL. Also GitHub urged devs to just [move to Node 20 directly](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).

2024-11-13 13:50 UTC, closed without merging