feat(gitlab): add gitlab multiple cache support
projen/projen pull request #3151
Opened 2023-12-02 14:08 UTC by alejandrolorefice

### Description of changes

In this PR I'm adding support for Gitlab multiple cache definition with a maximum of 4 as described in [their docs](https://docs.gitlab.com/ee/ci/caching/).

#### Fixes

Fixes #3022 

BREAKING CHANGE: current cache definitions will need to be changed into an array or will get a compile time exception.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-12-05 20:42 UTC, mrgrain commented
Change looks okay. I'll need to check how this ends up in jsii languages. But I'm on holiday, so it will have to wait until next week. (Unless you want to do that!)

If it doesn't come out with a reasonable type for them, will can make it an array and add some runtime validation.

2023-12-11 07:31 UTC, alejandrolorefice commented
> Change looks okay. I'll need to check how this ends up in jsii languages. But I'm on holiday, so it will have to wait until next week. (Unless you want to do that!)
> 
> If it doesn't come out with a reasonable type for them, will can make it an array and add some runtime validation.

I've checked and jsii doesn't like tuples. I'm switching to an array with runtime validation.

2023-12-14 21:57 UTC, alejandrolorefice commented
WDYT about this implementation? @mrgrain

2023-12-15 16:01 UTC, mrgrain commented on src/gitlab/configuration-model.ts
> +  /* A list of cache definitions (máx. 4) with the files and directories to cache between jobs. You can only use paths that are in the local working copy. */
```suggestion
  /* A list of cache definitions (max. 4) with the files and directories to cache between jobs. You can only use paths that are in the local working copy. */
```

2023-12-15 16:01 UTC, mrgrain commented on src/gitlab/configuration-model.ts
> +  /* A list of cache definitions (máx. 4) with the files and directories to cache between jobs. You can only use paths that are in the local working copy. */
```suggestion
  /* A list of cache definitions (max. 4) with the files and directories to cache between jobs. You can only use paths that are in the local working copy. */
```

2023-12-15 16:49 UTC, mrgrain requested changes
Nice, just one design change

2023-12-15 16:49 UTC, mrgrain commented on src/gitlab/configuration.ts
> +  public defaultCache?: Cache[];
What we normally do here is turn the property into a private, mutable one and then expose it via a getter.
```suggestion
  private _defaultCache?: Cache[];
  
  public get defaultCache: Cache[] | undefined {
    return this._defaultCache;
  }
```

2023-12-15 16:52 UTC, mrgrain commented on src/gitlab/configuration.ts
> +      throw new Error(`${this.name}: GitLab CI defines more than 4 caches.`);
```suggestion
      throw new Error(`${this.name}: GitLab CI can only define up to 4 caches, got: ${caches.length}`);
```

2023-12-18 10:26 UTC, mrgrain approved these changes
Thank you!

2023-12-18 10:39 UTC, merged