feat: add VSCode debugger setup to AwsCdkTypeScriptApp
projen/projen pull request #316
Opened 2020-11-18 17:20 UTC by tlakomy

Fixes #314

2020-11-18 17:46 UTC, hoegertn commented
Two proposals from my side. 1) Hide vscode settings behind a separate construct 2) add it to construct library too

2020-11-18 18:04 UTC, henrysachs commented
But wouldn't a special file type fit better so you could write a debugger config for each type of project?

2020-11-18 18:05 UTC, henrysachs commented
Or is construct === filetype?

2020-11-18 18:07 UTC, hoegertn commented
That is the same I think. I mean a class representing debugger configs

2020-11-18 18:33 UTC, eladb commented
Yes, this will likely be a bit more involved, but it will make the world a better place!

Let's create a `VsCode` class (extends `Component`) which has a method `addLaunchConfiguration()` which accepts a `LaunchConfiguration` struct that models the schema.

Then, we should probably add a `vscode` component to `NodeProject` so one can do `nodeProject.vscode.addLaunchConfiguration(...)`.

Then, we can create another component that represents `VsCodeCdkDebugger`. It should accept a `NodeProject` and then adds this launch configuration to it.

Then, we need to 

It should have a method like this:

```ts
launch.addConfiguration(...);
```

2020-11-18 19:33 UTC, henrysachs commented
Just a question here. Why would we extend component and not jsonfile?

2020-11-18 19:39 UTC, hoegertn commented
The VsCode class would HAVE a JsonFile and not BE one for two reasons.

1) Composition over inheritance
2) it might need to have other components later on like a second json file, or the proposed vscode extension file #315

2020-11-18 19:43 UTC, henrysachs commented
sounds great! and a Component can decide itself what types of files it generates?

2020-11-18 19:47 UTC, henrysachs commented
maybe i just wait for this PR to be merged and add the extension file afterwards :)

2020-11-18 23:11 UTC, eladb commented
https://github.com/projen/projen/issues/318

2020-11-18 23:12 UTC, eladb commented
Some ideas on how to codify these implicit assumptions: https://github.com/projen/projen/issues/318

2020-11-24 12:13 UTC, eladb commented
Please rebase (#319) and add this to the `VsCode` class (see how to `GitHub` stuff is organized as a reference).

2020-11-29 12:04 UTC, tlakomy commented
@eladb apologies for not getting back to you earlier, please take a look at my recent changes

2020-11-29 12:21 UTC, eladb requested changes

2020-11-29 12:21 UTC, eladb commented on src/vscode/launchConfiguration.ts
> +import { FileBase } from '../file';
nit: rename to `launch-config.ts`

2020-11-29 12:21 UTC, eladb commented on src/vscode/launchConfiguration.ts
> +export class VSCodeLaunchConfiguration extends FileBase {
I think the component should model the launch file and have an `addConfiguration()` method like so:

```ts
export class VsCodeLaunch extends Component { // the fact that it is a JsonFile is an impl. detail so don't extend

  private readonly content: any;

  constructor(vscode: VsCode) {
    super(vscode.project);

    this.content = {
      version: '0.2.0',
      configurations: []
    };
    
    new JsonFile(vscode.project, '.vscode/launch.json', {
      obj: this.content,
    });
  }

  public addConfiguration(cfg: VsCodeLaunchConfiguration) {
    this.content.configurations.push(cfg);
  }
}

export interface VsCodeLaunchConfiguration {
  readonly type: string;
  readonly request: ...
  // ... model it all
}
```

2020-11-29 12:26 UTC, tlakomy commented on src/vscode/launchConfiguration.ts
> +export class VSCodeLaunchConfiguration extends FileBase {
I see, that makes sense 👍

2020-11-29 12:54 UTC, tlakomy commented on src/vscode/launchConfiguration.ts
> +import { FileBase } from '../file';
Done 👍

2020-11-29 13:03 UTC, tlakomy commented on src/vscode/launchConfiguration.ts
> +export class VSCodeLaunchConfiguration extends FileBase {
Just pushed my recent changes, apparently there are quite a few optional fields in `launch.json` according to https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes

2020-12-01 07:08 UTC, eladb requested changes
Looks good. Minor notes.

Please re-request review when ready.

2020-12-01 07:08 UTC, eladb commented on src/vscode/launch-config.ts
> +interface VsCodeLaunchConfiguration {
Since this is a private type, move to the back of the file

2020-12-01 07:08 UTC, eladb commented on src/vscode/launch-config.ts
> +export interface Presentation {
Please add docstrings to all public APIs.

2020-12-01 07:08 UTC, eladb commented on src/vscode/launch-config.ts
> +  public addConfiguration(cfg: VsCodeLaunchConfigurationEntry) {
docstrings

2020-12-01 07:08 UTC, eladb commented on src/vscode/vscode.ts
> +  public addLaunchConfiguration() {
Since there is only a single launch config, I'd go with a lazy property instead of `addXxx()`:

```ts
public get launchConfiguration() {
  if (!this._launchConfig) {
    this._launchConfig = new VsCodeLaunchConfig(this);
  }

  return this._launchConfig;
}
```

2020-12-04 13:41 UTC, eladb approved these changes

2020-12-04 13:41 UTC, eladb commented on src/vscode/launch-config.ts
> +  readonly internalConsoleOptions?:
Use an enum

2020-12-04 13:49 UTC, merged