feat: add package.json publishconfig flag
projen/projen pull request #317
Opened 2020-11-18 20:30 UTC by henrysachs

Fixes #192 
I tried myself on this issue. I tried to use the existing parameters to not have a breaking change. Happy for feedback on the nested if and how to maybe deal with this better.

2020-11-18 20:36 UTC, henrysachs commented
so it seems like npm wants the publishconfig registry field to be a URI Scheme. But Jsii Release wants it without. Do we just replace it in the corresponding github workflows?

2020-11-19 05:02 UTC, gradybarrett requested changes

2020-11-19 05:02 UTC, gradybarrett commented on package.json
> +    "registry": "registry.npmjs.org",
A protocol is required here, otherwise, npm will fall back to defaults.

2020-11-19 05:06 UTC, gradybarrett commented
> so it seems like npm wants the publishconfig registry field to be a URI Scheme. But Jsii Release wants it without. Do we just replace it in the corresponding github workflows?

Hopefully, someone who knows the amazonlinux images can confirm, but my assumption is that there's a `https://${NPM_REGISTRY}` somewhere in there.

2020-11-19 05:08 UTC, gradybarrett commented
I was hoping we could also persist `registry` to a .npmrc file with a new component, to facilitate local development.

2020-11-19 08:11 UTC, henrysachs commented on src/node-project.ts
> +  readonly additionalProperties?: {[name: string]: any};
yeah i read that too and thought if someone wants to override additional properties he can through this interface

2020-11-19 08:12 UTC, henrysachs commented on src/node-project.ts
> +  readonly registry: string;
i'm not quite sure what you mean by this. Its quite typical to pull from one registry and push to another.

2020-11-19 16:53 UTC, henrysachs commented
But I dont know what we do about this now.

2020-11-19 17:42 UTC, gradybarrett commented on src/node-project.ts
> +  readonly registry: string;
Would you mind enlightening me with a use case?

Either way, this code doesn't support that use case. My point here is mainly that `publishConfig.registry` is confusing because it's setting both pull and publish registry configs, even though the interface indicates that it should only be affecting the publish-time registry config.

2020-11-19 17:46 UTC, gradybarrett commented on src/node-project.ts
> +  readonly additionalProperties?: {[name: string]: any};
I think the main thing to keep in mind is that it's harder to remove control than to add it in. Despite my tendency towards overdesign (😆), I'm a fan of waiting for use cases to come in before adding features because it results in cleaner, more specific implementations.

2020-11-19 17:48 UTC, gradybarrett commented
> But I don't know what we do about this now.

Maybe I misunderstood. What are you asking?

2020-11-19 18:07 UTC, henrysachs commented
I made some comments to your comments and we have a valid Issue asking for that feature. What do we need to change on the code to get this into master?

2020-11-20 11:00 UTC, markusl commented
I'm happy to try this after it's merged :)

2020-11-24 12:14 UTC, eladb commented
@henrysachs what's the status of this PR? Please add me as a reviewer when you are ready.

2020-11-24 21:13 UTC, henrysachs commented
I dont had the time to implement the changes requested by @gradybarrett

2020-11-24 21:15 UTC, henrysachs commented on src/node-project.ts
> +  readonly registry: string;
So just for the use case with pulling and publishing to different registries. In my company and others i heard of you have one registry that just mirrors the classic npm one and one where you publish your internal packages. Later on you have a npmrc which specifies to pull certain scopes from the internal registry.

2020-11-24 21:16 UTC, henrysachs commented on src/node-project.ts
> +  readonly registry: string;
but why is publishconfig.registry confusing? I thought i set it especially for the case that its only used for publishing? enlight me pls :D

2020-11-24 21:17 UTC, henrysachs commented on src/node-project.ts
> +  readonly additionalProperties?: {[name: string]: any};
yeah i can go with that but would like to keep the 3 main properties as specified on npm.

2020-11-24 22:37 UTC, gradybarrett commented on src/node-project.ts
> +  readonly registry: string;
Makes sense!

Ha, let me clarify. `publishConfig.registry` isn't itself confusing, just the fact that you've also deprecated `npmRegistry`.  If I set `publishConfig.registry`, I wouldn't expect it to impact where I pull packages from, but that's what currently happens.

Was your intention to allow pulling from one registry and pushing to another?

2020-11-25 06:58 UTC, eladb requested changes
I don't think `PublishConfigOptions` is really needed and I am not sure it's worth breaking the existing API for it. Why not just add `npmAccess` to `NodeProjectCommonOptions`?

2020-11-25 06:58 UTC, eladb commented on package.json
> +    "registry": "registry.npmjs.org",
What do you mean?

2020-11-25 07:58 UTC, henrysachs commented
so maybe I understood the code wrong but the only cases npmRegistry was used was regarding deployment with jsii and thats where the publishNPMRegistry should be in place shouldn't it? I'm open for Solutions but the more i'm reading into your proposals it seems like my approach was the wrong one. That's fine but I struggle to have a different idea on how to solve this?

2020-11-25 15:24 UTC, gradybarrett commented on package.json
> +    "registry": "registry.npmjs.org",
When I was messing around with this, yarn/npm didn't like that there wasn't a protocol declared. It wouldn't let me publish to a registry until I added HTTP/HTTPS.

2020-11-25 18:15 UTC, gradybarrett commented
@eladb, what about the build workflow? Does the `jsii/superchain` image default to the npm registry? Would you be opposed to adding the NPM_REGISTRY environment variable there as well?

I've gone back and forth a bit, but I think I still like the idea of having a .npmrc with the registry property set. It makes interacting with projects locally less confusing because I can rely on the project-level registry declaration to make sure I'm always pulling from the right place. Are there downsides to this?

2020-11-25 19:56 UTC, henrysachs commented on src/node-project.ts
> +  readonly registry: string;
yes this is the use case i had in mind with this feature. I only saw that npm registry was used in the steps that had something to do with publishing. so thats why i think i could deprecate it.

2020-11-25 19:57 UTC, henrysachs commented on package.json
> +    "registry": "registry.npmjs.org",
yeah thats what i was trying to say with my comment. We need a protocol here but jsii release needs the url without it.

2020-11-26 01:20 UTC, gradybarrett commented on package.json
> +    "registry": "registry.npmjs.org",
I don't want to overcomplicate this, so can we just assume https when this is fed to the publishConfigs? If we can't, then I'd say parse the protocol off of the registry input, and default to https if one wasn't provided.

2020-12-09 20:25 UTC, henrysachs commented
I think we try to achieve different things in our discussion. I wanted to achieve the Case pull from one registry push to another. Your idea more sounds like you want to move the registry settings to npmrc. This is for me personally currently the place where i set my installation source. the variable npmRegistry is currently only used for deploying it doesn't affect installing in any way. 
I don't want to sound harsh but before we don't agree on a way projen wants to take we don't need to implement any review comments.

2020-12-10 00:25 UTC, eladb commented on src/node-project.ts
> +  readonly additionalProperties?: {[name: string]: any};
How about this: `npmRegistry` stays like it is today and `publishConfig.registry` will automatically default to it unless it is explicitly set, and then it will only be used for publishing.

This way, if I want to pull from one and push to another, I can set `npmRegistry` to the one I pull from and `publishConfig.registry` to the one I want to push to.

Does that make sense?

2020-12-10 00:26 UTC, eladb commented on src/node-project.ts
> +                  NPM_REGISTRY: this.npmPublishConfig.registry,
So this needs to be: `this.npmPublishConfig.registry ?? this.npmRegistry`

2020-12-10 00:26 UTC, eladb requested changes
See my comments

2020-12-20 19:21 UTC, markusl commented
Hey! Nice to see some progress here. We would be happy to take projen into use after there is a possibility to specify `publishConfig` for internal usage. Hopefully, the comments can be resolved, and the feature could be merged soon  😇

2021-01-14 14:35 UTC, kcwinner commented
For anyone stumbling across this or waiting for it to merge I added a comment for how to make it work in the meantie [here](https://github.com/projen/projen/issues/192#issuecomment-760234634)

2021-01-20 16:20 UTC, eladb commented
Superseded by #510

2021-01-20 16:20 UTC, closed without merging