feat(typescript): ts-jest now uses a non-deprected implementation
projen/projen pull request #3201
Opened 2023-12-26 19:07 UTC by dkershner6

Resolves https://github.com/projen/projen/issues/2361

Continuing the good work of https://github.com/projen/projen/pull/2636 to get it over the finish line.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-12-27 12:48 UTC, mrgrain requested changes
Looks great! A few changes need to the types, which should also fix the build failure.

2023-12-27 12:48 UTC, mrgrain commented on .all-contributorsrc
Can you please revert the formatting changes here? This file is auto-generated. Thx!

2023-12-27 12:48 UTC, mrgrain commented on src/typescript/typescript.ts
> +  readonly stringifyContentPathRegex?: string | RegExp;
RegExp doesn't translate to other jsii languages. See failing build.
```suggestion
  readonly stringifyContentPathRegex?: string;
```

2023-12-27 12:48 UTC, mrgrain commented on src/typescript/typescript.ts
> +  // Warning from ts-jest: If you are using custom transform config, please remove preset from your Jest config to avoid issues that Jest doesn't transform files correctly.
Not sure what this comment is doing in exactly this spot!? Maybe this can just be in the PR description?
```suggestion
```

2023-12-27 12:48 UTC, mrgrain commented on src/typescript/typescript.ts
> +        "You are using a legacy version of jest and ts-jest that does not support tsJestOptions, they will be ignored."
Nice! Any chance we can include the min required version in the warning?

2023-12-27 12:48 UTC, mrgrain commented on src/typescript/typescript.ts
> +  readonly babelConfig?: boolean | string | Record<string, any>;
This needs to be an enum like helper class. It's annoying, but we can't use the full power of TypeScript with jsii.

```ts
class TsJestBabelConfig {
  public static default() {
    return new TsJestBabelConfig(true);
  }

  public static fromFile(path: string) {
    return new TsJestBabelConfig(path);
  }

  public static custom(config: Record<string, any>) {
    return new TsJestBabelConfig(config);
  }

  private constructor(private readonly config: boolean | string | Record<string, any>) {}

  /**
   * @jsii ignore
   * @internal
   */
  public toJSON(): boolean | string | Record<string, any> {
    return this.config;
  }
}
```

2023-12-27 12:48 UTC, mrgrain commented on src/typescript/typescript.ts
> +  readonly diagnostics?: boolean | Record<string, any>;
See `babelConfig`

2023-12-27 12:48 UTC, mrgrain commented on src/typescript/typescript.ts
> +  readonly tsconfig?: boolean | string | TypescriptConfigOptions;
see `babelConfig`

2023-12-27 15:51 UTC, dkershner6 commented on .all-contributorsrc
Whoops!  Didn't see that it formatted, and evidently it was wrong to edit anyway.

2023-12-27 15:58 UTC, dkershner6 commented on src/typescript/typescript.ts
> +  // Warning from ts-jest: If you are using custom transform config, please remove preset from your Jest config to avoid issues that Jest doesn't transform files correctly.
Just felt worth explaining why we are also avoiding preset (rather than explicitly following the deprecation), but you're right, it was odd and didn't provide value.

2023-12-27 16:04 UTC, dkershner6 commented on src/typescript/typescript.ts
> +  readonly babelConfig?: boolean | string | Record<string, any>;
Interesting!  Good to know and thank you for the learning!

2023-12-27 16:25 UTC, dkershner6 commented
Thank you for your patience, @mrgrain , not super familiar with JSII.

All requested changes have been made, and a local build was performed.  Snapshots updated, I checked each and they appear consistent with the intent of the PR.

2023-12-27 16:26 UTC, mrgrain commented
> Thank you for your patience, @mrgrain , not super familiar with JSII.
> 
> All requested changes have been made, and a local build was performed.  Snapshots updated, I checked each and they appear consistent with the intent of the PR.

No need to thank me, I than you for the contribution!

2023-12-27 16:39 UTC, mrgrain commented on .all-contributorsrc
Hmm, I still see it changed the formatting 🤔

If this is about adding you in, you should be able to use this command to manually add you. 

https://allcontributors.org/docs/en/cli/usage#all-contributors-add

Alternatively you get this PR merged and wait until I update the file again. Doing this irregularly though. Up to you!

2023-12-27 16:49 UTC, dkershner6 commented on .all-contributorsrc
Who would've thought that my inane quest for vain recognition would be the most difficult part of this PR?

You should be properly back to normal now.

2023-12-27 19:23 UTC, mrgrain requested changes
One last iteration on the enum-like classes. Mostly docs and naming. You catch my drift.

2023-12-27 19:23 UTC, mrgrain commented on src/typescript/typescript.ts
> +export class TsJestDiagnostics {
```suggestion
/**
 * @see https://kulshekhar.github.io/ts-jest/docs/getting-started/options/diagnostics/
 */
export class TsJestDiagnostics {
```

2023-12-27 19:23 UTC, mrgrain commented on src/typescript/typescript.ts
> +  public static default() {
As per the docs: "Disabling/enabling
By default all diagnostics are enabled. This is the same as setting the diagnostics option to true. To disable all diagnostics, set diagnostics to false. This might lead to slightly better performance, especially if you're not using Jest's cache."

```suggestion
/**
 * Enable all diagnostics.
 */
  public static all() {
```

2023-12-27 19:23 UTC, mrgrain commented on src/typescript/typescript.ts
> +  public static disabled() {
```suggestion
/**
 * Disable all diagnostics.
 */
  public static none() {
```

2023-12-27 19:23 UTC, mrgrain commented on src/typescript/typescript.ts
> +  public static custom(config: Record<string, any>) {
```suggestion
/**
 * Provide a custom diagnostics configuration.
 *
 * @see https://kulshekhar.github.io/ts-jest/docs/getting-started/options/diagnostics/
 */
  public static custom(config: Record<string, any>) {
```

2023-12-27 19:23 UTC, mrgrain commented on src/typescript/typescript.ts
> +export class TsJestBabelConfig {
```suggestion
/**
 * @see https://kulshekhar.github.io/ts-jest/docs/getting-started/options/babelConfig/
 */
export class TsJestBabelConfig {
```

2023-12-27 19:23 UTC, mrgrain commented on src/typescript/typescript.ts
> +  }
```suggestion
  /**
   * Path to a babelrc file
   * 
   * The path should be relative to the current working directory where you start Jest from. You can also use `\<rootDir>` in the path.
   */
  public static fromFile(filePath: string) {
    return new TsJestBabelConfig(filePath);
  }
  
  /**
   * Inline compiler options
   * @see https://babeljs.io/docs/options
   */
  public static custom(config: Record<string, any>) {
    return new TsJestBabelConfig(config);
  }
```

2023-12-27 19:23 UTC, mrgrain commented on src/typescript/typescript.ts
> +  }
```suggestion
  /**
   * Disables the use of Babel
   */
  public static disabled() {
    return new TsJestBabelConfig(false);
  }
  
  /**
   * Enables Babel processing
   *
   * `ts-jest` will try to find an existing Babel configuration and pass it to the `babel-jest` processor.
   */
  public static autoDetectConfig() {
    return new TsJestBabelConfig(true);
  }
```

2023-12-27 19:35 UTC, mrgrain requested changes

2023-12-27 19:35 UTC, mrgrain commented on src/typescript/typescript.ts
> +export class TsJestTsconfig {
```suggestion
/**
 * @see https://kulshekhar.github.io/ts-jest/docs/getting-started/options/tsconfig/
 */
export class TsJestTsconfig {
```

2023-12-27 19:35 UTC, mrgrain commented on src/typescript/typescript.ts
> +   * @default false
```suggestion
   * @default TsJestBabelConfig.disabled()
```

2023-12-27 19:35 UTC, mrgrain commented on src/typescript/typescript.ts
> +   * @default true
```suggestion
   * @default TsJestDiagnostics.all()
```

2023-12-27 19:35 UTC, mrgrain commented on src/typescript/typescript.ts
> +   * @default Your project's tsconfig dev file.
```suggestion
   * @default - Your project's `tsconfigDev` file.
```

2023-12-27 19:35 UTC, mrgrain commented on src/typescript/typescript.ts
> +            tsconfig: this.tsconfigDev.fileName,
Should this technically now be this?
```suggestion
            tsconfig: TsJestTsconfig.fromFile(this.tsconfigDev.fileName),
```

2023-12-27 19:35 UTC, mrgrain commented on src/typescript/typescript.ts
> +  }
```suggestion
  /**
   * Path to a `tsconfig` file
   *
   * The path should be relative to the current working directory where you start Jest from. You can also use `<rootDir>` in the path to start from the project root dir.
   */
  public static fromFile(filePath: string) {
    return new TsJestTsconfig(filePath);
  }

  /**
   * Inline compiler options
   *
   * @see TypescriptConfigOptions
   */
  public static custom(config: TypescriptConfigOptions) {
    return new TsJestTsconfig(config);
  }
```

2023-12-27 19:35 UTC, mrgrain commented on src/typescript/typescript.ts
> +  }
Not sure about this name, but don't have a better one right now.

```suggestion
  /**
   * Force` ts-jest` to use its built-in defaults even if there is a `tsconfig.json` in your project.
   */
  public static builtInDefaults() {
    return new TsJestTsconfig(false);
  }
```

2023-12-27 19:35 UTC, mrgrain commented on src/typescript/typescript.ts
> +  }
```suggestion
  /**
   * Uses `tsconfig.json` if found, or the built-in default TypeScript compiler options.
   */
  public static auto() {
    return new TsJestTsconfig(true);
  }
```

2023-12-27 19:55 UTC, dkershner6 commented on src/typescript/typescript.ts
> +            tsconfig: this.tsconfigDev.fileName,
Yeah, definitely, wondering how TS didn't catch, but I guess it has to be something about the return types.

2023-12-27 20:01 UTC, dkershner6 commented
All implemented @mrgrain , thanks for the naming/description help.

2023-12-27 23:59 UTC, mrgrain approved these changes

2023-12-28 00:00 UTC, merged

2023-12-28 00:02 UTC, mrgrain approved these changes

2023-12-28 06:25 UTC, blimmer commented
This PR broke an older project of mine: https://github.com/blimmer/cdk-static-wordpress/pull/31

When I ran this upgrade, I now get this build issue:

```
 👾 build » test | jest --passWithNoTests --updateSnapshot
FAIL test/index.test.ts
  ● Test suite failed to run

    Unable to process '/home/runner/work/cdk-static-wordpress/cdk-static-wordpress/test/index.test.ts', please make sure that `outDir` in your tsconfig is neither `''` or `'.'`. You can also configure Jest config option `transformIgnorePatterns` to inform `ts-jest` to transform /home/runner/work/cdk-static-wordpress/cdk-static-wordpress/test/index.test.ts

      at TsCompiler.getCompiledOutput (node_modules/ts-jest/dist/compiler/ts-compiler.js:136:27)
      at TsJestCompiler.getCompiledOutput (node_modules/ts-jest/dist/compiler/ts-jest-compiler.js:13:39)
      at TsJestTransformer.process (node_modules/ts-jest/dist/ts-jest-transformer.js:182:37)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:619:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:765:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:822:19)
```

This appears to be because I'm on `jest@27`, which I remain on because the projen `upgrade` task only works within the specified minor range.

Upgrading `jest` manually to `jest@29` restored functionality.