feat: Subproject Releases
projen/projen pull request #3208
Opened 2023-12-28 17:08 UTC by dkershner6

Resolves https://github.com/projen/projen/issues/3172

This is non-breaking, but some opinions made:
- Releases for each project should be a separate workflow, named after the project in the case of a subproject
- For the base release workflow job (creation of artifact), the default working-directory should be set to the relative outdir of the subproject, with an exception made for the install command, which should be run from the topLevelParent of the subproject outdir.
- The folder that the artifact is published from, for a subproject, should be the subproject's outdir + artifactDirectory.
- Perhaps we should break TaskWorkflow, but I just decomposed it.
- Settings - Nothing has changed default-wise, and as such, in order to release subprojects, you must manually set `github` to true and `release` to true.

Snapshots have changed, but it has been verified that the default release behavior for NON-subprojects has remained identical.

I attempted to test this on a monorepo, but the package linking process combined with projen's automated nature proved too difficult, but based on the unit tests, I believe it would satisfy.

Open to more testing ideas, but wanted to ensure the opinions formed are the right ones.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-12-28 17:52 UTC, dkershner6 commented
In order to test this in a more realistic way, I was able to add a project to projen with the following code.

```javascript
new javascript.NodeProject({
  parent: project,
  name: "my-subproject",
  defaultReleaseBranch: "main",
  outdir: "packages/my-subproject",
  release: true,
  github: true,
  minNodeVersion: "16.0.0",
  workflowNodeVersion: "18.14.0",
  releaseTagPrefix: "my-subproject@",
  releaseToNpm: true,
});
```

This produced the following workflow:

```yaml
# ~~ Generated by projen. To modify, edit .projenrc.js and run "/bin/bash ./projen.bash".

name: release_my-subproject
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      latest_commit: ${{ steps.git_remote.outputs.latest_commit }}
    env:
      CI: "true"
    defaults:
      run:
        working-directory: ./packages/my-subproject
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set git identity
        run: |-
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
      - name: Install dependencies
        run: yarn install --check-files --frozen-lockfile
        working-directory: .
      - name: release
        run: npx projen release
      - name: Check for new commits
        id: git_remote
        run: echo "latest_commit=$(git ls-remote origin -h ${{ github.ref }} | cut -f1)" >> $GITHUB_OUTPUT
      - name: Backup artifact permissions
        if: ${{ steps.git_remote.outputs.latest_commit == github.sha }}
        run: cd dist && getfacl -R . > permissions-backup.acl
        continue-on-error: true
      - name: Upload artifact
        if: ${{ steps.git_remote.outputs.latest_commit == github.sha }}
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: packages/my-subproject/dist
  release_github:
    name: Publish to GitHub Releases
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: needs.release.outputs.latest_commit == github.sha
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: dist
      - name: Restore build artifact permissions
        run: cd dist && setfacl --restore=permissions-backup.acl
        continue-on-error: true
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
        run: errout=$(mktemp); gh release create $(cat dist/releasetag.txt) -R $GITHUB_REPOSITORY -F dist/changelog.md -t $(cat dist/releasetag.txt) --target $GITHUB_REF 2> $errout && true; exitcode=$?; if [ $exitcode -ne 0 ] && ! grep -q "Release.tag_name already exists" $errout; then cat $errout; exit $exitcode; fi
  release_npm:
    name: Publish to npm
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: needs.release.outputs.latest_commit == github.sha
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14.0
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: dist
      - name: Restore build artifact permissions
        run: cd dist && setfacl --restore=permissions-backup.acl
        continue-on-error: true
      - name: Release
        env:
          NPM_DIST_TAG: latest
          NPM_REGISTRY: registry.npmjs.org
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx -p publib@latest publib-npm
```

When I compare this against my own monorepo and manual code, it looks identical other than naming and that I use PNPM.  The monorepo publish is confirmed working.

2023-12-29 17:43 UTC, mrgrain commented on test/release/release.test.ts
> +    expect(outdir).toMatchSnapshot();
Let's just use `outdir[".github/workflows/release_my-project.yml"]` as the snapshot that should be enough here.

2023-12-29 17:43 UTC, mrgrain commented on test/release/release.test.ts
> +    expect(outdir).toMatchSnapshot();
Not required here.

2023-12-29 17:46 UTC, mrgrain commented on src/project.ts
> +    this.relativeOutdir = options.outdir ?? Project.DEFAULT_OUTDIR;
Is `options.outdir` always relative?

2023-12-29 17:47 UTC, mrgrain commented on src/project.ts
> +  }
How is this different than `project.root`?

2023-12-29 17:50 UTC, mrgrain commented on src/project.ts
> +   * Relative output directory of this project.
Relative to what? Root or parent?

2023-12-29 17:53 UTC, mrgrain commented on src/release/release.ts
> +  private _findTargetGitHubForWorkflow(): GitHub | undefined {
Trying to get away from this convention. I know it's not consistently enforced.

```suggestion
  private findTargetGitHubForWorkflow(): GitHub | undefined {
```

2023-12-29 17:58 UTC, mrgrain commented on src/release/release.ts
> +    }
Thanks for adding validations! This feels a bit too prescriptive with the class having to be an `instanceof GitHubProject` and the `github` property. 

How about we use `GitHub.of(this.project.root)`?

--- 

Side note, there is probably a missing enforcement of only allowing a single `GitHub` component in the tree.

2023-12-29 17:59 UTC, mrgrain commented on src/release/release.ts
> +    }
Not sure I understand this early exit.

2023-12-29 18:15 UTC, dkershner6 commented on src/release/release.ts
> +    }
I know you are still reviewing, but I actually implemented this as their MUST be more than one `GitHub` set to true in the tree (as in you control each piece of the tree with this option).  This also would be why you are confused one comment below on the early exit.

2023-12-29 18:18 UTC, mrgrain commented on test/release/release.test.ts
> +      github: true,
I wonder if we want this. It's not used in the code, is it?

2023-12-29 18:19 UTC, dkershner6 commented on test/release/release.test.ts
> +      github: true,
https://github.com/projen/projen/pull/3208#discussion_r1438362070

It is, at least currently.

2023-12-29 18:20 UTC, dkershner6 commented on test/release/release.test.ts
> +      github: true,
My thought on this was that it is `true`, just "hoisted".

2023-12-29 18:22 UTC, mrgrain commented on src/github/workflow-steps.ts
> +  private static _adaptCommonJobStep(options: CommonJobStep): CommonJobStep {
```suggestion
  private static adaptCommonJobStep(options: CommonJobStep): CommonJobStep {
```

2023-12-29 18:26 UTC, mrgrain commented on src/github/workflows-model.ts
This doesnt' make sense to me. What's unique what's common and why. I'm guessing you are trying to avoid some duplication here, but I think we've made this more complicated than before. 

Also these end up as public interfaces, so we it's tricky to go back on this.

2023-12-29 18:34 UTC, mrgrain commented on src/javascript/node-project.ts
> +  }
Feels like we are doing this kind of check quite often. And both `topLevelParent` and `relativeOutdir` are new additions. Are they maybe not quite suitable to what we want to use them for? Or maybe we need a helper to convert relative paths between prefixless an with `./` prefix? IDK.

Also I don't think `working-directory` technically needs the prefix in GitHub Actions.

2023-12-29 18:36 UTC, mrgrain commented on src/javascript/node-project.ts
> +   * We may be running a Workflow with a default working-directory set, and we must set this in order to install from the root.
Should describe what this does, not why it exists.

2023-12-29 18:41 UTC, mrgrain commented on src/github/task-workflow.ts
Not your fault, but the diff makes this very confusing to review. Could you please describe what the refactor is here? I think it's just a refactor...

2023-12-29 18:46 UTC, mrgrain commented on src/javascript/node-project.ts
> +          }),
I think there is an implicit question about the workingDir for other steps in renderWorkflowSetup

2023-12-29 18:48 UTC, dkershner6 commented on src/github/task-workflow.ts
TaskWorkflow has been minimally changed, but otherwise just extracted to two static methods.

The only addition is the ability to control `JobDefaults` (which we use to control default `working-directory`)

2023-12-29 18:58 UTC, mrgrain requested changes
🚀 This is awesome, thank you! 

> * Releases for each project should be a separate workflow, named after the project in the case of a subproject
> * For the base release workflow job (creation of artifact), the default working-directory should be set to the relative outdir of the subproject, with an exception made for the install command, which should be run from the topLevelParent of the subproject outdir.

Each of these are reasonable by themselves. But together I'm struggling a bit to make sense of them. Are we treating the projects as separate things or not?
For Node Monorepo projects, it makes sense to run this at the top level only because that's how most monorepos work anway. But then why have it in separate workflows?


> * Perhaps we should break TaskWorkflow, but I just decomposed it.

As little change as possible please, that just makes the PR bigger and more complicated. I'd rather have a follow-up `chore` to clean things up.

> * Settings - Nothing has changed default-wise, and as such, in order to release subprojects, you must manually set `github` to true and `release` to true.

This seems like the biggest point of contention to discuss. Can you elaborate on your thinking?

> Open to more testing ideas, but wanted to ensure the opinions formed are the right ones.

I'll test this as well. Not sure either what we can do beside manual testing of the workflows.

> I considered writing a recursive `releaseTagPrefix` conflict checker, but it seemed outside the scope, and should be another request if desired.

Agreed, out of scope.

2023-12-29 19:06 UTC, dkershner6 commented
Thanks for the thoughtful review, I know it was a beefy one.

> Each of these are reasonable by themselves. But together I'm struggling a bit to make sense of them. Are we treating the projects as separate things or not?

The projects are treated as fully separate, any generation of workflows (release, anyway) are just "hoisted" to the `topLevelParent` project.  My wording was a little confusing, but the code should clearly dileneate this as the case.

> For Node Monorepo projects, it makes sense to run this at the top level only because that's how most monorepos work anway. But then why have it in separate workflows?

I think by "top level only" you may mean "as part of a single release workflow with the root project and subproject all as one workflow".  In general, I agree, people just rig up a nx or turborepo and just `[monorepohandler] run deploy`.  Most people also don't generally do artifact creation per project, then hand that to several publishing jobs, at least in my experience, and doing so would generally create at least some issues since artifact naming is per workflow.  For projen, the complexity level would be a significant uptick for this same reason, but not insurmountable, just some changes to `Publisher`.

2023-12-29 19:07 UTC, mrgrain commented on src/release/release.ts
> +    }
Yes, there is a wider discussion to be had. But this comment and the one about early exit are more basic. The validations as implemented are too prescriptive and will move us further away from being able to get rid of `GitHubProject`, which is a goal.

2023-12-29 19:09 UTC, mrgrain commented on src/release/release.ts
> +    }
I _think_ you tried to short circuit the helper, because `workflowTargetGitHub` is not used if `!this.github == true`. But that check is also done further up and that's confusing. I'd expect `findTargetGitHubForWorkflow()` to pretty much always find a workflow unless it is set to false everywhere. Might just need splitting up in a validation helper and a helper to get the object.

2023-12-29 19:10 UTC, dkershner6 commented
> This seems like the biggest point of contention to discuss. Can you elaborate on your thinking?

Agreed.  I believe we can ignore the `release` part and focus on `github`. My thinking was three things:

1. `github` is _technically_ true, as github-y things are being created and happening, they are just "hoisted" to the top level.
2. If you only have a single project in projen, and you want to release that project using GitHub workflows, `github` must be set to `true`.
3. When it comes to creating things that run automatically, opt-in is better than opt-out (and `release` didnt feel like enough of an opt-in to create workflows).

Open to other ideas, of course, there were a lot of possible paths here.

2023-12-29 19:12 UTC, mrgrain commented on test/release/release.test.ts
> +      github: true,
When I say it's not used, I mean that the actual component on the subproject is not used. I probably have missed something, but as far as I can tell we only use `subproject.github` (which is a component, not a boolean) as a boolean. But the actual workflows are created against `workflowTargetGitHub`.

2023-12-29 19:17 UTC, dkershner6 commented on test/release/release.test.ts
> +      github: true,
I see.  I believe that the `subproject.github` is used in the formation of the job that performs the release.  Things like `runsOn` and such.  The TARGET of the workflow is indeed the root, but essentially we are only using the root for a filepath.

2023-12-29 19:23 UTC, dkershner6 commented on src/release/release.ts
> +    }
Your second comment makes sense, thanks for circling back.

2023-12-29 19:27 UTC, dkershner6 commented on src/github/workflow-steps.ts
> +  private static _adaptCommonJobStep(options: CommonJobStep): CommonJobStep {
I try to use design pattern names when I am using one, but my first typed-in name was indeed `build`.

Since we are here chatting:
> Adapter is a structural design pattern, which allows incompatible objects to collaborate.

(the forced camelCase of JSII and forced kebab-case of GitHub, in this case)

> Builder is a creational design pattern that lets you construct complex objects step by step. The pattern allows you to produce different types and representations of an object using the same construction code.

Sure, that could work as well, for a simple single step, of course.

I'll switch this to build regardless as I want to stick to convention of this project, but since you asked! ;)

2023-12-29 19:30 UTC, dkershner6 commented on src/github/workflows-model.ts
Open to naming ideas, but the difference is that:

Common: Every single JobStep in existence can take this fields.
Unique: JobStep's generally only use one or two of these, never all, and we, as projen, build these fields using other interfaces, adapting the input to these.

2023-12-29 19:40 UTC, mrgrain commented
Thank you, that helps my understanding much better. 

In my mind, the other alternative is:

- Only allow a single GitHub Component in the tree. By default this Component would be attached to the root project, but it could feasibly be created manually. Obviously this is a breaking change, although I'm not sure if there's currently a meaningful way to use more than one of them.
- All features that the GitHub Component provides only exist at the root anyway. 
- This is opt-out at the root project level like before, releases can be opt-in at subproject level. Saying that, we default to releasing root projects, so I'm questioning why we would make a different default for subprojects.


> 1. `github` is _technically_ true, as github-y things are being created and happening, they are just "hoisted" to the top level.
> 2. If you only have a single project in projen, and you want to release that project using GitHub workflows, `github` must be set to `true`.

I think this is the core of my issue. Even currently it feels wrong to be able to set the `github` boolean option to `true` in the root project and `false` in subprojects. Like as if this makes a difference if the repo is hosted on GitHub or if GitHub Workflows are created or not. In this interpretation, the option would be better called something like `useGitHubFeatures`. However the actual currently implementation isn't strictly that either. It is pretty much `shouldCreateGitHubComponent`. And then features are added from the outside. Take the `UpgradeDependencies` component as an example. That creates a Github Workflow by default (if it can), but also has an option to disable that.

(There is this whole fluke that we are still using a `GitHubProject` but you can then disable `github`. But that's fine, we should pretend `GitHubProject` doesn't exist. That's the goal anyway.)

So what I'm struggling with here is if we can separate the root and subprojects enough to have multiple GitHub components. As an example, I can set the `projenCredentials` option on my subproject. Which credentials are we now going to use? If we enable `pullRequestLint` on the subproject, what does that mean?

I'm not really against having multiple GitHub Components, but we will have to sieve through the consequences of that (at least to some extend) and also we should than put it front-and-center that subprojects use their own `github` and not the root one.

---

> 3. When it comes to creating things that run automatically, opt-in is better than opt-out (and `release` didnt feel like enough of an opt-in to create workflows).

This feels like a discussion about sensible defaults that should not have any bearing on the rest.

2023-12-29 19:49 UTC, mrgrain commented
> I think by "top level only" you may mean "as part of a single release workflow with the root project and subproject all as one workflow". In general, I agree, people just rig up a nx or turborepo and just `[monorepohandler] run deploy`. Most people also don't generally do artifact creation per project, then hand that to several publishing jobs, at least in my experience, and doing so would generally create at least some issues since artifact naming is per workflow. For projen, the complexity level would be a significant uptick for this same reason, but not insurmountable, just some changes to `Publisher`.

Yes this is fine, we should not confuse this PR with a full Monorepo implemention. But the question remains what the basic algorithm looks like here. Is it something like this?

```
 (0) // starting at the project root
 (1) yarn install --check-files --frozen-lockfile
 (2) cd subproject/
 (3) projen release
 (4) |- projen bump
 (5) |- projen build
 (6)     |- projen default
 (7)     |- projen compile
 (8)     |- projen test
 (9)     |- projen package
(10) |- projen unbump
(11) ./upload.sh dist
```

This seems fine. (1) is required because we need to this to run projen itself
But it think we are assuming that (5) will just run without further work. Is that a correct assumption to make?

2023-12-29 20:05 UTC, dkershner6 commented
> But it think we are assuming that (5) will just run without further work. Is that a correct assumption to make?

You are definitely more familiar with projen than I...but I think we make the same assumption for normal projects, but provide the ability to add in `pre` and `post` build steps?  That should be true here as well...

Also, your algorithm is close, but instead of `cd`, I instead set default `working-directory` to the subproject and the `working-directory` for the `install` command to root.  This seemed more in the vein of what GitHub intended, but I think the practical difference is near zero...but I dont know that for sure, there could be some kind of nested action logic that reverts to the default `working-directory`.

2023-12-29 20:08 UTC, dkershner6 commented on test/release/release.test.ts
> +      github: true,
I am incorrect directly above, `github` is in fact a very simple object, and none of the info is used besides the root project.  The options I refer to are on the project itself, not in `github` (which I am not sure makes sense conceptually, but that is the same GitHubProject discussion)

2023-12-29 20:13 UTC, dkershner6 commented
> I'm not really against having multiple GitHub Components, but we will have to sieve through the consequences of that (at least to some extend) and also we should than put it front-and-center that subprojects use their own github and not the root one.

When I started this out, I assumed all GitHub related info would reside on `github`.  For whatever reason, I kept that constraint in my head.  Having looked at the actual object and how tiny it is, I think I should remove this constraint, and rely fully on `release` in order to determine if a subproject should generate a release workflow (which I think is what you are inclined to as well, please confirm).

Just as a comment for the sake of commenting, I think both of us knew I would run face-first into GitHubProject and likely somehow make the refactor situation worse, but I did do my best to avoid it where I could, "could" just wasn't a lot of places given current implementation.

2024-01-01 20:27 UTC, dkershner6 commented on src/project.ts
> +  }
Somehow I missed that one, will use.

2024-01-01 20:33 UTC, dkershner6 commented on src/javascript/node-project.ts
> +  }
I can't find an example without the `./`...maybe keep it around just so I can sleep at night?

I will create the helper though.

2024-01-01 21:34 UTC, dkershner6 commented on src/project.ts
> +   * Relative output directory of this project.
Moving away from this entirely, as requested.

2024-01-01 22:47 UTC, dkershner6 commented on src/github/workflows-model.ts
Alright, I took a stab at these, and renamed my Unique to Settings, which I think helps, but I need some help from you on this one:
What is the difference between a `Step` and a `JobStep`?  It _feels_ like perhaps someone accidentally conflated the two, and now we have two where we could have one.  `JobStep` only contains optional fields outside of what Step contains.  I only see Step used in JSII.

In any case, if we can combine all of these into one, I think my Common/Full additions will make way more sense.  If not, I just need help differentiating these names.

Leaving this unresolved.

2024-01-01 22:48 UTC, dkershner6 commented on src/github/task-workflow.ts
This is still true on my latest commits.

2024-01-01 22:49 UTC, dkershner6 commented on src/javascript/node-project.ts
> +          }),
Leaving unresolved intentionally.

2024-01-01 22:52 UTC, dkershner6 commented
Alright, @mrgrain , this is ready for another pass when you have (several) moments.

2024-01-03 01:40 UTC, dkershner6 commented on src/github/workflows-model.ts
Alright, I gave it some long thought and came up with the word `Configuration` to describe the JobSteps Who, Where, Why, and How (but not what).

2024-01-03 11:44 UTC, mrgrain commented on src/github/github-project.ts
> +          workflows: this.parent ? false : true, // Don't create workflows for subprojects, in the subproject
This seems unrelated to the PR? I guess it makes sense as a setting, but the again we have the issue that really non the stuff the `GitHub` component does make sense in a subproject. I guess the default can be changed by `githubOptions`, but I'd feel better if we don't touch the wider issue of `GitHub` component in subproject unless we absolutely have to.

2024-01-03 15:10 UTC, dkershner6 commented on src/github/github-project.ts
> +          workflows: this.parent ? false : true, // Don't create workflows for subprojects, in the subproject
This was more important when github was required to be true, but good catch, can now be removed.

2024-01-04 10:38 UTC, mrgrain commented on src/util/path.ts
> +export function formatPathAsDotNotation(path: string): string {
If you have a better name, I'd be up for that. Dot notation seems overloaded. I though it meant `path.to.file` first and was confused. Maybe `ensureRelativePathStartsWithDot` or something.

2024-01-04 10:41 UTC, mrgrain commented on src/release/release.ts
> +          `Subproject ${this.project.name} cannot create a release workflow to its top-level parent ${this.project.root.name} because it is not a GitHub project or does not have github set to true.`
```suggestion
          `Subproject ${this.project.name} cannot create a release workflow to its top-level parent ${this.project.root.name} because it does not have GitHub support enabled. Please enable GitHub support for ${this.project.root.name}.`
```

2024-01-04 15:47 UTC, dkershner6 commented
Ready to roll, @mrgrain .  Thank you, this back and forth was full of learnings.

2024-01-04 15:50 UTC, mrgrain commented on src/project.ts
> +  public static readonly DEFAULT_OUTDIR = ".";
Same as on the other PR, let's not have these in the public interface.

2024-01-04 15:54 UTC, mrgrain commented on src/github/workflows-model.ts
> + * These settings differentiate a JobStep from a generic Step.
Although this begs the question why is there difference between a JobStep and a generic Step and what is it, like in prose. 😅

2024-01-04 15:57 UTC, mrgrain commented on src/github/workflows-model.ts
@dkershner6 Can you give me prose summary why we need to introduce multiple levels between `Step -> JobStep`? Looks like we now have `Step -> StepConfiguration` and `JobStep -> (JobStepConfiguration -> StepConfiguration),  (Step -> StepConfiguration)`.

2024-01-04 16:20 UTC, dkershner6 commented on src/github/workflows-model.ts
I have no insight into the existence of `Step` + `JobStep`, they seem to be the same thing to me and could be combined (this was a decision made before my PR).

As to `Configuration` vs the other fields (`Command`):

Configuration: Fields that describe the How, Why, When, and Who of a (Job)Step.  These fields can have none present, but can be present on every single (Job)Step in existence, and have no effect on one another.  This was created for accuracy, we could _technically_ accept a whole (Job)Step into options when we are accepting parameters to create a (Job)Step(s), but it is more accurate to say we can only always accept these.

Command: These fields describe the What, and are generally mutually exclusive and will error if used together (`run` and `uses`, for instance).  This means if we were creating a (Job)Step that uses `uses`, and someone provided `run`, it would error (in github, once the workflow ran).

Hopefully this helps, @mrgrain , if you can help me with the difference between `Step` and `JobStep`, perhaps we can get this in order.

2024-01-04 16:45 UTC, mrgrain commented on src/util/path.ts
> +  if (path.startsWith("/")) {
This is odd. Normally paths starting with `/` are absolute paths?!

2024-01-04 16:56 UTC, mrgrain commented on src/github/task-workflow.ts
> +  public static buildJob(
So this is a `TaskJob` then basically? Can you make it a class instead of a static method that returns a struct?

2024-01-04 16:58 UTC, mrgrain commented
> Ready to roll, @mrgrain . Thank you, this back and forth was full of learnings.

Thanks @dkershner6 I'm going through it now. I think the result is what we want and the API for it is there as well. Most of my requests will now be about refactors that might or might not have been needed. But because they are shaping the public API, we'll have to go through it. In future, I'd suggest we split out refactorings and new features into multiple PRs.

2024-01-04 17:52 UTC, mrgrain commented on src/javascript/node-project.ts
> +  readonly installJobStepOverrides?: JobStep;
Can we make this the configuration? As in don't allow overwriting `run`?

```suggestion
  /**
   * Configure the install step in the workflow setup.
   *
   * @default - `{ name: "Install dependencies" }`
   *
   * @example - { workingDirectory: "rootproject-dir" } for subprojects installing from root.
   * @example - { env: { NPM_TOKEN: "token" }} for installing from private npm registry.
   */
  readonly installStepConfiguration?: JobStepConfiguration;
```

The `@default` might not work and just require text instead

2024-01-04 19:23 UTC, dkershner6 commented on src/github/task-workflow.ts
> +  public static buildJob(
I can implement this, but it is effectively just an adapter renaming all of the `TaskWorkflow` fields back to `Job` fields, when the `TaskWorkflow` fields are just renamed `Job` fields in the first place.  It is the reason I was asking if breaking was a good idea (to just make the fields the same names).

Regardless, my half measure was not the correct one, as you identified.

2024-01-04 19:23 UTC, dkershner6 commented on src/github/task-workflow.ts
> +  public static prepareWorkflow(
Was an attempt to deduplicate logic, but it isn't a lot, so I will use duplication instead.

2024-01-04 19:31 UTC, dkershner6 commented
> Thanks @dkershner6 I'm going through it now. I think the result is what we want and the API for it is there as well. Most of my requests will now be about refactors that might or might not have been needed. But because they are shaping the public API, we'll have to go through it. In future, I'd suggest we split out refactorings and new features into multiple PRs.

My message came across as an attempt to push, it was actually just meant to say "I am done with your most recent review".  Apologies.

2024-01-04 19:37 UTC, dkershner6 commented on src/github/workflows-model.ts
> + * These settings differentiate a JobStep from a generic Step.
Resolving in favor of detailed prose in conversation one below.

2024-01-04 19:48 UTC, dkershner6 commented on src/javascript/node-project.ts
> +  readonly installJobStepOverrides?: JobStep;
Worked as is.

2024-01-04 20:19 UTC, dkershner6 commented
Ready for another pass, @mrgrain .

2024-01-05 04:22 UTC, dkershner6 commented on src/github/workflows-model.ts
It's odd, I actually had some of this in a JSDoc, but must have lost them in a rename.  Re-adding now.

2024-01-05 18:30 UTC, mrgrain commented on src/github/task-workflow.ts
> +  constructor(taskStep: JobStep, options: TaskWorkflowJobOptions) {
I think the interface here would be the task itself. Both usage you introduce are just taking in the same input.

2024-01-05 18:31 UTC, mrgrain commented on src/github/task-workflow.ts
> +export class TaskWorkflowJob {
So I think according to our new nomenclature this is now a WorkflowAction. Correct?

Also, let's put this into a new file please.

2024-01-05 19:17 UTC, dkershner6 commented on src/github/task-workflow.ts
> +  constructor(taskStep: JobStep, options: TaskWorkflowJobOptions) {
The reason why I didn't do this is to allow for a flexible `GitHub.Project` to run `runTaskCommand` from.  The project attached to the `TaskWorkflow` or this job isn't necessarily the one we want to use (we use the subproject, but place the workflow on the rootProject, for instance).

If I am missing something surrounding this, please be more specific, it is entirely possible I am.

2024-01-05 19:20 UTC, dkershner6 commented on src/github/task-workflow.ts
> +export class TaskWorkflowJob {
New file heard.

`WorkflowAction` seems to be `group of JobSteps`.  That makes sense to me.

`Job` includes a field that contains not just a group of JobSteps, but all the steps for a given job, plus it has additional configuration associated with the Job itself (outside the steps).

I think it is named appropriately, as it is a `Job`, and more specifically, one that matches the (partial) interface of `TaskWorkflow`.

2024-01-05 19:25 UTC, mrgrain commented on src/github/workflows-model.ts
> +export interface StepConfiguration {
Okay, so this is down to PR https://github.com/projen/projen/pull/1787 and the `Step` interface being used for steps in the [action.yaml Metadata file for GitHub Actions ](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions).

Now I don't necessarily agree with this, or the naming, but that's what we have today. So we can keep it the way you have it. But would you mind updating the comment on `Step` and `StepConfiguration` to explain their purpose. Thanks!

2024-01-05 19:33 UTC, dkershner6 commented on src/github/workflows-model.ts
> +export interface StepConfiguration {
Oh...I see, that makes sense why it doesn't make sense here...it isn't for something in this library.

Yeah...I will do my best to explain.

2024-01-05 19:48 UTC, mrgrain commented on src/github/task-workflow-job.ts
> +export class TaskWorkflowJob {
this should implement `Job` right?

2024-01-05 19:52 UTC, mrgrain commented on src/release/release.ts
> +          : undefined,
I think this always is true, the working directory is always `path.relative(this.project.root.outdir, this.project.outdir)` because in the case of root project, the result is `''` empty string. We can check for that to just omit the whole thing, but don't need to check the parent anymore.

2024-01-05 19:55 UTC, mrgrain commented on src/release/release.ts
> +      );
Let's move this condition into the place where we are creating the release workflow.

2024-01-05 19:56 UTC, dkershner6 commented on src/github/task-workflow.ts
> +export class TaskWorkflowJob {
Resolving based on below comment.

2024-01-05 19:57 UTC, mrgrain commented on src/release/release.ts
> +            : this.artifactsDirectory,
We can just always do this, because in the case of root project, the result of `path.relative(this.project.root.outdir, this.project.outdir) ` is `''` the empty string.

2024-01-05 20:02 UTC, dkershner6 commented on src/release/release.ts
> +          : undefined,
I believe `outdir` on the OUTPUT of a Project class is an absolute path.  We are striving to get to relative here, and I removed the relativeOutDir property that I added earlier in the PR.

Basically, what I am trying to accomplish here is:
If subproject
subproject relative directory
else
default is good (because we are the root)

I think this code works, but if you have a cleaner implementation, I would need more help to find it.

2024-01-05 20:02 UTC, mrgrain commented on src/release/release.ts
> +    }
```suggestion
```

We don't actually need this. If we are not a subproject, we are a root project. And the code below will return the correct project.

Further more, we can lift this up to where we currently say `this.github = project.github;` => `this.github = this. findTargetGitHubForWorkflow()`. And then we can actually change the constructor from the current `project: Project` => `scope: IConstruct`.

2024-01-05 20:04 UTC, dkershner6 commented on src/release/release.ts
> +    }
I see, there is no third level (subproject of subproject), I didn't know that limit was in there, I can change accordingly.

2024-01-05 20:04 UTC, mrgrain requested changes
Okay, so my last round of reviews on the `Release` component has the goal to rid it of needing to know about subprojects and root projects. That's not something it should concern itself with. I left the inline notes that show you how to get rid of all the few remaining references.

Almost there, thanks for bearing with me!

2024-01-05 20:17 UTC, dkershner6 commented on src/github/task-workflow-job.ts
> +export class TaskWorkflowJob {
I get a JSII error if I literally `implements`, but I have done the legwork and it matches.

2024-01-05 20:19 UTC, dkershner6 commented
> Almost there, thanks for bearing with me!

The product we are ending with is much better than the one I started with, no question.

2024-01-05 20:20 UTC, dkershner6 commented
> Okay, so my last round of reviews on the Release component has the goal to rid it of needing to know about subprojects and root projects.

@mrgrain , inherent in some of your suggestions is that there can never be a subproject of a subproject.  I didn't go in with this constraint, and just want to be sure it, in fact, exists.

2024-01-05 20:23 UTC, mrgrain commented on src/release/release.ts
> +    }
We can actually have third levels, but what we are saying is that we always just use the `GitHub` component of the root project.

The code currently does this:

- `if not this.project.parent` => only the root project does not have a parent
  - `then use this.github` => that is the `GitHub` component of the root project
- `otherwise` => any other project is a subproject, no matter how many levels
  -  `then use GitHub.of(this.project.root) or throw` which is also the `GitHub` component of the root project or we fail

2024-01-05 20:24 UTC, mrgrain commented
> @mrgrain , inherent in some of your suggestions is that there can never be a subproject of a subproject. I didn't go in with this constraint, and just want to be sure it, in fact, exists.

No, this is in fact not a constraint that exists. But it is also not inherent to my assumptions. At least I don't think so. 😅

2024-01-05 20:25 UTC, dkershner6 commented
> > @mrgrain , inherent in some of your suggestions is that there can never be a subproject of a subproject. I didn't go in with this constraint, and just want to be sure it, in fact, exists.
> 
> No, this is in fact not a constraint that exists. But it is also not inherent to my assumptions. At least I don't think so. 😅

I think I still am reading some of your words incorrectly, I will see if anything comes up as I implement.

2024-01-05 20:28 UTC, mrgrain commented
> > Thanks @dkershner6 I'm going through it now. I think the result is what we want and the API for it is there as well. Most of my requests will now be about refactors that might or might not have been needed. But because they are shaping the public API, we'll have to go through it. In future, I'd suggest we split out refactorings and new features into multiple PRs.
> 
> My message came across as an attempt to push, it was actually just meant to say "I am done with your most recent review". Apologies.

Oh no, didn't read it that way actually. My message was really just telling you that you will get quicker results if you keep changes to the API surface tight. As much I as appreciate good code and refactoring, it inevitably makes everything a bit slower.

2024-01-05 20:29 UTC, mrgrain commented
> > > @mrgrain , inherent in some of your suggestions is that there can never be a subproject of a subproject. I didn't go in with this constraint, and just want to be sure it, in fact, exists.
> > 
> > 
> > No, this is in fact not a constraint that exists. But it is also not inherent to my assumptions. At least I don't think so. 😅
> 
> I think I still am reading some of your words incorrectly, I will see if anything comes up as I implement.

Might be my words. I'm not a native English speaker.

2024-01-05 20:30 UTC, mrgrain commented on src/release/release.ts
> +      );
By that I mean `NodeProject` should check if it is a subproject, and in that case pass a different default workflow name.

2024-01-05 20:31 UTC, dkershner6 commented
> > My message came across as an attempt to push, it was actually just meant to say "I am done with your most recent review". Apologies.
> 
> Oh no, didn't read it that way at all. My message was really just letting you know that you will get quicker results if you keep changes to the API surface tight. As much I as appreciate good code and refactoring, it inevitably makes everything a bit slower.

Asking me to turn my head is a big ask!

I hear you, but I also think this was very educational for me in my assessment of whether this lib can serve our needs and to what certain things are and how they should be used, so the time was not wasted (at least for me), and now we have slightly cleaner code!

2024-01-05 20:32 UTC, mrgrain commented on src/github/task-workflow-job.ts
> +export class TaskWorkflowJob {
What's the jsii error? If you push I can have a look at it.

2024-01-05 20:33 UTC, dkershner6 commented
> Might be my words. I'm not a native English speaker.

It isn't, I would've never known unless you said something.

2024-01-05 20:51 UTC, mrgrain commented on src/github/task-workflow.ts
> +  constructor(taskStep: JobStep, options: TaskWorkflowJobOptions) {
That's a good point actually. `GitHub.Project` isn't the right project here either. 🤔
I was thinking task has a reference to it's project, but that's not the case. This needs some thinking.

2024-01-05 20:51 UTC, dkershner6 commented on src/release/release.ts
> +            : this.artifactsDirectory,
I don't like the feel of `/dist` in the field (normally dist or something/dist)...

BUT, we can have one variable power all of these, I think, and that should help.

2024-01-05 21:03 UTC, dkershner6 commented on src/release/release.ts
> +      );
We cannot do this because a single `Release` may create several workflows (because of more than one branch being released), and so we are already editing the name inside Release (the nodeProject option it fills could even be called "prefix").

The `workflowName` right here is:
```
const workflowName = branch.workflowName ?? `release-${branchName}`;
```

2024-01-05 21:31 UTC, dkershner6 commented on src/release/release.ts
> +    }
The exact change throws errors in EVERY root project that doesn't have `github` enabled...which I am trying to determine if it is what we want...

2024-01-05 21:41 UTC, dkershner6 commented on src/release/release.ts
> +    }
OK, now I remember, this whole error was just in case someone had enabled github on the subproject, but not root.

This is no longer a thing, we just need to know if github is on the root.

2024-01-05 21:50 UTC, dkershner6 commented
OK, @mrgrain , I handled or replied to all comments.

Note that I had to handle one differently than either of us expected, but it is resolved: https://github.com/projen/projen/pull/3208#discussion_r1443392255

Essentially, we were erroring for reasons that no longer make sense.  Now we just do nothing, as per normal, single project, behavior.

2024-01-05 23:03 UTC, mrgrain commented on src/github/task-workflow.ts
> +  constructor(taskStep: JobStep, options: TaskWorkflowJobOptions) {
Alright I figured that out. `TaskWorkflowJob` needs to be a component, which gives us the right project. And that can also also be any project - so it's flexible.

It took the liberty to push the code.

2024-01-05 23:08 UTC, mrgrain commented on src/release/release.ts
> +      );
Okay this make sense. We are still loosing the ability to set the workflow name though. I can refactor this to be optional.

2024-01-05 23:20 UTC, dkershner6 reviewed
👍

2024-01-05 23:20 UTC, dkershner6 commented on src/github/task-workflow-job.ts
> +  constructor(scope: IConstruct, task: Task, options: TaskWorkflowJobOptions) {
You may consider adding something regarding:

> `scope` should be part of the project the `Task` belongs to.

This wouldn't have been obvious to me as a new user of `Component` with this interface.

2024-01-05 23:30 UTC, mrgrain commented on src/github/task-workflow-job.ts
> +  constructor(scope: IConstruct, task: Task, options: TaskWorkflowJobOptions) {
Done. Thanks!

2024-01-05 23:48 UTC, mrgrain commented
@dkershner6 Out of interest, have you read this yet? https://projen.io/constructs.html
Either way, does that help you understanding what scope is or is it missing something?

2024-01-05 23:49 UTC, mrgrain commented
@dkershner6 Pushed a couple more changes. I am happy with this now. Are you okay for me to merge?

2024-01-05 23:51 UTC, mrgrain commented on src/github/task-workflow-job.ts
> +  constructor(scope: IConstruct, task: Task, options: TaskWorkflowJobOptions) {
Yeah, it's actually quite a recent thing that we have fully adopted the constructs model. But it's awesome for exactly this reason!

2024-01-05 23:51 UTC, dkershner6 commented
> @dkershner6 Out of interest, have you read this yet? https://projen.io/constructs.html Either way, does that help you understanding what scope is or is it missing something?

I have, and I have used em quite a bit outside this lib, and am generally familiar from CDK, but that almost would make me complacent on the `scope` parameter, figuring it to be mostly about context and not that I specifically needed to target the subproject.

I mean, the chances of something going wrong are pretty small regardless, but it is worth telling folks, imo.

2024-01-05 23:52 UTC, dkershner6 commented
> @dkershner6 Pushed a couple more changes. I am happy with this now. Are you okay for me to merge?

I am.  Thanks for this, was a great experience and I love this feature!

2024-01-05 23:55 UTC, mrgrain commented
> > @dkershner6 Out of interest, have you read this yet? https://projen.io/constructs.html Either way, does that help you understanding what scope is or is it missing something?
> 
> I have, and I have used em quite a bit outside this lib, and am generally familiar from CDK, but that almost would make me complacent on the `scope` parameter, figuring it to be mostly about context and not that I specifically needed to target the subproject.
> 
> I mean, the chances of something going wrong are pretty small regardless, but it is worth telling folks, imo.

Oh yeah, I was just curious. And more docs are always nice. In projen the biggest win is direct access to the project. Which I guess is kind of like context.

2024-01-05 23:55 UTC, mrgrain commented
> > @dkershner6 Pushed a couple more changes. I am happy with this now. Are you okay for me to merge?
> 
> I am. Thanks for this, was a great experience and I love this feature!

:shipit:

2024-01-05 23:55 UTC, mrgrain approved these changes

2024-01-05 23:57 UTC, merged

2024-01-05 23:58 UTC, dkershner6 commented
> > > @dkershner6 Out of interest, have you read this yet? https://projen.io/constructs.html Either way, does that help you understanding what scope is or is it missing something?
> > 
> > 
> > I have, and I have used em quite a bit outside this lib, and am generally familiar from CDK, but that almost would make me complacent on the `scope` parameter, figuring it to be mostly about context and not that I specifically needed to target the subproject.
> > I mean, the chances of something going wrong are pretty small regardless, but it is worth telling folks, imo.
> 
> Oh yeah, I was just curious. And more docs are always nice. In projen the biggest win is direct access to the project. Which I guess is kind of like context.

Yes, very similar in benefit and use case of `Cdk.Stack.of`.  I will freely admit that it takes a bit of getting used to, but that might be something about convention, like a Java dev would immediately grasp it.  Either way, after getting used to, very useful.