fix: Prettier, ProjenRc, and .gitattributes added to packageIgnore (npmignore)
projen/projen pull request #3223
Opened 2024-01-02 04:23 UTC by dkershner6

Fixes https://github.com/projen/projen/issues/3215

.gitattributes was not part of the ticket, but I noticed it while I was working.  As part of that implementation, I noticed there was a race condition on the `addPackageIgnore` method, where if it was called before the `npmignore` `IgnoreFile` was initialized, the additions were lost.  I implemented the only pattern I know for safety without using abstract classes, essentially creating a temporary buffer that gets loaded on file initialization.  Not in love with this pattern if someone has a better idea, but it is effective.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-01-02 20:30 UTC, mrgrain requested changes
Right, regarding the race condition (great find by the way!): Let's turn `project.npmignore` into a getter that can initialized itself. Than we are guaranteed to have an ignore file.

2024-01-02 20:30 UTC, mrgrain commented on src/gitattributes.ts
> +    project.addPackageIgnore("/.gitattributes");
```suggestion
    this.project.addPackageIgnore("/.gitattributes");
```

2024-01-02 20:30 UTC, mrgrain commented on src/typescript/projenrc-ts.ts
> +  public static readonly DEFAULT_FILENAME = ".projenrc.ts";
I don't want this to be a public property on the class. Tbh, the components are purposely separate, so I'm fine with the duplication here.

Let's make it a local constant per component.

2024-01-02 20:30 UTC, mrgrain commented on src/typescript/typescript.ts
> +              RealProjenrcTs.DEFAULT_FILENAME,
This seems inaccurate? Seems like we want the projenrc instance and get `filePath` from that.

2024-01-02 20:30 UTC, mrgrain commented on test/javascript/jest.test.ts
> +    ProjenrcTs.DEFAULT_FILENAME,
Same as the other one.

2024-01-02 21:39 UTC, dkershner6 commented on src/typescript/typescript.ts
> +              RealProjenrcTs.DEFAULT_FILENAME,
This is a little tougher than meets the eye, since creating the ProjenrcFile requies the tsconfig to already be built (chicken/egg).  I tried to capture the spirit of what you wanted, though.

2024-01-02 22:01 UTC, dkershner6 commented
> Right, regarding the race condition (great find by the way!): Let's turn `project.npmignore` into a getter that can initialized itself. Than we are guaranteed to have an ignore file.

I just tried this, and it doesn't appear possible because we require storing ignores before `this` is available in NodeProject (during the run of `super`).  If I am missing something, let me know.

2024-01-03 11:25 UTC, mrgrain commented
> Another thing that came up: There appear to be two near-identical classes: Projenrc and ProjenrcTs. In some cases one is even renamed to the other. I used the more explicit, and didn't break anything, including inner library renaming, but it made my naming odd in some cases to do so. If you want me to be more opinionated, let me know.

These are two different components. `Projenrc` is for `TypeScriptProjects` only. `ProjenrcTs` can be used with any project type. Yes they are mostly the same, but the former can make assumptions that the latter can't and thus do more things. You'll probably need to update both.

2024-01-03 11:30 UTC, mrgrain commented on src/typescript/typescript.ts
> +                : PROJEN_RC,
This already gets added in `Projenrc`. Nice spotting the incorrect addition of `PROJEN_RC`. This can be added conditional as well.

2024-01-03 11:34 UTC, mrgrain commented on src/gitattributes.ts
> +    this.project.addPackageIgnore("/.gitattributes");
Actually never mind the race condition. You just have to add this in the pre-synth phase:
```suggestion
}
  public preSynthesize(): void {
    this.project.addPackageIgnore("/.gitattributes");
```

2024-01-03 11:35 UTC, mrgrain commented
> I just tried this, and it doesn't appear possible because we require storing ignores before `this` is available in NodeProject (during the run of `super`). If I am missing something, let me know.

No you are right. I've missed that as well. I remembered the proper way of doing this though and left a comment.

2024-01-04 20:45 UTC, dkershner6 commented
Ready for another pass, @mrgrain .

2024-01-05 11:30 UTC, mrgrain commented on src/javascript/node-project.ts
> +    }
```suggestion
    this.npmignore?.addPatterns(pattern);
```

The if statement is exactly what `?` does here.

2024-01-05 11:30 UTC, mrgrain commented on src/javascript/node-project.ts
> +    // packageIgnore added prior to initialization or npmignore disabled.
```suggestion
```

2024-01-05 11:32 UTC, mrgrain commented on src/typescript/projenrc-ts.ts
> +    project.gitignore.include(`/${this.filePath}`);
Wait why do you want this gitignored?
```suggestion
```

2024-01-05 11:35 UTC, mrgrain commented on test/javascript/node-project.test.ts
> +  test("npmignore should have NodeProject's default ignore patterns", () => {
```suggestion
  test("should have NodeProject's default ignore patterns", () => {
```

2024-01-05 11:36 UTC, mrgrain commented on test/javascript/node-project.test.ts
> +    expect(output[".npmignore"]).toMatchSnapshot();
```suggestion
    expect(output[".npmignore"]).toMatchSnapshot();
    expect(output[".npmignore"]).toContain("/.gitattributes");
```

2024-01-05 11:44 UTC, mrgrain commented on src/typescript/typescript.ts
> +      this.tsconfigDev.addInclude(PROJEN_RC); // projenrc.js created in NodeProject needs to be added in tsconfigDev
Not required for this PR, but if you are down for it.

```suggestion
    // when this is a root
    if (!this.parent) {
      if (options.projenrcTs) {
        new ProjenrcTs(this, options.projenrcTsOptions);
      } else {
        // projenrc.js created in NodeProject needs to be added in tsconfigDev
        const projenrcJs = Projenrc.of(this);
        if (projenrcJs) {
          this.tsconfigDev.addInclude(projenrcJs.filePath);
        }
      }
```

2024-01-05 11:46 UTC, mrgrain requested changes
Almost there. just a few minor changes now (one totally optional).

The big one that's confusing me is adding `.prjojenrc.ts` to gitignore. But I'm guessing that was a mistake?

2024-01-05 15:38 UTC, dkershner6 commented on src/typescript/projenrc-ts.ts
> +    project.gitignore.include(`/${this.filePath}`);
I think Copilot got me!

2024-01-05 15:43 UTC, dkershner6 commented on src/typescript/typescript.ts
> +      this.tsconfigDev.addInclude(PROJEN_RC); // projenrc.js created in NodeProject needs to be added in tsconfigDev
I'll track down the rest.

2024-01-05 15:55 UTC, dkershner6 commented on src/typescript/projenrc-ts.ts
> +    project.gitignore.include(`/${this.filePath}`);
WAIT, we both got fooled, this is INCLUDE for gitignore, as in `!`, as in ALWAYS DON'T ignore.

Here is the JS equivalent: https://github.com/projen/projen/blob/92e8b5ae1048d7185fcae5619abb4dae90041e4a/src/javascript/node-project.ts#L553

2024-01-05 15:56 UTC, dkershner6 commented
> Almost there. just a few minor changes now (one totally optional).
> 
> The big one that's confusing me is adding `.prjojenrc.ts` to gitignore. But I'm guessing that was a mistake?

@mrgrain , reposting here to ensure you see it:

This is INCLUDE for gitignore, as in `!`, as in ALWAYS DON'T ignore.

Here is the JS equivalent: https://github.com/projen/projen/blob/92e8b5ae1048d7185fcae5619abb4dae90041e4a/src/javascript/node-project.ts#L553

2024-01-05 16:01 UTC, mrgrain commented
> This is INCLUDE for gitignore, as in `!`, as in ALWAYS DON'T ignore.

Omg, that's embarrassing. I was wondering why the snapshots didn't change. 🙈  
Thanks for catching my stupidity.

2024-01-05 16:06 UTC, dkershner6 commented
> > This is INCLUDE for gitignore, as in `!`, as in ALWAYS DON'T ignore.
> 
> Omg, that's embarrassing. I was wondering why the snapshots didn't change. 🙈 Thanks for catching my stupidity.

I think this qualifies as an off by one error (number of negatives), so you are off the hook.

> There are 2 hard problems in computer science: cache invalidation, naming things, and off-by-1 errors.

2024-01-05 16:41 UTC, dkershner6 commented
Alright, @mrgrain , ready for your perusal, including the optional "fix all the projens".  You can note the corrected behavior in all the language snapshots.

`PROJEN_RC` is not exported from the root of the lib, and therefore isnt a public interface, so I gave it a bit more descriptive name.

2024-01-05 17:21 UTC, mrgrain approved these changes
🥳

2024-01-05 17:22 UTC, merged