feat(nextjs): add tailwindcss option
projen/projen pull request #326
Opened 2020-11-20 05:27 UTC by Chriscbr

Closes #325

Adds Tailwind CSS integration to NextJs and NextJsTypeScript projects.

I've set it up with defaults based on the Tailwind CSS docs - they can be changed if needed to be a bit more opinionated, but this should be a good enough starting point.

2020-11-23 10:40 UTC, eladb requested changes

2020-11-23 10:40 UTC, eladb commented on src/next.ts
> +export interface PostCssConfigOptions {
Move to a separate file

2020-11-23 10:40 UTC, eladb commented on src/next.ts
> +export class PostCssConfig {
Docstrings

Also rename to `PostCss`

2020-11-23 10:40 UTC, eladb commented on src/next.ts
> +      project.addDeps('tailwindcss', 'postcss', 'autoprefixer');
Move each dep to the specific component

2020-11-23 10:40 UTC, eladb commented on src/next.ts
> +export class TailwindConfig {
Move to a separate file.

I am okay with aggregating all these files under `src/web`

2020-11-25 03:59 UTC, Chriscbr commented on src/next.ts
> +      project.addDeps('tailwindcss', 'postcss', 'autoprefixer');
So my only objection here is that for Tailwind CSS, there are multiple ways to consume it ([docs](https://tailwindcss.com/docs/installation)). To summarize them:

- use it as a PostCSS plugin, requiring `tailwindcss, postcss, autoprefixer` dependencies (recommended by TailwindCSS). For NextJS, this works out of the box, and for other projects, a `tailwind build index.css -o tailwind.css` script needs to be added.
- use their CLI command, requiring the `tailwindcli` dependency, and requiring a `npx tailwindcss-cli@latest build -o tailwind.css` script to be added.
- referencing a CSS file from a CDN

Note that none of these choices have dependencies in common.

I'm implementing the first option as the default. But I don't want to lock users out of the others -- so I think `TailwindConfig` should only "model" the configuration file itself, and not the dependencies.

What I could do as a compromise is add a `tailwind` option to `PostCss`, and have that component keep the dependencies.

2020-11-25 04:01 UTC, Chriscbr commented on src/next.ts
> +export class TailwindConfig {
I wasn't sure which files you meant, so I just put these two components in `web.ts`.

2020-11-25 04:02 UTC, Chriscbr commented on src/next.ts
> +export class PostCssConfig {
done

2020-11-25 04:09 UTC, Chriscbr commented
I updated the implementation - in a nutshell, now `PostCss` has a `tailwind` option which if chosen, adds all necessary dependencies for Tailwind. But if some user wanted to just have a Tailwind config file without using PostCSS, they can also just use that component by itself, and it will not automatically add any dependencies (see the comment I made above for why). I think this is a good compromise, but I'm happy to do things another way.

2020-11-25 07:04 UTC, eladb commented on src/next.ts
> +      project.addDeps('tailwindcss', 'postcss', 'autoprefixer');
Sounds good. I think having each components expose these degrees of freedom while still encapsulating the details is the right way to go. I'd also be careful not to future-proof. Without taking an opinionated approach, it will be impossible to actually offer any abstraction.

My litmus test is usually what is the functional difference between the options. Sounds to me that there isn't much difference between these options.

2020-11-25 07:05 UTC, eladb commented on src/next.ts
> +export class TailwindConfig {
What I meant is:

```
web/tailwind.ts
web/next.ts
...
```

(basically start grouping domain-related classes in subdirectories/submodules -- like I did for `github`).

2020-11-25 07:10 UTC, eladb commented on src/web.ts
> +export interface PostCssOptions {
Split those to `web/postcss.ts` and `web/tailwind.ts`

2020-11-26 03:05 UTC, Chriscbr commented
Updated. Just note the change from:
```ts
const { ReactTypeScriptProject } = require('projen');

const project = new ReactTypeScriptProject({
```
to
```ts
const { web } = require('projen');

const project = new web.ReactTypeScriptProject({
```

2020-11-26 18:23 UTC, eladb approved these changes
👌👌🎉

2020-11-26 18:23 UTC, merged