feat(task): getStep, editStep, removeStep, cwd
projen/projen pull request #3311
Opened 2024-01-30 15:57 UTC by dkershner6

Fixes https://github.com/projen/projen/issues/1904

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-01-31 11:09 UTC, mrgrain reviewed
```
    // If the list of steps is a Lazy value, we can't know what the steps
    // are until synthesis occurs, so just return an empty array.
```

The `steps` getter has this note. How does this PR deal with this?

2024-02-04 18:08 UTC, dkershner6 commented
> ```
>     // If the list of steps is a Lazy value, we can't know what the steps
>     // are until synthesis occurs, so just return an empty array.
> ```
> 
> The `steps` getter has this note. How does this PR deal with this?

Added a warning for folks to try using the `preSynthesize` phase if they somehow run into that for all methods.  Good to look over once more, @mrgrain .

2024-02-04 18:20 UTC, dkershner6 commented
Tests failing on what seems like an errant type in a lib:

```
node_modules/@types/node/ts4.8/crypto.d.ts:3495:17 - error TS1110: Type expected.
```

2024-02-05 13:10 UTC, mrgrain requested changes

2024-02-05 13:10 UTC, mrgrain commented on src/task.ts
> +    }
Nice and thanks for adding this everywhere! Can you pull this out into a helper, similar to `assertUnlocked()` so we don't have to repeat ourselves.

2024-02-05 18:12 UTC, dkershner6 commented
@mrgrain , I realized that `reset()` would also have failed, so I added a check there as well, but all now use a centralized helper.  Feel free to have another look at your convenience.

2024-02-07 16:17 UTC, mrgrain approved these changes

2024-02-07 16:43 UTC, merged