feat: Sub-Project Build Workflow
projen/projen pull request #3317
Opened 2024-01-31 18:46 UTC by timothymathison

Creates a working `build` workflow specific to a sub-project when that project has `buildWorkflow` set to `true`.

Based on #3208. So most of the same decisions were made. The `install` command is always run in the root directory same as the `release` workflow. But based on discussion in #3304, we may want to make that configurable. I could make that change in this PR for `build`. Or just address it in a followup PR for both `build` and `release`.
I added a `buildWorkflowName` option to `NodeProject` to support customizing each build workflow name; but it still defaults to `build` or `build_{package-name}` for sub-projects.

I've successfully tested this with my own monorepo and added a few tests.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-01-31 18:53 UTC, timothymathison commented on src/github/workflow-actions.ts
> +        },
Instead of adding this option (which I'm just using to set it to `./`), I'm considering just hard-coding it always to `./`. I can't think of a scenario where it would actually be desirable to set it to anything besides `./` (repo root)

2024-02-01 22:13 UTC, timothymathison commented
@mrgrain are you able to approve the build workflow for this PR?

2024-02-01 22:51 UTC, timothymathison commented
Thanks @mrgrain. The build is failing with a unclear jsii test failure. But I also get the same failure when running tests with the head of `main` checked out. Any idea what's going on?

2024-02-01 22:58 UTC, mrgrain commented
Not sure what's going on. The last CI/CD build on main was still successful: https://github.com/projen/projen/actions/runs/7734258354/job/21087924904 🤔

2024-02-02 11:44 UTC, mrgrain commented
@timothymathison See https://github.com/projen/projen/pull/3320#issuecomment-1923644372

I't will probably take me over the weekend to get this sorted. Apologies.

2024-02-07 20:22 UTC, timothymathison commented
thanks @mrgrain! Mind giving this a review?

2024-02-07 22:59 UTC, mrgrain commented
Yeah yeah, I'll get to it. ,🤣

2024-02-14 20:44 UTC, mrgrain commented
Sorry this is taken a bit longer than usual. I should have some more time next week.

2024-02-26 23:04 UTC, timothymathison commented
@mrgrain any update?

2024-02-27 13:03 UTC, mrgrain requested changes

2024-02-27 13:03 UTC, mrgrain commented on src/javascript/node-project.ts
> +  readonly buildWorkflowName?: string;
```suggestion
  readonly buildWorkflowOptions?: BuildWorkflowOptions;
```

And then define BuildWorkflowOptions

2024-02-27 13:04 UTC, mrgrain commented
Sorry this took so long. Do you know the feeling when you're going into what you expect to be a quiet week, and then it isn't? 🙈

2024-02-27 22:49 UTC, timothymathison commented on src/javascript/node-project.ts
> +  readonly buildWorkflowName?: string;
yeah I was following the pattern of `releaseWorkflowName`. But I agree its a better pattern to define an object with that option nested inside of it

2024-02-27 22:51 UTC, timothymathison commented on src/build/build-workflow.ts
> +        projectPathRelativeToRoot.length > 0 // is subproject,
Sure. I copied this approach from #3208. But it can probably be more proper

2024-02-27 22:51 UTC, timothymathison commented on src/build/build-workflow.ts
> +    const github = GitHub.of(this.project.root);
Yes

2024-02-27 22:57 UTC, timothymathison commented on src/github/workflow-actions.ts
> +          ? ensureRelativePathStartsWithDot(options.workingDirectory)
I'm not 100% sure. The Github actions syntax docs example uses `./` for a relative path but but I didn't see it say if that's required. So I added it based on its use in #3208

2024-02-27 23:01 UTC, timothymathison commented on src/github/workflow-actions.ts
> +        },
> Why is it not just workingDir + patchFileName?

The additional logic is just removing any `./` prefix when the working directory is root.

> I don't think it can just be root, given the in the previous step the patch file is generated in a subdirectory.

What I meant was that I don't think we would ever want to generate the patch file in a subdirectory. So we could just hard-code both the previous step and this step to use the root directory.

2024-02-29 18:15 UTC, timothymathison commented on src/javascript/node-project.ts
> +  readonly buildWorkflowName?: string;
I'm not sure it would be desirable to have two different `BuildWorkFlowOptions` types. So I'm considering just using [the existing `BuildWorkflowOptions` interface](https://github.com/projen/projen/blob/0d9027ac26d93c30784c1e184312189bc9e31cf5/src/build/build-workflow.ts#L33) here which would support a customizing a bunch of other things

2024-02-29 19:56 UTC, timothymathison commented on src/javascript/node-project.ts
> +  readonly buildWorkflowName?: string;
`BuildWorkflowOptions` has a few properties that shouldn't be exposed at the `NodeProject` constructor level. So I made an interface called `NodeProjectBuildWorkflowOptions`. I wanted to use `Omit` with `BuildWorkflowOptions` to just exclude a few properties from `BuildWorkflowOptions`. But jsii doesn't support `Omit` 😕 . So I copy pasted properties from `BuildWorkflowOptions`.
Since there are several other `NodeProject` options that  are specific to `BuildWorkflow`, I marked them as deprecated and they can be replaced with properties within `NodeProjectBuildWorkflowOptions`.

2024-02-29 19:58 UTC, timothymathison commented on src/javascript/node-project.ts
> +export interface NodeProjectBuildWorkflowOptions {
Wanted to define this type as
```ts
Omit<BuildWorkflowOptions, 'buildTask' | 'artifactsDirectory' | 'gitIdentity'>
```
But alas jsii does not support `Omit`.

2024-03-05 11:26 UTC, mrgrain commented on src/github/workflow-actions.ts
> +        },
Gotcha. Yeah I think this would be clearer & safer actually. Because a sub-project could absolutely cause a file outside itself to change, and if we limit the mutation to the subproject we'd miss that.

So let's change it to run mutation detection at root level only. Please make sure to add comments in, so we don't forget about it.

2024-03-05 11:34 UTC, mrgrain commented on src/javascript/node-project.ts
> +export interface NodeProjectBuildWorkflowOptions {
Fair, but I really don't think we need all of these options here for now. Can we please limit this to `name`, `mutableBuild` and `workflowTriggers` for now please. We can iterate over the other options later. Particularly pre/post build steps needs some cleaning up I think.

PS: The way to do what you wanted to do, would be to pull out the shared options into a `Common BuildWorkflowOptions` interface or something and than extend implementations from it.

2024-03-05 11:36 UTC, mrgrain requested changes
I think this will be the last round of changes.

2024-03-05 15:40 UTC, timothymathison commented on src/javascript/node-project.ts
> +export interface NodeProjectBuildWorkflowOptions {
> Can we please limit this to `name`, `mutableBuild` and `workflowTriggers` for now please.

I have some specific use cases for setting `permissions` and `preBuildSteps`. And I'd like to avoid using a workaround just to patch the job to add those a different way. Any specific reasons you're against going ahead and adding those options along with `postBuildSteps`?

2024-03-05 15:41 UTC, timothymathison commented on src/javascript/node-project.ts
> +export interface NodeProjectBuildWorkflowOptions {
Hmm I forgot about the fact its exported from a submodule

2024-03-05 23:28 UTC, mrgrain commented on src/javascript/node-project.ts
> +export interface NodeProjectBuildWorkflowOptions {
Just to keep this already large PR under control and moving. You've correctly picked up on the redundancy for the other props.

Definitely happy for you to discuss additional props on a follow up issue/PR.

2024-03-12 19:47 UTC, timothymathison commented
@mrgrain can I get another review please?

2024-03-13 15:00 UTC, mrgrain requested changes
One additional request, and the already open request to split the features out into separate PRs.

2024-03-13 21:51 UTC, timothymathison commented on src/github/workflow-actions.ts
> +        workingDirectory: "./",
Can you think of a valid use case for running this step from anything besides the root of a git repository?

2024-03-13 21:55 UTC, timothymathison commented on src/build/build-workflow.ts
> +}
I just ripped out all the `buildWorkfowOptions` changes since they're not strictly required for this feature.

2024-03-14 19:29 UTC, timothymathison commented on src/github/workflow-actions.ts
> +        workingDirectory: "./",
>Use case would be having different workflows that are looking at subsets of the repo.

The diff would still include changes in other directories though - even if its run from a subdirectory (i.e. the unexpected behavior I was referring to).

2024-03-20 21:56 UTC, timothymathison commented on src/github/workflow-actions.ts
> +        workingDirectory: "./",
If the `workingDirectory` option is set to something other then the root directory, we could add `./` to the `git diff` command to make it only report the diff of that working directory since I think that's the behavior that having a `workingDirectory` option implies. Thoughts?

>It's a breaking change otherwise and I don't see why we would not make it an option.

I'm not sure I see how its really a breaking change to _not_ have the `workingDirectory` option and hard code it to root (`./`) since that's the default behavior anyway - except for when the working directory of the whole job happens to have been overridden. But if that were to be the case, without my change, I think `uploadArtifact` would fail anyway because it would expect `GIT_PATCH_FILE` to be at the root while `git diff` would have created it inside the subdirectory.

I think making `workingDirectory` an option could be valid. But its not strictly required for this feature and would add complexity, while hardcoding it to `./` (root) updates a bunch of snapshots but should be a functional noop.
Otherwise, I can add the `workingDirectory` option back in and add the `./` path to the `git diff` command to make it behave as one would expect (only collect diff from subdirectory).

2024-03-25 09:46 UTC, mrgrain approved these changes

2024-03-25 09:55 UTC, merged