chore(github): bump actions to versions with LTS node version
projen/projen pull request #3335
Opened 2024-02-07 20:39 UTC by icj217

- chore(deps): upgrade dependencies (#2513)
- fix(github): extend PullRequestOptions to include PushOptions (#2511)
- feat(javascript): Jest config support for addSetupfile() addSetupAfterEnv() (#2516)
- chore: fix test that updates snapshot locally (#2518)
- chore(javascript): fix invalid arg name in JSDocs (#2522)
- chore(deps): upgrade dependencies (#2523)
- feat(typescript): support `importsNotUsedAsValues` (#2520)
- chore(deps): upgrade dependencies (#2527)
- chore(deps): upgrade dependencies (#2534)
- fix(file): marker notice is referencing the wrong projenrc file (#2498)
- chore(deps): upgrade dependencies (#2538)
- fix(node): Upgrade Workflow is missing id-token permission when GitHub OIDC configured (#2537)
- chore: remove dependency on fs-extras (#2540)
- feat: generic .projenrc.ts file that can be used in non-TS projects (#2521)
- feat(cli): allow running `projen` from a subdirectory (#2493)
- fix(subprojects): unnecessary use of `cd` when spawning default task of root project (#2542)
- fix(auto-merge): Mergify is not merging pull requests (#2517)
- feat(node)!: default to node16 and remove `jsii/superchain` from workflows (#2510)
- feat(jsii): support for setting new `jsiiVersion` (#2539)
- chore(deps): upgrade dependencies (#2546)
- fix: projen cannot be used with node "< 16.0.0" (#2547)
- chore(python-project): correction to projenrcTs option's docstring (#2549)
- chore(deps): upgrade dependencies (#2551)
- chore(deps): upgrade dependencies (#2553)
- fix(typescript): support `jsxImportSource` in TypescriptConfig (#2550)
- chore(deps): upgrade dependencies (#2555)
- chore(deps): upgrade dependencies (#2556)
- chore(deps): upgrade dependencies (#2558)
- chore: update contributing guide with minimal git version (#2544)
- chore(deps): upgrade dependencies (#2564)
- fix(cli): command suggestion prevents use of external projects (#2557)
- feat(javascript): add `addScripts` to `NodeProject` (#2562)
- feat(vscode): support dev container features (#2559)
- chore(deps): upgrade dependencies (#2566)
- fix(file): annotate generated in sub-project creates incorrect patterns (#2561)
- chore!: upgrade build tools to jsii@5.0.0 (#2541)
- chore(deps): upgrade dependencies (#2568)
- chore(deps): upgrade dependencies (#2573)
- feat: add `workflowContainerImage` to `Publisher` (#2572)
- fix(new): cli fails on windows with RangeError (#2575)
- chore(deps): upgrade dependencies (#2577)
- chore(deps): upgrade dependencies (#2578)
- chore(deps): upgrade dependencies (#2580)
- feat(typescript): add `disableTsconfigDev` property to not generate the `tsconfig.dev.json` (#2569)
- fix(file): marker contains wrong rcfile name (#2585)
- chore(deps): upgrade dependencies (#2588)
- feat(cli): validate options when creating projects from external packages (#2563)
- chore(deps): upgrade dependencies (#2593)
- feat(tasks): support fixed arg lists for better task reusability (#2594)
- feat(github): expose GitHub Actions workflow helpers (#2595)
- chore(deps): upgrade dependencies (#2596)
- fix(jest): cannot set `preset` and `globals` config when using in a typescript project (#2567)
- feat(github)!: add createPullRequest Workflow Action to create PRs without using a patch (#2597)
- chore(deps): upgrade dependencies (#2600)
- feat(jsii): new `JsiiProject`s default to version `~5.0.0` (#2598)
- fix(python): unescape poetry version metadata in pyproject.toml (#2602)
- feat(typescript): new typescript projects use `projenrcTs` by default (#2599)
- fix(node): typesVersions is added by jsii  and removed by projen (#2603)
- chore(deps): upgrade dependencies (#2604)
- chore(deps): upgrade dependencies (#2605)
- chore: use node 16.14 version for github workflows (#2610)
- fix: remove deprecated zlib library (#2608)
- chore(deps): upgrade dependencies (#2611)
- fix(release): incorrect prerelease version when there is a regular version (#2609)
- chore(deps): upgrade dependencies (#2612)
- chore: explain how to report security vulnerabilities (#2613)
- chore: upgrade jest dependencies (#2615)
- fix: Cannot find module 'projen' or its corresponding type declarations (#2617)
- chore(deps): upgrade dependencies (#2618)
- chore(deps): upgrade dependencies (#2620)
- chore(deps): upgrade dependencies (#2622)
- chore(deps): upgrade dependencies (#2623)
- feat(java): expose readonly maven packaging dist dir (#2624)
- chore(deps): upgrade dependencies (#2625)
- chore(deps): upgrade dependencies (#2626)
- chore(deps): upgrade dependencies (#2627)
- chore(deps): upgrade dependencies (#2629)
- chore(deps): bump yaml from 2.0.0 to 2.2.2 (#2630)
- chore(deps): upgrade dependencies (#2631)
- feat(node-project): use resolution-mode=highest for pnpm by default (#2632)
- chore(deps): upgrade dependencies (#2633)
- chore(deps): upgrade dependencies (#2637)
- feat(javascript): generic `tryResolveDependencyVersion` node-package method. (#2634)
- feat(typescript): TypeScript TSConfig 5.0+ parameters, support for TSConfig extends. (#2607)
- chore(deps): upgrade dependencies (#2639)
- chore(deps): upgrade dependencies (#2640)
- chore(deps): upgrade dependencies (#2643)
- chore(deps): upgrade dependencies (#2646)
- fix(github): untrusted input should only be used as action input or env variable (#2647)
- chore(deps): upgrade dependencies (#2648)
- chore(deps): upgrade dependencies (#2651)
- fix(cli): improved error messages for `new` command (#2650)
- chore(deps): upgrade dependencies (#2652)
- fix: ensure env command is package manager specific (#2653)
- chore: note for windows users regards build script (#2654)
- feat(project): public subprojects property (#2655)
- chore(deps): upgrade dependencies (#2658)
- chore(deps): upgrade dependencies (#2659)
- chore(deps): upgrade dependencies (#2662)
- chore(deps): upgrade dependencies (#2664)
- fix(sample-file): unable to create empty sample directory (#2656)
- chore(deps): upgrade dependencies (#2666)
- chore(deps): upgrade dependencies (#2668)
- fix(javascript): do not rely on `package.json` being a valid entrypoint for dependency resolution. (#2645)
- fix(xml): upgrade xmlbuilder2 to version ^3.1.1 (#2669)
- chore(deps): upgrade dependencies (#2670)
- chore(deps): upgrade dependencies (#2672)
- chore(deps): upgrade dependencies (#2673)
- chore(deps): upgrade dependencies (#2678)
- chore(deps): upgrade dependencies (#2680)
- chore(deps): upgrade dependencies (#2682)
- feat(javascript): implement additional manifest resolution strategies for packages with no default or package.json exports. (#2681)
- feat(python): python executable can be set to any path (#2661)
- chore(deps): upgrade dependencies (#2684)
- feat(tasks): Add support for environment variables in task steps (#2663)
- fix(gitlab): `artifacts:reports:coverage_report` replaces deprecated `artifacts:reports:cobertura` (#2683)
- chore(deps): upgrade dependencies (#2687)
- fix(node-package): allow to remove resolutions (#2685)
- chore(deps): upgrade dependencies (#2689)
- chore(deps): upgrade dependencies (#2691)
- chore(deps): upgrade dependencies (#2692)
- feat(typescript): pass `--swc` to `ts-node` in default task (#2677)
- chore(deps): upgrade dependencies (#2693)
- chore(deps): upgrade dependencies (#2697)
- feat(tasks): add conditions to task steps (#2686)
- feat(task): support adding condition to task (#2694)
- chore(deps): upgrade dependencies (#2699)
- chore(deps): upgrade dependencies (#2700)
- fix(javascript): correct `TypeScriptCompilerOptions.emitDeclarationOnly` from `true` -> `boolean` (#2701)
- chore(deps): upgrade dependencies (#2702)
- chore(deps): upgrade dependencies (#2703)
- chore(deps): upgrade dependencies (#2705)
- fix(javascript): codeartifact repo containing a dash (`-`) not detected (#2706)
- feat(javascript): add workflowPackageCache (#2709)
- fix(javascript): workflowPackageCache doesn't work with pnpm (#2711)
- chore(deps): upgrade dependencies (#2714)
- chore(deps): upgrade dependencies (#2716)
- fix(node): print PATH without escaping double quotes (#2719)
- chore(deps):  [...]

2024-02-07 23:32 UTC, mrgrain requested changes
Can you keep this limited to upload/download and split other actions in to separate PRs please?

2024-02-08 14:06 UTC, icj217 commented
> Can you keep this limited to upload/download and split other actions in to separate PRs please?

Sure thing. [Here's the separate PR](https://github.com/projen/projen/pull/3338)

2024-02-09 11:42 UTC, mrgrain commented on src/github/workflow-steps.ts
> +   * @default true (to maintain backwards compatibility)
```suggestion
   * Introduced in v4 and represents a breaking change from the behavior of the v3 action.
   * To maintain backwards compatibility with existing, this should be set the `true` (the default).
   *
   * @default true
```

2024-02-09 21:04 UTC, mrgrain approved these changes
:shipit:

2024-02-09 21:14 UTC, merged