feat: create github repository
projen/projen pull request #336
Opened 2020-11-25 16:56 UTC by campionfellin

Signed-off-by: campionfellin <campionfellin@gmail.com>

Fixes #310

2020-11-25 17:28 UTC, pgollucci commented on src/cli/synth.ts
> +        exec(`gh repo create ${gitProjectName}`);
-d description, --public --enable-wiki, --enable-issues ?

2020-11-25 17:29 UTC, pgollucci commented on src/cli/synth.ts
> +    exec('git branch -M main');
I think projen has git branch discovery somewhere

2020-11-25 17:29 UTC, pgollucci commented
👍

2020-11-25 23:37 UTC, Chriscbr requested changes
Thanks for the pull request!

Aside from the comments below, what occurs if the user does not have the GitHub CLI installed? Can we check for this and stop the setup process gracefully / add a message saying that it must be installed?

2020-11-25 23:37 UTC, Chriscbr commented on src/cli/index.ts
> +  synth(); // eslint-disable-line @typescript-eslint/no-floating-promises
Is it possible to had `await` here since we aren't inside a function? Or does that cause a breakage somewhere else?

2020-11-25 23:37 UTC, Chriscbr commented on src/cli/synth.ts
> +  if (!fs.existsSync(gitFolder)) {
Let's put this logic for creating a github repository (in the if branch) into a separate function.

2020-11-25 23:37 UTC, Chriscbr commented on src/cli/synth.ts
> +        name: 'I don\'t have a git repository and want to make one on Github',
nitpick: Although in this repo we only capitalize the first letter in "github" for class and variable names, for the text printouts I think it's fine to use the proper capitalization "GitHub" 🙂

2020-11-25 23:37 UTC, Chriscbr commented on src/cli/synth.ts
> +        exec(`gh repo create ${gitProjectName}`);
I think it's okay leaving most customizations for the user to setup later, though being able to specify the repository as public/private upfront might be useful. Or at least updating the message above to say "We will make you a _public_ repository on GitHub".

2020-11-25 23:37 UTC, Chriscbr commented on src/cli/synth.ts
> +          formattedGitRepoURL = `https://github/${gitRepoURL}`;
I think this is missing .com

2020-11-25 23:43 UTC, campionfellin commented on src/cli/synth.ts
> +        exec(`gh repo create ${gitProjectName}`);
By specifying nothing, the user gets to choose public .or private interactively


![Nov-25-2020 15-43-10](https://user-images.githubusercontent.com/11984923/100292312-f5963980-2f34-11eb-966a-4743e65e7a24.gif)

2020-11-26 00:10 UTC, campionfellin commented on src/cli/synth.ts
> +    exec('git branch -M main');
In this case since it's the initial commit, I'm making the assumption there isn't any branches and just using `main` as the default

2020-11-26 00:11 UTC, campionfellin commented on src/cli/index.ts
> +  synth(); // eslint-disable-line @typescript-eslint/no-floating-promises
Getting another typescript error with `await` here:

```
Top-level 'await' expressions are only allowed when the 'module' option is set to 'esnext' or 'system', and the 'target' option is set to 'es2017' or higher
```

Though I changed it in the other place!

2020-11-27 23:14 UTC, Chriscbr commented on src/cli/synth.ts
> +        logging.warn('Looks like you do not have the GitHub CLI installed. Please install with \'brew install gh\' and try again.');
This error message would look funny on Linux or Windows -- maybe we can just link to https://cli.github.com/ ?

2020-11-27 23:23 UTC, campionfellin commented on src/cli/synth.ts
> +        logging.warn('Looks like you do not have the GitHub CLI installed. Please install with \'brew install gh\' and try again.');
```suggestion
        logging.warn('Looks like you do not have the GitHub CLI installed. Please go to https://cli.github.com/ to install and try again.');
```

2020-11-28 01:17 UTC, Chriscbr approved these changes
🎉

2020-11-28 01:22 UTC, merged