feat: download artifact workflow step
projen/projen pull request #3365
Opened 2024-02-14 22:29 UTC by vinayak-kukreja

This PR is adding a `download artifact` helper function to create a download artifact workflow step.

Here is the download artifact action for reference: https://github.com/actions/download-artifact?tab=readme-ov-file

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-02-14 22:39 UTC, mrgrain requested changes

2024-02-14 22:39 UTC, mrgrain commented on test/github/__snapshots__/github-workflow.test.ts.snap
> +"
I would have expected this to not be in the template. I think it's because you have added the defaults in to our code. What we usually do, is that we document them with `@default` but don't actually set them in code and rather let GitHub do its thing.

2024-02-14 22:45 UTC, vinayak-kukreja commented on test/github/__snapshots__/github-workflow.test.ts.snap
> +"
Ok, removing it now.

2024-02-15 09:08 UTC, mrgrain approved these changes

2024-02-15 09:25 UTC, merged