feat(bundler): add more esbuild controls, escape hatch
projen/projen pull request #3366
Opened 2024-02-14 22:47 UTC by giseburt

Fixes #3364

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-02-15 15:49 UTC, giseburt commented
I realize I have one property I haven't implemented yet, but I feel it's a fairly powerful option, but it has ramifications:

```typescript
  /**
   * Run compilation using tsc before running file through bundling step.
   * This usually is not required unless you are using new experimental features that
   * are only supported by typescript's `tsc` compiler.
   * One example of such feature is `emitDecoratorMetadata`.
   *
   * @default false
   */
  readonly preCompilation?: boolean;
```

This is inherited from [@aws-cdk-lib/aws-lambda-nodejs](https://github.com/aws/aws-cdk/blob/c3c771c6f6f6790f2298a85a549bded640d2e35b/packages/aws-cdk-lib/aws-lambda-nodejs/lib/bundling.ts#L195) as well. I feel the comment 👆🏻 by @hassanazharkhan (in aws/aws-cdk#16543) describes its usefulness quite well.

The issue here is that the existing option `BundlerOptions.addToPreCompile` (with `@default true`) will put the bundle task *before* compile (in `pre-compile`, actually), but with this new `AddBundleOptions.preCompilation` option (which I see now needs renamed), we want compile *first*, then have `esbuild` bundle the *compiled results*.

Unless anyone objects, I will:
- [ ] Add `BundlerOptions.addToPostCompile`, rename the new and unused `AddBundleOptions.preCompilation` to `AddBundleOptions.bundleCompiledResults` to make it more clear
- [ ] Default `BundlerOptions.addToPostCompile` to `true` and `BundlerOptions.addToPreCompile` to `false` when `AddBundleOptions.bundleCompiledResults` is set to `true` (being careful to not adjust existing default behavior)
- [ ] Throw an error if `AddBundleOptions.bundleCompiledResults` is `true` and `AddBundleOptions.preCompilation` was explicitly set to `true`

2024-02-16 00:14 UTC, giseburt commented
Ok, I believe all new options are implemented and test coverage is complete.

2024-02-16 19:59 UTC, mrgrain commented on src/javascript/bundler.ts
> +  private addToPostCompile?: boolean;
```suggestion
  private readonly addToPreCompile?: boolean;
  private readonly addToPostCompile?: boolean;
```

2024-02-16 20:02 UTC, mrgrain commented on test/javascript/bundler.test.ts
> +
```suggestion
```

2024-02-16 20:03 UTC, mrgrain commented on test/javascript/bundler.test.ts
> +test("bundleCompiledResults  fails if both addToPreCompile and addToPostCompile are set", () => {
```suggestion
test("bundleCompiledResults fails if both addToPreCompile and addToPostCompile are set", () => {
```

2024-02-16 20:04 UTC, mrgrain commented on test/javascript/bundler.test.ts
> +      addToPostCompile: true,
Is this ever valid? I feel like this should already throw when NodeProject is instantiated.

2024-02-16 20:05 UTC, mrgrain commented on test/javascript/bundler.test.ts
> +test("bundleCompiledResults fails if bundleCompiledResults are set (later)", () => {
I don't understand what this test is trying to test. Can you help me out by adding `//GIVEN` `//WHEN` & `//THEN` comments and explain in comments what should happen and why.

2024-02-16 20:07 UTC, mrgrain commented on test/javascript/bundler.test.ts
> +  p.bundler.bundleTask;
I've seen this a few times. What's up with it? Is this unsuspecting property access call actually mutating something?

2024-02-16 20:20 UTC, mrgrain requested changes
This looks great, thank you!  I've left feedback on a few minor things.

The biggest change would be how we are handling `addToPre/PostCompile`. I appreciate the effort to make this just work, but I think it unintentional ended up being a bit complicated and opaque.

I think what we have here is a three-way decision:

```ts
enum RunBundleTask {
  /**
   * Don't bundle automatically as part of the build.
   */
  MANUAL: "manual",
  /**
   * Bundle automatically before compilation.
   */
  PRE_COMPILE: "pre_compile",
  /**
   * Bundle automatically after compilation. Set this when using....
   */
  POST_COMPILE: "post_compile",
}


interface BundlerOptions {
  // ...

  /**
   * 
   * @default RunBundleTask.MANUAL
   */
  runBundleTask?: RunBundleTask;
}
```

And then throw and error when`options.runBundleTask != RunBundleTask.POST_COMPILE` and `bundleCompiledResults` is set.

We can keep backwards compatibility by setting something like `this.runBundleTask = options.runBundleTask ?? (options.addToPreCompile ? RunBundleTask.PRE_COMPILE : RunBundleTask.MANUAL)`.

What do you think?

2024-02-16 20:26 UTC, mrgrain commented on src/javascript/bundler.ts
> +  private addToPostCompile?: boolean;
Ah I see now why you did it. Sorry this breaking your PR. I'll revert. 😂

2024-02-16 20:27 UTC, mrgrain commented on src/javascript/bundler.ts
> +  private readonly addToPostCompile?: boolean;
```suggestion
  private addToPreCompile?: boolean;
  private addToPostCompile?: boolean;
```

2024-02-16 21:57 UTC, giseburt commented on test/javascript/bundler.test.ts
> +  p.bundler.bundleTask;
Yeah, this will be cleaned up by your main suggestion.

2024-02-16 23:20 UTC, giseburt commented
Thank you for the review!

Looking over your comments, I realize that `addToPreCompile` is completely redundant, and can be removed when moving to `RunBundleTask` as you suggested.

I'm making two minor adjustments:
- Marking `addToPreCompile` as `@depricated` due to the redundancy
- To ensure not breaking downstream, if neither `runBundleTask` nor `addToPreCompile` are defined, assume `RunBundleTask.PRE_COMPILE` as before

I just pushed the new code.

One other note: I'd like to provide more control over the bundle task name. For example, since I switched to `./lib/hello.js` from `./src/hello.ts` then bundle task name changed to `bundle:lib/hello` and I'd prefer to use `bundle:hello` or in fact I may prefer to call it `bundle:production` or whatever. Should I put that in this PR and make another after this? I think it'll be a few lines of code and twice that many of comments/docs.

2024-02-16 23:45 UTC, mrgrain commented
>  Should I put that in this PR and make another after this? I think it'll be a few lines of code and twice that many of comments/docs.

I always prefer separate PRs to keep things moving and independent.

2024-02-16 23:50 UTC, mrgrain approved these changes

2024-02-17 00:04 UTC, merged