feat: sequences
projen/projen pull request #337
Opened 2020-11-26 02:37 UTC by eladb

Sequences are a project-level feature to define a project command system backed by shell scripts. Sequences are synthesized into a spec stored in `.projen/xxx.seq.json` files , where `xxx` is the sequence name.

The `projen` CLI automatically discovers these files and extends the CLI to support executing and inspecting these sequences.

For example:

```ts
const seq = project.addSequence('hello');
seq.add('echo "hello, world!"');
```

Will result in a new CLI command called `hello` to be introduced:

```shell
$ projen hello
-----------------------------------------
hello: echo "hello, world!"
hello, world!
```

The CLI also allows you to inspect the command:

```shell
$ projen hello -i
echo "hello, world!"
```

If you inspect the `build` command of the projen project, it looks like this:

```shell
compile:
  npm exec -- tsc
  npm exec -- jsii-docgen
test:
  npm exec -- jest --passWithNoTests --updateSnapshot
  eslint:
    npm exec -- eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src test
package:
  npm exec -- rm -fr dist
  npm exec -- mkdir -p dist/js
  npm exec -- yarn pack
  npm exec -- mv *.tgz dist/js/
readme-macros:
  npm exec -- mv README.md README.md.bak
  npm exec -- cat README.md.bak | npx markmac > README.md
  npm exec -- rm README.md.bak
```

Sequences can invoke each other, so we are starting to model some relationships between sequences.

In the roadmap, we will be able to also model cause->effect information and basically implement a makefile-like build system based on hash or timestamp checks.

All npm scripts from the `NodeProject` heirarchy were converted to use sequences instead of `addScript()` and `addScriptCommand()`.

BREAKING CHANGE: This is (surprisingly) not a breaking change. It likely has bugs, but from a project workflow perspectice (as in using things like `yarn build`, it should continue to work (the npm script will delegate to the sequence).
* The `addScript()` method no longer supports adding start-menu items. To do that, just convert your code to use `addSequence()`. It should be straightforward. `addScript()` can still be used to add just npm scripts that are not advertised as sequences.
* The `addScriptCommand()` method was removed. Use `addSequence()` instead.

---

TODO:

- [ ] Tests
- [ ] Clean up
- [ ] Test with a bunch of projects

2020-11-26 02:41 UTC, eladb commented on src/cli/index.ts
> +function addBuildCommands(ya: yargs.Argv) {
```suggestion
function addSequences(ya: yargs.Argv) {
```

2020-11-27 00:10 UTC, Chriscbr commented
At a high level I like this - it's pretty similar to what I imagined when you mentioned moving command logic outside of package.json. (I see there is still a "start" section - not sure if it can be removed, but it's not a big deal to me.)

That said, I'm a little iffy on expanding the scope of ownership of the library to handle build logic.

> In the roadmap, we will be able to also model cause->effect information and basically implement a makefile-like build system based on hash or timestamp checks. 

Is modeling dependency information and artifact-invalidation logic is something that should fall under projen? (If that is the goal, maybe this feature should be renamed to "trees" or "graphs" instead of "sequences"?)

Although I don't have a lot of hands-on experience, I know there are a *lot* of tools that try to solve this problem (bazel, cmake, gradle, gulp, grunt, ninja, ...). So, I'm just not sure if it might be more worthwhile to limit the scope of projen's build/script responsibilities to just being an "interface" for other build/script tools (without modeling dependencies/artifacts). That is, invest efforts in supporting existing build tools rather than creating a new build system from scratch.

Also, this PR makes it much harder for people to "eject" projen from their repo if they wanted to. We are essentially losing that feature with package.json "scripts" only referring to projen commands. I don't think this should be overlooked.

...That said, I have a lot less industry experience / might not have the right background knowledge to appreciate this feature (or might be overestimating the amount of complexity or optimization that actually exist in the build tools I mentioned), so take this with a heavy grain of salt. :-)  There could also be other benefits of this that I'm underestimating (like defining dependency-based build scripts between subprojects perhaps). What are your thoughts?

Also, interfacing with commands through "pj \<cmd\>" looks great / makes a lot of sense.

2020-11-28 18:15 UTC, pgollucci commented
I agree; however, I think the Level of Effort to migrate to or from projen is pretty low

2020-11-28 18:20 UTC, pgollucci commented
It builds over here.  Lets see if I can use it somewhere.

2020-11-28 18:31 UTC, pgollucci commented
So we're now committing to the `targets`? I'm not sure that was what was intended.  I can still work around this making a 'pre-build' 'hook' and then just making a wrapper to make sure they get called in sequence! ha, see what I did there!

The first thing I notice is I used to use `prependScriptCommand()` from #283, except I didn't b/c it never got merged, so I overrode build and I converted that to this

```ts
project.addSequence('build', {
  description: "builds it",
  shell: "bin/smilectl conf_merge && yarn run test && yarn run compile && yarn run synth",
});
```

```shell
pjp

🤖 Synthesizing project...
/Users/pgollucci/src/github.com/pgollucci/projen/lib/seqs/seq.js:160
            throw new Error(`duplicate sequence "${name}"`);
            ^

Error: duplicate sequence "build"
    at Sequences.addSequenceSpec (/Users/pgollucci/src/github.com/pgollucci/projen/lib/seqs/seq.js:160:19)
    at new Sequence (/Users/pgollucci/src/github.com/pgollucci/projen/lib/seqs/seq.js:27:23)
    at AwsCdkTypeScriptApp.addSequence (/Users/pgollucci/src/github.com/pgollucci/projen/lib/project.js:99:16)
    at AwsCdkTypeScriptApp.addSequence (/Users/pgollucci/src/github.com/pgollucci/projen/lib/node-project.js:454:27)
    at Object.<anonymous> (/Users/pgollucci/src/github.com/trexsolutions/smile-cdk/.projenrc.js:79:9)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
```

2020-11-28 19:12 UTC, pgollucci commented
So I've "converted" something over. `projen build` and `projen build -i` do the right thing. but `yarn build` which forwards to`projen build` does nothing.

```shell
yarn run build
yarn run v1.22.10
$ yarn run projen build
$ projen build
✨  Done in 0.50s.
```

2020-11-29 08:00 UTC, eladb commented
@Chriscbr good points about "projen ejection" and about leveraging existing build tools. I've been thinking about these topics, and I am trying to decide what to do. 

Perhaps the right direction is indeed to implement Sequences as an abstract interface with a pluggable backend (with a the current implementation as the base case perhaps), and allow build systems to be plugged-in. One such backing implementation could be to simply run those commands within npm scripts, to serve the "projen ejection" use case.

Naturally there is nothing the precludes simply using any build system behind those sequences...

Perhaps the correct abstraction, which is more inline with what this is currently about is to rename this to "Commands" and focus more on the CLI extension experience and less on the actual execution engine.

@pgollucci I'll have a look to see why this is not working as intended.

Let me revise and get back to you.

2020-11-29 14:30 UTC, eladb commented
@pgollucci wrote:

> So I've "converted" something over. projen build and projen build -i do the right thing. but yarn build which forwards toprojen build does nothing.

This is because you are using a local build of projen which gets overridden during synthesis when yarn installs the actual dependency. Simply run `yarn link projen` in order to restore the local link before `projen build` and you should be golden.

2020-11-29 14:41 UTC, eladb commented
@Chriscbr 

I understand there are many tools for implementing development workflows and builds but I'm a bit hesitant at the moment to take a strong dependency on one of them. And one of the goals of "tasks" is to be a unified command system for all projen projects. I am absolutely open if anyone is interested in offering a good execution engine for tasks, and we can easily switch up the underlying implementation.

I've also been thinking about the "eject" scenario and I think that we should formalize it. At the moment, it is merely a side-effect of how projen works, but it's not officially supported and requires manual tweaking. Let's add official support for ejecting projects (LOVE the term by the way!) which will perform the necessary changes. Namely: (1) make all files read-write; (2) remove projen markers; and (3) convert tasks to npm scripts.

The latter (convert tasks to npm scripts) can also be something we support as a switch if people are interested in "flattening" their tasks into npm scripts. We can do this quite easily today with the tasks model (simply synthesize the script content by concatenating all the commands in a task).

In the meantime, I am going to leave this like this (npm scripts delegate to projen commands), and see what people are thinking.

2020-11-30 00:15 UTC, eladb commented on src/node-project.ts
> +   */
Add default

2020-11-30 00:17 UTC, eladb commented on src/node-project.ts
>      if (options.start ?? true) {
just deprecate this

2020-11-30 00:20 UTC, eladb commented on src/project.ts
> -    const start = this.components.find(c => c instanceof Start);
Yes, these were intentionally removed

2020-11-30 00:22 UTC, eladb commented on src/tasks/task.ts
> +  readonly skipIf?: string;
Not implemented yet

2020-11-30 00:23 UTC, eladb commented on src/tasks/task.ts
> +  public static readonly MANIFEST_FILE = join(PROJEN_DIR, 'tasks.json');
Do we need this here?

2020-11-30 00:23 UTC, eladb commented on src/tasks/task.ts
> +  public readonly tasks: Tasks;
Make private

2020-11-30 00:25 UTC, eladb commented on src/tasks/tasks.ts
> +  public env(name: string, value: string) {
`addEnv`?

2020-11-30 00:29 UTC, eladb commented
@Chriscbr @pgollucci this is ready for another look if you are interested. I think the changes to `node-project.ts` can be a good way to see the full picture.

2020-11-30 01:21 UTC, Chriscbr requested changes
Cool! 👍  Yeah I don't think I would have suggested committing to any external build tool at this time (and even in the future, it might not be that advisable). And I agree, having project ejection as a separate operation is just as satisfactory. I think by keeping that as a feature, it might also have the side effect of keeping the complexity of this task system in check, in some respect.

2020-11-30 01:21 UTC, Chriscbr commented on src/tasks/task.ts
> +  public readonly tasks: Tasks;
What is this field for?

2020-11-30 07:20 UTC, eladb commented on .projenrc.js
> +  npmTaskExecution: NpmTaskExecution.SHELL,
Add comment for why this is needed

2020-11-30 07:20 UTC, eladb commented on package.json
> +    "bump": "standard-version",
No-changes is missing here

2020-11-30 07:20 UTC, eladb commented on src/jsii-docgen.ts
> +    project.compileTask.exec('jsii-docgen');
Delegate to docgen instead of run manually

2020-11-30 07:20 UTC, eladb commented on src/jsii-project.ts
> +    const compatCmd = this.addTask('compat', {
```suggestion
    const compatTask = this.addTask('compat', {
```

2020-11-30 07:20 UTC, eladb commented on src/node-project.ts
> -  readonly startOptions?: StartOptions;
Mention in breaking changes

2020-11-30 07:20 UTC, eladb commented on src/node-project.ts
> +  public readonly compileTask: Task;
Docstrings

2020-11-30 07:20 UTC, eladb commented on src/node-project.ts
> +  public addBuildCommand(...commands: string[]) {
Add @deprecation

2020-11-30 07:20 UTC, eladb commented on src/project.ts
> +  public findJsonFile(filePath: string): JsonFile | undefined {
TryFind

2020-11-30 07:20 UTC, eladb commented on src/projen-upgrade.ts
>        if (!project.github) {
Strong-reference task within workflow

2020-11-30 07:20 UTC, eladb commented on src/tasks/runtime.ts
> +  public readonly manifest: TaskManifest;
Docstrings

2020-11-30 07:20 UTC, eladb commented on src/tasks/runtime.ts
> +  public find(name: string): TaskSpec | undefined {
TryFind

2020-11-30 07:20 UTC, eladb commented on src/tasks/runtime.ts
> +        }
Then it will have its own header. The logs currently won't reflect the hierarchy.

Let me see what I can do

2020-11-30 07:20 UTC, eladb commented on src/tasks/runtime.ts
> +  private renderRuntimeEnvironment(env: {[k: string]: string}, cwd: string) {
Docstring

2020-11-30 07:20 UTC, eladb commented on src/tasks/task.ts
> +  public readonly tasks: Tasks;
Not sure. Maybe I can remove. Let me check

2020-11-30 07:20 UTC, eladb commented on src/typescript-typedoc.ts
> +    project.addTask('docgen', {
Shouldn't this also be part of "build"?

2020-11-30 07:20 UTC, eladb commented on src/version.ts
> +      skipIf: noChanges,
Implement

2020-11-30 07:20 UTC, eladb commented on src/web/react.ts
> +      description: 'Ejects your React application from react-scripts',
Lol didn't know they have that

2020-12-01 06:48 UTC, eladb commented on src/tasks/task.ts
> +  public readonly tasks: Tasks;
It's needed in order to be able to resolve subtasks

2020-12-01 06:49 UTC, eladb commented on src/tasks/runtime.ts
> +        }
Fixed.

2020-12-01 08:45 UTC, merged

2020-12-01 14:01 UTC, Chriscbr commented
🎉

2020-12-01 14:30 UTC, eladb commented
> 🎉 

Thanks for all the feedback. Lmk what you think about the result.

2020-12-01 23:53 UTC, Chriscbr commented
It's great! Love how the printouts with chevrons look. I could nitpick a few things, like the name "spawn" feels a bit weird compared to "subtask", and giving RunTask a constructor with a side effect seems like nonstandard from a Java background (where having an execute() or run() method would be more common I think - also maybe rename it `TaskRunner`?)

But the rest of the changes makes sense. I think the real test would be seeing how well it plays with a module in another language, e.g. `PythonProject` (something I've been wanting to experiment with at some point, but it would take a bit of research).

2020-12-02 01:35 UTC, pgollucci commented
I understand that I can do `project.buildTask.spawn(foo) to` run something after the existing build but what about BEFORE?

2020-12-02 01:36 UTC, pgollucci commented
> I understand that I can do `project.buildTask.spawn(foo) to` run something after the existing build but what about BEFORE?

This one is going to take a minute for $work.

2020-12-02 01:37 UTC, pgollucci commented
The npx projen and simpler scripts in package.json is quite sweet

2020-12-02 01:39 UTC, pgollucci commented
It looks like yarn run became npx regardless of the `packageManager` setting, I assume that was intentional?

2020-12-02 01:41 UTC, pgollucci commented
Based on the `projen/projen` repo it looks like we are meant to commit `.projen/` dir. I don't have an issue with this, but it does open up the possibility we will write a secret to it which someone will then commit.

2020-12-02 01:47 UTC, pgollucci commented
> Based on the `projen/projen` repo it looks like we are meant to commit `.projen/` dir. I don't have an issue with this, but it does open up the possibility we will write a secret to it which someone will then commit.
I guess they would have already been in .projenrc.js so n/m

2020-12-02 10:35 UTC, eladb commented
@Chriscbr I tend to agree about `spawn`. I was looking for a verb and that's why `subtask` didn't work. How about `execTask()`?

2020-12-02 13:08 UTC, Chriscbr commented
@eladb I think they're equally good.

2020-12-02 13:24 UTC, eladb commented
> Based on the `projen/projen` repo it looks like we are meant to commit `.projen/` dir. I don't have an issue with this, but it does open up the possibility we will write a secret to it which someone will then commit.

Since projen manages your gitignore file, it should be included in your repo