fix(python): update `pyproject.toml` structure for `PythonProject` using Poetry
projen/projen pull request #3375
Opened 2024-02-17 19:07 UTC by garysassano

[Poetry 1.2.0](https://python-poetry.org/blog/announcing-poetry-1.2.0/) introduced the `group` notation for managing dependencies, which has been the recommended way to organize dependencies inside your `pyproject.toml` file for almost two years. The older `dev-dependencies ` notation was deprecated, as detailed [here](https://python-poetry.org/docs/master/managing-dependencies/), and its use is discouraged.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-02-19 10:14 UTC, mrgrain commented on src/python/poetry.ts
> +        requires: ["poetry-core"],
Given that we now require poetry >= 1.2.0 we should probably keep that in there.

2024-02-19 10:16 UTC, mrgrain requested changes
Can you also mark this as a breaking change with a note how to resolve it (ie. upgrade poetry). Thanks!

2024-02-19 10:30 UTC, garysassano commented on src/python/poetry.ts
> +        requires: ["poetry-core"],
No, [poetry-core](https://github.com/python-poetry/poetry-core) is just the build system which is part of [poetry](https://github.com/python-poetry/poetry). It's a component which is kept separate so that other projects can make use of it.

What you want to do is currently not possible, despite being a feature that people have been asking for quite a long time as you can see from [this open issue](https://github.com/python-poetry/poetry/issues/3316).

2024-02-19 10:33 UTC, garysassano commented on src/python/poetry.ts
> +        requires: ["poetry-core"],
It's a very common misconception, one that I also fell for in the past.

2024-02-22 09:43 UTC, mrgrain requested changes

2024-02-22 09:43 UTC, mrgrain commented on src/toml.ts
> +    // Convert JSON content to TOML string
This seems entirely unrelated to this PR. Please keep it separate

2024-02-22 13:30 UTC, garysassano commented on src/toml.ts
> +    // Convert JSON content to TOML string
How is it unrelated? Without modifying `toml.ts`, the formatting results in odd indentation that does not align with a fresh `pyproject.toml` file generated by `poetry init`. The aim is to produce a file through projen that appears as though it was directly created by poetry.

2024-02-22 14:01 UTC, mrgrain commented on src/toml.ts
> +    // Convert JSON content to TOML string
None of that is described in the PR or explicitly tested aside from the snapshot. I'd expect a bit of a write up about that and some investigation/reasoning why there is a discrepancy. 

Additionally I'm not at all convinced that that string manipulation is the right approach here. If the current TOML library is not capable of producing the desired output we will have to look for an alternative one. Swapping out the TOML package will definitely require a separate PR.

tl;dr All this just prevents a perfectly fine fix from being merged.

2024-02-24 08:29 UTC, mrgrain approved these changes

2024-02-24 08:38 UTC, merged