feat: add error handling and better messaging for --from flag
projen/projen pull request #3385
Opened 2024-02-22 15:40 UTC by adamelkhayyat

Improvement to error handling and error messages thrown in cases where `--from` flag is used (ex: `npx projen new --from [SPECIFIED0NPM-PACKAGE]`).

This PR covers the cases:
* where npm package specified does not exist in the registry and gracefully handles error with informative message to user
* where npm package specified is not jsii module and gracefully handles error with informative message to user

Fixes #https://github.com/projen/projen/issues/3303

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-02-26 14:29 UTC, mrgrain commented on src/cli/util.ts
> +      return undefined;
```suggestion
      // the provided module is not a jsii module
      return undefined;
```

2024-02-26 14:33 UTC, mrgrain commented on src/cli/util.ts
> +    logging.info(`Validating external module's (${module}) existence...`);
I don't think this needs to be visible in the regular logs.
```suggestion
    logging.debug(`Checking if external module '${module}' exists...`);
```

And maybe also add a debug log for the various result cases.

2024-02-26 14:34 UTC, mrgrain commented on src/cli/util.ts
> +      return fs.existsSync(module);
What is this case covering? Local file?

2024-02-26 14:40 UTC, mrgrain commented on src/cli/util.ts
> +    const externalModule = !module.startsWith("./");
This feels like a new restriction. We might have to find out how `npm` does the disambiguation.

2024-02-26 14:43 UTC, mrgrain commented on src/cli/cmds/new.ts
> +      `Cannot find '${moduleName}/.jsii', ensure this is a jsii module first!`
Something like this maybe?
```suggestion
      `Module '${moduleName}' does not look like it is compatible with projen. Reason: Cannot find '${moduleName}/.jsii'. All projen module must be jsii modules!`
```

2024-02-26 14:43 UTC, mrgrain requested changes
I'm excited by this! A few minor notes.

2024-02-27 11:26 UTC, adamelkhayyat commented on src/cli/util.ts
> +      return fs.existsSync(module);
This covers the case when you reference a local tarball (using `npm pack [dep]`).

2024-02-27 12:21 UTC, adamelkhayyat commented on src/cli/util.ts
> +    const externalModule = !module.startsWith("./");
I looked into this further and I believe if I extend the function to check if the module starts with `./` or `/` (absolute paths) it should cover all cases where we're referencing a local file to install with `npm`.

Example installing a local package `some-local-package`:
- `npm install some-local-package` - ❌ Errors out as it attempts to find the package in registry
- `npm install /some-local-package` - ❌ Errors out as it expects absolute path, incomplete absolute path
- `npm install ./some-local-package` - ✅ reference a file that is in the root of the project
- `npm install --from /Users/adam.el-khayyat/Documents/personal-projects/testing-npm-pack/some-local-package`  - ✅ reference via absolute path

💡 I'd also need to adjust the code to accommodate Windows when checking if the local package/file exists (`\` path separator).

Please challenge my conclusion above if you see anything I might've missed or any flaws and I'll adjust as needed!

2024-02-28 11:42 UTC, mrgrain commented on src/cli/util.ts
> +    const externalModule = !module.startsWith("./");
This works for me:

```
npm install some-local-package.tgz
```

2024-02-29 13:28 UTC, mrgrain commented on src/cli/util.ts
> +    const externalModule = !module.startsWith("./");
I think if we extend this test case: https://github.com/projen/projen/blob/main/test/new.test.ts#L122
to run

- without `./` in front
- resolving to an absolute path

we should have tests for most cases

2024-02-29 14:23 UTC, adamelkhayyat commented on src/cli/util.ts
> +    const externalModule = !module.startsWith("./");
> I think if we extend this test case: https://github.com/projen/projen/blob/main/test/new.test.ts#L122 to run
> 
> * without `./` in front
> * resolving to an absolute path
> 
> we should have tests for most cases

In that case we can check if the `module` ends in `.tgz` (and ensure the tarball exists) and we'll cover all existing test cases.

However, this function will return `false` if the `module` references a local project (example: `/Users/adam.el-khayyat/Documents/projects/my-projen-project`) that isn't a tar file compressed and cause a misleading error that the module doesn't exist.

2024-02-29 14:26 UTC, adamelkhayyat commented on src/cli/util.ts
> +    const externalModule = !module.startsWith("./");
I've extended the function in https://github.com/projen/projen/pull/3385/commits/00ddc146dc9d7018e24475b082cf29e4f75d6da4 to check all conditions to determine if the module is a local one and changed one test based on your comment, let me know if this covers it well enough!

2024-03-01 15:09 UTC, mrgrain commented on src/cli/util.ts
> +    const externalModule = !module.startsWith("./");
@adamelkhayyat I'd prefer if we have dedicated tests for all 3 cases, i.e. the existing one plus two new variations.

2024-03-01 15:25 UTC, adamelkhayyat commented on src/cli/util.ts
> +    const externalModule = !module.startsWith("./");
Got it, wanted to confirm the approach first and then write the additional tests.

I'll try to get to this sometime this weekend!

2024-03-03 10:57 UTC, adamelkhayyat commented on src/cli/util.ts
> +    const externalModule = !module.startsWith("./");
@mrgrain, I've added tests in https://github.com/projen/projen/pull/3385/commits/452d9ef840f56db1a970e63914845b4a644c0661, please let me know what you think!

2024-03-03 11:10 UTC, adamelkhayyat commented on src/cli/util.ts
> +    const externalModule = !module.startsWith("./");
Note: absolute path test is failing on CI, I'll try to address this sometime this coming week.

2024-03-04 10:30 UTC, mrgrain commented on test/new.test.ts
> +      )}`,
This should do it
```suggestion
      `${resolve(
        projectdir,
        "pepperize-projen-awscdk-app-ts-0.0.333.tgz"
      )}`,
```

2024-03-04 10:52 UTC, mrgrain commented
Thanks @adamelkhayyat I think I can take it from here!

2024-03-04 10:53 UTC, mrgrain approved these changes

2024-03-04 11:00 UTC, mrgrain approved these changes

2024-03-04 11:05 UTC, merged