feat(core): add CLI switch for post synthesis
projen/projen pull request #339
Opened 2020-11-27 10:40 UTC by Chriscbr

Fixes #322 

- Add CLI options --post and --no-post to enable or disable post-synthesis operations (such as installing node dependencies) during `yarn projen` or `npx projen new <project>` commands.
- Update several tests to disable post-synthesis operations, reducing the total testing runtime from ~44s to ~11s (about 75%)

2020-11-29 10:04 UTC, eladb requested changes

2020-11-29 10:04 UTC, eladb commented on src/cli/cmds/new.ts
> +    process.env.POST_SYNTHESIS_ENABLED = args.post.toString();
Rename (and reverse logic) to `PROJEN_DISABLE_POST`

We want the lack of this defined to be the default behavior.

2020-11-29 10:04 UTC, eladb commented on src/cli/index.ts
> +  .option('post', { type: 'boolean', default: true, desc: 'Run post-synthesis steps such as installing dependencies' })
```suggestion
  .option('post', { type: 'boolean', default: true, desc: 'Run post-synthesis steps such as installing dependencies. Use --no-post to skip' })
```

2020-11-29 10:04 UTC, eladb commented on test/toml.test.ts
> +  const out = synthSnapshot(prj, true);
Let's make `synthSnapshot` default to skipping post synthesis and add `synthSnapshotWithPost` for the cases where it's desired.

2020-11-30 07:17 UTC, Chriscbr commented on src/cli/cmds/new.ts
> +    process.env.POST_SYNTHESIS_ENABLED = args.post.toString();
Done

2020-11-30 07:25 UTC, eladb commented on src/project.ts
> +    if (process.env.PROJEN_DISABLE_POST !== 'true') {
I usually like `1` to also be a valid truthy value for boolean environment variables.

2020-11-30 07:25 UTC, eladb approved these changes

2020-11-30 07:26 UTC, merged