fix(python): generated `pyproject.toml` has correct formatting style when using Poetry
projen/projen pull request #3405
Opened 2024-02-27 11:35 UTC by garysassano

This PR fixes the following issues:
- TOML sections indentation (.e.g `[tool.poetry.dependencies]` section)
- Spaces surrounding string values within square brackets (e.g. `[ "poetry-core" ]`)

#### pyproject.toml (before)
```toml
# ~~ Generated by projen. To modify, edit .projenrc.py and run "npx projen".

[tool.poetry]
name = "example"
version = "0.1.0"
description = ""
authors = [
  "First Last <email@example.com>"
]
readme = "README.md"

  [tool.poetry.dependencies]
  aws-cdk-lib = "^2.130.0"
  constructs = "^10.0.5"
  python = "^3.8"

[tool.poetry.group.dev.dependencies]
projen = "0.80.1"
pytest = "7.4.3"

[build-system]
requires = [ "poetry-core" ]
build-backend = "poetry.core.masonry.api"
```

#### pyproject.toml (after)
```toml
# ~~ Generated by projen. To modify, edit .projenrc.py and run "npx projen".

[tool.poetry]
name = "example"
version = "0.1.0"
description = ""
authors = [
  "First Last <email@example.com>"
]
readme = "README.md"

[tool.poetry.dependencies]
aws-cdk-lib = "^2.130.0"
constructs = "^10.0.5"
python = "^3.8"

[tool.poetry.group.dev.dependencies]
projen = "0.80.1"
pytest = "7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-02-27 11:44 UTC, mrgrain requested changes
We are not going to bundle 2 TOML libraries. This will have to get rid of the previous one as well.

2024-03-01 02:47 UTC, garysassano commented
@mrgrain The `json2toml` module just does a one-way conversion from JSON to TOML, it's not able to parse TOML and convert it to a JS Object, which is used in the latest test I've added.

2024-03-01 02:48 UTC, garysassano commented
The `json2toml` module just does a one-way conversion from JSON to TOML, it's not able to parse TOML and convert it to a JS Object, which is used in the latest test I've added.

2024-03-01 02:48 UTC, garysassano commented
The `json2toml` module just does a one-way conversion from JSON to TOML, it's not able to parse TOML and convert it to a JS Object, which is done in the latest test I've added.

2024-03-01 02:53 UTC, garysassano commented
The `json2toml` module just does a one-way conversion from JSON to TOML, it's not able to parse TOML and convert it to a JS Object, which is used to check the generated `pyproject.toml` in several tests.

2024-03-01 11:24 UTC, mrgrain commented
> The `json2toml` module just does a one-way conversion from JSON to TOML, it's not able to parse TOML and convert it to a JS Object, which is used to check the generated `pyproject.toml` in several tests.

We can move `@iarna/toml` to be a unbundled test dependency then, right?

2024-03-04 10:59 UTC, mrgrain requested changes
One last thing: Let's keep the snapshot.

2024-03-04 10:59 UTC, mrgrain commented on test/python/poetry.test.ts
> -  expect(snapshot["pyproject.toml"]).toMatchSnapshot();
Can we keep the snapshot please?

These help maintainers understanding changes better.

2024-03-04 10:59 UTC, mrgrain commented on test/python/poetry.test.ts
> +      `package2@{ path = "../mypackage/foo" }`,
I don't mind this, but this seems like an entirely unnecessary change (both the spaces and the change in quotes). In future please try to not make these changes. They add no value and only create noise and work for reviewers.

2024-03-04 15:40 UTC, mrgrain approved these changes

2024-03-04 15:42 UTC, merged

2024-03-06 01:49 UTC, automartin5000 commented
This one's been annoying me for a while, thanks @garysassano!

2024-03-07 00:12 UTC, agdimech commented
This PR is causing issues as it doesn't cater for all cases (comma splitting is to blame) https://github.com/projen/projen/issues/3426

2024-03-07 09:53 UTC, mrgrain commented
Hi all, this was just reverted. Apologies for accepting this PR in the first place. I had missed that the new method `permitTomlInlineTableDeps` is effectively attempting to implement TOML parsing.

Let's be very clear that going forward, we are only going to accept a contribution that (in it's essence) only swaps out the calls to `TOML.stringify()` and `TOML.parse()` with a different version from a well regarded library.

I appreciate that this might be a very high bar, given that this library also has to match our licensing requirements.