fix(docs): link to GitHub API reference
projen/projen pull request #3434
Opened 2024-03-08 14:24 UTC by froblesmartin

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-03-08 16:38 UTC, mrgrain requested changes

2024-03-08 16:38 UTC, mrgrain commented on docs/integrations/github/index.md
> +See the `GitHub`, `GithubWorkflow`, and `Job` types in the [GitHub](/docs/api/github/) and [GitHub Workflow](/docs/api/github.workflows/) API references for currently available APIs.
This needs to link to the respective markdown files. The URl is converted during the docs page build.

2024-03-11 22:13 UTC, froblesmartin commented on docs/integrations/github/index.md
> +See the `GitHub`, `GithubWorkflow`, and `Job` types in the [GitHub](/docs/api/github/) and [GitHub Workflow](/docs/api/github.workflows/) API references for currently available APIs.
Okay! Done 😉

2024-03-12 20:35 UTC, mrgrain approved these changes

2024-03-12 20:52 UTC, merged