fix: upgrade-dependencies should (ncu) upgrade packages with ^ (non-pinned), and NOT upgrade pinned packages (without ^)
projen/projen pull request #3463
Opened 2024-03-18 16:47 UTC by dkershner6

Fixes https://github.com/projen/projen/issues/3462

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-03-18 16:57 UTC, mrgrain requested changes

2024-03-18 16:57 UTC, mrgrain commented on test/javascript/upgrade-dependencies.test.ts
> -    deps: ["some-dep@^10"],
I don't understand why this test needs changing

2024-03-18 18:28 UTC, dkershner6 commented on test/javascript/upgrade-dependencies.test.ts
> -    deps: ["some-dep@^10"],
I added a more comprehensive function to handles this determination as well as explanatory comments and JSDoc.

2024-03-18 18:28 UTC, dkershner6 commented
I gave `allowMinorUpgrades` a shot, @mrgrain , let me know your thoughts.

2024-03-27 09:34 UTC, mrgrain commented on src/javascript/upgrade-dependencies.ts
> +    const parts = version.split(".").filter((ver) => ver !== "x");
```suggestion
    const parts = version.split(".").filter((ver) => ver !== "x" && ver !== "*");
```

2024-03-27 09:36 UTC, mrgrain commented on test/javascript/upgrade-dependencies.test.ts
> +test("upgrade command does not include non-standard dependency versions", () => {
Can you make this a bit more descriptive? I don't understand what the test non-standard dependency versions are

2024-03-27 09:42 UTC, mrgrain commented on test/javascript/upgrade-dependencies.test.ts
> +test("ncu upgrade command should include dependencies with non-pinned versions, along with package manager upgrade", () => {
This test is the opposite of what we are trying to achieve here.

`some-dep` has a version constraint define. Therefore projen will ALWAYS write the version constraint back to `package.json`, therefor running `ncu` to update the version constraint in `package.json` is pointless because projen will ALWAYS override it again. However `yarn upgrade` et. al. will make sure that the latest version according to the constraint is installed.

2024-03-27 09:44 UTC, mrgrain requested changes
Something still isn't quite right. Appreciate the issue has changed a bit and a I'm not sure if you have updated the title and code yet in all places. But I'm really missing a simple test case for the problem you are trying to solve.

2024-03-29 16:51 UTC, dkershner6 commented
Alright, @mrgrain , I think we are on the same page now. Please confirm.

2024-04-01 10:43 UTC, mrgrain commented on src/javascript/upgrade-dependencies.ts
> +      // remove those that have a pinned version (unless includeConstraint is true)
```suggestion
      // remove those that have a constraint version (unless includeConstraint is true)
```

2024-04-01 10:45 UTC, mrgrain commented on test/javascript/upgrade-dependencies.test.ts
> +    deps: ["some-dep@10.0.0"],
```suggestion
    deps: ["some-dep@^10", "other-dep@10.0.0"],
```

2024-04-01 10:47 UTC, mrgrain commented on test/javascript/upgrade-dependencies.test.ts
> +    deps: ["some-dep@10.0.0"],
Same as above

```suggestion
    deps: ["some-dep@^10", "other-dep@10.0.0"],
```

2024-04-01 10:49 UTC, mrgrain commented on src/javascript/upgrade-dependencies.ts
> +  private packageIsUsingDefaultVersioning(
Let's give this a more descriptive name
```suggestion
  private isProjenManagedVersion(
```

2024-04-01 10:51 UTC, mrgrain commented on src/javascript/upgrade-dependencies.ts
> +  }
Let's give this a more descriptive name
```suggestion
  private isProjenManagedVersion(
    version: string | undefined
  ): boolean {
    // No version means "latest"
    return version && version !== "*";
  }
```

2024-04-01 10:51 UTC, mrgrain commented on src/javascript/upgrade-dependencies.ts
> +          includeConstraint || this.packageIsUsingDefaultVersioning(d.version)
```suggestion
          includeConstraint || !this.isProjenManagedVersion(d.version)
```

2024-04-01 10:52 UTC, mrgrain requested changes
Yes we are ineeded. @dkershner6 Thanks for working through this! Just some minor comments on the naming/tests. Otherwise good to go.

2024-04-03 15:44 UTC, dkershner6 commented on src/javascript/upgrade-dependencies.ts
> +  }
I think the name doesn't reverse the logic here... "Projen Managed" would be anything where a version is not provided, or IS star...

I'll change the name, but keep the logic.

2024-04-03 15:45 UTC, dkershner6 commented on src/javascript/upgrade-dependencies.ts
> +          includeConstraint || this.packageIsUsingDefaultVersioning(d.version)
See https://github.com/projen/projen/pull/3463#discussion_r1550003129

2024-04-03 16:03 UTC, dkershner6 commented
@mrgrain , minor changes made. Note that I did correct one of your suggestions regarding the direction of the conditional, but otherwise it is exactly as requested.

2024-04-03 23:45 UTC, mrgrain requested changes

2024-04-03 23:45 UTC, mrgrain commented on src/javascript/upgrade-dependencies.ts
> +  private isProjenManagedVersion(version: string | undefined): boolean {
Sorry to be pedantic here, but it's exactly the other way around. Projen only manges the version if it's `undefined` and not `*`.

Hence my original suggestion.

2024-04-04 15:30 UTC, dkershner6 commented on src/javascript/upgrade-dependencies.ts
> +  private isProjenManagedVersion(version: string | undefined): boolean {
> Projen only manges the version if it's undefined and not *.

Just to be clear, you are saying that `*` is a version constraint like any other (`^1.0.0`), and that projen should just let the package manager handle that as well.  This seems a little odd since they seem equal, but I suppose using actual `*` is pretty rare and perhaps explicit should have meaning.

If so, we don't need the `!==`, we can just only look for falsy, period.  I will also add a test using explicit `*` to indicate this.

@mrgrain

2024-04-04 21:11 UTC, mrgrain commented on src/javascript/upgrade-dependencies.ts
> +  private isProjenManagedVersion(version: string | undefined): boolean {
No pretty sure `*` is special and will not end up not being managed by projen.

I think the code is all correct now. Just the way it is the function ought to be named `isNotManagedByProjen`. And because I wanted to avoid this kind of negative naming I inverted the name and Boolean expression.

2024-04-04 21:13 UTC, mrgrain commented on src/javascript/upgrade-dependencies.ts
> +  private isProjenManagedVersion(version: string | undefined): boolean {
Your comment makes me think we are still not aligned though.

The `version` value here is the one projen knows about and has nothing to do with the package manager yet.

2024-04-05 01:24 UTC, dkershner6 commented on src/javascript/upgrade-dependencies.ts
> +  private isProjenManagedVersion(version: string | undefined): boolean {
I think maybe "Managed by Projen" might be the unclear part...

This function was designed to detect when NCU was able to change the package.json version for packages.  I called this "default" behavior because it was instigated when the version was omitted (or `*`, presumably, but the lack of a variable is often called default).  This could also be called "managed by projen", since projen is changing versions on a command (upgrade), thereby removing control from the package manager and taking it for itself.

It seems that you mean that "managed by projen" was when the projen default command sets the version as dictated by the version constraint, then delegates control to the package manager.  This feels less "manage" to me, but I could see how you could get there, especially when the version constraint is pinned.

My thought is that we should name it something clearer than either of us have come up with.  My suggestion is `packageCanBeUpgradedInPackageJson`, leaves nothing to the imagination and we can leave affirmative, easy to understand logic.

Since we live in opposite parts of the world, in the interest of time, i'll implement this in the PR, but leave this comment unresolved for now.

Tagging for visibility: @mrgrain

2024-04-05 12:41 UTC, mrgrain commented on src/javascript/upgrade-dependencies.ts
> +  private isProjenManagedVersion(version: string | undefined): boolean {
I love the new name, `packageCanBeUpgradedInPackageJson` is so much better!

2024-04-05 12:41 UTC, mrgrain approved these changes

2024-04-05 12:43 UTC, merged