feat: Support Publishing of JSII Python Artifacts to AWS CodeArtifact
projen/projen pull request #3475
Opened 2024-03-22 21:40 UTC by timothymathison

Makes pypi publisher job support targeting AWS CodeArtifact. Re-uses the `CodeArtifactOptions` already added to support publishing of NPM packages to CodeArtifact.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-03-22 21:43 UTC, timothymathison commented on src/release/publisher.ts
> +        run: `echo "TWINE_PASSWORD=$(aws codeartifact get-authorization-token --domain ${domain} --domain-owner ${account} --region ${region} --query authorizationToken --output text)" >> $GITHUB_ENV
Unfortunately publib does not natively support codeartifact for python like it does for npm. So had to add this step.

2024-03-25 12:18 UTC, mrgrain commented on src/release/publisher.ts
> +export function awsCodeArtifactInfoFromUrl(url?: string): AwsCodeArtifactInfo {
No need for this to be exported.
```suggestion
function awsCodeArtifactInfoFromUrl(url?: string): AwsCodeArtifactInfo {
```

2024-03-25 12:19 UTC, mrgrain commented on src/release/publisher.ts
> +export interface AwsCodeArtifactInfo {
No need for this to be exported and part of the public API.

```suggestion
interface AwsCodeArtifactInfo {
```

2024-03-25 12:22 UTC, mrgrain requested changes
Couple of minor changes. Note that removing the export will also require an update the the generated docs again.

2024-03-25 14:55 UTC, mrgrain approved these changes
Nice one! This was long overdue

2024-03-25 15:04 UTC, merged