fix(release): retrying the workflow can have no affect
projen/projen pull request #3526
Opened 2024-04-15 16:13 UTC by iliapolo

When a release succeeds to create the GitHub tag, but fails on other publish steps (for example NPM), retrying the workflow has no affect. This is because we only run publishing jobs in case the tag doesn't exist. In case of a partial failure, the tag exists but the workflow didn't actually succeed and we'd like to retry.

This PR makes it so the GitHub tag is only created if all other publishing jobs succeeded. 

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-04-15 16:23 UTC, iliapolo commented on src/release/publisher.ts
> +const PUBLISH_JOB_PREFIX = "release_";
I took a quick glance and it seems to require quite a bit of refactoring in order to avoid this and have the `addPublishJob` method return the job name. 

This is a lazy way of at least avoiding duplicate strings and "syncing" job name to `dependsOn`.

2024-04-15 16:23 UTC, iliapolo commented on src/release/publisher.ts
> +  private packageManagersPublishJobs: string[] = [];
Again, lazy way to keep track of publishing jobs.

2024-04-16 12:59 UTC, mrgrain requested changes

2024-04-27 13:58 UTC, mrgrain approved these changes

2024-04-27 14:07 UTC, merged