Adding Plugin Repository and Enhancing Repository Options
projen/projen pull request #3534
Opened 2024-04-19 14:23 UTC by awbdallas

- Added Plugin Repositories
- Added Maven Repository Policies
- Added Tests

Links:
- https://maven.apache.org/settings.html#repositories

Fixes #

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-04-26 16:43 UTC, awbdallas commented
@mrgrain  Any chance you can take a look?

2024-04-26 16:48 UTC, mrgrain commented on src/java/pom.ts
> +  readonly updatePolicy?: "always" | "update" | "never" | `interval:${number}`;
Needs to be an enum like class, cause type unions don't translate well to java.

2024-04-26 16:48 UTC, mrgrain commented on src/java/pom.ts
> +  readonly checksumPolicy?: "ignore" | "fail" | "warn";
Needs to be an enum like class, cause type unions don't translate well to java.

2024-04-26 16:49 UTC, mrgrain requested changes
See inline comments. Rest looks fine.

2024-07-09 11:00 UTC, mrgrain commented on src/java/pom.ts
> +      pluginRepositories: { pluginRepositories: this.pluginRepositories },
I think it should be this?
```suggestion
      pluginRepositories: { pluginRepository: this.pluginRepositories },
```

2024-07-09 11:01 UTC, mrgrain commented on test/java/__snapshots__/pom.test.ts.snap
> +        <pluginRepositories>
This looks incorrect. See other comment.
```suggestion
    <pluginRepositories>
        <pluginRepository>
```

2024-07-09 11:04 UTC, mrgrain commented on test/java/__snapshots__/pom.test.ts.snap
> +            </policyRepository>
I cannot find a reference for this at all.
Looks like policies are added to `snapshots` and `releases`? 
https://maven.apache.org/pom.html#repositories

Can you help me find the right reference if this is something that does indeed exist?

2024-07-09 11:05 UTC, mrgrain requested changes
Apologies this took so long. I've found two issues. See inline comments.

2024-07-13 13:51 UTC, awbdallas commented on test/java/__snapshots__/pom.test.ts.snap
> +            </policyRepository>
You're absolute right this has been updated!

2024-07-23 13:30 UTC, mrgrain requested changes
Code looks mostly good now. Mainly some housekeeping to be done.

2024-07-23 13:30 UTC, mrgrain commented on src/java/pom.ts
> +  readonly releases?: MavenRepositoryPolicy;
Needs a doc string please

2024-07-23 13:30 UTC, mrgrain commented on src/java/pom.ts
> +   * Repository Policy
```suggestion
   * Repository Policy for Snapshots
```

2024-07-23 13:30 UTC, mrgrain commented on src/java/pom.ts
> +   * Checksum Policy
```suggestion
   * Checksum Policy
   * When Maven deploys files to the repository, it also deploys corresponding checksum files.
```

2024-07-23 13:30 UTC, mrgrain commented on src/java/pom.ts
> +   * Update Policy
```suggestion
   * Update Policy
   * This element specifies how often updates should attempt to occur. Maven will compare the local POM's timestamp (stored in a repository's maven-metadata file) to the remote.
   * @default UpdatePolicy.DAILY
```

2024-07-23 13:30 UTC, mrgrain commented on src/java/pom.ts
> +   * Is enabled
```suggestion
   * Whether this repository is enabled  for the respective type (`releases` or `snapshots`).
```

2024-07-23 13:30 UTC, mrgrain commented on src/java/pom.ts
> +  static get always() {
By the way, these don't need to be getters.
```suggestion
  static get ALWAYS() {
```

2024-07-23 13:30 UTC, mrgrain commented on src/java/pom.ts
> +  }
```suggestion
  static get DAILY() {
    return "daily";
  }
```

2024-07-23 13:30 UTC, mrgrain commented on src/java/pom.ts
> +  }
```suggestion
  static get NEVER() {
    return "never";
  }
```

2024-07-23 13:30 UTC, mrgrain commented on src/java/pom.ts
> +  static interval(num: number) {
```suggestion
  /**
   * Updates at an interval of X minutes.
   */
  static interval(minutes: number) {
```

2024-07-23 13:30 UTC, mrgrain commented on src/java/pom.ts
> +  public addPluginRepository(repository: MavenRepository) {
Needs a docstring

2024-07-29 15:11 UTC, mrgrain approved these changes

2024-07-29 16:47 UTC, mrgrain approved these changes

2024-07-29 17:03 UTC, merged