feat(gitpod): Support Gitpod -- take #3
projen/projen pull request #360
Opened 2020-12-10 15:11 UTC by pgollucci

Some Project vs NodeProject issues need to be sorted before this
can be implimented in finalization, but this should allow use for now.

2020-12-10 15:23 UTC, pgollucci commented
This still needs tests but pending feedback first.  I addressed a few things from the previous version

2020-12-10 21:57 UTC, Chriscbr requested changes

2020-12-10 21:57 UTC, Chriscbr commented on src/gitpod.ts
> +        docker: this.docker,
If `options.docker` is `{ file: '.gitpod.Dockerfile' }`, then this gets synthesized as
```
docker:
  file: .gitpod.Dockerfile
```
when it should get synthesized as
```
image:
  file: .gitpod.Dockerfile
```

2020-12-10 21:57 UTC, Chriscbr commented on src/gitpod.ts
> +    }
These comments are valid concerns - I think for now it's fine if the default behavior (in the else branch) is to add no tasks, assuming that is allowed by the spec. If .gitpod.yml for some reason requires at least one task, then you could just put a simple "echo initialized" command instead, just so we aren't tied to any NodeProject specific details.

2020-12-10 21:57 UTC, Chriscbr commented on src/gitpod.ts
> +    this.tasks.push(...task);
```suggestion
  public addTasks(...tasks: GitpodTask[]) {
    this.tasks.push(...tasks);
```

2020-12-10 21:57 UTC, Chriscbr commented on src/gitpod.ts
> +  public customDocker(docker: GitpodDocker) {
```suggestion
  public addCustomDocker(docker: GitpodDocker) {
```

2020-12-10 21:57 UTC, Chriscbr commented on src/project.ts
> +  readonly gitPod?: boolean;
I think this should be `gitpod`, along with the other occurrences in the file
```suggestion
  readonly gitpod?: boolean;
```

2020-12-10 21:57 UTC, Chriscbr commented on src/project.ts
> +   * It can be customized later if needed
```suggestion
   * Adds a gitpod configuration
```

2020-12-10 21:57 UTC, Chriscbr commented on src/project.ts
> +   * @default false
I'd be okay with enabling gitpod by default, but it's up to what you and others think.

2020-12-10 21:57 UTC, Chriscbr commented on src/gitpod.ts
> +  constructor(project: Project, options?: GitpodOptions) {
I think it's fine to omit the docstring for the constructor here.
```suggestion
  constructor(project: Project, options?: GitpodOptions) {
```

2020-12-10 21:57 UTC, Chriscbr commented on src/gitpod.ts
> +   * @default BOTTOM
```suggestion
   * @default GitpodOpenIn.BOTTOM
```

2020-12-10 21:57 UTC, Chriscbr commented on src/gitpod.ts
> +   * @default
I found some more default information mentioned in https://github.com/gitpod-io/gitpod/blob/master/components/dashboard/public/schemas/gitpod-schema.json
```suggestion
   * @default GitpodOpenMode.TAB_AFTER
```

2020-12-10 21:57 UTC, Chriscbr commented on src/gitpod.ts
> +export class Gitpod extends Component {
This description is kind of superfluous -- maybe just highlighting the output would make more sense?
```suggestion
/**
 * Creates a Gitpod configuration file
 */
export class Gitpod extends Component {
```

2020-12-10 21:57 UTC, Chriscbr commented on src/gitpod.ts
> +  private docker: GitpodDocker;
We could consider just omitting these docstrings, since these are private fields and I think their purpose should be clear from `GitpodOptions`.

2020-12-10 21:57 UTC, Chriscbr commented on src/gitpod.ts
> +   * Splits and adds the terminal to the tops
```suggestion
   * Splits and adds the terminal to the top
```

2020-12-11 01:19 UTC, smacintyre commented on .gitpod.yml
> +  image: jsii/superchain
Yes, this should be `image:` [See to gitpod docs.](https://www.gitpod.io/docs/config-docker/)

Also, can we please default to `gitpod/workspace-full` -- it's the standard gitpod image. The `jsii/superchain` is not required unless you are actually developing CDK. And to the best of my knowledge it's not completely compatible with gitpod. My team exclusively develops in gitpod, using CDK, and have never run into any issues with the default image: `gitpod/workspace-full`. 

Also, It should seem odd for projen to default to CDK develop specific image. Projen should be more neutral.

2020-12-11 01:28 UTC, smacintyre commented on src/gitpod.ts
> + * https://hub.docker.com/r/gitpod/workspace-full/ is the default Gitpod image
Here is says `gitpod/workspace-full` is the default image. However in the code and other comments `jsii/superchain` is the default.

We should be keeping proejn application neutral and so use the standard default of `gitpod/workspace-full`

2020-12-11 15:04 UTC, pgollucci commented on src/gitpod.ts
> +  readonly docker?: GitpodDocker;
I'm torn here. Gitpod defaults to the full one.  Which is true if you have no .gitpod.yml or if you leave out the image/file fields.

Projen itself is defaulting it to jsiii/superchain. 

I'm not sure which makes the most sense to do.  I don't think we need jsii/superchain the giptod one has 90-100% of the deps, we can install anything missing in a `before`

2020-12-11 15:04 UTC, pgollucci commented on .gitpod.yml
> +  image: jsii/superchain
yep my goof

2020-12-11 15:07 UTC, pgollucci commented on src/gitpod.ts
> +  readonly docker?: GitpodDocker;
See below going with Gitpod defaults

2020-12-11 15:23 UTC, pgollucci commented on src/gitpod.ts
> +    }
It does not require it, but I like the echo initiliazed

2020-12-11 15:26 UTC, pgollucci commented on src/gitpod.ts
> +   * @default BOTTOM
fixed

2020-12-11 15:29 UTC, pgollucci commented on src/gitpod.ts
> +export class Gitpod extends Component {
done

2020-12-11 15:29 UTC, pgollucci commented on src/gitpod.ts
> +   * Splits and adds the terminal to the tops
fixed

2020-12-11 15:30 UTC, pgollucci commented on src/gitpod.ts
> + * https://hub.docker.com/r/gitpod/workspace-full/ is the default Gitpod image
agree. done.

2020-12-11 15:30 UTC, pgollucci commented on src/gitpod.ts
> +  private docker: GitpodDocker;
done

2020-12-11 15:30 UTC, pgollucci commented on src/gitpod.ts
> +   * @default
done

2020-12-11 19:06 UTC, pgollucci commented on src/project.ts
> +  readonly gitPod?: boolean;
Formally its Gitpod so I guess that makes it one word in which case gitpod would be correct.

2020-12-11 19:09 UTC, pgollucci commented on src/project.ts
> +  readonly gitPod?: boolean;
renamed

2020-12-11 19:10 UTC, pgollucci commented on src/project.ts
> +   * @default false
Leaving as is for this pr, we can flip the default seperately

2020-12-11 19:20 UTC, pgollucci commented
I ran an integration test live in Gitpod on this PR works fine.  Though it does look like GitPod is going to move to GitLab eventually as GitHub brings on CodeSpaces.

2020-12-11 19:21 UTC, pgollucci commented
@Chriscbr @smacintyre  That's all the comments.

2020-12-11 21:18 UTC, pgollucci commented
Alright, what am I missing, if you call addTasks() or addCustomerDocker() they run fine, but when you call synth later the output is unchanged even though the project object's component gitpod is updated.  This looks similar to the mergify setup to.

2020-12-11 22:39 UTC, Chriscbr reviewed
> Alright, what am I missing, if you call addTasks() or addCustomerDocker() they run fine, but when you call synth later the output is unchanged even though the project object's component gitpod is updated. This looks similar to the mergify setup to.

This is because of the way object references are handled in JavaScript - when you set `this.docker = ...` in `addCustomDocker()`, it changes which object `this.docker` points to, but the `YamlFile` keeps pointing to the old object.

One way to get around this is to ensure `YamlFile` unambiguously gets the latest value of `this.docker` each time, like this:

```ts
new YamlFile(project, GITPOD_FILE, {
  obj: {
    image: () => this.renderDockerImage(),
    tasks: this.tasks,
  },
});
```

with a corresponding function like:
```ts
private renderDockerImage() {
  if (this.docker?.image) {
    return this.docker.image;
  } else if (this.docker?.file) {
    return {
      file: this.docker.file,
    };
  } else {
    return undefined;
  }
}
```

2020-12-12 00:01 UTC, pgollucci commented
@eladb tests added.

Thanks @Chriscbr

2020-12-12 00:33 UTC, Chriscbr commented on test/gitpod.test.ts
> +    }
```suggestion
    project.gitpod?.addCustomDocker({ image: 'jsii/superchain' });
```
Same change can be made for the other tests below.

2020-12-12 00:34 UTC, pgollucci commented on test/gitpod.test.ts
> +    }
oh yeah duh.

2020-12-13 23:06 UTC, Chriscbr requested changes
Can these comments be removed before merging?

#362 mentions possibly restructuring things to use a more abstract API, but I think this PR/implementation for Gitpod is good enough to publish - it's okay if things change later. I'm fine with merging after these changes. Feel free to shout out if you have other thoughts or comments @eladb

2020-12-14 00:11 UTC, pgollucci commented on src/gitpod.ts
> +   * XXX: NodeProject
I agree

2020-12-14 00:21 UTC, pgollucci commented
@projen rebuild

2020-12-14 06:56 UTC, eladb requested changes
@pgollucci Looks awesome. A few minor comments and we are ready

2020-12-14 06:56 UTC, eladb commented on src/gitpod.ts
> +   * @default
Missing default description. Something like:

```
@default - uses the standard gitpod image (see [LINK])
```

By convention, if you don't have a specific value for default, use `-`

2020-12-14 06:56 UTC, eladb commented on src/gitpod.ts
> +   * @default
Make sure to doc all defaults

2020-12-14 06:56 UTC, eladb commented on src/gitpod.ts
> +  readonly tasks: GitpodTask[];
```suggestion
  readonly tasks?: GitpodTask[];
```

2020-12-14 06:56 UTC, eladb commented on src/gitpod.ts
> +  private tasks = new Array<GitpodTask>();
```suggestion
  private readonly tasks = new Array<GitpodTask>();
```

2020-12-14 06:56 UTC, eladb commented on src/gitpod.ts
> +  private docker: GitpodDocker | undefined;
```suggestion
  private readonly docker: GitpodDocker | undefined;
```

2020-12-14 06:56 UTC, eladb commented on src/gitpod.ts
> +   * @param docker
Missing docstrings

2020-12-14 06:56 UTC, eladb commented on src/gitpod.ts
> +    this.tasks.unshift(...tasks);
Why unshift instead of push?

2020-12-14 12:40 UTC, pgollucci commented on src/gitpod.ts
> +    this.tasks.unshift(...tasks);
Its b/c of the default echo Initialized.  This lets that remain the last statement.  Otherwise, It would be first, or we need change a default.  Or it doesn't matter

2020-12-14 12:47 UTC, pgollucci commented
@projen rebuild

2020-12-14 15:46 UTC, pgollucci commented
All feedback addressed again except for the `unshift` which I explained above.

2020-12-14 15:57 UTC, eladb requested changes

2020-12-14 15:57 UTC, eladb commented on src/gitpod.ts
> +    this.tasks.unshift(...tasks);
That's weird because it will cause any `addTasks()` call to add tasks before the existing tasks.

Why do we need the "echo Initialized" default?

2020-12-16 12:02 UTC, eladb commented on src/gitpod.ts
> +    this.tasks.unshift(...tasks);
Ping @pgollucci

2020-12-16 13:03 UTC, pgollucci commented on src/gitpod.ts
> +    this.tasks.unshift(...tasks);
we don't.

2020-12-16 13:20 UTC, pgollucci reviewed
@projen rebuild

2020-12-16 13:36 UTC, pgollucci commented
@projen rebuild

2020-12-16 13:39 UTC, pgollucci commented
unshift() has been addressed

2020-12-16 18:27 UTC, eladb approved these changes

2020-12-19 14:55 UTC, pgollucci commented
@Chriscbr ping, I think you need to give an approval

2020-12-19 15:46 UTC, Chriscbr approved these changes

2020-12-19 18:16 UTC, merged