feat: support github java package
projen/projen pull request #363
Opened 2020-12-11 16:17 UTC by mmuller88

fixes: 355
* Add the envs necessary for releasing to github java artefact package https://github.com/aws/jsii-release#maven
(I will see where I have to provide more docu)

2020-12-11 19:25 UTC, eladb commented on src/jsii-project.ts
> +              MAVEN_REPOSITORY_URL: '${{ secrets.MAVEN_REPOSITORY_URL }}',
Wondering if these two should just be under the `jsii.java` option and then hard coded here instead of a secret. Those secrets are such a pain to manage.

2020-12-11 19:35 UTC, mmuller88 commented on src/jsii-project.ts
> +              MAVEN_REPOSITORY_URL: '${{ secrets.MAVEN_REPOSITORY_URL }}',
Yes was thinking similar and wanted to wait for feedback :). I think having them in the options woulds be cool.

2020-12-12 07:03 UTC, mmuller88 commented on src/jsii-project.ts
> +              MAVEN_REPOSITORY_URL: '${{ secrets.MAVEN_REPOSITORY_URL }}',
@eladb  I will make that change request in a bit. Thank you for your feedback :)

2020-12-12 14:41 UTC, mmuller88 commented on src/jsii-project.ts
> +              MAVEN_REPOSITORY_URL: '${{ secrets.MAVEN_REPOSITORY_URL }}',
I might have to give the private method publishToMaven() those properties in the options object.

2020-12-13 11:17 UTC, eladb requested changes

2020-12-13 11:17 UTC, eladb commented on src/jsii-project.ts
> +              // MAVEN_SERVER_ID: '${{ secrets.MAVEN_SERVER_ID }}',
What's up here? I expected these to be fed from "options" now

2020-12-14 15:19 UTC, mmuller88 commented on src/jsii-project.ts
> +              // MAVEN_SERVER_ID: '${{ secrets.MAVEN_SERVER_ID }}',
yeah that was my question if it is like that. Will adjust

2020-12-14 20:21 UTC, eladb commented on src/jsii-project.ts
> +              // MAVEN_SERVER_ID: '${{ secrets.MAVEN_SERVER_ID }}',
Yap

2020-12-17 18:21 UTC, mmuller88 commented on src/jsii-project.ts
> +              // MAVEN_SERVER_ID: '${{ secrets.MAVEN_SERVER_ID }}',
done :)

2020-12-23 07:29 UTC, eladb requested changes

2020-12-23 07:29 UTC, eladb commented on docs/awscdk-construct.md
> +* Java: `MAVEN_GPG_PRIVATE_KEY`, `MAVEN_GPG_PRIVATE_KEY_PASSPHRASE`, `MAVEN_PASSWORD`, `MAVEN_USERNAME`, `MAVEN_STAGING_PROFILE_ID`, `MAVEN_SERVER_ID`, `MAVEN_REPOSITORY_URL` ([docs](https://github.c
I believe there is no need to upload these as secrets.

2020-12-31 16:02 UTC, mmuller88 commented on docs/awscdk-construct.md
> +* Java: `MAVEN_GPG_PRIVATE_KEY`, `MAVEN_GPG_PRIVATE_KEY_PASSPHRASE`, `MAVEN_PASSWORD`, `MAVEN_USERNAME`, `MAVEN_STAGING_PROFILE_ID`, `MAVEN_SERVER_ID`, `MAVEN_REPOSITORY_URL` ([docs](https://github.c
reverted it :)

2021-01-01 07:06 UTC, mmuller88 commented
Fixed some outdatd issues. happy new year :)

2021-01-06 07:22 UTC, mmuller88 commented
@eladb i updated my fork with. I hope everything looks good now :)

2021-01-06 07:25 UTC, eladb requested changes
Please add unit test

2021-01-06 07:25 UTC, eladb commented on src/jsii-project.ts
> +  readonly mavenServerId?: string;
Can we take the opportunity and add some docstrings here?

2021-01-06 07:26 UTC, mmuller88 commented on src/jsii-project.ts
> +  readonly mavenServerId?: string;
jup. in the aws-cdk main project is kind of check for that to enforce docstrings. I would like to have that :D

2021-01-06 08:38 UTC, mmuller88 commented
@eladb I added it to the snapshot test. I think that was you mean with unit test right?

2021-01-06 08:48 UTC, eladb commented on src/jsii-project.ts
> +   */
Default should be explicitly marked like so:

```suggestion
  /**
   * Used in maven settings for credential lookup (e.g. use github when publishing to GitHub).
   * @default "ossrh" Defaults to Maven Central.
   */
```

2021-01-06 08:49 UTC, eladb commented on src/jsii-project.ts
> +   * Deployment repository when not deploying to Maven Central
Add "@default"

2021-01-06 08:53 UTC, eladb requested changes
See comments

2021-01-06 08:53 UTC, eladb commented on src/__tests__/integration/cdk-watchful.projenrc.js
> +    mavenServerId: 'github',
Instead of tweaking this integration test, I rather we add a more fine grained unit test to `jsii.test.ts`. Something like this should do:

```ts
test('maven repository options', () => {
  const p = new JsiiProject({
    outdir: mkdtemp(),
    name: 'testproject',
    mavenServerId: 'github',
    mavenRepositoryUrl: 'footer',
  });

  const workflow = synthSnapshot(p))['.github/workflows/xxxx'];
  // now assertions on the workflow
});
```

2021-01-06 08:53 UTC, eladb commented on src/__tests__/__snapshots__/integ.test.ts.snap
> +            "mavenRepositoryUrl": "https://maven.pkg.github.com/eladb",
Wait?! why are these going into `package.json`. I don't believe they are needed in there.

2021-01-06 09:11 UTC, mmuller88 commented on src/__tests__/__snapshots__/integ.test.ts.snap
> +            "mavenRepositoryUrl": "https://maven.pkg.github.com/eladb",
At least for the first one following the instructions here https://github.com/aws/jsii-release#maven you have to save somehow if you want to use maven central or github and if github which repository Url. 

But yes we might could calculate mavenRepositoryUrl out of the choice if "github" and the existing repository name? that would be cool.

2021-01-06 09:15 UTC, mmuller88 commented on src/__tests__/__snapshots__/integ.test.ts.snap
> +            "mavenRepositoryUrl": "https://maven.pkg.github.com/eladb",
kind of

"https://maven.pkg.github.com/${{ github.repository }}"

2021-01-07 16:56 UTC, mmuller88 commented on src/__tests__/integration/cdk-watchful.projenrc.js
> +    mavenServerId: 'github',
I think I get what you say and I try to add the test to jsii.test.ts but the running of the unit test is a bit strange. It seems I can not directly run it out of my VS Code with clicking on run there. It tries to run compiled js tests from the lib folder. 

And it happened two times now that the whole projen project erased itself from my local storage 0.o. I do use Ubuntu 20.04.

Can you please explain me how your workflow is to run tests from jsii.test.ts.

2021-01-07 19:24 UTC, eladb commented on src/__tests__/integration/cdk-watchful.projenrc.js
> +    mavenServerId: 'github',
Sorry about that. My workflow is: start `yarn watch` and then run `yarn test:watch`. 

Then you have an interactive jest experience. You can press `p` to select which test to run and `u` to update snapshots.

2021-01-08 06:44 UTC, mmuller88 commented on src/__tests__/integration/cdk-watchful.projenrc.js
> +    mavenServerId: 'github',
oh wow thats a really cool way of unit testing. Basically on the fly <3. I added a unit test as you requested :).
Maybe not necesarry but the way of testing you describe here is very useful, do we have it in the docs somewhere? If not can we add it?

2021-01-13 05:48 UTC, mmuller88 commented
@eladb  could you have a look please :)

2021-01-13 17:57 UTC, eladb requested changes

2021-01-13 17:57 UTC, eladb commented on src/jsii-project.ts
> +   * @default not set
```suggestion
   * @default - not set
```

2021-01-13 17:57 UTC, eladb commented on src/jsii-project.ts
> +          repositoryUrl: options.publishToMaven.mavenRepositoryUrl,
Why are those here? They are not needed/supported by jsii-pacmak:

https://aws.github.io/jsii/dev-guide/configuration/targets/java/

2021-01-13 17:57 UTC, eladb commented on src/jsii-project.ts
> +  private publishToMaven(java: any) {
Keep a minimal surface area if possible:

```suggestion
  private publishToMaven(serverId: string | undefined, repositoryUrl: string | undefined) {
```

2021-01-16 07:33 UTC, mmuller88 commented
Hi @eladb  thank you for your patient. And sorry for the late response. The week was a bit rough :)

2021-01-17 08:20 UTC, eladb approved these changes

2021-01-17 08:25 UTC, merged