feat: projenrc folder now may have tests within it
projen/projen pull request #3637
Opened 2024-06-06 20:34 UTC by dkershner6

Fixes https://github.com/projen/projen/issues/3630

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-06-07 09:08 UTC, mrgrain commented on src/typescript/typescript.ts
> +    const validTestRootDirs = [this.srcdir, this.testdir, "projenrc"];
This is a variable as well actually: projenCodeDir 
https://projen.io/docs/api/typescript?_highlight=projenrc#projen.typescript.ProjenrcOptions.property.projenCodeDir

2024-06-07 09:08 UTC, mrgrain requested changes
Needs to be dynamic

2024-06-07 14:39 UTC, dkershner6 commented
Had to change the field from `private` to `public` on `ProjenrcTs`, and store `projenrcTs` on `TypeScriptProject`, and change the order of the constructor to get there, but everything seems as it should now, @mrgrain .

2024-06-10 12:08 UTC, mrgrain requested changes
Thanks for the change. I think this is the wrong way around though. We would want the `ProjenRc` component to do `Jest.of()` and add a new pattern. This can also totally be a separate entry in the array.

2024-06-10 19:11 UTC, dkershner6 commented
As I was diving into the new change, I realized there were several very similar `dirTestMatch` pattern creations going on (and I was creating one more), so I centralized the logic to the `Jest` class in a static method, made it use the Jest best practices (from the docs and defaults), then used that everywhere, including the new feature.

So, it's a bit more than I intended to take on, but should now work really well and the responsibilities are in the correct places (and should be easier to maintain that in the future). @mrgrain

2024-06-18 14:45 UTC, dkershner6 commented
> Still on my list. Should get to it this week. Sorry for the delay.

No worries, just wanna be sure it wasn't forgotten.

2024-06-21 12:02 UTC, mrgrain requested changes
I like the direction. But there are some gnarly little issues we need to sort out.

2024-06-21 12:02 UTC, mrgrain commented on test/typescript/__snapshots__/typescript.test.ts.snap
> +        "<rootDir>/@(src|test)/**/__tests__/**/*.[jt]s?(x)",
I don't think this is a good idea. This used to match ts files only on purpose.

```suggestion
        "<rootDir>/@(src|test)/**/?(*.)+(spec|test).ts?(x)",
        "<rootDir>/@(src|test)/**/__tests__/**/*.ts?(x)",
```

2024-06-21 16:50 UTC, dkershner6 commented on src/javascript/jest.ts
> +    this.testMatch.push(...patterns);
Reverted.

2024-06-21 17:19 UTC, dkershner6 commented on test/typescript/__snapshots__/typescript.test.ts.snap
> +        "<rootDir>/@(src|test)/**/__tests__/**/*.[jt]s?(x)",
I made it follow the `allowJs` variable, which seems like a valid compromise.

2024-06-21 19:44 UTC, dkershner6 commented
@mrgrain , this has been updated.

In order to accommodate the `discover` method, I had to lazily load the testMatches.  I am reasonably sure this actually fixed a bug where all testMatches added after initialization were ignored, but it does require a `ts-expect-error` due to types.

2024-07-03 10:22 UTC, mrgrain commented on src/javascript/jest.ts
> +  ): void {
I think we need one more iteration on the API. Something like this:
```suggestion
  public discoverTests(
    directories: string[],
    options?: DiscoverTestsOptions
  ): void {
  const patterns = options.fileExtensionPattern ?? "[jt]s?(x)";
```

with 

```
interface DiscoverTestsOptions {
    fileExtensionPattern?: String
}
```

2024-07-03 10:26 UTC, mrgrain commented on src/javascript/jest.ts
> +  }
I think this is a bit weird to have the defaults and the `buildMatchPatterns` helper wrapped up in the some method.
Let's make `dirs` required instead and put the defaults into a separate private helper and just call them explicitly.

The way it's done right now allows to add multiple default patterns by calling `discoverTestMatchPatternsForDirs` repetitively.

2024-07-03 10:26 UTC, mrgrain requested changes
Sorry this took again longer than expected. We'll need an other iteration on the API.

2024-07-03 22:52 UTC, dkershner6 commented
Changes have been made, @mrgrain .

2024-07-08 14:21 UTC, mrgrain commented
Looks good now. I just have to deal with the failing Maven release first.

2024-07-08 21:53 UTC, mrgrain approved these changes

2024-07-08 22:13 UTC, merged