feat: add support for github issue templates
projen/projen pull request #3648
Opened 2024-06-09 15:04 UTC by kennyg

adds support for github issue templates. Closes #3567. Tested this by setting up a local project and adding this snippet to the `.projenrc.ts`

```
new IssueTemplate(project.github!, {
  templates: {
    'bug-report.md': '',
    'feature-request.yml': '',
  },
});
```

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-06-10 19:16 UTC, mrgrain commented on src/github/issue-template.ts
> +    }
Let's convert this into a public `addTemplate()` class method so it can be reused.

2024-06-10 19:17 UTC, mrgrain commented on src/github/issue-template.ts
> +   * Defaults to '.github/ISSUE_TEMPLATE'.
Is there any realistic possibility of the the files NOT being inside the `.github` directory?
If not, let's just drop the prefix.

2024-06-10 19:30 UTC, mrgrain commented on src/github/issue-template.ts
> +    const project = github.project;
We have moved on from this approach. This is the current state of the art:
```suggestion
  constructor(scope: IScope, options: IssueTemplateOptions) {
    super(scope, "<enter_unique_id_here_if_this_is_a_singleton_component>");
    const project = this.project;
    const github = GitHub.of(project);
    if (!github) {
      // add warning here. Or hard fail, but it seems like the github component is not actually needed for this
    }
```

2024-06-10 19:31 UTC, mrgrain commented on test/github/issue-template.test.ts
> +        "feature-request.yml": "<!-- Feature request template content -->",
doesn't a yaml file imply using an object here?

2024-06-16 10:59 UTC, kennyg commented on src/github/issue-template.ts
> +    }
sounds good. i've made the change.

2024-06-16 10:59 UTC, kennyg commented on src/github/issue-template.ts
> +   * Defaults to '.github/ISSUE_TEMPLATE'.
you're right. I removed this.

2024-06-16 11:00 UTC, kennyg commented on src/github/issue-template.ts
> +    const project = github.project;
also updated this. thanks for the tip.

2024-06-16 11:01 UTC, kennyg commented on test/github/issue-template.test.ts
> +        "feature-request.yml": "<!-- Feature request template content -->",
you're right. I updated the tests to reflect that.

2024-06-18 08:38 UTC, mrgrain commented on src/github/issue-template.ts
> +  readonly templatePath?: string;
You previously indicated you had removed this, but it's still here?
```suggestion
```

2024-06-18 08:39 UTC, mrgrain commented on src/github/issue-template.ts
> +  public addTemplates(options: IssueTemplateOptions) {
Neither `options.configOptions` nor `options.templatePath` are used. This should take the templates directly.

2024-06-18 08:40 UTC, mrgrain commented on src/github/issue-template.ts
> +      new YamlFile(project, ".github/config.yml", {
```suggestion
      new YamlFile(this, ".github/config.yml", {
```

2024-06-18 08:40 UTC, mrgrain commented on src/github/issue-template.ts
> +          new TextFile(this.project, filePath, {
```suggestion
          new TextFile(this, filePath, {
```

2024-06-18 08:48 UTC, mrgrain commented on test/github/issue-template.test.ts
> +        "feature-request.yml": YAML.stringify(data),
I was more hoping to create an API that can take in objects directly. Having to stringify data just for it to be parsed again seems counter-intuitive.

I'd suggest an enum-like class approach:

```
IssueTemplate.markdown(markdown: string);
IssueTemplate.form(data: IssueFormSchema);
```

2024-06-18 08:49 UTC, mrgrain requested changes
Just need to do something about the API for forms

2024-06-18 21:02 UTC, kennyg commented on src/github/issue-template.ts
> +  readonly templatePath?: string;
I've removed this

2024-06-18 21:04 UTC, kennyg commented on src/github/issue-template.ts
> +  readonly templatePath?: string;
i've removed this

2025-02-19 09:25 UTC, mrgrain commented
Closing stale PR

2025-02-19 09:25 UTC, closed without merging