fix: fix sample code for specify app entrypoint
projen/projen pull request #365
Opened 2020-12-12 12:59 UTC by guan840912

## fix: fix sample code for specify app entrypoint

When `appEntrypoint` is specified, let the test sample code be changed together.

### Test Pic .
![截圖 2020-12-12 下午8 52 53](https://user-images.githubusercontent.com/46012524/101984425-602cd080-3cbc-11eb-8241-6747b60669bc.png)

![截圖 2020-12-12 下午8 53 01](https://user-images.githubusercontent.com/46012524/101984423-5dca7680-3cbc-11eb-8995-7a30ac9fc37a.png)

2020-12-13 11:19 UTC, eladb requested changes

2020-12-13 11:19 UTC, eladb commented on src/awscdk-app-ts.ts
> +    const appEntrypointName = this.appProject.appEntrypoint.split('.')[0];
Use `basename(x, '.ts')` to remove an extension

2020-12-13 11:51 UTC, guan840912 commented on src/awscdk-app-ts.ts
> +    const appEntrypointName = this.appProject.appEntrypoint.split('.')[0];
Thanks @eladb, no problem 👍

2020-12-17 14:49 UTC, guan840912 commented
Hi @eladb, ready to be reviewed. :)

2020-12-17 16:08 UTC, eladb approved these changes

2020-12-17 16:13 UTC, merged