feat: support configuring eslint command flags
projen/projen pull request #3655
Opened 2024-06-14 22:20 UTC by timothymathison

Adds an option to disable `--fix` flag and an option to provide additional flags for the `eslint` command run by the `eslint` task.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-06-17 16:00 UTC, timothymathison commented
@mrgrain any idea why there's test failures for windows - unrelated to my changes?

2024-06-26 12:23 UTC, mrgrain requested changes
We need tests for this please.

2024-07-10 15:30 UTC, mrgrain commented on src/javascript/eslint.ts
> +export interface EslintCommandOptions {
Let's flatten this and include it in `EslintOptions`

2024-07-10 15:31 UTC, mrgrain commented on src/javascript/eslint.ts
> +   * Whether to include --fix flag in base eslint task
```suggestion
   * Whether to fix eslint issues when running the eslint task
```

2024-07-10 15:32 UTC, mrgrain commented on src/javascript/eslint.ts
> +  readonly extraFlagArgs?: string[];
```suggestion
  /**
   * Additional arguments to pass to eslint command line.
   */
  readonly extraArgs?: string[];
```

2024-07-10 15:32 UTC, mrgrain requested changes
Thanks for the tests! Just some tiny changes to the API and descriptions.

2024-07-10 20:27 UTC, mrgrain approved these changes

2024-07-10 20:38 UTC, merged