fix(jsii): package task failing on windows
projen/projen pull request #3723
Opened 2024-07-18 18:11 UTC by mrgrain

Fixes failing packaging step in windows builds.
Reverts the special treatment of packaging in Windows builds.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-07-18 18:12 UTC, mrgrain commented
@gmeligio FYI Trying if this small change will be enough.

2024-07-18 19:11 UTC, gmeligio commented
You did a good one. I tried test and other shell variants to make an small change with shx but couldn't make it work. I ended up with the JS script. I'll check it out anyways and see if I can reuse something from this PR.

2024-07-18 19:17 UTC, gmeligio commented
Looking at [where `rsync` failed ](https://github.com/projen/projen/actions/runs/9996668356/job/27631538201?pr=3723#step:5:2988), it might be enough to install rsync in the step or the job.

2024-07-18 19:29 UTC, mrgrain commented
> Looking at [where `rsync` failed ](https://github.com/projen/projen/actions/runs/9996668356/job/27631538201?pr=3723#step:5:2988), it might be enough to install rsync in the step or the job.

Good idea 🤔

2024-07-18 21:49 UTC, gmeligio commented
I think the specific windows build step can't be removed, because `shell` doesn't accept variables nor matrix. We are assuming and testing with the same shell as NodeJS default in local which is `cmd`, while the windows runner sets `pwsh` by default, like in this job https://github.com/projen/projen/actions/runs/9998223427/job/27636610342?pr=3723#step:6:3 .

I got curious, and I tried to reproduce the command you created for the package step locally by cloning your branch. But the `test` command is not found in my local Windows 11 in pwsh or cmd. It could be that it's available in the runner, but I haven't found the documentation that mentions that. It could be that I'm missing something about the runner, but it seems that we need to think more about the cross-platform `if` condition.

```bash
❯ yarn package  
yarn run v1.22.19
$ node ./projen.js package
👾 package | test -n "${CI}" && ((rsync -a . .repo --exclude .git --exclude node_modules && rm -rf dist && mv .repo dist) || exit 1) || node ./projen.js package-all
'test' is not recognized as an internal or external command,
operable program or batch file.
👾 package-all » package:js | jsii-pacmak -v --target js
[jsii-pacmak] [INFO] Found 1 modules to package
[jsii-pacmak] [INFO] Packaging NPM bundles
[jsii-pacmak] [INFO] Loading jsii assemblies and translations
[jsii-pacmak] [INFO] Packaging 'js' for projen
[jsii-pacmak] [INFO] js finished
[jsii-pacmak] [INFO] Packaged. npm pack (3.4s) | js (0.0s) | load jsii (0.0s) | cleanup (0.0s)
👾 package-all » package:java | jsii-pacmak -v --target java
[jsii-pacmak] [INFO] Found 1 modules to package
[jsii-pacmak] [INFO] Packaging NPM bundles
```

What do you think?

2024-07-18 21:52 UTC, gmeligio commented
Actually, I was amazed when I noticed the shell used was pwsh, because some tests with tricky quoting or shell specifics have failed for me in pwsh but worked in cmd.

2024-07-19 07:08 UTC, mrgrain commented
Hmm. I was thinking the `test` command is made available through `shx` which I thought runs all projen commands. 🤔

2024-07-19 07:13 UTC, mrgrain commented
Regarding `shell`: This was something you originally added to the matrix in the big compat PR I think!? But looking at it now, it doesn't seem to be used. 

But then Windows tests are passing and running in this PR, so I'm a little confused about the need for it in the first place. 🤔

2024-07-21 15:07 UTC, mrgrain commented
> Hmm. I was thinking the `test` command is made available through `shx` which I thought runs all projen commands. And in this PR the package step seems to work without problems 🤔

This was wrong. Shx only runs for a pre-defined list of commands. `test` is not one of them. I guess it is just available in powershell.

2024-07-21 15:08 UTC, mrgrain commented
> Regarding `shell`: This was something you originally added to the matrix in the big compat PR I think!? But looking at it now, it doesn't seem to be used.
> 
> But then Windows tests are passing and running in this PR, so I'm a little confused about the need for it in the first place. 🤔

Okay, I think I am following you know @gmeligio . Out of curiosity: What was the reason you preferred testing with `cmd` over `powershell`?

2024-07-22 09:37 UTC, mrgrain commented
Alright @gmeligio I think I have addressed all the issues now.

2024-07-23 07:05 UTC, gmeligio commented
> Okay, I think I am following you know @gmeligio . Out of curiosity: What was the reason you preferred testing with `cmd` over `powershell`?

My reason was to use the same shell a contributor will use locally. Multiple sources say that NodeJS will use `cmd` by default in Windows. Here is one in the docs https://docs.npmjs.com/cli/v10/using-npm/config#script-shell

Then, the runner default was `push` and wanted to force `cmd` in the job, thinking that would set the shell for NodeJS. But I was wrong. NodeJS uses `cmd` shell in Windows by default, regardless of the shell of the caller command.

So, I understand now that `cmd` doesn't need to be forced, and it's OK to use the runner shell as it is. Thank you for mentioning this.

I'll do a review later today.

2024-07-23 08:50 UTC, gmeligio requested changes
Looks great. Only a couple of changes about the shell. Sorry for the back and forth regarding that.

The task condition is a very helpful feature. I didn't know about that.

2024-07-23 08:50 UTC, gmeligio commented on projenrc/windows-build.ts
> +      ...convertStepToShellMatrix("build", buildJobPath("/steps/4"), "cmd"),
Not needed anymore. As we discussed, NodeJS will use cmd by default which is the expected one, regardless of the shell of the caller command.

2024-07-23 08:50 UTC, gmeligio commented on projenrc/windows-build.ts
> +        shell: "pwsh",
No need to specify the shell here. pwsh is already the default in the Windows runner.

2024-07-23 08:50 UTC, gmeligio requested changes
Looks great. Only a couple of changes about the shell. Sorry for the back and forth regarding that.

The task condition is a very helpful feature. I didn't know about that.

2024-07-23 09:38 UTC, gmeligio approved these changes
Perfect! Thanks.

2024-07-23 10:15 UTC, iliapolo approved these changes

2024-07-23 10:15 UTC, merged