fix(python): dynamic environment variables not working on Windows
projen/projen pull request #3792
Opened 2024-08-22 20:24 UTC by gmeligio

Fixes #1003

The fix uses NodeJS CLI to resolve the dynamic environment variables. Also the upgrade command for pip needs to be different on Windows.

Thanks to [`evalEnvironment`](https://github.com/gmeligio/projen/blob/985264ea5ea0151747b1e0a945033b4fe033b010/src/task-runtime.ts#L240) parsing of `$(...)` expressions, so far it seems the logic works for both Linux and Windows and no OS conditional is needed.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-08-22 21:11 UTC, mrgrain commented on src/python/venv.ts
> +      `$(node -p "\`${venvPathExpression}\`")`
Given that is python, can we use python?

(Node will be fine since it's required for projen, but you know...)

2024-08-22 21:17 UTC, gmeligio commented on src/python/venv.ts
> +      `$(node -p "\`${venvPathExpression}\`")`
Good idea! I'll check with Python.

2024-09-02 10:35 UTC, mrgrain commented on src/python/venv.ts
> +    const pythonDir = isWindows ? "Scripts" : "bin";
This will still change the task definition, depending on the OS that projen is run on.

2024-09-02 10:37 UTC, mrgrain requested changes
Code looks good, but the pythonDir check needs to move into the python script as well.

> This adds the withPlatforms test helper to save snapshots for both Linux and Windows with minimal boilerplate. In the case of Python, the virtual environment will be stored in ./.env/Scripts on Windows and ./.env/bin on Linux. It's good to save both snapshots instead of discarding that path difference to have only one snapshot.

I don't think this is the right approach. We want snapshots to be identical on both platforms, otherwise we get the issue with differences between Win and Linux when `projen default` runs.

2024-09-02 10:44 UTC, gmeligio commented on src/python/venv.ts
> +    const pythonDir = isWindows ? "Scripts" : "bin";
Thank you for the review. I didn't notice that it could also be moved inside the script. I'll do that.

2024-09-02 20:11 UTC, gmeligio commented on src/python/venv.ts
> +    const quote = isWindows ? '""' : '\\"';
@mrgrain This quoting part depends on the shell (cmd or bash), which happens before running the Python script, so it can't be moved into the Python script. I haven't found a way to make it cross-platform. As it is right now, it will produce different snapshots for Linux and Windows.

2024-09-02 20:15 UTC, gmeligio commented on src/python/venv.ts
> +    const quote = isWindows ? '""' : '\\"';
Another place that it comes to my mind is to have a special escape syntax for projen, like `$(` is for expressions, so that evalEnvironment does the escaping depending on the platform.

2024-09-02 20:24 UTC, gmeligio commented on src/python/venv.ts
> +    const quote = isWindows ? '""' : '\\"';
On the other hand, it's possible that escaping the quotes is not needed after moving the script into a function in `.projenrc.py` or in another generated file.

What's the best option in this case?

2024-09-04 10:39 UTC, mrgrain commented on src/python/venv.ts
> +    const quote = isWindows ? '""' : '\\"';
To confirm my understanding (using simplified python code):

In bash (or shell) we need to do this:
```bash
python -c "import os; os.environ[\"PATH\"]"
```

But in cmd we need to do this?
```cmd
python -c "import os; os.environ[""PATH""]"
```

2024-09-04 10:46 UTC, mrgrain commented on src/python/venv.ts
> +    const quote = isWindows ? '""' : '\\"';
I think in this situation we can get around this with adjusting the python syntax:
```bash
python3 -c  "import os; path = os.environ['PATH']; print(f'{path}')"
```
or maybe even this due to better backwards compat:
```bash
"import os; print('{}'.format(os.environ['PATH']));"
```

2024-09-04 10:54 UTC, mrgrain commented on src/python/venv.ts
> +    const quote = isWindows ? '""' : '\\"';
Now long term, this is obviously super annoying. I think we should write code in one form (likely nix) and not have to worry about the shell it will be executed in. 

Not entirely how that would be implemented, but we can look at what other tools are doing (e.g. npm's [run-script](https://github.com/npm/run-script) or [shelljs](https://www.npmjs.com/package/shelljs) or other tasks runners. This sounds like a hard, but solved problem. It might also just be a case of running commands always throw shelljs.

2024-09-04 10:55 UTC, mrgrain commented on src/python/venv.ts
> +    const pathEnvironmentExpression = `${pythonDirPathExpression}{os.pathsep}{os.environ[${quote}PATH${quote}]}`;
Side note, I think we should accept the duplication here and define the both python code snippets as full strings. The way this is now, it's really hard to argue about.

2024-09-07 14:57 UTC, gmeligio commented on src/python/venv.ts
> +    const pathEnvironmentExpression = `${pythonDirPathExpression}{os.pathsep}{os.environ[${quote}PATH${quote}]}`;
You're right. It's better to duplicate to read the TS, shell, and Python mix a bit easier.

2024-09-07 14:58 UTC, gmeligio commented on src/python/venv.ts
> +    const quote = isWindows ? '""' : '\\"';
> python3 -c  "import os; print('{}'.format(os.environ['PATH']));"

The str.format() actually solved the quote problem. Thank you for providing alternatives. I was trying to use f-string and then working around it instead of taking a step back and find a shell compatible way.

2024-09-07 15:05 UTC, gmeligio commented on src/python/venv.ts
> +    const quote = isWindows ? '""' : '\\"';
Regarding the long term, I think we can for sure understand how other shell tools do it and design a simple and cross-platform way for projen. I need to investigate more before proposing an RFC or some plan.

From my point of view, projen is already more advanced than the other tools. For example: npm run-script, shelljs don't manage cross-platform environment variables. But there is room for simplification in terms of standardizing the projen syntax for scripts, likely shell/*nix as you said.

2024-09-09 09:57 UTC, mrgrain approved these changes

2024-09-09 10:50 UTC, gmeligio commented
Thank you again for the review @mrgrain ! Sorry, I just updated the PR description because it was outdated after removing `withPlatforms`. I hope there is still time before the actual commit message is created.

2024-09-09 12:29 UTC, mrgrain commented
Ah great! It wasn't merged yet, so you are all good. Thanks for catching that. <3

2024-09-09 12:57 UTC, merged