chore(github/workflows): allow setting a workflow name in the options
projen/projen pull request #3814
Opened 2024-08-30 19:16 UTC by shinebayar-g

Fixes #3811

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-09-02 10:16 UTC, mrgrain commented on src/github/workflows.ts
> +  readonly name?: string;
We will have to improve the API for this. With your (very welcome!) change we now have two things that are called `name`. The argument doesn't even have a description right now 🙈

2024-09-02 10:19 UTC, mrgrain requested changes
I like the change, but can you suggest an API that doesn't use `name` everywhere. And make sure to update (and add where needed) existing doc blocks as well.

2024-09-21 01:08 UTC, shinebayar-g commented
Changed `name` parameter in the constructor to `filePath`. I think it's fitting since the underlying Yamlfile also uses the same parameter.

2024-09-21 12:18 UTC, mrgrain commented
Thanks for the change. In the meantime #3851 was raised which is somewhat similar.

I think what we should do is flip this around:
- Keep the the `name` parameter as it is. It represents the name of the workflow and will be used to derive a file path.
- Add a new `fileName` option (not path because it's going ti be places into the right path automatically) 
- When `fileName` is provided, we use that **exactly as it is** as the filename. So make sure we add an example showing the file extension.
- If `fileName` option is not provided, we default it to `${name}. yml`

That we we can solve both issues with a not too complicated API.

2024-10-29 10:28 UTC, mrgrain approved these changes

2024-10-29 11:15 UTC, merged