feat: DevContainer component
projen/projen pull request #391
Opened 2020-12-22 05:00 UTC by Chriscbr

Fixes #362 

BREAKING CHANGES:
- Deprecated `GitpodDocker` for `WorkspaceDockerImage`.
- Deprecated `gitpod.addCustomDocker()`; use the `gitpod.dockerImage` field directly instead.
- Changed `gitpod.addTasks` to take `Task` instances as inputs. Tasks can be created via `const task = project.addTask('name', { ...options })`.

Other changes:

- Creates an abstract interface for configuring container-based IDE tools like Gitpod and GitHub Codespaces.
- Adds `addTaskWithOptions`, `addPorts`, and `addVscodeExtensions` methods to `Gitpod`.
- Adds the `DevContainer` component which defines `.devcontainer.json` files.
- Fix bug where `JsonFile` can fail to synthesize when a function is passed as obj
- Fix bug where `YAMLFile` can synthesize incorrectly because `JsonFileOptions` get ignored.
- Refactored several unit tests

2020-12-22 16:39 UTC, pgollucci commented
Gitpod doesn't actually use Vscode, it uses Thea.

2020-12-22 18:06 UTC, Chriscbr commented
> Gitpod doesn't actually use Vscode, it uses Thea.

Thanks for pointing that out, I wasn't aware. I think I can still leave the API name `addVscodeExtensions()` as is since the GitHub page for Theia refers to them that way ("supports VS Code Extension protocol").

2020-12-23 02:01 UTC, Chriscbr commented
Just tested that this works with GitHub codespaces.  On a separate branch I enabled `devContainer: true` and added this snippet to `.projenrc.js`, and the task ran & extension was installed.

```ts
const workspaceSetup = project.addTask('workspace:setup');
workspaceSetup.exec('yarn install');
workspaceSetup.spawn(project.buildTask);

project.devContainer.addTasks(workspaceSetup);
project.devContainer.addVscodeExtensions('dbaeumer.vscode-eslint');
```

2020-12-27 14:00 UTC, eladb requested changes

2020-12-27 14:00 UTC, eladb commented on src/devcontainer.ts
> +export abstract class WorkspaceConfig extends Component {
I am not sure about this name. First, we usually try to refrain from using `Config` when we model things in the CDK because this is not a model of the configuration, it's a model of the actual workspace. The configuration is the artifact. (this is why the AWS CDK has a `Stack` class instead of a `Template` class.).

How about calling this `DevEnvironment`?

2020-12-27 14:00 UTC, eladb commented on src/devcontainer.ts
> +import { Component } from './component';
Can you move `devcontainer.ts` under `vscode/` and only leave the abstract types here?

2020-12-28 10:01 UTC, smacintyre commented
@Chriscbr I just noticed this, looks cool. From the Gitpod side, would it be possible to include [prebuilds](https://www.gitpod.io/docs/prebuilds/#configure-the-github-app)? I didn't realize there was this effort to merge the two and need prebuilds and the VS Code extension features from Gitpod so I had created #417

2020-12-29 00:19 UTC, Chriscbr commented
@smacintyre No problem, I've gone ahead and added prebuilds. :)

2020-12-29 06:35 UTC, eladb approved these changes
A was expecting to see gitpod and devcontainer at the Project level replaced by the abstract api. I'd like us to slowly move towards a place where the Project API is mostly agnostic to the specific tools people/concrete projects decide to use.

Examples: tasks, deps.

2020-12-29 06:35 UTC, eladb commented on src/gitpod.ts
> +  readonly port?: string;
Why string?

2020-12-29 06:35 UTC, eladb commented on src/project.ts
> +  public readonly devContainer: DevContainer | undefined;
Shouldn't that be part of the `project.GitHub` api?

2020-12-29 06:36 UTC, merged

2020-12-29 08:55 UTC, Chriscbr commented
@eladb Yeah I'm not totally satisfied with this design... It's hard to choose the right abstraction sometimes. devcontainer.json for instance can be used for GitHub Codespaces, but it also can be used directly with the VS Code "Remote Containers" extension. It probably would be OK under the `project.Vscode` namespace.

But taking a step back, I agree with your broader point. One logical conclusion of that could be creating a `project.devenv` space, similar to `project.GitHub`, which manages _all_ "development environment" options, and put Gitpod and VS Code escape-hatch access inside that (with room for more, e.g. [.editorconfig files](https://editorconfig.org/) and [sublime workspaces](https://www.sublimetext.com/docs/3/projects.html) maybe). And APIs like `addExtensions` or `setIndentSize` would automatically dispatch to those different implementations under the hood. And the task system should play nicely with them as well, in order to generate e.g. `.vscode/tasks.json`.

2020-12-29 08:56 UTC, Chriscbr commented on src/gitpod.ts
> +  readonly port?: string;
Sorry, I should have made this clearer in the docs. Gitpod allows you to specify individual ports **or** ranges of ports ("3000-3999").