feat(pytest): configurable test path
projen/projen pull request #3914
Opened 2024-10-27 04:21 UTC by mikejgray

chore(docs): clarify pytestoptions.testdir purpose

Fixes #1620

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-10-28 09:53 UTC, mrgrain requested changes
I like the direction of this change, but it's getting more confusing with this.

Couple thoughts:

- if `testdir` is not what it claims to be and isn't even used in the component, we should deprecate it (both as options and component property).
- `testPaths` should probably be exposed as a prop on the component
- should the pytest samples be created outside of pytest?

Looking forward to a proposal that will create more consistency!

2024-10-29 01:12 UTC, mikejgray commented
> * if `testdir` is not what it claims to be and isn't even used in the component, we should deprecate it (both as options and component property).
`testdir` is used in the component as the location for sample tests. This is consistent with the NodeProject class IIRC, so deprecating it doesn't seem like the right path forward. Ideally it would be renamed, but I'm not sure what the projen maintainers' policy is on renaming. It wouldn't be a big lift to deprecate `testdir` and point it at a newly named property instead.
> * `testPaths` should probably be exposed as a prop on the component
Good callout, done and coming in a followup commit.
> * should the pytest samples be created outside of pytest?
I have no strong opinion on this. What's the behavior in other project types? PythonProject does not support other Python test modules directly like `unittest` or `nose`, nor does it have the class infrastructure in place to handle that currently.

As a general statement I think it would be appropriate to create some kind of testing base class and subclass that for all project types - one base class per type, as I could imagine the basic testing requirements for Python will differ from Node will differ from Java etc. Pytest is probably the most commonly used, largely because of its support for unittest, but nose has a dedicated following too.

2024-10-31 11:01 UTC, mrgrain commented
> > * if `testdir` is not what it claims to be and isn't even used in the component, we should deprecate it (both as options and component property).
> 
> `testdir` is used in the component as the location for sample tests. This is consistent with the NodeProject class IIRC, so deprecating it doesn't seem like the right path forward. Ideally it would be renamed, but I'm not sure what the projen maintainers' policy is on renaming. It wouldn't be a big lift to deprecate `testdir` and point it at a newly named property instead.

Hmm. I suppose I don't like having both `testdir` and `testPaths`. That's seems like duplication of the same thing. From a `Pytest` component perspective I think it would make sense to deprecate `testdir` in favor of the more flexible `testPaths`. That's kind of how the Jest component works as well (although it's patterns there). This applies both to the option and class property.

> > * should the pytest samples be created outside of pytest?
> 
> I have no strong opinion on this. What's the behavior in other project types? PythonProject does not support other Python test modules directly like `unittest` or `nose`, nor does it have the class infrastructure in place to handle that currently.

Sample code seems to be generally created by the projects. So I guess the current location is fine. But instead of using (the now deprecated) `testdir` from pytest, we should use the project testdir `this.testdir` here:
https://github.com/projen/projen/blob/9aa183d14a9fc1902082a7c59e83d1dc46b65ed6/src/awscdk/awscdk-app-py.ts#L107

And in [the line above](https://github.com/projen/projen/blob/9aa183d14a9fc1902082a7c59e83d1dc46b65ed6/src/awscdk/awscdk-app-py.ts#L106) we will need to combine `this.testdir` with `options.pytestOptions.testPaths`.

2024-11-07 10:55 UTC, mrgrain commented
@mikejgray Are you happy with my proposal? If you're too busy I can also try and pick it up.

2024-11-07 22:34 UTC, mikejgray commented
> @mikejgray Are you happy with my proposal? If you're too busy I can also try and pick it up.

Proposal sounds good! Sorry, I did indeed get busy. I will try to carve out some time to finish this one up

2024-11-18 01:52 UTC, mikejgray commented
@mrgrain I took a closer look at what is happening with Node/Jest and discovered that `testdir` is not defined or exposed on the project level in Python. I took the opportunity to expose it and make it match Node, and then changed `testPaths` to `testMatch` for consistency with jest. Bringing the Python resources in line with Node makes a lot of sense here and requires less juggling to accomplish the same goals.

Please let me know what you think and if any other changes are made. I'd like to get this right and preferably in a backwards-compatible way.

2024-11-18 13:57 UTC, mrgrain commented on src/python/pytest.ts
> +    this.testMatch = options.testMatch ?? [""];
Why not an empty array?

2024-11-18 14:02 UTC, mrgrain commented
Thanks @mikejgray I'm pretty opposed to naming something `testdir` that isn't actually used for that. It's also wrong in the Node/Jest components. If we want to have it, I suggest we call it `sampleTestdir`.

`Pytest` component looks good now!

2024-11-18 14:03 UTC, mrgrain commented on src/python/pytest.ts
> +   * @deprecated Reference `testdir` on the project instead.
```suggestion
   * @deprecated Reference `testdir` on the project instead. To change the directory where tests are discovered from, use `testMatch`.
```

2024-11-18 14:03 UTC, mrgrain requested changes

2024-11-18 14:03 UTC, mrgrain commented on src/python/python-project.ts
> +  public readonly testdir: string;
```suggestion
  public readonly sampleTestdir: string;
```

2024-11-18 14:06 UTC, mikejgray commented
Understood - I'll make your requested changes and make sure it's backwards-compatible!

2024-11-18 14:08 UTC, mrgrain commented
> Understood - I'll make your requested changes and make sure it's backwards-compatible!

Thank you. Just to be clear: Let's not touch Node/Jest in this PR.

2024-11-18 14:09 UTC, mrgrain commented on src/python/python-project.ts
> +   * Directory where sample tests are stored.
```suggestion
   * Directory where sample tests are located.
```

2024-11-18 17:32 UTC, mrgrain commented on src/python/pytest.ts
> +   * @default tests
```suggestion
   * @default "tests"
```

2024-11-18 17:33 UTC, mrgrain commented on src/python/python-project.ts
> +   * @default tests
```suggestion
   * @default "tests"
```

2024-11-18 17:33 UTC, mrgrain commented on src/python/python-project.ts
> +   * @default tests
```suggestion
   * @default "tests"
```

2024-11-18 17:36 UTC, mrgrain commented on src/awscdk/awscdk-app-py.ts
> -  readonly testdir?: string;
I think we still needs this as an input, but deprecated.

2024-11-19 10:38 UTC, mrgrain commented on src/awscdk/awscdk-app-py.ts
> +    this.testdir = this.sampleTestdir = options.sampleTestdir ?? "tests";
```suggestion
    this.testdir = this.sampleTestdir = options.sampleTestdir ?? options.testdir ?? "tests";
```

2024-11-19 10:38 UTC, mrgrain commented on src/awscdk/awscdk-app-py.ts
> +      new AwsCdkPytestSample(this, this.testdir);
```suggestion
      new AwsCdkPytestSample(this, this.sampleTestdir);
```

2024-11-19 10:39 UTC, mrgrain commented on src/python/pytest.ts
> +   * @deprecated Reference `testdir` on the project instead. To change the directory where tests are discovered from, use `testMatch`.
```suggestion
   * @deprecated Reference `sampleTestdir` on the project instead. To change the directory where tests are discovered from, use `testMatch`.
```

2024-11-19 10:39 UTC, mrgrain commented on src/python/pytest.ts
> +   * @deprecated Use `testdir` on the project instead.
```suggestion
   * @deprecated Use `sampleTestdir` on the project instead.
```

2024-11-19 10:41 UTC, mrgrain requested changes
I know this got very confusing with all the name changes. Think this is the last batch of changes.

2024-11-19 10:41 UTC, mrgrain commented on src/awscdk/awscdk-app-py.ts
> +    this.testdir = this.sampleTestdir = options.sampleTestdir ?? "tests";
When deprecating, we try to keep the functionality around but with less priority.

2024-11-20 10:58 UTC, mrgrain approved these changes

2024-11-20 12:04 UTC, merged