fix: defaults the `new` repository name to `cwd` vs `cwd`/..
projen/projen pull request #403
Opened 2020-12-26 14:06 UTC by pgollucci

Previous: cwd: /path/org/repo => org
Now:      cwd: /path/org/repo => repo

2020-12-26 19:30 UTC, eladb requested changes

2020-12-26 19:30 UTC, eladb commented on src/cli/cmds/new.ts
> +            default: () => repoName(),
why lazy?

```suggestion
            default: repoName(),
```

2020-12-26 19:31 UTC, pgollucci commented on src/cli/cmds/new.ts
> +            default: () => repoName(),
brain fart, IDK

2020-12-27 10:10 UTC, eladb approved these changes

2020-12-27 10:16 UTC, merged