feat: allow text file to be marked as executable
projen/projen pull request #458
Opened 2021-01-04 23:05 UTC by jakepearson

Add optional field to FileBase that will allow it to be marked as executable. It merges with the value of readonly to produce the correct file permissions
Fixes #454

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-01-04 23:09 UTC, smashedtoatoms approved these changes

2021-01-04 23:48 UTC, Chriscbr requested changes

2021-01-04 23:48 UTC, Chriscbr commented on src/file.ts
> +   * Whether the generated file should be readonly.
Needs to be updated

2021-01-04 23:55 UTC, jakepearson commented on src/file.ts
> +   * Whether the generated file should be readonly.
Oops.

2021-01-05 00:24 UTC, Chriscbr commented on src/util.ts
> +  const readonly = options.readonly ?? true;
I just realized we need to be careful since the are a few other places where `writeFile` is used in the repo, and they're expecting the file to be writeable afterwards. Could you update this (and the docstring) so the default for `readonly` is false?

2021-01-05 00:44 UTC, pgollucci commented on src/util.ts
> +  const readonly = options.readonly ?? true;
Would it make more sense to expose the full `mode` ?

2021-01-05 02:01 UTC, Chriscbr commented on src/util.ts
> +  const readonly = options.readonly ?? true;
I'm not against it, but for now this helper method does a good job keeping the chmod details in a single abstraction. We can open it up more later if needed

2021-01-05 14:14 UTC, jakepearson commented on src/util.ts
> +  const readonly = options.readonly ?? true;
@Chriscbr, I updated the default value for `readonly` as you suggested. Thanks for looking at this.

2021-01-05 21:07 UTC, Chriscbr approved these changes

2021-01-05 21:11 UTC, merged