fix(eslint): lintProjenRc not working with compiled jest tests
projen/projen pull request #473
Opened 2021-01-08 07:02 UTC by Chriscbr

Fixes #472

Changes eslint's default behavior in TypeScript projects so that by default it creates its own tsconfig file, independent of the one used by jest (`tsconfig.jest.json`). An alternative option here would have been to add more conditional logic for when `tsconfig.jest.json` should be created / when eslint should depend on it, but this solution seemed more robust to future changes.

Exposes `eslintOptions` on JsiiProjectOptions since JsiiProjectOptions doesn't extend TypescriptProjectOptions for some reason. (?)

Deletes tsconfig.jest.ts since it is not currently being generated/used.

Enables `lintProjenRc` on projen repo.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-01-10 08:29 UTC, eladb requested changes

2021-01-10 08:29 UTC, eladb commented on .projenrc.js
> +    lintProjenRc: true,
Shouldn't that be the default?

2021-01-10 08:29 UTC, eladb commented on src/eslint.ts
> +  public generateTypescriptConfig(options: TypescriptConfigOptions) {
Looking at this code I don't really understand what additional logic is added here compared to just `new TypescriptConfig()`

2021-01-10 08:29 UTC, eladb commented on src/typescript.ts
> +      if (options.disableTsconfig) {
Does this mean that if we use jsii then projenrc is not linted?

2021-01-10 11:07 UTC, Chriscbr commented on src/eslint.ts
> +  public generateTypescriptConfig(options: TypescriptConfigOptions) {
Ah you're right -- I originally wrote it this way for parity with a similar method in the `Jest` class, but that's not really needed here. Will fix.

On one hand I'd like to refactor this further so that, say, `tsconfig.jest.json` is managed by `Jest` and `tsconfig.eslint.json` is managed by `Eslint` (so that changes to "include"/"exclude" options are kept in sync easier). But this breaks OOP principles by leaking a lot of Typescript logic elsewhere, so I'd have to think about it more.

2021-01-10 11:10 UTC, Chriscbr commented on .projenrc.js
> +    lintProjenRc: true,
It is usually the default, although there was a line of code added that makes the default "false" if compiled tests are being used (I'm not totally sure why)

https://github.com/projen/projen/blame/6e17704cf0b49c6d40a8913ddf2072e498b03574/src/typescript.ts#L347

I'll remove that line, can easily revert if something comes to your mind

2021-01-10 11:10 UTC, Chriscbr commented on src/typescript.ts
> +      if (options.disableTsconfig) {
As long as the eslintrc's `parserOptions.project` refers to the tsconfig generated by jsii, yes -- it will not get linted. But we can change it to refer to any tsconfig file we want. (Hence in this PR I create a new tsconfig file for it to refer to).

[Before projen v0.13.0-ish, eslint was getting synthesized with `parserOptions.project: "tsconfig.jest.json"`, so this was not an issue. But since we moved projen tests to `src/__tests__`, it's now synthesized with `parserOptions.project: "tsconfig.json"` by default, hence the bug.]

2021-01-18 14:57 UTC, eladb approved these changes

2021-01-18 20:40 UTC, eladb commented
@projen rebuild

2021-01-19 05:09 UTC, eladb approved these changes

2021-01-19 05:09 UTC, eladb commented on src/typescript.ts
> +      // eslint only lints files that are included in the tsconfig it refers to.
```suggestion
      // eslint only lints files included in the tsconfig it refers to.
```

2021-01-19 05:18 UTC, merged