feat: introduce addOverride escape hatch
projen/projen pull request #495
Opened 2021-01-16 10:32 UTC by Chriscbr

Adds standard escape hatches for all object-based files (JSON, YAML, TOML) in the form of `addOverride(path, value)` and `addDeletionOverride(path)`. All you need to do is directly access the file, for example:

```ts
project.tryFindYamlFile('.github/workflows/release.yml').addOverride('jobs.build.env', {
  CI: true,
  myKey: 'myValue',
});
```

The `tryFindYamlFile()` and `tryFindTomlFile()` methods were also added to complement the existing `tryFindJsonFile()` method.

Most of the code for `addOverride` and its test cases were adopted from the aws-cdk project [here](https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/core/lib/cfn-resource.ts).

`GithubWorkflow` had to be refactored in order for it to work with the new escape hatch methods (since they all exist in the `ObjectFile` class).

BREAKING CHANGE: `GithubWorkflow` no longer extends `FileBase`. Use `workflow.file` instead to access file properties.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-01-16 10:42 UTC, Chriscbr commented
Though I initially included this in an RFC yesterday (#493), I think it's ultimately independent from the multi-tiered components concept, so it can probably be extracted out of the RFC and implemented sooner since we can already get immediate benefits. I also feel like this API is pretty robust since it was already done by the CDK / the parallels are more similar. But we can definitely put this on hold if we want to consider other kinds of escape hatch mechanisms.

I think one direction that would be natural after this PR is to begin deprecating raw object fields from being public (e.g. `public manifest: any` or `public config: any` in the `NodePackage` and `Jest` components respectively), and instead provide direct access to the underlying file, through which these escape hatches can be accessed.

2021-01-16 10:43 UTC, Chriscbr commented
@projen rebuild

2021-01-17 08:20 UTC, eladb requested changes
Please add documentation under `docs/`

2021-01-17 08:20 UTC, eladb commented on src/object-file.ts
>    public readonly obj: object;
Can we make this `private`? This is eventually our goal. Otherwise `package.maniest.obj` is a leak.

2021-01-17 08:20 UTC, eladb commented on src/object-file.ts
> +function deepMerge(target: any, ...sources: any[]) {
Don't we have that function in `util` or somewhere?

2021-01-17 08:20 UTC, eladb commented on src/project.ts
> +  public tryFindYamlFile(filePath: string): YamlFile | undefined {
Why do we need to distinguish between file types here? Can we just offer `tryFindObjectFile`?

2021-01-18 08:31 UTC, Chriscbr commented on src/object-file.ts
> +function deepMerge(target: any, ...sources: any[]) {
Yes, although there is subtle difference between the two versions. The `deepMerge(base, override)` in `util` is purely constructive, so when it's given `{ key: undefined }` in `override`, it essentially says "there is nothing to merge, so I'll keep the existing value of `key` from `base`".

But the deepMerge I am adding is destructive (in order to support `addDeletionOverride`), so when it sees `{ key: undefined }` in `override` it essentially says "this key should be deleted from `base`". (And if the object is empty as a result, the object will be deleted). For example:

```ts
deepMerge({ a: "1" }, { a: undefined }) // interpreted as merging the right obj onto the left
```

produces `{ a: "1" }` for the constructive version, and `{}`  for destructive version.

----

I did consider just relying on this destructive version everywhere. But with the way options currently pass through constructors, using this implementation would lead to confusing behavior for users. For example, consider passing in this options to `ReactTypescriptProject`...

```
tsconfig: {
  compilerOptions: {
    module: undefined,
  }
},   
```

tsconfig.compilerOptions.module defaults to "CommonJS" in `TypeScriptProject`, but `ReactTypescriptProject` overrides this with "esnext". So when this user option gets deepMerge'd in the first constructor, the "module" field gets removed (kind of like how `addOverride` operates with `undefined` values); but when the parent class constructor gets called, the "CommonJS" default gets [added back](https://github.com/projen/projen/blob/ea15a203aaec945ea7edb346a2c333c5e787d8d2/src/typescript.ts#L249-L250)! So the user setting it to "undefined" changed the value from "esnext" to "CommonJS" (!?)

There isn't any simple way to fix this independently, so it makes sense to keep the prior behavior (where the user providing `undefined` will set the field to the correct default value, which here would be "esnext"), and leave the two versions of `deepMerge` separate.

2021-01-18 08:58 UTC, Chriscbr commented on src/project.ts
> +  public tryFindYamlFile(filePath: string): YamlFile | undefined {
Sure. I think for consistency it makes sense to deprecate tryFindJsonFile then.

2021-01-18 08:59 UTC, eladb commented on src/object-file.ts
> +function deepMerge(target: any, ...sources: any[]) {
Let's add an option to the util one that enables the destructive behavior?

2021-01-18 08:59 UTC, eladb commented on src/project.ts
> +  public tryFindYamlFile(filePath: string): YamlFile | undefined {
👍

2021-01-18 09:48 UTC, Chriscbr commented on src/object-file.ts
> +function deepMerge(target: any, ...sources: any[]) {
OK. I made non-destructive the default behavior since that's what's wanted in most other places.

2021-01-18 09:48 UTC, Chriscbr commented on src/object-file.ts
>    public readonly obj: object;
Done.

2021-01-18 10:01 UTC, eladb approved these changes
Looks great!

2021-01-18 10:01 UTC, eladb commented on src/object-file.ts
> +  private readonly obj: object;
Announce as a breaking change

2021-01-18 10:03 UTC, Chriscbr commented
OK, there's a small issue where _if_ you enable the "marker" option for pom.xml (currently off by default - I might as well change that right?), the build fails, because pom.xml doesn't allow a \<!-- Generated by ... --> comment at the top, for whatever reason. It looks like inserting it at the end fixes it though.

2021-01-18 10:14 UTC, Chriscbr commented on src/object-file.ts
> +  private readonly obj: object;
Done.

2021-01-18 10:19 UTC, Chriscbr commented
@eladb Build passes, but needs manual merge due to changes to github workflows

2021-01-18 12:19 UTC, merged