WIP: feat: #503 implement docker compose version tag
projen/projen pull request #504
Opened 2021-01-18 06:36 UTC by mmuller88

---
#503
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-01-18 07:17 UTC, eladb requested changes
Test?

2021-01-19 07:06 UTC, mmuller88 commented
@eladb  done :)

2021-01-19 07:13 UTC, eladb requested changes

2021-01-19 07:13 UTC, eladb commented on src/docker-compose.ts
> +  readonly version?: string;
Rename to `schemaVersion`

2021-01-19 07:13 UTC, eladb commented on src/docker-compose.ts
> +    }
TBH this validation seems a bit redundant

2021-01-19 08:47 UTC, mmuller88 commented on src/docker-compose.ts
> +    }
Happy to remove it. I thought it could be useful to get the error already at synth time and not ad docker-compose deploy time ?!

2021-01-19 09:12 UTC, eladb approved these changes

2021-01-19 09:35 UTC, merged