feat: python projects
projen/projen pull request #514
Opened 2021-01-24 10:33 UTC by Chriscbr

WIP

Todo:

- [ ] add more unit tests
- [ ] add basic pytest options
- [ ] implement setuptools and poetry components? (optional)

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-01-24 10:44 UTC, Chriscbr reviewed
I wanted to also have some kind of task that would activate the virtual environment in the developer's shell, but tasks currently just run in a child process IIRC so it's yet not possible to do that. But I don't think it's strictly needed for a MVP.

2021-01-24 10:44 UTC, Chriscbr commented on src/__tests__/__snapshots__/new.test.ts.snap
> +  pythonPath: '/Users/rybickic/.pyenv/shims/python',
Need to fix this. That said, I _would_ like to keep the behavior of filling in the pythonPath automatically at runtime

2021-01-24 10:44 UTC, Chriscbr commented on src/python/requirements-file.ts
> +  readonly _lazyPackages?: any;
Trying to think of a better solution for this

2021-01-24 10:44 UTC, Chriscbr commented on src/python/python-project.ts
> +    }
Could remove this. The issue is if I don't, imports in sample code based on the module name require special syntax e.g. if it has dashes, instead of:

```python
import python_code
```
I'd need
```python
__import__('python-code')
```
which most nobody uses since they just name modules sensibly. So I think I'll just keep this.

2021-01-24 10:44 UTC, Chriscbr commented on src/python/python-project.ts
> +    return name.replace('-', '_');
Update this to also replace periods with underscores

2021-02-01 07:59 UTC, eladb requested changes
Looks great!

Feels like we should find a more robust pattern for "toolchain selection". It's a repeating pattern and maybe we can do better than a set of hard-coded booleans (which is what we've done so far, I know...)

I'll try to sketch something and share.

2021-02-01 07:59 UTC, eladb commented on docs/python.md
> +$ projen new python --name=my-project --python-path=/usr/bin/python
```suggestion
$ projen new python --name=my-project [--python-path=/usr/bin/python]
```

2021-02-01 07:59 UTC, eladb commented on docs/python.md
> +> specifying your project definitions in python.
yass sooner rather then later. happy to help out with that

2021-02-01 07:59 UTC, eladb commented on docs/python.md
> +a component for managing packaging the library. Some components satisfy multiple
```suggestion
a component for packaging the library. Some components satisfy multiple
```

2021-02-01 07:59 UTC, eladb commented on docs/python.md
> +    'aws-cdk.core@*',
The "*" shouldn't be required:

```suggestion
    'aws-cdk.core', // implies "@*"
```

2021-02-01 07:59 UTC, eladb commented on docs/python.md
> +converted to the appropriate syntax in synthesized files. For example,
```suggestion
converted to the appropriate dependency manager syntax in synthesized files. For example,
```

2021-02-01 07:59 UTC, eladb commented on src/__tests__/new.test.ts
> +      execProjenCLI(projectdir, ['new', '--no-synth', '--python-path=/usr/bin/python', type.pjid]);
This looks odd here for the general case. Why is this required?

2021-02-01 07:59 UTC, eladb commented on src/python/pip.ts
> +export class Pip extends Component implements IPythonDeps {
docstrings

2021-02-01 07:59 UTC, eladb commented on src/python/python-deps.ts
> +  /**
Feels like `installTask` should also be part of this

2021-02-01 07:59 UTC, eladb commented on src/python/python-project.ts
> +    }
Sounds good

2021-02-01 07:59 UTC, eladb commented on src/python/python-project.ts
> +    this.envManager.setupEnvironment();
Perhaps `envManager` and `depsManager` should just be `Component`s and then they can just implement `postSynthesize()` on their own, no?

2021-02-01 07:59 UTC, eladb commented on src/python/requirements-file.ts
> +  readonly _lazyPackages?: any;
maybe:

```ts
packageProvider: IPackageProvider;
```

And then:

```ts
interface IPackageProvider {
  getPackages(): ...
}
```

Or something like that.

2021-02-01 23:02 UTC, Chriscbr commented on src/__tests__/new.test.ts
> +      execProjenCLI(projectdir, ['new', '--no-synth', '--python-path=/usr/bin/python', type.pjid]);
pythonPath is a required parameter that gets auto-filled into .projenrc.js with the value of $(which python). Since this depends on your environment, I added this to make the Python .projenrc.js snapshot deterministic. I'll add a conditional to help make it clear that it isn't needed for all projects.

2021-02-01 23:03 UTC, Chriscbr commented on src/python/python-deps.ts
> +  /**
Sure, definitely.

2021-02-01 23:05 UTC, Chriscbr commented on src/python/python-project.ts
> +    this.envManager.setupEnvironment();
I considered that initially, but then the execution order becomes ambiguous (it's not really transparent which component's `postSynthesize()` would get called first, so `installDeps()` could run before `setupEnvironment()` and then modules could get installed to your global python installation instead of the virtual environment).

2021-02-01 23:10 UTC, Chriscbr commented
> Feels like we should find a more robust pattern for "toolchain selection". It's a repeating pattern and maybe we can do better than a set of hard-coded booleans (which is what we've done so far, I know...)
> 
> I'll try to sketch something and share.

Cool, I'm totally down. 👍

2021-02-02 00:28 UTC, Chriscbr commented on src/python/requirements-file.ts
> +  readonly _lazyPackages?: any;
Hmm, yeah that's an idea. Object oriented design patterns to the rescue 😅

2021-02-02 02:30 UTC, Chriscbr commented on src/python/python-project.ts
> +  readonly setuptoolsOptions?: SetuptoolsOptions;
Substitute this with a more general `packagingOptions` field, and eliminate any of the xxxOptions fields that aren't needed

2021-02-02 07:51 UTC, eladb commented on src/__tests__/new.test.ts
> +      execProjenCLI(projectdir, ['new', '--no-synth', '--python-path=/usr/bin/python', type.pjid]);
Thinking about this some more- I think python path should probably just be based on the system definition and not baked into the project because there might be differences between developer environments and CI environments

2021-02-03 06:51 UTC, Chriscbr commented on src/__tests__/new.test.ts
> +      execProjenCLI(projectdir, ['new', '--no-synth', '--python-path=/usr/bin/python', type.pjid]);
Hmm... I think you're right. Where you have your python installation really shouldn't be tied to the project at all. I'll make the assumption that consumers should have the version of python that they want to use accessible via the `python` command and they should adjust their PATH accordingly.

2021-02-03 12:21 UTC, eladb reviewed
Looks good. See minor comment.

2021-02-03 12:21 UTC, eladb commented on src/cli/macros.ts
> +    case '$PYTHON_PATH': return resolvePython();
Is this still needed?

2021-02-03 12:21 UTC, eladb commented on src/python/poetry.ts
> +    this.uploadTestTask = project.addTask('upload:test', {
should this be called `publish` instead of "upload"?

2021-02-03 12:21 UTC, eladb commented on src/python/python-project.ts
> +    this.envManager.setupEnvironment();
Okay. sounds good

2021-02-04 06:18 UTC, Chriscbr commented on src/cli/macros.ts
> +    case '$PYTHON_PATH': return resolvePython();
Good catch

2021-02-04 06:18 UTC, Chriscbr commented on src/python/poetry.ts
> +    this.uploadTestTask = project.addTask('upload:test', {
Yep, updating

2021-02-04 07:26 UTC, Chriscbr commented
Updated the docs and PR description.

cc @garnaat Feel free to take a look. The docs rendered [here](https://github.com/Chriscbr/projen/blob/feat/python-project/docs/python.md) give an overview of what we have so far.

There are still some high level features like github workflows and configuration through projenrc.py left, but I'll leave those for a later PR.

I think the mental model I've captured here for several of the python tools is a good enough start, but like @eladb mentioned, there might be a better way to structure the APIs for choosing between these tools. 

As far as what the components actually do under the hood, most of it I feel OK with, although I wonder if `Pip` should be doing more -- like perhaps freezing the requirements and automatically diff'ing the results with the previous version and showing the changes to the user etc. But I don't have much python dependency management experience to build off of, so I'm mostly reading docs online to see what the options are. I just know we want the different language project types to feel similar to use.

Anyway, I'm looking forward to having this merged. :D

2021-02-04 08:13 UTC, eladb approved these changes

2021-02-04 08:18 UTC, merged