feat: migrate from master branch to main branch
projen/projen pull request #517
Opened 2021-02-02 03:56 UTC by campionfellin

I think this will introduce breaking changes for projects using `projen`. Making changes here I think will be more impactful. Rather than leaving each repository to choose to migrate `master` to `main`, we can now default `projen` projects to `main`.

After merging this into `master`, change main `projen` project branch to `main` and copy branch over.

Signed-off-by: campionfellin <campionfellin@gmail.com>

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-02-02 05:44 UTC, Chriscbr requested changes
I support changing the default to `main`. I agree it will probably break consumers, but prioritizing it sooner is better than later.

Also normally we don't include version bumps in PRs, and it looks like the bump-workflow automatically got ran on your branch - I'm guessing that should be reverted (you might have to disable the workflow on your fork)

2021-02-02 05:44 UTC, Chriscbr commented on src/gitpod.ts
> -  readonly master?: boolean;
This field was taken from a schema here: https://github.com/gitpod-io/gitpod/blob/master/components/dashboard/public/schemas/gitpod-schema.json

Since "main" might not be valid, I think this change should be reverted

2021-02-02 12:18 UTC, eladb commented on CHANGELOG.md
> +## [0.16.0](https://github.com/projen/projen/compare/v0.5.2...v0.16.0) (2021-02-02)
revert

2021-02-02 12:18 UTC, eladb commented on package.json
> +  "version": "0.16.0",
revert

2021-02-02 12:19 UTC, eladb commented on src/__tests__/dev-env.test.ts
> -    master: true,
revert

2021-02-02 12:19 UTC, eladb reviewed
see comments + add a "BREAKING CHANGE" section in PR desc.

2021-02-02 16:00 UTC, campionfellin commented on src/gitpod.ts
> -  readonly master?: boolean;
Thanks for the callout! Reverted

2021-02-03 14:43 UTC, eladb approved these changes

2021-02-03 14:44 UTC, merged