feat(AwsCdkConstruct): make cdkDependencies behavior configurable
projen/projen pull request #581
Opened 2021-03-01 09:09 UTC by Miradorn

Hey there!

This is a first draft based on the feedback in #577 .
Please tell me what you think!

closes #577
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-03-01 09:54 UTC, eladb requested changes

2021-03-01 09:54 UTC, eladb commented on src/awscdk-construct.ts
> +   *
```suggestion
  /** 
   * If this is enabled (default), all modules declared in `cdkDependencies` will be also added as normal `dependencies` (as well as `peerDependencies`).
   *
```

2021-03-01 09:54 UTC, eladb commented on src/awscdk-construct.ts
> +  readonly addCdkDependenciesToDeps?: boolean;
Rename to: `cdkDependenciesAsDeps`

2021-03-01 11:45 UTC, eladb commented on API.md
> +  * **addCdkDependenciesToDeps** (<code>boolean</code>)  Should `cdkDependencies` be added to package.json `dependencies`. __*Default*__: true
Rebuild

2021-03-01 11:45 UTC, eladb commented on src/awscdk-construct.ts
> +   * If `false` `cdkDependencies` will be added to `devDependencies` to ensure they are present during development.
```suggestion
   * This is to ensure that downstream consumers actually have your CDK dependencies installed
   * when using npm < 7 or yarn, 
where peer dependencies are not automatically installed. 
   * If this is disabled, `cdkDependencies` will be added to `devDependencies` to ensure they are present during development.
```

2021-03-01 11:45 UTC, eladb commented on src/awscdk-construct.ts
> +  public readonly cdkDependenciesAsDeps: boolean
Docstring please

2021-03-01 13:41 UTC, eladb commented on src/awscdk-construct.ts
> +   */
Wrap:

```suggestion
  /**
   * If this is enabled (default), all modules declared in `cdkDependencies` will be also added as
   * normal `dependencies` (as well as `peerDependencies`).
   *
   * This is to ensure that downstream consumers actually have your CDK dependencies installed
   * when using npm < 7 or yarn, where peer dependencies are not automatically installed.
   * If this is disabled, `cdkDependencies` will be added to `devDependencies` to ensure
   * they are present during development.
   *
   * @default true
   */
```

2021-03-01 13:42 UTC, eladb commented on src/awscdk-construct.ts
> +   */
```suggestion
  /**
   * Whether CDK dependencies are added as normal dependencies (and peer dependencies).
   */
```

2021-03-01 13:46 UTC, eladb commented
@projen rebuild

2021-03-01 13:47 UTC, eladb approved these changes

2021-03-01 13:52 UTC, merged

2021-06-11 07:36 UTC, hoegertn commented
@Miradorn if using the new flag and installing CDK as devDeps and peerDeps, shouldn't the devDeps be pinned to guarantee a minimal version and the peerDeps are `^` 

Currently both are unpinned.