fix(node): removeScript does not remove scripts associated with tasks
projen/projen pull request #632
Opened 2021-03-18 03:34 UTC by Chriscbr

Fixes #631.

Deprecates the `hasScript` method on node projects (it still partially works, but `setScript` and `removeScript` APIs now use the [override escape hatch](https://github.com/projen/projen/blob/main/docs/escape-hatches.md) which is designed to be write-only, so only scripts added via the task system will be detected).

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-03-18 06:04 UTC, eladb requested changes

2021-03-18 06:04 UTC, eladb commented on src/__tests__/__snapshots__/integ.test.ts.snap
> -      "build": "npx projen build",
What happened here?

2021-03-18 06:04 UTC, eladb commented on src/node-package.ts
> +  private file: JsonFile;
```suggestion
  private readonly file: JsonFile;
```

2021-03-24 03:37 UTC, Chriscbr commented on src/__tests__/__snapshots__/integ.test.ts.snap
> -      "build": "npx projen build",
This is part of the snapshot test for cdk8s-projenrc.js. You can see [here](https://github.com/projen/projen/blob/05025555ef8448978450241a36b4bdfe48536101/src/__tests__/integration/cdk8s/cdk8s.projenrc.js#L52) it calls a shared "fixup" function, which calls `project.setScript('build', 'yarn compile');`. From my perspective, "yarn compile" is the correct output -- setScript was just ignored before because a corresponding task named "build" was taking higher precedence.

2021-03-24 03:38 UTC, Chriscbr commented on src/node-package.ts
> +  private file: JsonFile;
Done.

2021-03-24 18:29 UTC, eladb approved these changes

2021-03-24 18:34 UTC, merged