chore: update xmlbuilder2 dependency
projen/projen pull request #635
Opened 2021-03-19 01:41 UTC by campionfellin

I am hoping that this will fix https://github.com/projen/projen/issues/498

You can see the diff between the current `xmlbuilder2` library and my fork of it here - 

https://github.com/oozcitak/xmlbuilder2/compare/master...campionfellin:master

Basically, just changing the dependency on `@types/node` from `14.6.2` to `*`

Signed-off-by: campionfellin <campionfellin@gmail.com>

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-03-24 16:14 UTC, eladb commented
@campionfellin isn't it possible to get this updated upstream (i.e. submit a PR against `xmlbuilder2`) instead of forking? How do we expect to maintain the fork?

2021-03-24 16:15 UTC, eladb requested changes
See comment

2021-03-24 16:20 UTC, campionfellin commented
@eladb it doesn't really seem like `xmlbuilder2` is actively maintained, there is this PR from January: https://github.com/oozcitak/xmlbuilder2/pull/69

And there hasn't been a real commit since November - https://github.com/oozcitak/xmlbuilder2/commits/master

2021-03-24 16:23 UTC, eladb commented
I see https://github.com/oozcitak/xmlbuilder2/issues/84 has been raised a few hours ago. Shall we try to ping the maintainer there and see where this goes? Perhaps submit a PR?

2021-03-24 16:36 UTC, campionfellin commented
Sure! That works for me

2021-04-08 20:27 UTC, campionfellin commented
Looks like a new version of `xmlbuilder` was released 8 hours ago - https://www.npmjs.com/package/xmlbuilder2

I expect dependabot to make a PR to update sometime within the next 24 hours. Closing this PR.

2021-04-08 20:27 UTC, closed without merging