feat: allow users to customize the publisher workflow image
projen/projen pull request #640
Opened 2021-03-23 02:43 UTC by misterjoshua

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-03-24 03:56 UTC, Chriscbr approved these changes
LGTM

2021-03-24 18:28 UTC, eladb requested changes
Can this be just `workflowImage`?

2021-03-24 18:47 UTC, misterjoshua commented
> Can this be just `workflowImage`?

I couldn't see the details of the review clearly - I've pushed up some changes. Is this what you had in mind?

2021-03-25 06:59 UTC, eladb commented on src/__tests__/node-project.test.ts
> +    workflowContainerImage: 'some-other-workflow-image',
```suggestion
    workflowImage: 'some-other-workflow-image',
```

2021-03-25 06:59 UTC, eladb approved these changes

2021-03-25 07:05 UTC, eladb requested changes
Wait... I misunderstood this PR...

What's the use case for customizing only the image used to call `jsii-release-npm`? What is the motivation?

2021-03-25 07:05 UTC, eladb commented
To work around #639 you should be able to use escape hatches, no?

2021-03-25 08:21 UTC, misterjoshua commented
> To work around #639 you should be able to use escape hatches, no?

No obvious ways how jump out at me, but I may be missing some context. What escape hatches would have even been available to substitute the faulty job container in that npm publish step?

At the time, none of the node commands or `jsii-release-npm` worked in the superchain container. It seemed pretty reasonable to look to work around the issue by replacing the bad container image with a known good one. But, while the build job container was easy to change by project prop, it didn't seem like there was any straightforward way to patch the publishing job container since it was hard-coded.

But maybe there's something I don't understand here?

2021-03-25 10:25 UTC, eladb commented
You should be able to to find the workflow file using `tryFindObjectFile` and then add an override.

See https://github.com/projen/projen/blob/main/docs/escape-hatches.md and let me know if that makes sense.

2021-03-25 15:18 UTC, misterjoshua commented
> You should be able to to find the workflow file using `tryFindObjectFile` and then add an override.
> 
> See https://github.com/projen/projen/blob/main/docs/escape-hatches.md and let me know if that makes sense.

@eladb Ah. I see now. I hadn't discovered these methods. I looked in all the wrong places too. Lol. Yeah, with these methods, I don't think this PR is strictly necessary.

2021-03-25 21:41 UTC, closed without merging