feat(python): pipenv support
projen/projen pull request #649
Opened 2021-03-26 17:16 UTC by ArmaanT

This PR adds the ability for python projects to use Pipenv to manage virtual environments and dependencies. I also cleaned up a bit of duplicate code in the python tests.
Alongside the unit tests, I've tested this PR out locally by creating a small python project managed by projen.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-03-26 19:27 UTC, Chriscbr requested changes
Looks great! See comments below

2021-03-26 19:27 UTC, Chriscbr commented on src/python/pipenv.ts
> +  }
Can you add some unit tests that check `Pipfile` synthesizes correctly when the user adds dependencies with different kinds of  (e.g. `deps: ['flask', 'isort@^5.8.0', 'test@0.0.1']`)? When I tried this out, it seemed to cause issues because it looks like Pipefile expects packages in a specific format (see [here](https://github.com/pypa/pipfile#pipfile)).

We have a utility function [here](https://github.com/projen/projen/blob/b9152631d7f79d83df175cda497fe3f01cb3b46f/src/util/semver.ts#L52) that converts strings like '*' or '^6.0.3' into traditional python version strings, like '>=0.0.0' and '>=6.0.3, <7.0.0' respectively; this might help.

2021-04-18 05:37 UTC, eladb commented
@ArmaanT would you be able to address @Chriscbr's feedback?

2021-04-25 03:58 UTC, ArmaanT commented
Sorry about that, I had a busy few weeks. I can definitely make those changes in the next week or so.

2021-05-21 06:30 UTC, eladb commented
Any updates? Should we close for now until you are ready to pick this up?

2021-05-25 15:31 UTC, ArmaanT commented
Yeah, I think closing for now makes sense. I have a couple of questions about PEP 508 markers that I think should be resolved before merging this. I'll make an issue for that discussion.

2021-05-25 15:31 UTC, closed without merging