feat(dependencies): dependencies upgrade via github-actions
projen/projen pull request #652
Opened 2021-03-29 08:45 UTC by iliapolo

Dependency upgrades in projen are currently managed by dependabot, which creates a PR for each package upgrade separately. This poses two issues:

- Creates clutter and possibly high maintenance load of PR's cannot be automatically merged.
- Prevents updates of packages that need to be upgraded in unity (for example `@aw-cdk`).

This PR introduces an alternative by using a GitHub workflow that executes `npm-check-updates` to upgrade `package.json` files, and `yarn` to synchronize the lock file.

Another problem with the current setup is that automatic merges are accomplished by two distinct mergify rules. 

- `auto-merge` label + build passes CI.
- PR's from dependabot + build passes CI.

This approach breaks down if branch protection rules require a PR approval. Since this is the best practice we want to encourage, we need to come up with a different merge mechanism. 

With this PR, dependency update PR's will be automatically approved by a different github workflow (`auto-approve.yml`).
This means we can remove the aforementioned mergify rules, and use the standard rule of merging approved PR's that pass CI build.

The auto approval workflow is enabled by default since it can utilize the default github token available to workflows, without requiring an additional projen specific token.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-03-29 09:25 UTC, iliapolo commented on src/projen-upgrade.ts
> -  readonly autoUpgradeSecret?: string;
Instead, I exposed `projenSecret` on `NodeProject` and reused it.

2021-03-29 09:25 UTC, iliapolo commented on src/node-project.ts
> +  public static dependabot(options: DependabotOptions = {}): DependenciesUpgrade {
Not in love with this API, happy to accept alternatives :)

2021-03-29 09:25 UTC, iliapolo commented on src/node-project.ts
> +  public static readonly GITHUB_ACTIONS: DependenciesUpgrade = new DependenciesUpgrade('github-actions');
Just some sugar to provide an enum like experience for the common use-case.

2021-03-29 12:29 UTC, eladb requested changes
High level comment is whether we really need the projen upgrade workflow any more.

2021-03-29 12:29 UTC, eladb commented on .github/workflows/auto-approve.yml
> +    if: contains(github.event.pull_request.labels.*.name, 'pr/auto-approve')
I don't see a huge value in the `pr/` prefix here.

```suggestion
    if: contains(github.event.pull_request.labels.*.name, 'auto-approve')
```

2021-03-29 12:29 UTC, eladb commented on .github/workflows/auto-approve.yml
> +    if: contains(github.event.pull_request.labels.*.name, 'pr/auto-approve')
Are we at all concerned that this basically allows maintainers to approve their own PRs even if "required for administrators" is set. @RomainMuller will likely have a strong opinion here.

2021-03-29 12:29 UTC, eladb commented on src/__tests__/node-project.test.ts
> +  test('defaults to github actions when a projen secret is defined', () => {
```suggestion
  test('defaults to a github workflow when a projen secret is defined', () => {
```

2021-03-29 12:29 UTC, eladb commented on src/github/auto-approve.ts
> +   * @default pr/auto-approve
Defaults should be JSON encoded (and also, please change to `auto-approve`)

```suggestion
   * @default "auto-approve"
```

2021-03-29 12:29 UTC, eladb commented on src/github/auto-approve.ts
> +    this.label = options.label ?? 'pr/auto-approve';
```suggestion
    this.label = options.label ?? 'auto-approve';
```

2021-03-29 12:29 UTC, eladb commented on src/github/auto-approve.ts
> +        'if': `contains(github.event.pull_request.labels.*.name, '${this.label}')`,
Mmm.. curious - what will cause this it fail if this is the same user?

2021-03-29 12:29 UTC, eladb commented on src/github/auto-upgrade-dependencies.ts
> +   * @default - Only projen itself is ignored.
```suggestion
   * @default - `projen` is ignored since there is a separate workflow to upgrade it.
```

Which makes me wonder - with the combination of this and the self-mutation feature, do we really need a separate upgrade workflow for projen? Feel like we can just use this workflow to upgrade projen itself, and let the self-mutation workflow update the branch if there are any synth changes, no?

2021-03-29 12:29 UTC, eladb commented on src/github/auto-approve.ts
> +export class AutoApprove extends Component {
I am wondering how this will work with the self-mutation workflow (the current version and the future version which will submit a PR against your branch). 

I am thinking that maybe initially we can avoid auto-approve in the dependency upgrade workflows, so that if there are any synth changes that result in the update, a human will need to review them. WDYT?

2021-03-29 12:29 UTC, eladb commented on src/github/auto-upgrade-dependencies.ts
> +export interface AutoUpgradeDependenciesOptions {
Rename to `UpgradeDependencies` instead of `AutoUpgradeDependencies` - the "auto" part is optional.

2021-03-29 12:29 UTC, eladb commented on src/github/auto-upgrade-dependencies.ts
> +  DAILY = 'daily',
NEVER is missing

2021-03-29 12:29 UTC, eladb commented on src/github/auto-upgrade-dependencies.ts
> +    const dependencies = project.github.addWorkflow('auto-upgrade-dependencies');
```suggestion
    const dependencies = project.github.addWorkflow('upgrade-dependencies');
```

2021-03-29 12:29 UTC, eladb commented on src/github/auto-upgrade-dependencies.ts
> +            run: `yarn install && yarn upgrade --pattern !(${ignore.join('|')})`,
We should use `npm` if the project is configured to use npm, no?

2021-03-29 12:29 UTC, eladb commented on src/github/auto-upgrade-dependencies.ts
> +              'token': `\${{ secrets.${project.projenSecret} }}`,
Is this really needed? I suspect a scheduled task should have a read/write token by default.

2021-03-29 12:34 UTC, iliapolo commented on .github/workflows/auto-approve.yml
> +    if: contains(github.event.pull_request.labels.*.name, 'pr/auto-approve')
See https://github.com/projen/projen/pull/652#discussion_r603120017

2021-04-14 03:56 UTC, pgollucci commented on src/__tests__/integration/cdk-watchful.projenrc.js
> +  projenSecret: 'PROJEN_GITHUB_TOKEN',
Why did this get renamed again ?

2021-04-14 03:58 UTC, pgollucci commented on src/github/auto-upgrade-dependencies.ts
> +   * @default - Only projen itself is ignored.
tough question.

2021-04-14 03:58 UTC, pgollucci commented on src/github/auto-upgrade-dependencies.ts
> +            run: `yarn install && yarn upgrade --pattern !(${ignore.join('|')})`,
https://github.com/projen/projen/issues/651

2021-04-14 04:00 UTC, pgollucci commented on src/github/index.ts
> +export * from './workflows';
Make a workflows dir ?
workflows/auto-merge
worksflow/foo
worksflows/....
?

2021-04-18 05:38 UTC, eladb commented
@iliapolo any chance we can get this merged? It will quickly get stale and hard to maintain this branch...

2021-04-28 08:26 UTC, RomainMuller commented on src/github/auto-upgrade-dependencies.ts
> +export enum AutoUpgradeDependenciesSchedule {
I don't like how all of these options are at midnight UTC. You'd usually want to randomise that a bit to spread the load over (free) CI environments... As a basic courtesy.

At least, there should be an option to provide one's own POSIX cron expression.

2021-04-28 08:26 UTC, RomainMuller commented on src/github/auto-upgrade-dependencies.ts
> +            run: `npx npm-check-updates --upgrade --reject '${ignore.join(',')}'`,
Suggest making the upgrade target explicit (valid values are: `'minor' | 'patch' | 'latest'`).

```suggestion
            run: `npx npm-check-updates --upgrade --target 'minor' --reject '${ignore.join(',')}'`,
```

1. If the environment has `npm@^7`, this will actually not work, as it'll hang on a prompt asking if it's okay to install `npm-check-updates` before proceeding
2. Since you control the project settings, why not add `npm-check-updates` to the `devDependencies` of the project, and open with a dependency install stage? This has the added benefit of allowing the customer to control what version of `npm-check-updates` is being used (you may get nasty surprises otherwise, as `npx` will just get whatever the `latest` is... it may be incompatible with your invocations!
3. There are missing features here:
   1. I need to be able to major-pin certain dependencies (typically, I'd want this workflow NOT to upgrade any of my non-`dev` dependencies to a new major line -- and also `@types/node` should remain on the lowest supported `node` major). I'd be tempted to make this `pinToMajor = ['@types/node']`, perhaps with a way to opt out of the `dependencies` security.
   2. I need to be able to minor-pin certain dependencies (some packages do not honour SemVer, and so you wanna make sure they only get patch-upgraded... for example: `typescript`). I'd be tempted to make this `pinToMinor=['typescript']`
   3. This is not `yarn workspaces`/mono-repos aware. This may be fine (does `projen` support this use-case anyway?)

2021-04-28 08:26 UTC, RomainMuller commented on src/github/auto-upgrade-dependencies.ts
> +            run: `yarn install && yarn upgrade --pattern !(${ignore.join('|')})`,
This is precisely why I'd have named this `yarn-upgrade`, and would have checked that the project uses `yarn` before configuring.

2021-04-28 08:26 UTC, RomainMuller commented on src/github/auto-upgrade-dependencies.ts
> +              'token': `\${{ secrets.${project.projenSecret} }}`,
Check out the (relatively new) [`permissions`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idpermissions) configuration...

Since this workflow triggers either on a `cron` or `workflow_dispatch`, it can be seen as only touching code that has been accepted into the default branch already (i.e: is "trusted")... You could grant the workflow extended permissions so you no longer have to provision a PAT for this kind of use-case.

2021-04-28 08:26 UTC, RomainMuller commented on src/github/auto-upgrade-dependencies.ts
> +              'body': 'Upgrade dependencies\n\n------\n\n*Automatically created by projen via GitHubActions*',
Those should be made user-configurable (`labels` obviously is already).

I would also not name the default branch `github-actions/dependencies` -- it's way too generic and could likely end up being shared by several dependency-management actions, which would not be good... At the very least, you'll want this to include the name of the workflow.

2021-04-28 08:26 UTC, RomainMuller commented on src/github/auto-upgrade-dependencies.ts
> +      case AutoUpgradeDependenciesSchedule.WEEKDAY:
If you have `WEEKDAY` you also need `WEEKEND`. And then again... Are these defined "universally"? I'd be tempted to say a weekend is Saturday & Sunday... But folks in Israel may be tempted to say it's Friday & Saturday... Depending on *why* you want to refer to the week-end here (you likely mean "days when nobody is in the office").

This looks like trying too hard to me, and I'd kinda feel like you might want to allow people to craft their own CRON expression, possibly with factories for the "basic" cases such as daily, weekly, and monthly.

2021-04-28 08:26 UTC, RomainMuller commented on src/node-project.ts
> +        throw new Error(`Unsupported dependency upgrade type: ${this.type}`);
❤️

2021-04-28 08:26 UTC, RomainMuller commented on src/node-project.ts
> +  }
I'm not entirely sure these are necessary, as they are 2/3rd boilerplate... The one-liner content could probably have been directly in the `switch` within `bind`... But since they're already broken out... I guess it's not bad!

2021-05-10 11:20 UTC, eladb reviewed
Looking forward for this!

2021-05-13 07:01 UTC, eladb commented on src/upgrade-dependencies.ts
> +        'permissions': 'write-all',
Can we scope this down?

2021-05-13 07:01 UTC, eladb commented on src/upgrade-dependencies.ts
> +          name: 'Update status check',
Can this be reused with the node build workflow somehow?

2021-05-13 07:01 UTC, eladb commented on src/upgrade-dependencies.ts
> +            GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}',
Is this needed?

2021-05-16 09:12 UTC, eladb approved these changes
See some comments. Added `do-not-merge`

2021-05-16 09:12 UTC, eladb commented on src/node-project.ts
> +  public static githubActions(options: UpgradeDependenciesOptions = {}) {
The name `githubActions` is a bit ambiguous. It could be interpreted as "only upgrade GitHub actions". It's also not very accurate because the actual tool is not actions.

Maybe the name of the class could be different- something like `DependencyUpgradeMechanism` and then instead of githubActions we can use `ncu`?

2021-05-16 09:12 UTC, eladb commented on src/upgrade-dependencies.ts
> +   * Which secret to use when creating the PR.
Describe the difference between using the default token and a user supplied token

2021-05-16 09:12 UTC, eladb commented on src/upgrade-dependencies.ts
> +   * @default - no labels.
```suggestion
   * @default [] no labels.
```

2021-05-16 09:12 UTC, eladb commented on src/upgrade-dependencies.ts
> +   * Execute 'build' after the upgrade.
Add some details on what that means

2021-05-16 09:12 UTC, eladb commented on src/upgrade-dependencies.ts
> +   * Include a github workflow for creating PR's that upgrades the
What happens if this is `false`? Does that imply dependabot? Does that imply that upgrades can be done manually?

2021-05-16 09:12 UTC, eladb commented on src/upgrade-dependencies.ts
> +   * @default 'upgrade-dependencies'.
```suggestion
   * @default "upgrade-dependencies"
```

Defaults should be JSON

2021-05-16 09:12 UTC, eladb commented on src/upgrade-dependencies.ts
> +  readonly ignoreProjen?: boolean;
Why not just make this the default for 'exclude'?

2021-05-16 09:12 UTC, eladb commented on src/upgrade-dependencies.ts
> +export class UpgradeDependenciesSchedule {
Style: I prefer to put all these auxiliary types _after_ the main options and class.

2021-05-16 09:12 UTC, eladb commented on .projen/tasks.json
> -    "projen:upgrade": {
I expected to see the new task here

2021-05-16 09:12 UTC, eladb commented on src/node-project.ts
> +    if (dependenciesUpgrade.ignoresProjen && this.package.packageName !== 'projen') {
Why is this only used if ignoreProjen is true?

2021-05-16 09:12 UTC, eladb commented on src/upgrade-dependencies.ts
> +    const project = this.project as NodeProject;
I'd keep `nodeProject` as a member (otherwise this can break in the future)

2021-05-16 09:13 UTC, eladb requested changes
No do not merge so changed review verdict to avoid auto-merge

2021-05-17 21:13 UTC, iliapolo commented on src/github/auto-upgrade-dependencies.ts
> +export enum AutoUpgradeDependenciesSchedule {
Exposed a way to provide a custom cron expression 👍

2021-05-17 21:15 UTC, iliapolo commented on src/github/auto-upgrade-dependencies.ts
> +            run: `npx npm-check-updates --upgrade --reject '${ignore.join(',')}'`,
- This isn't mono-repo aware, projen doesn't really support it anyway. 

- Regarding specific minor-pins - yes, feature needed. I'll add in a subsequent PR. This currently only addresses the naive case. 

- `npm-check-updates` now added to `devDependencies` 👍

2021-05-17 21:16 UTC, iliapolo commented on src/github/auto-upgrade-dependencies.ts
> +              'body': 'Upgrade dependencies\n\n------\n\n*Automatically created by projen via GitHubActions*',
Yeap, added workflow name.

2021-05-17 21:17 UTC, iliapolo commented on src/github/auto-upgrade-dependencies.ts
> +      case AutoUpgradeDependenciesSchedule.WEEKDAY:
Added custom cron expression support - this should suffice for now.

2021-05-17 21:18 UTC, iliapolo commented on src/node-project.ts
> +  }
Simplified by having the static factories pass a `binder` function

2021-05-17 21:19 UTC, iliapolo commented on src/github/auto-upgrade-dependencies.ts
> +              'token': `\${{ secrets.${project.projenSecret} }}`,
Yeap - using the default token with `write-all` permissions.

2021-05-17 21:19 UTC, iliapolo commented on src/github/auto-upgrade-dependencies.ts
> +            run: `yarn install && yarn upgrade --pattern !(${ignore.join('|')})`,
Added support for all package managers

2021-05-17 21:19 UTC, iliapolo commented on src/github/auto-merge.ts
> -  public readonly autoMergeLabel: string;
Yeap

2021-05-17 21:20 UTC, iliapolo commented on src/node-package.ts
> +  public renderInstallCommand(frozen: boolean) {
It avoid duplicating the exact same logic in the upgrade workflow. Since this method doesn't expose anything inherently private, figured its harmless.

2021-05-17 21:20 UTC, iliapolo commented on src/node-project.ts
> -  readonly mergifyAutoMergeLabel?: string;
yes

2021-05-17 21:30 UTC, iliapolo commented on src/upgrade-dependencies.ts
> +      const schedule = options.schedule ?? UpgradeDependenciesSchedule.DAILY;
Not sure which part you mean here exactly. I've refactored the code since this comment so hopefully its more readable and clean now.

2021-05-17 21:33 UTC, iliapolo commented on src/upgrade-dependencies.ts
> +        'permissions': 'read-all',
added

2021-05-17 21:33 UTC, iliapolo commented on src/upgrade-dependencies.ts
> +              GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}',
Its not, letfovers.

2021-05-17 21:35 UTC, iliapolo commented on src/upgrade-dependencies.ts
> +        'permissions': 'write-all',
I think so, let me try.

2021-05-17 21:36 UTC, iliapolo commented on src/upgrade-dependencies.ts
> +            GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}',
Yes - its used in the authentication header of the `curl` command.

2021-05-17 21:39 UTC, iliapolo commented on src/upgrade-dependencies.ts
> +          name: 'Update status check',
With a little work, yes - but i'll skip it for now.

2021-05-17 21:41 UTC, iliapolo commented on package.json
> -    "projen:upgrade": "/bin/bash ./projen.bash projen:upgrade",
What's the meaning of a `projen:upgrade` task in projen itself? It uses its own source code.

2021-05-17 21:45 UTC, iliapolo commented on src/node-project.ts
> +  public static githubActions(options: UpgradeDependenciesOptions = {}) {
I've been struggling with this :\ 

`ncu` also feels funky cause its an implementation detail - if we switch to `npm update` would we have to change the name? 

I'll change to `DependencyUpgradeMechanism.githubWorkflow` and let me know what you think.

2021-05-17 21:49 UTC, iliapolo commented on src/upgrade-dependencies.ts
> +   * Which secret to use when creating the PR.
Added

2021-05-17 21:53 UTC, iliapolo commented on src/upgrade-dependencies.ts
> +   * Execute 'build' after the upgrade.
Added

2021-05-17 21:55 UTC, iliapolo commented on src/upgrade-dependencies.ts
> +   * Include a github workflow for creating PR's that upgrades the
It simply creates a local projen task and upgrades can be done manually by running `yarn upgrade-dependencies`. It's not related to dependabot. Added to comment.

2021-05-17 21:57 UTC, iliapolo commented on src/upgrade-dependencies.ts
> +  readonly ignoreProjen?: boolean;
So that when a user explicitly sets `exclude` - they are not implicitly including `projen`. This seemed simpler, and is consistent with how the dependabot component configures it.

2021-05-17 21:58 UTC, iliapolo commented on src/upgrade-dependencies.ts
> +export class UpgradeDependenciesSchedule {
👍

2021-05-17 21:59 UTC, iliapolo commented on .projen/tasks.json
> -    "projen:upgrade": {
No - since projen itself doesn't need a `projen:upgrade` task..unless i'm missing something - this never belonged here.

2021-05-17 22:00 UTC, iliapolo commented on src/upgrade-dependencies.ts
> +    const project = this.project as NodeProject;
👍

2021-05-17 22:02 UTC, iliapolo commented on src/node-project.ts
> +    if (dependenciesUpgrade.ignoresProjen && this.package.packageName !== 'projen') {
Because otherwise projen is already being taken care of. Note the code below only configures a projen upgrade.

2021-05-17 22:59 UTC, iliapolo commented on src/upgrade-dependencies.ts
> +        'permissions': 'write-all',
Yes, scoped down to: 

- `content` (push branch)
- `pull-request` (create pr)
- `checks` (update status check - if needed)

2021-05-17 23:14 UTC, iliapolo commented
@eladb Addressed all your comments.

Note that I changed the default `dependabot` to `false` - so you'll see an `upgrade-dependencies.yml` workflow here instead. 

Capturing the outcome after this PR:

- When `dependabot` is `true` - use dependabot.
- When `dependabot` is `false` - use new workflow. This might be a little surprising - should we switch to not use anything at all? 
- When `dependabot` is `undefined` - users get the new workflow.

In all cases users get a projen upgrade workflow like they have now in case a projen secret is configured.

2021-05-18 05:22 UTC, eladb commented on .projen/tasks.json
> -    "projen:upgrade": {
I meant the "upgrade-dependencies" task

2021-05-18 05:32 UTC, eladb approved these changes
Ship it 🛳️

2021-05-18 07:42 UTC, merged