fix: honor mergify: false when dependabot: true
projen/projen pull request #714
Opened 2021-04-21 22:22 UTC by pgollucci

Fixes: https://github.com/projen/projen/issues/696

Its perfectably legit to have dependabot on but not mergify, or
mergify to not be involved in that flow.

I will add a test, but am I blind, I don't see _any_ dependabot, mergify
tests??

2021-04-22 12:51 UTC, eladb requested changes

2021-04-22 12:51 UTC, eladb commented on src/node-project.ts
> -    if (options.dependabot ?? true) {
It seems like this implies that if mergify is `false` dependabot is never enabled, no?

2021-04-22 12:55 UTC, pgollucci commented on src/node-project.ts
> -    if (options.dependabot ?? true) {
I will take another look. I didn't check too closely before.

2021-04-28 11:21 UTC, eladb commented
@RomainMuller #741 supersedes this PR, correct? Can we close this one?

2021-05-02 01:35 UTC, closed without merging