feat: only show featured options in new projenrc files by default
projen/projen pull request #747
Opened 2021-04-29 01:09 UTC by Chriscbr

Showing only featured options is now the default for new projen projects. Options for projects can be annotated as featured by including the @featured tag in the docstring.

Note: this does not fix #746.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-04-29 01:16 UTC, Chriscbr commented on src/cli/cmds/new.ts
> +    comments: args.comments ? ProjectOptionsVerbosity.FEATURED : ProjectOptionsVerbosity.NONE,
I added an enum to represent all three ways of rendering the commented options (all options, featured options, or none options), but it might be superfluous given the "comments" flag has to be boolean (in this code I am doing the conversion) for usage in the CLI.

Maybe we should just scrap this enum and the code which renders all of the options altogether?

2021-04-29 08:55 UTC, eladb commented on src/node-package.ts
> +   * @featured
```suggestion

```

2021-04-29 08:55 UTC, eladb commented on src/node-package.ts
> +   * @featured
```suggestion

```

2021-04-29 08:56 UTC, eladb commented on src/typescript.ts
> +   * @featured
```suggestion

```

2021-04-29 08:57 UTC, eladb commented on src/javascript/render-options.ts
> +export enum ProjectOptionsVerbosity {
```suggestion
export enum OptionHints {
```

2021-04-29 08:58 UTC, eladb reviewed
Yey!

2021-04-29 16:30 UTC, Chriscbr commented
Comments have been addressed

2021-04-29 16:31 UTC, eladb commented on API.md
> +[javascript.RenderProjectOptions](#projen-javascript-renderprojectoptions)|Options for `renderProjectOptions`.
This should be updated?

2021-04-29 16:32 UTC, eladb commented on src/javascript/projenrc.ts
> +   * @default ProjectOptionsVerbosity.FEATURED
```suggestion
   * @default OptionHints.FEATURED
```

2021-04-29 16:32 UTC, eladb commented on src/javascript/render-options.ts
> +   * @default ProjectOptionsVerbosity.FEATURED
```suggestion
   * @default OptionHints.FEATURED
```

2021-04-29 16:32 UTC, Chriscbr commented on API.md
> +[javascript.RenderProjectOptions](#projen-javascript-renderprojectoptions)|Options for `renderProjectOptions`.
Agh, I keep assuming `yarn build` will update my API.md for me. On it

2021-04-29 16:33 UTC, eladb commented on src/javascript/render-options.ts
> +      renders[optionName] = `// ${optionName}: ${defaultValue?.replace(/"(.+)"/, '\'$1\'')},`; // single quotes
Can we reuse the `.replace(...)` code between here and line 120?

2021-04-29 16:34 UTC, eladb commented on src/typescript/projenrc.ts
> +   * @default ProjectOptionsVerbosity.FEATURED
```suggestion
   * @default OptionHints.FEATURED
```

2021-04-29 16:34 UTC, eladb commented on API.md
> +## struct RenderProjectOptions 🔹 <a id="projen-javascript-renderprojectoptions"></a>
Where is this coming from?

2021-04-29 16:35 UTC, eladb commented on src/javascript/index.ts
> +export * from './render-options';
The `render-options` file should not be exported here - it contains internal stuff. If it's needed from another file inside the project, just reference it directly and not through the `javascript` directory

2021-04-29 16:35 UTC, eladb commented on API.md
> +[javascript.RenderProjectOptions](#projen-javascript-renderprojectoptions)|Options for `renderProjectOptions`.
It's supposed to!

2021-04-29 16:37 UTC, Chriscbr commented on API.md
> +[javascript.RenderProjectOptions](#projen-javascript-renderprojectoptions)|Options for `renderProjectOptions`.
Err, you're right lol. Misread which line this was referring to.

2021-04-29 16:40 UTC, Chriscbr commented on API.md
> +## struct RenderProjectOptions 🔹 <a id="projen-javascript-renderprojectoptions"></a>
Hmmm so I put `OptionHints` in `render-options.ts`, but this file wasn't being exported, so after exporting it this interface also got exported. I can move OptionHints somewhere else if we don't want to expose RenderProjectOptions.

2021-04-29 16:40 UTC, Chriscbr commented on src/javascript/index.ts
> +export * from './render-options';
Ah cool 👍

2021-04-29 16:45 UTC, eladb commented on API.md
> +## struct RenderProjectOptions 🔹 <a id="projen-javascript-renderprojectoptions"></a>
Yes. Will likely need to go somewhere else and then will also need a new name such as `NewProjectOptionHints`

2021-04-29 17:15 UTC, Chriscbr commented on src/javascript/index.ts
> +export * from './render-options';
So I couldn't just reference OptionHints directly from `render-options` because `OptionHints` is getting used in several exported interfaces (and `render-options` isn't exported), which is a jsii error.

I also couldn't move it to javascript/projenrc.ts because this caused a runtime dependency cycle.

So I've moved it to it's own file in the root directory for now.

2021-04-29 17:18 UTC, Chriscbr commented on src/javascript/render-options.ts
> +      renders[optionName] = `// ${optionName}: ${defaultValue?.replace(/"(.+)"/, '\'$1\'')},`; // single quotes
Done - I created a helper

2021-04-29 17:19 UTC, Chriscbr commented on API.md
> +## struct RenderProjectOptions 🔹 <a id="projen-javascript-renderprojectoptions"></a>
Just saw this -- yep this sounds better, changing

2021-04-29 17:23 UTC, Chriscbr commented
Have to run, but can address any other issues this evening

2021-05-02 05:44 UTC, eladb requested changes

2021-05-02 05:44 UTC, eladb commented on src/javascript/projenrc.ts
> -  readonly comments?: boolean;
so... I think this option should be passed as part of the `project.newProject` field and not through the normal options route (similar to `jsiiFqn`) because we only care about this when we create new projects. Does that make sense?

2021-05-02 20:05 UTC, Chriscbr commented on src/javascript/projenrc.ts
> -  readonly comments?: boolean;
I think so - just had to spend a little time to wrap my head around how the bootstapping works. There's a bit of overlap between some of the interfaces (like `NewProject`, `ProjenNew`, and `RenderProjectOptions`) but I wasn't sure if it would be right to merge them or not somehow

2021-05-02 20:11 UTC, Chriscbr commented
The updated changes now fix #746.

2021-05-03 05:25 UTC, eladb approved these changes
Great job. That's exactly what I had in mind :-)

2021-05-03 05:25 UTC, eladb commented on src/javascript/projenrc.ts
> +      comments: bootstrap.comments,
👍

2021-05-03 05:25 UTC, merged