feat(cli): allow enum-based CLI arguments
projen/projen pull request #770
Opened 2021-05-08 04:44 UTC by Chriscbr

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-05-08 04:48 UTC, Chriscbr commented on src/javascript/render-options.ts
> +  if (['string', 'number', 'boolean'].includes(option.type) || option.name === 'devDeps') {
This is referencing the line of code here:

https://github.com/projen/projen/blob/46fa460ada2d23e01493f481aa994ba394c45051/src/cli/cmds/new.ts#L269-L273

The `--from cdk-appsync-project` unit test wouldn't pass unless I added this exception.

2021-05-09 06:15 UTC, eladb requested changes
This is very cool!

A few notes:
1. Should we include the enum options in `--help`?
2. We need to add support for `projenrc.java`...

I am wondering if we need some form of a "compliance test" that will go through all projenrc types and make sure we don't miss future projenrc languages in the future if we add things like this.

2021-05-21 06:29 UTC, eladb commented
@Chriscbr let me know when this is ready for another review.

2021-05-25 09:01 UTC, Chriscbr commented
I didn't test if this implementation will handle enums that are defined without strings (i.e. `enum Foo { BAR }` instead of `enum Foo { BAR = 'bar' }`), but I don't think we have many enums like that so I don't think it should be an issue.

2021-05-25 09:34 UTC, eladb commented
> I didn't test if this implementation will handle enums that are defined without strings (i.e. `enum Foo { BAR }` instead of `enum Foo { BAR = 'bar' }`), but I don't think we have many enums like that so it shouldn't be an issue.

Are the names of the CLI switches derived from the member name or from the member value? I believe they should be derived from the member name, no?

2021-05-25 09:35 UTC, eladb approved these changes

2021-05-25 09:40 UTC, merged

2021-05-25 21:23 UTC, Chriscbr commented
Yeah, you're right. From the CLI standpoint, `yargs` just gives us a string passed by the user such as "lib" (which we expect is the member name), and in `Projenrc` it gets translated based on the jsii manifest into "ProjectType.LIB". So at no point does the underlying member value have an affect in this process.

I also did a quick manual test where I changed some member values, and the CLI still worked as expected.