feat: generate tasks for deploy groups
projen/projen pull request #779
Opened 2021-05-11 15:06 UTC by hoegertn

This feature add the new option `deployGroups` to any AwsCdkTypeeScriptApp.

It allows to defined named glob patterns that result in tasks to deploy/diff/destroy these stacks.

```ts
{
  prod: 'stacks-prod-*'
}
```

results in `deploy:prod`, `diff:prod`, and `destroy:prod` tasks that target all stacks starting with `stacks-prod-`

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-05-11 16:40 UTC, hoegertn commented
I am happy to support this too. But I see the `*` a lot in the wild.

2021-05-21 06:38 UTC, eladb requested changes
Add unit tests please

2021-05-21 06:38 UTC, eladb commented on src/awscdk-app-ts.ts
> +  readonly deployGroups?: { [groupName: string]: string };
Let's rename this from "deploy groups" to "stack groups" since this is not only for deployment.

I'd also change the api to allow passing an array of patterns:

```ts
{
  prod: [ "prod-*", "production-*" ],
  // ...
}
```

2021-05-21 06:38 UTC, eladb commented on src/awscdk-app-ts.ts
> +        if (Object.prototype.hasOwnProperty.call(options.deployGroups, groupName)) {
Why is this needed?

2021-05-21 06:38 UTC, eladb commented on src/awscdk-app-ts.ts
> +    this.addTask(`deploy:${groupName}`, {
Validate group name does not have unwanted chars like spaces.

Probably `/[a-z0-9\-_]+/i`

2021-05-21 07:31 UTC, hoegertn commented on src/awscdk-app-ts.ts
> +  readonly deployGroups?: { [groupName: string]: string };
Can I specify multiple patterns on a `cdk deploy`?

2021-05-21 07:32 UTC, hoegertn commented on src/awscdk-app-ts.ts
> +        if (Object.prototype.hasOwnProperty.call(options.deployGroups, groupName)) {
I learned this as best practice for `for..in` to make sure you iterate only over real fields and not internal stuff of the object. It is also what VSCode generates for loops. But I can get rid of it if you like.

2021-05-21 07:33 UTC, hoegertn commented on src/awscdk-app-ts.ts
> +    this.addTask(`deploy:${groupName}`, {
Shouldn't this be part of the Task class to validate that the name is valid?

2021-06-10 20:46 UTC, eladb commented
Closing for now. Reopen when ready to continue

2021-06-10 20:47 UTC, closed without merging