feat(node-project): codeowners file
projen/projen pull request #806
Opened 2021-05-18 20:22 UTC by Hunter-Thompson

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-05-18 20:26 UTC, Hunter-Thompson commented
Builds failing due to #805

2021-05-18 21:38 UTC, eladb reviewed
Wouldn't it makes sense to provide a higher level API than just an array of strings?

2021-05-18 21:46 UTC, hoegertn commented
Additionally, the default value doe snot really make sense imho. So maybe it would be enough to have one field with the content (high-level) and then create the file or not. I do not see much value in a boolean activation flag and the content option.

2021-05-18 22:17 UTC, Hunter-Thompson commented
> Wouldn't it makes sense to provide a higher level API than just an array of strings?

Could you provide an example? Il work on a Component based of the example.

> Additionally, the default value does not really make sense imho. So maybe it would be enough to have one field with the content (high-level) and then create the file or not. I do not see much value in a boolean activation flag and the content option.

Makes sense, will work on updating the PR.

2021-05-20 08:08 UTC, eladb commented
@Hunter-Thompson when I say higher-level API I mean something like this:

```ts
const owners = new CodeOwners(project);
owners.addOwners('*', '@global-owner1', '@global-owner2');
owners.addOwners('*.js', '@js-owner');
owners.addOwners('*.go', 'docs@example.com');
owners.addOwners('/build/logs/', '@doctocat');
owners.addOwners('docs/*', 'docs@example.com');
// ...
```

Additionally, we can offer an initializer API:

```ts
const owners = new CodeOwners(project, {
  owners: [
    { pattern: '*', owners: [ '@global-owner1', '@global-owner2' ] },
    { pattern: '*.js', owners: [ '@js-owner' ] },
  ],
});

owners.addOwners(...);
```

2021-05-20 08:09 UTC, eladb requested changes
see comment

2021-05-28 06:28 UTC, Hunter-Thompson commented
> @Hunter-Thompson lmk if you'd like to follow up here or should we close for now

@eladb, will pick this up over the weekend.

2021-05-28 16:57 UTC, Hunter-Thompson commented
@eladb, made the required changes and updated the PR description. Let me know where you'd like changes.

2021-05-29 17:22 UTC, eladb commented on src/github/codeowners.ts
> +  public addOwners(owner: Owner) {
Why not?

```ts
addOwners(pattern: string, ...owners: string[])
```

2021-05-29 17:22 UTC, eladb commented on src/github/codeowners.ts
> +  readonly owners?: Owner[];
Why not?

```ts
{
  owners: {
    pattern: [ owners ],
    ...
  }
  
}
```

2021-05-30 09:40 UTC, eladb commented
@Hunter-Thompson could you please update the APIs to the proposed option. I think the ergonomics are better.

2021-05-30 10:24 UTC, Hunter-Thompson commented
> @Hunter-Thompson could you please update the APIs to the proposed option. I think the ergonomics are better.

Sure thing, will make the changes when I get some time tomorrow.

2021-06-06 11:43 UTC, eladb commented
?

2021-06-06 12:01 UTC, Hunter-Thompson commented
> ?

Not getting time to work on this feature, please gimme a day or two.

2021-07-03 01:24 UTC, closed without merging