feat(node): support node config file
projen/projen pull request #818
Opened 2021-05-23 23:06 UTC by hoegertn

Support writing a project local `.npmrc` file. E.g. this could be used to configure mirrors for all packages or for specific scopes.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-05-23 23:19 UTC, hoegertn commented
I have no idea why the `new` test fails. I did not change this.

2021-05-24 04:52 UTC, Chriscbr commented
@hoegertn Looks like a flakey test that I updated not too long ago. I'll try to submit a PR to fix it. But I think it should be safe to merge your PR. :-)

2021-05-24 07:31 UTC, eladb requested changes
Here's a proposed alternative API that is more inline with projen's (undocumented :-)) API standards:

```ts
export interface NpmRcOptions {
  /**
   * NPM registry to use
  readonly registry?: string;
}

export interface NpmRc extends Component {
  private readonly obj: any;

  constructor(project: NodeProject, options: NpmRcOptions = {}) {
    super(project, { obj });

    if (options.registry) {
      this.addRegistry(options.registry);
    }
  }

  public addRegistry(url: string, scope?: string) {
    const key = scope ? `${scope}:registry` : 'registry';
    this.addConfig(key, url);
  }

  public addConfig(name: string, value: string) {
    this.obj[name] = value;
  }
}
```

Also:
* Make sure to include docstrings on all public APIs
* Add unit tests

2021-05-24 20:57 UTC, hoegertn commented
@eladb I changed the API a bit

2021-05-25 05:56 UTC, eladb requested changes

2021-05-25 05:56 UTC, eladb commented on src/javascript/node-config.ts
> +export class NodeConfig extends Component {
Rename to `NpmConfig` or `NpmRc`

2021-05-25 05:56 UTC, eladb commented on src/javascript/node-config.ts
> +  public configureRegistry(scope: string, url: string) {
I preferred the previous version so it's possible to specify registry after initialization:

```ts
addRegistry(url: string, scope?: string)
```

2021-05-25 05:56 UTC, eladb commented on src/javascript/node-config.ts
> +   * URL of the registry mirror to use
Mention `addRegistry` here

2021-05-25 08:18 UTC, eladb approved these changes
Looks good!

2021-05-25 08:39 UTC, hoegertn commented
How do we proceed with the failing test? Is this fixed?

2021-05-25 08:54 UTC, eladb commented
> How do we proceed with the failing test? Is this fixed?

I believe it was fixed (#821) by @Chriscbr

2021-05-25 08:55 UTC, eladb commented
Did you merge the latest from main?

2021-05-25 09:56 UTC, hoegertn commented
Merged it. I was confused as I expected GitHub to show an update branch button...

2021-05-25 10:00 UTC, merged