feat(project): auto approve workflow
projen/projen pull request #824
Opened 2021-05-26 16:43 UTC by nija-at

Set up an auto approve workflow that will approve pull requests with a
known label and from an allowed set of Github usernames.

Remove part of the auto merge functionality that allowed pull requests
with the 'auto-merge' label to be merged without an approval. `mergify`
does not support merging pull requests unapproved pull requests.
So this really never worked.

BREAKING CHANGE: The `mergifyAutoMerge` option in `NodeProjectOptions`
has been removed. To auto merge PRs, use the 'auto approve'
functionality via the `autoApproveEnabled` and `autoApproveOptions`
options.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-05-26 16:44 UTC, nija-at commented
### Remaining work

- [ ] Test against a real project and check the auto approve actually works
- [ ] synth projen on projen
- [ ] error if the upgrade action identity is the same as approve action identity

2021-05-28 06:19 UTC, eladb requested changes

2021-05-28 06:19 UTC, eladb commented on src/github/auto-approve.ts
> +   * Only pull requests authored by these Github usernames will be auto-approved.
1. This default might be surprising. For example, I am not sure it's a safe practice to auto-approve dependency upgrades.
2. Is there a way not to specify a user filter? E.g I want to auto approve all PRs with the defined label?

2021-05-28 06:19 UTC, eladb commented on src/github/auto-approve.ts
> +  readonly secret?: string;
How can the default token approve PRs submitted by the GitHub user itself?

(Seems like the default behavior of auto-approving to only PRs from GitHub bot will just not work..)

2021-05-28 06:19 UTC, eladb commented on src/github/auto-approve.ts
> +   * @default 'GITHUB_TOKEN' https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
Do we really need to specify the token here? If the default token already has permissions to approve PRs?

2021-05-28 06:19 UTC, eladb commented on src/project.ts
> +   * and auto-merged. This is applied for the dependency upgrade PRs set up by projen.
I prefer that the default behavior won't be to auto approve dep upgrades as it poses a security risk

2021-05-28 06:19 UTC, eladb commented on src/project.ts
> +  readonly autoApproveEnabled?: boolean;
```suggestion
  readonly autoApprove?: boolean;
```

2021-05-28 06:19 UTC, eladb commented on src/github/auto-approve.ts
> +      return;
I think this should probably fail and not just bail out.

Maybe you can simply require a GitHub object instead of Project (like GitHubWorkflow does)

2021-05-28 12:43 UTC, nija-at commented on src/github/auto-approve.ts
> +   * Only pull requests authored by these Github usernames will be auto-approved.
> This default might be surprising. For example, I am not sure it's a safe practice to auto-approve dependency upgrades.

Good point. 

How about this - enable the auto approve workflow by default but do not add the 'auto-approve' label to any generated PRs by default. Does that work?

> Is there a way not to specify a user filter? E.g I want to auto approve all PRs with the defined label?

By providing an empty list. Is this good enough, or should there be clear option on the API?

2021-05-28 12:45 UTC, nija-at commented on src/github/auto-approve.ts
> +   * @default 'GITHUB_TOKEN' https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
It's here because of your previous comment because of the inability for default tokens to approve their own PRs. 
I'm still working on the best customer experience on configuring this.

2021-05-28 12:46 UTC, nija-at commented on src/project.ts
> +   * and auto-merged. This is applied for the dependency upgrade PRs set up by projen.
Yes. see conversation https://github.com/projen/projen/pull/824#discussion_r641519102

2021-05-28 15:23 UTC, BenChaimberg commented on src/project.ts
> +   * Configure the 'auto approve' workflow. See `autoApproveEnabled` to enable this workflow.
minor: autoApproveEnabled no longer exists

2021-06-01 12:28 UTC, nija-at commented on src/github/auto-approve.ts
> +   * Github forbids an identity to approve its own pull request.
Yes, and that's what the message says.

What are you suggesting to do here? 

I weighed the benefits of making this optional vs mandatory. 
Leaving it optional would likely mean that the average experience being incorrectly configured tokens, lots of debugging and digging only to find that this property needed to be configured.
Making it mandatory, on the other hand, forces the user to read the documentation with a higher chance of correctly configuring it. They can still choose to set this to `GITHUB_TOKEN`.

Further, going from mandatory -> optional is backwards compatible while the opposite is not.

2021-06-01 12:36 UTC, nija-at commented on src/project.ts
> +   * Configure the 'auto approve' workflow. See `autoApproveEnabled` to enable this workflow.
```suggestion
   * Enable and configure the 'auto approve' workflow.
```

2021-06-01 12:40 UTC, eladb commented on src/github/auto-approve.ts
> +   * Github forbids an identity to approve its own pull request.
Okay. Sounds good

2021-06-01 12:42 UTC, eladb commented on src/github/auto-approve.ts
> +   * Hence, this cannot be the default secret
It _can_ be the default token

2021-06-01 13:01 UTC, nija-at commented on src/github/auto-approve.ts
> +   * Hence, this cannot be the default secret
```suggestion
   * If your project produces automated pull requests using the Github default token -
   * {@link https://docs.github.com/en/actions/reference/authentication-in-a-workflow `GITHUB_TOKEN` }
   * - that you would like auto approved, such as when using `depsUpgrade` property in `NodeProjectOptions`,
   * then you must use a different token here.
```

2021-06-01 13:02 UTC, nija-at commented on src/github/auto-approve.ts
> +   * {@link https://docs.github.com/en/actions/reference/authentication-in-a-workflow 'GITHUB_TOKEN' }.
```suggestion
```

2021-06-01 13:23 UTC, eladb approved these changes

2021-06-01 13:28 UTC, eladb commented
@nija-at you'll need to rebuild locally and commit any changes (the self-mutation feature does not work for forks)

2021-06-01 13:44 UTC, nija-at commented
> @nija-at you'll need to rebuild locally and commit any changes (the self-mutation feature does not work for forks)

Done! @eladb

2021-06-02 10:42 UTC, iliapolo commented on src/github/auto-approve.ts
> +      pullRequest: {
@nija-at This might be problematic. If the PR's are created with a custom token, than a user will likely want to pass the default github token here, which won't work because it has `read-only` permissions on this trigger. 

I think we should use `pull_request_target` to accommodate this use case as well.  See https://github.com/aws/aws-cdk/pull/14939

2021-06-03 09:04 UTC, nija-at commented on src/github/auto-approve.ts
> +      pullRequest: {
changed.

2021-06-03 09:47 UTC, eladb requested changes

2021-06-03 09:47 UTC, eladb commented on src/__tests__/__snapshots__/integ.test.ts.snap
> +          labels: \\"\\"
This looks like a bug

2021-06-03 09:47 UTC, eladb commented on src/github/auto-approve.ts
> +      pullRequestTarget: {
Can you please add some notes about why `pullRequestTarget` is needed here and emphasize the security considerations and why it is safe?

2021-06-03 10:34 UTC, nija-at commented on src/__tests__/__snapshots__/integ.test.ts.snap
> +          labels: \\"\\"
Are you referring to the 'auto-merge' being removed or that `labels` being an empty string?

2021-06-03 11:11 UTC, eladb commented on src/__tests__/__snapshots__/integ.test.ts.snap
> +          labels: \\"\\"
The empty string

2021-06-03 11:50 UTC, nija-at commented on src/__tests__/__snapshots__/integ.test.ts.snap
> +          labels: \\"\\"
Fixed

2021-06-03 11:55 UTC, eladb approved these changes

2021-06-03 13:34 UTC, merged