fix(jsii-project): option to disable release to npm
projen/projen pull request #851
Opened 2021-06-03 09:09 UTC by Hunter-Thompson

`releaseToNpm: false` was not being honored by `jsii-project`, this resulted in an unwanted workflow for every project extended using `jsii-project`.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-03 09:16 UTC, Hunter-Thompson commented
This issue might be fixed by #850?

2021-06-06 11:42 UTC, eladb requested changes
I am not sure that's the desired behavior. By definition, jsii projects are expected to be published at least to npm and this is why this is the default behavior.

Can we leave the default to always publish to npm but also allow disablement?

2021-06-06 12:00 UTC, Hunter-Thompson commented
@eladb, when I set `releaseToNpm` to true, the integration tests are failing. Unable to figure that out.

2021-06-07 07:44 UTC, eladb requested changes

2021-06-07 07:44 UTC, eladb commented on src/jsii-project.ts
> -    this.publisher?.publishToNpm({
Revert this change and add an `if` statement here that will respect `options.releaseToNpm`

2021-06-07 07:44 UTC, eladb commented on src/jsii-project.ts
> -      releaseToNpm: false, // we have a jsii release workflow
revert this change so that by default we pass `false` to super class

2021-06-07 09:20 UTC, eladb requested changes
@Hunter-Thompson please add a unit test for this

2021-06-07 09:49 UTC, merged