added top level config for deps upgrade auto merge
projen/projen pull request #871
Opened 2021-06-09 11:40 UTC by iliapolo

As things stand now, its too complicated to setup auto merges for dependency upgrade PR's. Here is what it takes:

```ts
const project = new TypeScriptProject({
  ...
  projenUpgradeSecret: 'PROJEN_GITHUB_TOKEN',

  // first we need to enable auto approval
  autoApproveOptions: {
    allowedUsernames: ['aws-cdk-automation'],
    secret: 'GITHUB_TOKEN',
    label: 'auto-approve'
  },

  // then we need to apply it on the deps upgrade workflow.
  // which means overriding the default values, and redefining them.
  depsUpgrade:  DependenciesUpgradeMechanism.githubWorkflow({
    workflowOptions: {
      labels: ['auto-approve'], // this must match the configured auto-approve label, which is why we explicitly set it above as well 
    },
    ignoreProjen: false,
    secret: 'PROJEN_GITHUB_TOKEN',
  })
});
```

This PR proposes an alternative by introducing the `depsUpgradeAutoMerge` property, similar to the already existing `projenUpgradeAutoMerge` property. 

```ts
const project = new TypeScriptProject({
  ...
  projenUpgradeSecret: 'PROJEN_GITHUB_TOKEN',
  autoApproveOptions: {
    allowedUsernames: ['aws-cdk-automation'],
    secret: 'GITHUB_TOKEN',
  },
  depsUpgradeAutoMerge: true,
});
```

Even this simplification is somewhat cumbersome, and can be improved if we decide at some point to simply default to auto-merging dependencies if `autoApprove` is configured. 

I feel its ok to start off safe and make it explicit, we can always relax requirements later. 

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-09 11:41 UTC, iliapolo commented on src/github/dependabot.ts
> -  readonly autoMerge?: boolean;
Decided to remove this and align the behavior with the upgrade workflow that simply accepts `labels` and moves the auto-merge responsibility to the caller for now.

2021-06-09 11:42 UTC, iliapolo commented on src/github/dependabot.ts
> -    }
This shouldn't be here anyway since it doesn't comply with branch protection rules (missing approval)

2021-06-09 11:46 UTC, iliapolo commented on src/node-project.ts
> +  readonly depsUpgradeAutoMerge?: boolean;
Should be probably called `depsUpgradeAutoApprove` since mergify might be disabled...but this does convey better intent and is aligned with the `projenUpgradeAutoMerge` property. 

I can be persuaded otherwise though.

2021-06-09 12:22 UTC, eladb requested changes
I think the semantics should be "autoApprove" all the way.

Auto-merge of approved PRs is a different concern.

I think we should do something about the autoApprove config. Still feels clunky, but maybe we can leave this for a subsequent PR.

2021-06-09 12:22 UTC, eladb commented on src/github/dependabot.ts
> +          'labels': options.labels ?? [],
```suggestion
          'labels': options.labels ? options.labels : undefined,
```

2021-06-09 12:22 UTC, eladb commented on src/node-project.ts
> +   * @default - true
```suggestion
   * @default true
```

2021-06-09 12:22 UTC, eladb commented on src/node-project.ts
> +   * Only applies if `autoApproveOptions` are defined.
Should this fail if autoApprove is not configured?

2021-06-09 12:22 UTC, eladb commented on src/node-project.ts
> +  readonly depsUpgradeAutoMerge?: boolean;
I prefer to change both to be called `autoApproveUpgrades` and `autoApproveProjenUpgrades`.

2021-06-09 13:33 UTC, iliapolo commented on src/node-project.ts
> +  readonly depsUpgradeAutoMerge?: boolean;
@elad What if move these down to the `autoApprove` configuration (and break the existing config)?

```ts
autoApprove: {
  projenUpgrade: true,
  depsUpgrade: true
}
```

This also means auto approve will have to be configured avoiding the need to validate it.

2021-06-09 15:19 UTC, eladb commented on src/node-project.ts
> +  readonly depsUpgradeAutoMerge?: boolean;
But autoApprove doesn't know about deps upgrade. It's a separate component.

2021-06-09 16:48 UTC, iliapolo commented on src/node-project.ts
> +   * Only applies if `autoApproveOptions` are defined.
Yes. Changed.

2021-06-09 16:48 UTC, Chriscbr commented on src/github/dependabot.ts
> -  readonly autoMerge?: boolean;
"BREAKING CHANGE" boilerplate should probably be added to the PR description if we're removing an option from the API.

2021-06-09 16:57 UTC, iliapolo commented on src/node-project.ts
> +  readonly depsUpgradeAutoMerge?: boolean;
Yeah I know, ok changed the names and added a deprecation

2021-06-10 07:51 UTC, eladb approved these changes

2021-06-10 07:57 UTC, merged