feat(github): Create generic GitHub workflows
projen/projen pull request #895
Opened 2021-06-15 20:26 UTC by eduardomourar

There is no real logic change within this PR. The only thing is that a new generic GitHub workflow is being exposed, as well as now in use within `NodeProject` and `Release` classes.

Related to #74 and #298.
 
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-15 20:40 UTC, eladb requested changes

2021-06-15 20:40 UTC, eladb commented on src/__tests__/release/__snapshots__/release.test.ts.snap
> +        env:
All those snapshot changes seem like bugs 🐜

2021-06-15 21:29 UTC, Chriscbr commented on src/github/generic-workflows.ts
> +export class GenericWorkflow extends GithubWorkflow {
Will it be possible to expand this beyond GitHub-specific workflows? Based on the name `GenericWorkflow`, it reads to me like a universal workflow, i.e. one that is generic across CI providers, so it would be great if we could later upgrade this to support #137.

2021-06-15 21:43 UTC, eduardomourar commented on src/github/generic-workflows.ts
> +export class GenericWorkflow extends GithubWorkflow {
I believe it is best to rename this to `GenericGitHubWorkflow` to avoid confusion, because the implementation is quite specific to GitHub.

2021-06-19 09:33 UTC, eduardomourar commented on src/__tests__/release/__snapshots__/release.test.ts.snap
> +        env:
done

2021-06-29 16:07 UTC, eduardomourar commented
@eladb , I fixed the snapshots. Please, could you have a look into this PR and let me know what do you think?

2021-06-30 10:37 UTC, eladb requested changes
This looks really good, but I am not sure about the name... `GenericGithubWorkflow` is not really conveying the idea behind this workflow.

Trying to think what's the abstraction here and I think it's about tasks. It's basically a workflow backed by a projen task.

Perhaps we can call it `TaskGithubWorkflow`? Not sure...

2021-06-30 10:37 UTC, eladb commented on src/github/generic-workflows.ts
> +  readonly initialSteps?: JobStep[];
Rename to `preCheckoutSteps`?

2021-06-30 10:37 UTC, eladb commented on src/github/generic-workflows.ts
> +  readonly antitamperDisabled?: boolean;
Reverse logic:

```suggestion
  readonly antitamper?: boolean;
```

2021-06-30 10:37 UTC, eladb commented on src/github/generic-workflows.ts
> +   * Steps to run after the main build step.
Please add `@default` to all options

2021-07-06 18:36 UTC, eladb requested changes
Can you make sure to rebase this branch with `main`? There are a few changes in the `Release` class that I don't see here.

2021-07-06 18:36 UTC, eladb commented on src/node-project.ts
> +    const project = github.project as NodeProject;
```suggestion
    const project = this;
```

2021-07-06 18:36 UTC, eladb commented on src/node-project.ts
> +  private createBuildWorkflow(options: NodeWorkflowOptions): TaskGithubWorkflow {
Feels like this method can be removed and the code moved back to the call site.

2021-07-06 18:36 UTC, eladb commented on src/release/release.ts
> +  public static readonly BUILD_JOBID = 'release';
Why do we need this to be public?

2021-07-06 20:00 UTC, eduardomourar commented
> Can you make sure to rebase this branch with `main`? There are a few changes in the `Release` class that I don't see here.

Yes, working on it. I am trying to figure out how to resolve the conflicts, but I will get there.

2021-07-06 20:47 UTC, eduardomourar commented on src/release/release.ts
> +  public static readonly BUILD_JOBID = 'release';
I usually like the idea of making those default values accessible to the user, but I will leave private to align with what it was originally.

2021-07-06 20:52 UTC, eladb commented on src/release/release.ts
> +  public static readonly BUILD_JOBID = 'release';
As a general rule I rather expose the minimum amount of API possible. It's always possible to extend an API but impossible to narrow without breaking.

2021-07-07 06:09 UTC, eladb requested changes

2021-07-07 06:09 UTC, eladb commented on src/node-project.ts
> +        },
This feels wrong (why do we need to pass buildTask twice). Isn't the whole point of the workflow to run the build task?

2021-07-07 06:09 UTC, eladb commented on src/release/release.ts
> +  private static readonly BUILD_JOBID = 'release';
Just leave this as a file-local constant.

As a general practice it's better to keep commits that include refactoring to the bear minimum and not "pollute" them with stylistic changes so it's easier to have confidence

2021-07-07 06:09 UTC, eladb commented on src/release/release.ts
> +    const postBuildSteps = new Array<JobStep>(...this.postBuildSteps);
Just not just pass `this.postBuileSteps` as is?

2021-07-07 06:09 UTC, eladb commented on src/release/release.ts
> +      },
??

2021-07-07 08:02 UTC, eduardomourar commented on src/node-project.ts
> +        },
we are overriding the default value for the name within the build step

2021-07-07 08:02 UTC, eduardomourar commented on src/release/release.ts
> +      },
the same as above

2021-07-07 08:08 UTC, eduardomourar commented on src/node-project.ts
> +        },
i will make a commit removing `buildStep` property and you will see they would look like in the snapshots

2021-07-07 11:46 UTC, eduardomourar commented on src/release/release.ts
> +  private static readonly BUILD_JOBID = 'release';
done and moved the other constants in the `task-workflow.ts` as well to align with your comment

2021-07-07 12:01 UTC, eduardomourar commented on src/release/release.ts
> +    const postBuildSteps = new Array<JobStep>(...this.postBuildSteps);
this is needed (improved the unit test to cover it), because we are running the `createWorkflow` method while looping over every branch.

2021-07-07 12:13 UTC, eladb commented on src/node-project.ts
> +        },
We can just use the name of the task in the step inside the workflow - no worries if the step display name will change.

2021-07-07 12:27 UTC, eladb requested changes

2021-07-07 12:27 UTC, eladb commented on src/github/task-workflow.ts
> +export class TaskGithubWorkflow extends GithubWorkflow {
We should rename `GithubWorkflow` to `Workflow` at some point (because now it's under the `github` submodule), but this one can already be named appropriately:

```suggestion
export class TaskWorkflow extends GithubWorkflow {
```

2021-07-07 12:27 UTC, eladb commented on src/github/task-workflow.ts
> +  protected getMainStep(options: TaskGithubWorkflowOptions) {
Why is this needed?

2021-07-07 12:27 UTC, eladb commented on src/github/task-workflow.ts
> +  protected createWorkflow(options: TaskGithubWorkflowOptions) {
Why does this have to be protected? If we don't have a concrete use case for this to be protected (which is effectively public API), always prefer `private`.

2021-07-07 12:27 UTC, eladb commented on src/github/task-workflow.ts
> +        if: 'always()',
why do we need `always()` here?

2021-07-07 12:27 UTC, eladb commented on src/github/task-workflow.ts
> +    const job: Mutable<Job> = {
Does it have to be mutable?

```suggestion
    const job: Job = {
```

2021-07-07 12:27 UTC, eladb commented on src/github/task-workflow.ts
> +    return this;
Not needed:

```suggestion

```

2021-07-07 12:27 UTC, eladb commented on src/github/task-workflow.ts
> +  protected createWorkflow(options: TaskGithubWorkflowOptions) {
This method feels redundant

2021-07-07 12:27 UTC, eladb commented on src/github/task-workflow.ts
> +
```suggestion
```

2021-07-07 12:27 UTC, eladb commented on src/github/task-workflow.ts
> +type Mutable<T> = { -readonly [P in keyof T]: T[P] };
Not needed

2021-07-07 12:27 UTC, eladb commented on src/node-project.ts
> +export type NodeWorkflowOptions = Omit<TaskGithubWorkflowOptions, 'buildStep'>;
Why is this needed?

2021-07-07 12:27 UTC, eladb commented on src/github/task-workflow.ts
> +  readonly antitamper?: boolean;
I don't think anti-tamper is needed at the TaskWorkflow level. It's only used for the build workflow (the release workflow includes it as part of the task), so I'd just leave it there.

This will also mean that you no longer need the `finalSteps` option because basically `postBuildSteps` can cover all the post build activity.

2021-07-07 12:39 UTC, eduardomourar commented on src/github/task-workflow.ts
> +        if: 'always()',
you would want to upload artifacts even if the previous steps have failed (e.g. coverage report, internal logs, etc)

2021-07-07 12:43 UTC, eladb commented on src/github/task-workflow.ts
> +        if: 'always()',
Is that what that means? Ha! TIL.

(can you add a comment?)

2021-07-07 12:54 UTC, eduardomourar commented on src/node-project.ts
> +export type NodeWorkflowOptions = Omit<TaskGithubWorkflowOptions, 'buildStep'>;
the interface NodeWorkflowOptions was in that file already, but i will remove it

2021-07-07 12:55 UTC, eduardomourar commented on src/github/task-workflow.ts
> +  protected getMainStep(options: TaskGithubWorkflowOptions) {
no reason. removed

2021-07-07 12:55 UTC, eduardomourar commented on src/github/task-workflow.ts
> +  protected createWorkflow(options: TaskGithubWorkflowOptions) {
done

2021-07-07 12:55 UTC, eduardomourar commented on src/github/task-workflow.ts
> +    const job: Mutable<Job> = {
it does not

2021-07-07 14:14 UTC, eduardomourar commented on src/github/task-workflow.ts
> +        if: 'always()',
will do

2021-07-07 15:19 UTC, eladb requested changes

2021-07-07 15:19 UTC, eladb commented on src/github/task-workflow.ts
> +  readonly buildStep?: JobStep;
Remove this please

2021-07-07 15:19 UTC, eladb commented on src/github/task-workflow.ts
> +  readonly env?: Record<string, string>;
```suggestion
  readonly env?: Record<string, string | undefined>;
```

2021-07-07 15:19 UTC, eladb commented on src/github/task-workflow.ts
> +  readonly github: GitHub;
```suggestion
  private readonly github: GitHub;
```

2021-07-07 15:19 UTC, eladb commented on src/github/task-workflow.ts
> +  readonly jobId: string;
```suggestion
  public readonly jobId: string;
```

2021-07-07 15:19 UTC, eladb commented on src/node-project.ts
> +      const antitamperSteps = (!mutableBuilds ?? this.antitamper) ? [{
Remove

2021-07-07 15:19 UTC, eladb commented on src/node-project.ts
> +          ...antitamperSteps,
Remove

2021-07-07 15:33 UTC, eduardomourar commented on src/node-project.ts
> +      const antitamperSteps = (!mutableBuilds ?? this.antitamper) ? [{
i think i don't understand. we will still have an options called `antitamper` for a NodeProject, so we have to add the checks steps there, right?

2021-07-07 15:38 UTC, eladb commented on src/node-project.ts
> +      const antitamperSteps = (!mutableBuilds ?? this.antitamper) ? [{
Oh sorry! Didn't realize this is in NodeProject. Taking it back.

2021-07-07 15:39 UTC, eduardomourar commented on src/github/task-workflow.ts
> +  readonly env?: Record<string, string>;
i get the following JSII error
> Compilation errors prevented the JSII assembly from being created
src/github/task-workflow.ts:82:12 - error JSII3999: Encountered optional value in location where a plain type reference is expected
82   readonly env?: Record<string, string | undefined>;
              ~~~
src/github/task-workflow.ts(137,7): error TS2322: Type 'Record<string, string | undefined> | undefined' is not assignable to type 'Record<string, string> | undefined'.
  Type 'Record<string, string | undefined>' is not assignable to type 'Record<string, string>'.
    Index signatures are incompatible.
      Type 'string | undefined' is not assignable to type 'string'.
        Type 'undefined' is not assignable to type 'string'.

2021-07-07 15:41 UTC, eladb commented on src/github/task-workflow.ts
> +   *
```suggestion
   * A directory name which contains artifacts to be uploaded (e.g. `dist`). If this is set, the 
   * contents of this directory will be uploaded as an artifact at the end of the workflow run.
   *
```

2021-07-07 15:44 UTC, eladb reviewed
Getting there... A few minor comments remaining :-D Thanks for bearing with me

2021-07-07 15:44 UTC, eladb commented on src/github/task-workflow.ts
> +  readonly trigger?: Triggers;
```suggestion
  readonly triggers?: Triggers;
```

2021-07-07 15:44 UTC, eladb commented on src/github/task-workflow.ts
> +  readonly buildStep?: JobStep;
Ping

2021-07-07 15:44 UTC, eladb commented on src/github/task-workflow.ts
> +  readonly env?: Record<string, string>;
Changed my suggestion - I believe this should work

2021-07-07 15:57 UTC, eduardomourar commented on src/github/task-workflow.ts
> +  readonly buildStep?: JobStep;
done

2021-07-07 18:36 UTC, eladb approved these changes

2021-07-11 15:27 UTC, merged