feat(cdk8s-*-ts): option to set cdk8s-plus-17 version
projen/projen pull request #897
Opened 2021-06-16 09:31 UTC by Hunter-Thompson

Option to set a version for cdk8s-plus-17, pinned or unpinned. Defaults to `this.cdk8sVersion` for backward compatibility.

Fixes #896 
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-06-16 14:27 UTC, eladb approved these changes

2021-06-16 14:27 UTC, eladb requested changes
I guess we should also offer a way to control the CDK8s CLI version. All of these modules now have separate versions.

2021-06-18 07:15 UTC, Hunter-Thompson commented
@eladb, made the changes.

2021-06-18 13:26 UTC, eladb approved these changes

2021-06-18 13:27 UTC, merged