chore: deprecate task categories
projen/projen pull request #918
Opened 2021-07-04 19:57 UTC by Chriscbr

Since the start menu was removed in v0.24.6, task categories can be deprecated.

I'm open to leaving them in if we think they can be used in other ways in the future (as metadata or otherwise).

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-07-04 20:30 UTC, eladb commented
Lol I was just thinking we should get rid of these!

2021-07-04 20:30 UTC, eladb requested changes

2021-07-04 20:30 UTC, eladb commented on src/node-package.ts
> -    if (!this.isRelaseBuild) {
☹️

2021-07-04 20:30 UTC, eladb commented on src/tasks/model.ts
> +   * @deprecated - start menu has been removed (use `projen --help`)
Just remove this I think. I doubt it will break anyone

2021-07-04 22:01 UTC, Chriscbr commented on src/node-package.ts
> -    if (!this.isRelaseBuild) {
do you want this omitted?

2021-07-05 05:25 UTC, eladb approved these changes

2021-07-05 05:25 UTC, merged