feat: add private registry support to dependabot options
projen/projen pull request #933
Opened 2021-07-09 14:49 UTC by kcwinner

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-07-09 15:44 UTC, kcwinner commented on src/github/workflows.ts
> +export function kebabCaseKeys<T = unknown>(obj: T, recursive = true): T {
This was iffy. Wondering if it should be pulled out/up to be re-used.

2021-07-11 15:24 UTC, eladb commented on src/github/dependabot.ts
> +   * @default undefined
```suggestion
   * @default - use public registries
```

2021-07-11 15:26 UTC, eladb requested changes

2021-07-11 15:26 UTC, eladb commented on src/github/dependabot.ts
> + * https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#configuration-options-for-private-regist
```suggestion
 * @see https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#configuration-options-for-private-registries
```

2021-07-11 15:26 UTC, eladb commented on src/github/dependabot.ts
> +  readonly type: string;
enum?

2021-07-11 15:26 UTC, eladb commented on src/github/dependabot.ts
> +   * @default undefined
In such cases we prefer to specify the default behavior (i.e. what `undefined` means):

```suggestion
   * @default - do not authenticate
```

2021-07-11 15:26 UTC, eladb commented on src/github/workflows.ts
> +export function kebabCaseKeys<T = unknown>(obj: T, recursive = true): T {
Pull out into `util.ts` please which is not exported out.

2021-07-19 02:00 UTC, kcwinner commented
Been slow due to being on my honeymoon! Addressed the comments and pulled the registry types into an enum

2021-07-19 05:19 UTC, eladb approved these changes

2021-07-19 05:25 UTC, merged