fix(nextjs): next CLI unable to update `next-env.d.ts` while building
projen/projen pull request #935
Opened 2021-07-10 05:42 UTC by Chriscbr

Fixes #934. According to the [next.js docs](https://nextjs.org/docs/basic-features/typescript), the `next-env.d.ts` "can change at any time" by the next cli tools, so we're just making it mutable.

Also, updating README.md to replace some outdated info.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-07-11 15:23 UTC, eladb requested changes

2021-07-11 15:23 UTC, eladb commented on README.md
> -❯ compile          Only compile
LOL I just noticed that we still have that :-) Thanks!

2021-07-11 15:23 UTC, eladb commented on src/web/next.ts
> +      readonly: false,
But then what happens if the CLI updates this file and projen overwrites it... Anti tamper will fail, no?

2021-07-11 21:12 UTC, Chriscbr commented on src/web/next.ts
> +      readonly: false,
Ah, forgot about this...

By technicality, anti-tamper wouldn't fail since `next build` gets run after `projen default` in the build task -- but, I still agree it's being modeled wrong (since next.js is managing the file).

I did some testing, and it looks like Next.js will automatically generate the file if it's needed, so I'm just going to remove this component altogether.

2021-07-11 21:27 UTC, Chriscbr commented on src/web/next.ts
> +      readonly: false,
On second thought, I think including it as a sample file might be a good since it will include the file in the initial commit.

2021-07-12 05:46 UTC, eladb approved these changes
Good solution

2021-07-12 08:08 UTC, merged