feat: specify labels that prevent PR auto-merges
projen/projen pull request #936
Opened 2021-07-10 07:24 UTC by Chriscbr

Allow specifying labels that prevent PR auto-merges through the `withoutLabels` field in the `AutoMerge` component.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-07-10 07:30 UTC, Chriscbr commented on .projenrc.js
> +mergify.addRule({
Wasn't sure if I should expose the new option through some other field within the project constructor, like `autoMergeOptions` or something....

2021-07-10 07:30 UTC, Chriscbr commented on src/github/auto-merge.ts
> +  readonly withoutLabels?: string[];
Not sure if I love this name - maybe something else like  `blockingLabels` would be better?

2021-07-11 15:21 UTC, eladb requested changes

2021-07-11 15:21 UTC, eladb commented on .projenrc.js
> +mergify.addRule({
Yes, I think `autoMergeOptions` is called for

2021-07-11 15:21 UTC, eladb commented on src/github/auto-merge.ts
> +  readonly withoutLabels?: string[];
Yes, this name is not ideal... `blockingLabels` is better.

2021-07-11 15:21 UTC, eladb commented on src/github/auto-merge.ts
> +   * @default []
I am comfortable with `do-not-merge` as a default blocking label

2021-07-12 05:45 UTC, eladb approved these changes

2021-07-12 08:03 UTC, eladb commented
BTW @Chriscbr you should be able to push branches to this repo directly now and not to a fork.

2021-07-12 08:03 UTC, merged