feat: Add lambda bundling to cdk construct libs
projen/projen pull request #940
Opened 2021-07-17 00:31 UTC by haimlit

Solves #783 by introducing lambda bundling as part of build.
Includes construct generation, inspired by [construct-hub .projenrc](https://github.com/cdklabs/construct-hub/blob/main/.projenrc.js#L190).

Worth discussing:

1. In order for construct lib tests which synthesize the lambda construct to pass, a stub handler file was added. Other alternatives can be pointing directly to the lib folder, however this creates an unnatural dependency between compile and test steps.
2. By convention, files with suffix 'lambda' are assumed to be lambda handlers and are targeted for bundling and construct generation.
3. There are flags to turn off partial functionality (construct generation, stub creation and customizing suffix for lambda) - is this excessive? Should we start with just on/off switch?

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-07-18 07:28 UTC, eladb requested changes
At first glance, can you please add some docs to https://github.com/projen/projen/blob/main/docs/awscdk-construct.md - that would be a good way to describe the feature as this is been code reviewed?

2021-07-18 17:45 UTC, eladb requested changes
Please also take a look at the latest version in construct-hub to make sure we didn't miss anything.

2021-07-18 17:45 UTC, eladb commented on src/__tests__/awscdk-construct.test.ts
> +    expect(snapshot[`src/__tests__/integration/lambda/mylambda-${handlerExt}.ts`]).toMatchSnapshot();
Something odd is happening here. Where are the .lambda. files coming from. The TestProject is supposed to be located in a temporary directory...

2021-07-18 17:45 UTC, eladb commented on src/awscdk-construct.ts
> +  readonly bundleLambda?: boolean;
Docstrings please

2021-07-18 17:45 UTC, eladb commented on src/__tests__/integration/lambda/mylambda-js.lambda.js
> +export function handler() {
Can we add a test that checks that dependencies are bundled?

2021-07-18 17:45 UTC, eladb commented on src/awscdk-construct.ts
> +    this.logger.info('hello!!!!');
```suggestion
```

2021-07-18 17:45 UTC, eladb commented on src/awscdk-construct.ts
> +    this.addDevDeps('aws-sdk'); // common lambda runtime dependency
I don't think that's needed. If users want they can add it easily (and control the version etc)

2021-07-18 17:45 UTC, eladb commented on src/awscdk-construct.ts
> +    this.addDevDeps('esbuild');
Add a major version `@^N`

2021-07-18 17:45 UTC, eladb commented on src/awscdk-construct.ts
> +    this.eslint?.addOverride({
Add a comment explaining why this is needed

2021-07-18 17:45 UTC, eladb commented on src/awscdk-construct.ts
> +      const bundleDir = path.join(parsedPath.dir, `${parsedPath.name}.bundle`);
```suggestion
      const bundleDir = path.join(parsedPath.dir, bundleDirName);
```

2021-07-18 17:45 UTC, eladb commented on src/awscdk-construct.ts
> +      const parsedPath = path.parse(file);
Please extract this to a public method called `addLambdaBundle(...)` so users can disable auto-detect and explicitly add bundles if they want.

2021-07-18 17:45 UTC, eladb commented on src/awscdk-construct.ts
> +      const bundleLambdaTask = this.addTask(`bundleLambda:${file}`, {
I think in this context, "bundle:" is sufficient as a prefix.

```suggestion
      const bundleLambdaTask = this.addTask(`bundle:${file}`, {
```

2021-07-18 17:45 UTC, eladb commented on src/awscdk-construct.ts
> +          '--target="node14"',
Extract to an option. This also needs to impact the generated construct.

2021-07-18 17:45 UTC, eladb commented on src/awscdk-construct.ts
> +          '--external:aws-sdk',
This needs to be an option (especially if people want to control the version of the SDK)

2021-07-18 17:45 UTC, eladb commented on src/node-lambda-construct-source-code.ts
> +import * as path from 'path';
Move to `src/cdk` (I am slowly trying to organize the src tree)

2021-07-18 17:45 UTC, eladb commented on src/awscdk-construct.ts
> +  private bundleLambdas(bundleLambdaOptions?: BundleLambdaOptions) {
I am wondering if it makes sense to extract all of this logic into a separate `Component` and just add it here. This way it will be possible e.g. to add that to other types of projects, such as CDK apps...

(and add it to CDK apps as well)

2021-07-18 17:45 UTC, eladb commented on src/node-lambda-construct-source-code.ts
> +    super.line(`code: lambda.Code.fromAsset(path.join(__dirname, '/${handlerDirPath}')),`);
```suggestion
    super.line(`code: lambda.Code.fromAsset(path.join(__dirname, handlerDirPath)),`);
```

2021-07-18 17:45 UTC, eladb commented on src/node-lambda-construct-source-code.ts
> +    super.line('runtime: lambda.Runtime.NODEJS_14_X,');
This needs to be configurable

2021-07-18 17:45 UTC, eladb commented on src/awscdk-construct.ts
> +  readonly bundleLambda?: boolean;
I am thinking that enable/disable should just be for automatic bundling, and the options at this level should reflect the defaults applied to the auto-detected handlers. Additionally users should be able to call something like `addBundleLambda(handlerPath[, options])` to explicitly specify a handler for bundling with its own options.

2021-07-18 18:13 UTC, haimlit commented on src/node-lambda-construct-source-code.ts
> +import * as path from 'path';
👍 I actually did exactly did initially, but reverted to avoid a bigger refactor, or having inconsistent paths.

2021-07-18 18:19 UTC, haimlit commented on src/node-lambda-construct-source-code.ts
> +    super.line(`code: lambda.Code.fromAsset(path.join(__dirname, '/${handlerDirPath}')),`);
Note sure I understood why would that work. The generated code has no `handlerDirPath` variable.

2021-07-18 18:29 UTC, haimlit commented on src/awscdk-construct.ts
> +  private bundleLambdas(bundleLambdaOptions?: BundleLambdaOptions) {
What's the motivation for adding this to CDK apps? I thought CDK apps are the end consumer of constructs, and won't benefit from the bundling process during build time, and the CDK bundling works well for that use case. Given the bundling part is redundant, is the lambda construct generation useful enough to be used on CDK apps as well?

If you think the answer is yes, I'll extract to `Component`

2021-07-18 18:30 UTC, haimlit commented on src/awscdk-construct.ts
> +  readonly bundleLambda?: boolean;
👍 , Changing to `autoBundleLambda` to make the distinction clear.

2021-07-18 18:33 UTC, eladb commented on src/node-lambda-construct-source-code.ts
> +    super.line(`code: lambda.Code.fromAsset(path.join(__dirname, '/${handlerDirPath}')),`);
lol you are right. So just remove the / from the string.

2021-07-18 18:34 UTC, eladb commented on src/awscdk-construct.ts
> +  private bundleLambdas(bundleLambdaOptions?: BundleLambdaOptions) {
I think there's definitely benefits to this approach for CDK apps as well and we can give people choice

2021-07-18 18:36 UTC, haimlit commented on src/node-lambda-construct-source-code.ts
> +    super.line('runtime: lambda.Runtime.NODEJS_14_X,');
Adding this as a configuration will force us to add a peer dependency on CDK (unless you see another way). Is this desired?

2021-07-18 18:54 UTC, eladb commented on src/node-lambda-construct-source-code.ts
> +    super.line('runtime: lambda.Runtime.NODEJS_14_X,');
Why? I would just add explicit support for a bundle of nodejs versions that are supported both by esbuild and lambda

2021-07-18 19:54 UTC, haimlit commented on src/awscdk-construct.ts
> +    this.addDevDeps('aws-sdk'); // common lambda runtime dependency
`aws-sdk` can easily add to `devDep`, but can't be easily added to `esbuild ... --external:aws-sdk`, as I didn't make it configurable. I tried to walk the fine line of providing some basic defaults and the fully blown bundler on CDK's Lambda NodeJS.

Do you think I should make externals configurable, adding each to both `devDep` and as `esbuild` arg? Or just keep the hardcoded `aws-sdk` one?

2021-07-18 20:02 UTC, haimlit commented on src/node-lambda-construct-source-code.ts
> +    super.line('runtime: lambda.Runtime.NODEJS_14_X,');
Isn't it kind of duplicating `lambda.Runtime` class? Perhaps duplicating and taking supported esbuild node versions, then it's not that bad.

2021-07-18 22:19 UTC, haimlit commented on src/__tests__/awscdk-construct.test.ts
> +    expect(snapshot[`src/__tests__/integration/lambda/mylambda-${handlerExt}.ts`]).toMatchSnapshot();
I thought this is intended behavior for testing projects to contain the files in `__tests__` when running TestProject, but given your response I understand this is unexpected behavior. After digging a bit, I found out the root cause is that `process.cwd()` determines where things like `glob` are going to act on. So basically all the project source files can potentially be discovered, and the files I've defined on the integration folder aren't special at all.

So now let's talk about alternatives - using plain `new SampleCode(project, 'mylambda.lambda.ts')` doesn't work - Lambda bundling doesn't pick that up, as lambda handler scan happens on project constructor, while file is created only during synthesis.

I considered moving everything to integ tests, but I think integ tests should be used much more sparingly, especially as the integration is reading a file and doing specific assertions. I think we have a new type of beast here.

After a lot of experimenting, the following works:

```typescript
    // GIVEN
    const prepProject = new TestProject({
      cdkVersion,
    });
    new SampleFile(prepProject, 'src/mylambda.lambda.ts', {
      contents: '// empty lambda handler',
    });
    synthSnapshot(prepProject, false); // added flag to skip output folder removal in `utill.ts`
    process.chdir(prepProject.outdir); // reuse folder for next project

    const project = new TestProject({
      cdkVersion,
    });
    const snapshot = synthSnapshot(project);

    // THEN
    expect(snapshot['src/mylambda.ts']).toBeDefined();
```

I like this far better than writing an integ test, despite this being a bit verbose and ridden with implementation details. I wanted to extract to a util, but the magic happens between constructor calls. The only way I could extract it to a util is by wrapping all project calls in lazy init functions, which makes the code much less readable.

So I'm going to change to the above, let me know if you have a better idea.

2021-07-18 22:23 UTC, haimlit commented on src/__tests__/integration/lambda/mylambda-js.lambda.js
> +export function handler() {
I think it'll take much more work beyond the scope of this PR. We can test that a bundle task is created, but I'm not aware of a way to test its execution, as it's pretty much running `npx projen build`. I'll do a manual test, please let me know if you can think of a reasonable way to test this.

2021-07-19 05:09 UTC, eladb commented on src/__tests__/awscdk-construct.test.ts
> +    expect(snapshot[`src/__tests__/integration/lambda/mylambda-${handlerExt}.ts`]).toMatchSnapshot();
This just uncovered a bug in the lambda discovery code. 

We need to pass the project `outdir` to your `glob()` call.

And in the test, just use ```
writeFileSync(join(project.outdir, 'src', 'handler.lambda.ts'))
```

2021-07-19 05:27 UTC, eladb commented on src/__tests__/integration/lambda/mylambda-js.lambda.js
> +export function handler() {
Okay fair enough

2021-07-19 06:28 UTC, eladb commented on src/awscdk-construct.ts
> +    this.addDevDeps('aws-sdk'); // common lambda runtime dependency
We are slowly realizing that the pre-bundling approach works much better then the "synth-time" bundling. Eventually I can envision that most customers will use this over `NodejsFunction` and friends (as much as I like them). To that end, I don't see a reason why certain features should be supported there and not here.

2021-07-19 07:45 UTC, haimlit commented on src/awscdk-construct.ts
> +    this.addDevDeps('aws-sdk'); // common lambda runtime dependency
👍 , I guess I was trying to start simple a bit too much, I'll update with more bundling options then.

2021-08-06 01:26 UTC, closed without merging