fix(jsii): configure job env correctly for Maven GitHub Packages
projen/projen pull request #950
Opened 2021-07-25 13:26 UTC by mKeRix

This pull request adapts the GitHub Actions job generation for Maven in a way that publishing to GitHub Packages (a) is possible again and (b) roughly matches the steps required for publishing npm to Packages. To do this, I ended up changing two things:

- the permissions of the job are set correctly to `packages: write` when needed (same logic as for npm)
- the `MAVEN_USERNAME` is set to be the GitHub Actor automatically if no override was given, like shown in the GitHub docs

To do the latter I introduced a concept of `expressions` to the `PublishJobOptions`, which allow more freedom than the secrets option, but use the same logic. I also converted the secrets implementation to use these expressions under the hood, so they are essentially a shortcut for an expression now.

Jobs that publish to Maven Central or other repositories will be generated in the same way still, however the `MAVEN_USERNAME` env variable moved spots (hence the change in release.yml).

I tested it in a private project and can confirm that it works now, see below for an excerpt from my test config and the result as a screenshot.

```typescript
const project = new AwsCdkConstructLibrary({
  publishToMaven: {
    javaPackage: 'com.github.mkerix.projenmaventest',
    mavenArtifactId: 'projen-maven-test',
    mavenGroupId: 'com.github.mkerix',
    mavenServerId: 'github',
    mavenRepositoryUrl: 'https://maven.pkg.github.com/mKeRix/projen-maven-test',
    mavenPassword: 'GITHUB_TOKEN',
  },
});
```

![Bildschirmfoto 2021-07-25 um 15 23 12](https://user-images.githubusercontent.com/770596/126900642-c5232aed-64f8-4835-a33b-0a791cff2add.png)

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-07-25 14:31 UTC, eladb requested changes

2021-07-25 14:31 UTC, eladb commented on src/release/publisher.ts
> -  readonly secrets?: { [name: string]: string };
I would just replace `secrets` with `workflowEnv` and just pass `${ secrets.Xxx }` for values (or implement a helper function `secret(x)` which returns that.

2021-07-25 14:31 UTC, eladb commented on src/release/publisher.ts
>    public publishToMaven(options: JsiiReleaseMaven = {}) {
Please add information about this behavior to the docstrings in `JsiiReleaseMaven`

Bonus points for adding this also to https://github.com/projen/projen/blob/main/docs/publisher.md

2021-07-25 14:31 UTC, eladb commented on src/release/publisher.ts
>          MAVEN_SERVER_ID: options.mavenServerId,
Can we default to `github` here if `isGitHubPackages` is enabled and if it is actually set, should we verify that it is always set to `github` to avoid errors?

2021-07-27 16:46 UTC, mKeRix commented on src/release/publisher.ts
> -  readonly secrets?: { [name: string]: string };
Implemented! Wasn't sure where the best place for the helper function is, so I ended up putting it close to its use. Happy to move it if you think it fits better somewhere else.

2021-07-27 17:41 UTC, eladb approved these changes
looks great!

2021-07-28 17:47 UTC, mKeRix commented
@eladb I regenerated the project and pushed it again - that should hopefully take care of the broken build.

2021-07-28 18:04 UTC, merged