feat: `.projenrc.json`
projen/projen pull request #999
Opened 2021-08-20 19:32 UTC by Chriscbr

Adds a `--projenrc-json` option for all project types that will generate a `.projenrc.json` file for managing the project instead of `.projenrc.js`. The `.projenrc.json` can contain any fields that can be passed to the constructor of the appropriate project type. The JSON file must also contain a field named "projectTypeFqn" that contains the fully-qualified name of the project type (e.g. `projen.web.React`, `my-jsii-module.MyProjectType`, ...).

Since projenrc.json only allows passing properties that could be passed to the project's constructor it is less flexible than other projenrc types and does not provide access to the other API.

Closes #990 
Fixes #994

Example CLI usage: `npx projen new typescript --projenrc-json`.
Example `.projenrc.json`:

```json
{
  "projectTypeFqn": "projen.TypeScriptProject",
  "defaultReleaseBranch": "main",
  "name": "projen-test",
  "projenrcJson": true
}
```

Comments:

- It would be nice to eventually define schemas for projenrc.json so that users editing JSON manually can get autocomplete etc.
- It could be beneficial to unify projenrc options/flags later (instead of having `--projenrc-json`, `--projenrc-js`, `--projenrc-java` etc., we could use `--projenrc=js` etc.)

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-08-20 19:33 UTC, Chriscbr commented on src/json/run-projenrc.task.ts
> +].join('\n'), ctx);
Some of this logic is copied from `new.ts`, we can probably extract it out...

2021-08-22 08:53 UTC, eladb requested changes
Looks great @Chriscbr - I love the creative reuse of the javascript rendering.

Can we add an issue to also support YAML? It should be straightforward given YAML is JSON.

Added a few minor comments.

2021-08-22 08:53 UTC, eladb commented on src/__tests__/util.ts
> +  process.env.PROJEN_TEST = 'true';
Add a note why this is needed

2021-08-22 08:53 UTC, eladb commented on src/cli/cmds/new.ts
> +  } else if (process.env.PROJEN_LINK_LOCAL) {
Is this documented somewhere?

2021-08-22 08:53 UTC, eladb commented on src/json/projenrc.ts
> +      projectTypeFqn: bootstrap.fqn,
Let's rename this to something a bit less intimidating. Maybe just `type`? or `base`?

2021-08-22 08:53 UTC, eladb commented on src/json/run-projenrc.task.ts
> +].join('\n'), ctx);
Yes, that would be nice

2021-08-24 18:07 UTC, alexforsyth commented
This looks awesome! Thanks so much. @Chriscbr let's say i'm using an external project. Does that change anything? How would I know what version I need to use?

2021-08-29 05:27 UTC, eladb approved these changes

2021-08-29 05:27 UTC, eladb approved these changes

2021-08-29 05:28 UTC, merged